### ISSUE TITLE
Observations on (broken) `update` behavior

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1007]
```
...collection/aligned (git)-[master] % datalad ls -r
.                                  [annex]  master  - 2016-09-13/10:16:40  X
src/raw                            [annex]  master  - 2016-09-02/09:38:19  OK
% datalad update src/raw
2016-10-14 08:19:41,515 [WARNING] 'src/raw' not known to dataset <snip>collection/aligned.
| Skipping (update.py:102)
```

For some reason I thought I could just tell it what to update. But current API considers from where to update the most important thing.

```
% datalad update -d src/raw
2016-10-14 08:20:40,055 [INFO   ] Updating dataset '<snip>/collection/aligned/src/raw' ... (update.py:115)
2016-10-14 08:20:40,170 [ERROR  ] 'git fetch -v origin master' returned with exit code 128
| stderr: 'fatal: Couldn't find remote ref master
| fatal: The remote end hung up unexpectedly' [cmd.py:wait:335] (GitCommandError) (main.py:270)
```

but

```
% git -C src/raw fetch --all
Fetching origin
```

I am not sure completely sure what the desired behavior is, but this seems to not make sense upon first glance.

**Comment by bpoldrack** [comment]
To have the behaviour of `git -C src/raw fetch --all`, you'd need `datalad update -d src/raw --fetch-all`.
Don't know atm, whether it actually expected a master branch or just tried, but `--all` isn't default behaviour (as it isn't for `git fetch`).

Regarding telling what to update rather than where to update from:
It simply follows `git fetch` atm and this totally makes sense to me ;-)

**Comment by mih** [comment]
> To have the behaviour of git -C src/raw fetch --all, you'd need datalad update -d src/raw --fetch-all.
Don't know atm, whether it actually expected a master branch or just tried, but --all isn't default behaviour (as it isn't for git fetch).

That is fine with me but `git fetch` does this:

````
% git -C src/raw fetch
-> exit 0
````

while `update` results in a fatal error.

> Regarding telling what to update rather than where to update from:
It simply follows git fetch atm and this totally makes sense to me ;-)

We know that this is no argument. Imagine I would say: "`install` follows `git clone` and this totally makes sense to me" :-(

**Comment by bpoldrack** [comment]
I agree, the fatal error isn't desirable and I don't say this isn't buggy.

> We know that this is no argument. Imagine I would say: "install follows git clone and this totally makes sense to me" :-(

Okay. So, the argument is: `update` operates on a dataset. This is derived from CWD or `-d` as everywhere else. So the only thing left would be the remote to update from. Otherwise we suddenly start to specify the dataset to operate on by NOT using `-d`, which to me seems to be an inconsistent API. Of course we can do it, but then you have to specify the dataset in different ways depending on what command you use. Doesn't sound reasonable to me.

**Comment by mih** [comment]
I agree, but it is in conflict with the desired behavior of `install` and `get` as per most recent API eruption. One of the themes there was auto-guessing what dataset to operate on (e.g. `get path2 path2`, where both paths do not share a dataset).

Only trying to figure out a way to be able to describe how the API is meant to be -- I had hoped to be able to write it down one day, but it seems I am not the chosen one ;-)

**Comment by yarikoptic** [comment]
> Only trying to figure out a way to be able to describe how the API is meant to be -- I had hoped to
> be able to write it down one day, but it seems I am not the chosen one ;-)

You are the chosen one, even though they nail you to the crest and throw stones at you!  So please don't feel stopped.  Just remember that we had already some write ups on how API was "meant to be" (original grant, numerous google docs and github PRs/issues), so it would be nice for it to reflect accumulated experience, and if anything to address known issues.

**Comment by mih** [comment]
The chosen one say: This is no open issue.
