### ISSUE TITLE
GitRepo.get_remotes() behavior surprising (maybe)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1036]
```
In [1]: from datalad.api import Dataset
In [2]: ds=Dataset('test').create()
2016-10-20 10:36:45,655 [INFO   ] Creating a new annex repo at /tmp/test 
In [3]: ds.repo.get_remotes()
Out[3]: []
In [4]: ds.config.add('remote.whatever.something', 'ignore', where='local')
In [5]: ds.repo.get_remotes()
Out[5]: [u'whatever']
```

It seems that some uses of `get_remotes` assume that there would be at least a URL configured. Found one such case in #1018 

Maybe we should consult other info too?

I understand that there is `with_refs`, but there is a vacuum between "I have a config variable" and "i have fetched stuff from a configured remote".

**Comment by bpoldrack** [comment]
Hm. Right, it assumes there is an URL, since this is what is required by `git remote add`. However, this is not true if there's just an entry in `git/config`, that was added without invoking `remote add`. I agree, this is not as reliable as it should be. But I'm not sure what you expect it to behave like. Do you think it should return a remote only if there is an URL and ignore an entry like the one you generated here?

**Comment by mih** [comment]
I don't know. `git remote` also reports it like this, so we could consider it as "by design", but given that some parts of the code mix these two cases together there is at least one bug....somewhere.

**Comment by bpoldrack** [comment]
Yes, I think we should stick to git's behaviour at this level and consider code making invalid assumptions about `get_remotes` to be the bug.

**Comment by bpoldrack** [comment]
Solved for quite some time now. We have an option `with_urls_only`.
