### ISSUE TITLE
`AnnexRepo.file_has_content` reports False for locally present files

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1100]
That is whenever a file is directly in Git and not annexed. So I need to test for that condition any time I use it. Moreover, I need to also test whether I have an AnnexRepo at hand or not.

I would prefer to have a set of functions that behave uniform across GitRepo and AnnexRepo, and are more result-oriented. From my POV, when I call `file_has_content()` I want to know just that. So if the file is untracked, uncommited, unannexed, directly in Git, any anything else -- it does not matter, because the content is there.

**Comment by bpoldrack** [comment]
Hm. It wasn't foreseen to ask a `GitRepo' whether or not a file has content. But I see your point.

The question to me is: How far is this going to go? Do you want to be able to call `unannex` on a plain git repo, since - well, the result will be okayish? What about `drop` or `get`? Could be done as well.
Basically everything can be interpreted somehow to fit to both kinds of repos. Is this what we want? To have all methods available from both classes? I'm serious. This would be a major design decision and we better make it soon.

**Comment by mih** [comment]
I wouldn't not aim for uniformity for uniformity sake. `drop` has no meaning or even utility in Git. Same for many other aspects.

Here is a non-exhaustive list where it would make sense for me:

- get_file_size
- file_has_content
- is_under_annex
- ...

**Comment by bpoldrack** [comment]
Okay. So, let's grow that list and have a third class, that declares those (abstract). Then `GitRepo` and `AnnexRepo` have to implement them. That way that list would be easy to grow and maintain.
And: I'd like to make it explicit, that these methods are supposed to work on both, while being implemented differently and while, at a first glance, some of them might not really make sense for a `GitRepo`. That's why a dedicated container for these "result oriented cross repo methods" is appealing to me. Just adding them to `GitRepo` and overriding in `AnnexRepo` would look strange in cases like `is_under_annex`.

Agree?

**Comment by mih** [comment]
There is Repo already.

**Comment by bpoldrack** [comment]
I'm not sure what you are talking about. Do you mean `git.Repo`?

**Comment by mih** [comment]
Yeah, my bad. I was mistaking `gitrepo.Repo` for a class (because of the capitalization....).

**Comment by bpoldrack** [comment]
Started to actually work on that, but this raises questions.

The approach to let a `GitRepo ` answer the question `file_has_content` always with `True` (or `is_under_annex` with `False`) sounds reasonable at a first glance. But: Shouldn't it actually say "I don't know"?

To put in other words: It probably makes sense only, if we ensure that a `GitRepo` can not be instantiated while pointing to a physical annex repository. Otherwise it cannot derive a valid answer, I think.
Enforcing this makes sense to me for another reason, too: The possibility to treat an actual annex as if it was a pure git by using an instance of `GitRepo` makes sense in V5 indirect mode only anyway.

Do you agree @mih , @yarikoptic ?

**Comment by mih** [comment]
I agree, GitRepo pointing to a non-indirect V5 annex repo could have the potential to reek havoc.

However, I am not convinced that we need to add extra measures to prevent it. Many use cases are absolutely OK -- in our own tests we use this quite a bit. Moreover, it is unlikely to happen during normal use.

`GitRepo.file_has_content() -> True` still makes sense to me. For all Git knows, a dead symlink is the content. Also GitRepo does not, and likely will never, test whether a particular git repo it is pointed to is fully capable of performing all functions we require -- we simply assume that, because it is most often true. Hence I consider it out-of-scope to have GitRepo test this particular aspect, when we test pretty much nothing else, and when it is only a problem for some part of the functionality.

**Comment by bpoldrack** [comment]
> Moreover, it is unlikely to happen during normal use.

Probably true, since we simply should use `Dataset.repo` in higher level functions.
I'm fine with that, but we should be aware.

**Comment by mih** [comment]
https://www.youtube.com/watch?v=XkU23m6yX04&t=1m27s

**Comment by mih** [comment]
Is this issue being addressed in any ongoing work?

**Comment by yarikoptic** [comment]
Found the RepoInterface and its sth_like_file_has_content in current code base and wondered either they are to stay or just be killed
FWIW -- I am inline with @mih in https://github.com/datalad/datalad/issues/1100#issuecomment-278891823

**Comment by mih** [comment]
FTR: We have passed the 6-month reconsideration period. It seems nothing speaks against:

`GitRepo.file_has_content(whatever): return exists(whatever) and not isdir(whatever)`

**Comment by yarikoptic** [comment]
@mih: Sounds good to us (@yarikoptic and @kyleam )

**Comment by mih** [comment]
Also see #2055

**Comment by mih** [comment]
FTR: If this get's fixed eventually, please grep for '#2055' and unuglify the code.

**Comment by mih** [comment]
I will take the liberty to close this (as the original author). In -revolution this has been made obsolete, by an `annexstatus()` function.
