### ISSUE TITLE
asks for ssh password for every dataset while installing recursively:

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1127]
version 0.4.1
```shell
$> datalad install -r -s smaug:/mnt/btrfs/dbic/inbox/bids dbic-bids
[INFO   ] Installing dataset at /data/dbic-bids_/dbic-bids from smaug:/mnt/btrfs/dbic/inbox/bids 
ECDSA host key for IP address '129.170.233.9' not in list of known hosts.
yoh@smaug's password: 
...
[INFO   ] Installing subdataset <Dataset path=/data/dbic-bids_/dbic-bids/dbic> 
ECDSA host key for IP address '129.170.233.9' not in list of known hosts.
yoh@smaug's password: 
```
and so on... you could try yourself on our canonical dataset  (and this one with current master)

```shell
hopa:/tmp
$> datalad install -r falkor:/srv/datasets.datalad.org/www
[INFO   ] Installing dataset at /tmp/www from falkor:/srv/datasets.datalad.org/www 
Enter passphrase for key '/home/yoh/.ssh/id_rsa': 
Enter passphrase for key '/home/yoh/.ssh/id_rsa': 
[INFO   ] Installing subdataset <Dataset path=/tmp/www/crcns> 
Enter passphrase for key '/home/yoh/.ssh/id_rsa': 
[INFO   ] Installing subdataset <Dataset path=/tmp/www/dicoms> 
Enter passphrase for key '/home/yoh/.ssh/id_rsa': 
```

**Comment by bpoldrack** [comment]
Did you try with all the SSH fixes in #1037?

**Comment by yarikoptic** [comment]
On November 23, 2016 3:53:03 AM EST, Benjamin Poldrack <notifications@github.com> wrote:
>Did you try with all the SSH fixes in #1037?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/1127#issuecomment-262460363

Ah, forgot that it was there and not yet finished/merged... Did you try it?

**Comment by bpoldrack** [comment]
Nope. Can't log into smaug recently and didn't figure out yet, what this is about.
But what I did try is to simulate it by installing datasets.datalad.org locally and then again from the local source via `localhost: ...`, so I have an SSH source. It behaves like you described in master, but with `rf-publish` branch it's somewhat different. It works nicely at the first level but then also starts asking for password for seemingly every subdataset at the second level.
So - conclusion: The issue is different but "real". ;)

**Comment by bpoldrack** [comment]
I think I got it.

This happened, whenever we `git annex init`-ed a fresh clone, which had to enable a datalad special remote. For some reason this led to an exception in `AnnexRepo.__del__` (`TypeError NoneType not callable`). I didn't figure out where this comes from, but worked around it by ignoring this kind of exception, since it is unlikely to cause some harm. However, this was not the actual issue. Instead the problem came from having two datalad processes. One for the actual datalad command, that calls `git annex init`, which in return creates a second datalad process to enable our special remote. Therefore we had two independent `SSHManager` instances, using the same connections. Ending the special remote process then led to "clean up" and close all connections used by `SSHManager`. Therefore the connections originally opened by the datalad command's `SSHManager` were closed and needed to be opened again.
See PR #1206

@yarikoptic : Can you confirm this doesn't happen anymore?
