### ISSUE TITLE
Cannot use `submodule add` in direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1208]
From tests

````
CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', '-c', 'core.bare=False', 'submodule', 'add', 'file:///tmp/datalad_temp_testrepo_WZ5ySr', 'subm 1']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', '-c', 'core.bare=False', 'submodule', 'add', 'file:///tmp/datalad_temp_testrepo_WZ5ySr', 'subm 1'] under '/tmp/datalad_temp_testrepo_gMCtaQ'. Exit code=1. out= err=fatal: $program_name cannot be used without a working tree.
````

**Comment by mih** [comment]
Among tons of other errors this seems to be the #1 to be addressed to get any further.

**Comment by bpoldrack** [comment]
Agree. Seems to be the most essential one for now. Looking into it.

**Comment by bpoldrack** [comment]
Note, that `git -c core.bare=False submodule add` works in direct mode in general. The issue is somehow more specific, which is good news, I think, since it doesn't look like we need a major design change.

**Comment by mih** [comment]
I think I recall that some time back this approach also failed for some Git
versions.



On Jan 23, 2017 16:07, "Benjamin Poldrack" <notifications@github.com> wrote:

Note, that git -c core.bare=False submodule add works in direct mode in
general. The issue is somehow more specific, which is good news, I think,
since it doesn't look like we need a major design change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/datalad/datalad/issues/1208#issuecomment-274512122>,
or mute
the thread

**Comment by bpoldrack** [comment]
Just tried with git 1.7.9.5 - worked for me.

**Comment by bpoldrack** [comment]
Okay, this is weird. It happens within testrepo creation. But when I use the debugger to dig into it, I find a strange situation: The submodule to be added doesn't exist at all (not even the directory). Furthermore `git annex info` says the repo is in direct mode, while `ls` is showing a broken symlink.

Still not sure, what this is about, but for now I don't think it's really the `git submodule add` what causes the trouble.

**Comment by bpoldrack** [comment]
I can add the very same submodule to the very same annex repository in direct mode manually, while it fails with 'fatal: $program_name cannot be used without a working tree.' in the tests.

**Comment by bpoldrack** [comment]
ATM using #1216 to figure it out.

I guess I can fix the tests, but I don't know why yet.
This failure happens during testrepo creation, not within the actual tests. Those repositories are using `GitRepo._git_custom_command` for now in order to call git/git-annex. When I switch to a direct use of `Runner` it works. Couldn't reproduce it outside of the context of testrepo creation and I can't reproduce it within these repositories via shell either.
Worth noting is another effect: Using `pdb.set_trace()` from within the testrepo's `populate()` method leads to nose just hanging. To get a debugger I can only raise a fake exception at that point and then running the test with `--pdb`. Don't know whether this is connected, but it's a strange thing and it occurs at the same time ...

**Comment by bpoldrack** [comment]
@yarikoptic : Just in case the description above rings a bell - let me know.

**Comment by yarikoptic** [comment]
- `_git_custom_command` probably uses GitRunner, not just Runner so it might adjust environment etc -- verify that it is not the case
- `leads to nose just hanging` -- probably there is a wrapping with `swallow_outputs` somewhere above it so all outputs are "swallowed" -- could remove/comment that context handler out for troubleshooting

**Comment by bpoldrack** [comment]
Re different environment: Right, I tried this but there's nothing indicating that this is causing the issue.

Re `swallow_outputs`: Thanks. Will look for this.



I think, I got it finally. @mih recalled correctly, there's something about using `-c core.bare=False`, that is troublesome with certain git version. While I tried an older git because of his hint, I missed checking a newer one. It's git version 2.11.0, that causes the issue. While using the shell as well as a "pure" `Runner` instance  are using my system-wide installation (2.7.0), we now use the bundled git delivered with git-annex-standalone when invoking via our Repo classes. And this is currently 2.11.0

As @mih pointed out in another issue, git 2.11.0 somehow ignores the per-call configuration passed via `-c core.bare=false`, while it still works if that value is set in `.git/config`.

I'd consider this a bug in git, but probably we should talk to git folks. What do you think, @yarikoptic ?

**Comment by yarikoptic** [comment]
if it worked before -- indeed seems like a (regression) bug in git, what do you think @joeyh?  
I would have quickly checked on #git IRC  showing a simple example on two version of git, and then took from there -- to either report to the mailing list or ...

**Comment by mih** [comment]
Independent of the Git version issue, can we make `care.bare=false` a permanent config setting while being in direct mode? Anything that would stop working if we did? I guess we would leave the repo in an unexpected state for non-annex-aware tools...

**Comment by joeyh** [comment]
You are free to set core.bare=false in direct mode, but you lose a very
important safeguard if you do this. It's quite easy to accidentially
commit large files into git, or run a git command that loses the content
of annexed files when it's configured this way.

-- 
see shy jo

**Comment by joeyh** [comment]
I'll bet the git developers won't see this as a regression. And to an
extent rightly so. Direct mode's use of core.bare=true is surely a hack
-- direct mode is entirely a hack -- and hacks break.

-- 
see shy jo

**Comment by bpoldrack** [comment]
For now I implemented a workaround, setting `core.bare=false` in `.git/config` in direct mode. But only on a per-call basis, so it is restored to original value after the git call. This slows down things a little bit, I guess, but until we come up with a better idea, it ensures things to work (not just `git submodule add`)

@joeyh 

> I'll bet the git developers won't see this as a regression. And to an
extent rightly so. Direct mode's use of core.bare=true is surely a hack
-- direct mode is entirely a hack -- and hacks break.

Well, what I consider a bug here actually isn't about `core.bare` from my point of view. Instead `-c` option is supposed to overrule whatever `.git/config` says, so ignoring this setting is a break of `git`'s API, isn't it?

**Comment by joeyh** [comment]
Benjamin Poldrack wrote:
> Well, what I consider a bug here actually isn't about core.bare from my point
> of view. Instead -c option is supposed to overrule whatever .git/config says,
> so ignoring this setting is a break of git's API, isn't it?

As yes, that sounds like a bug indeed.

-- 
see shy jo
