### ISSUE TITLE
Fragile `create_sibling()` and `add_sibling()` interaction

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1233]
If I see this correctly, a recursive `create_sibling()` will generate target path names, and then hand over to `add_sibling` to rediscover all subdatasets, and reimagine the URLs that match the generated target paths -- which were created with different code. A comment in there promises a centralization of this functionality. 

I don't like that much.

I propose the following change: RF `add_sibling()` to offer a helper function that performs most of its functionality, but bypasses all dataset discovery, and accepts a data structure that contains all relevant information, including the target URL.

@bpoldrack?

**Comment by bpoldrack** [comment]
Re your suspected "reimagination" of URLs: You probably mean the template replacement? This doesn't happen, since the passed URL isn't a template.

But the call to `AddSibling` with `recursive` probably is troublesome anyway, since we can pass things only wrt to the toplevel one. More complicated setups than the initally imagined ones will be tough that way, I think. If `CreateSibling` is redone without actual recursion, `AddSibling` should be called for each dataset separatly, I guess.


Re RF proposal:
Wouldn't be necessary with an iterative approach as far as can see it ATM, since we then can pass all relevant information directly anyway. From my point of view you would "centralize" the core of `add-sibling` instead of the part, that could be reused with `create-sibling` and may be even `rewrite-urls`.

But in general: That comment is there for reason. So, I agree in not liking the current state. At that point I wanted to wait for us to know more cases for templates and "real" setups in order to figure out how to reasonably centralize it. 

Conclusion: As of now, I'd prefer to just follow the same iterative approach as with other commands in `create-sibling`, calling `add-sibling` on a per-dataset basis (non-recursive) and leave the rest of it as is until we played with it a little bit more.
