### ISSUE TITLE
bring --kill back?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1282]
ATM the only "fast" way to remove some temp dataset is 
```shell
datalad remove --nocheck --if-dirty=ignore PATH
```
as far as I see it.  Could/should we have something more concise and easy to discover, e.g. --kill which would set those necessary options to achieve desired behavior? ;)

**Comment by mih** [comment]
Question is: do we still need that `if_dirty`? I don't really see it as a given.

**Comment by bpoldrack** [comment]
Well, a clean repo might be re-obtainable. A dirty one definitely isn't. So, I think a check for this is desirable.
BTW: Do we currently provide a check on whether or not the current commit would be obtainable from a remote? Might be nice to have, too.

**Comment by yarikoptic** [comment]
the idea of `--kill` was pretty much just to facilitate "chmod +w -R PATH; rm -rf PATH" operation, when you do not care to check etc. so none of the dirty/etc checks are of relevance

**Comment by mih** [comment]
I had to "kill" quite a number of datasets recently and I want to share this experience: In order to have the desired effect `--kill` would need to be an alias for `-r --nocheck --if-dirty ignore`. In my recent experience I was frequently surprised by the presence of subdatasets that caused a `remove -d <ds> --no-check` to fail -- for good reason, in my case.

However, given #2655 and the general state of things, maybe a dedicated `--kill` would at least indicate that all bets are off. However, we might want to keep such functionality out of `remove` for clarity otherwise we runs into combinatorial semantics: `--kill` would have to overwrite any other given options, otherwise we would not be able to just run "chmod +w -R PATH; rm -rf PATH", but instead would need to go through all the subcontent discovery stack (which is the cause of some latency. But if it overwrites stuff like `-r` people might perform "unexpected" removals.

Dedicated command (or even a procedure) seems like the better choice.

**Comment by yarikoptic** [comment]
So you are getting into aliases now? even I am ok without a dedicated kill ;-)
