### ISSUE TITLE
Metadata aggregation should support git-annex metadata

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1285]
We will use that anyways. This kind of metadata is per file/key, so without file-based metadata support (still shaky) it can only be some kind of summary.

Or we cheat and attach arbitrary metadata for the dataset as a whole to a dedicated "placeholder" file under `.datalad/`.

But see #1287 for a possible twist in the story.

**Comment by yarikoptic** [comment]
just a note: as we briefly discussed before, it might be worthwhile aggregating a "summary" of per-file meta-data (e.g. meta-data fields and all unique values present across files) into dataset meta-data, while then leaving more detailed access to it demanding full repository being present.  Otherwise, amount of stored in .git/objects meta-data might be overwhelming for any reasonably sized repository (unless we offload detailed one to be stored in annex as well, probably in some compressed format since it would not benefit from deltas etc git provides)

**Comment by mih** [comment]
this issue is about the other direction: aggregate per-file git-annex metadata that already exists into a superdataset. The what and how of metadata storage in a single dataset is the topic of #1287

**Comment by mih** [comment]
FTR: This is coming in #1630

**Comment by mih** [comment]
Done in #1630.
