### ISSUE TITLE
git-annex-status to ignore submodules

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1314]
A call to either `git status` or `git annex status` can be very expensive in large submodule hierarchies. For `git status` there's `--ignore-submodules`, which can be used to examine just the repository we are in without inspecting its submodules. Since this is way faster while it often provides all we actually need, I'd love to see that option for `git annex status`, too.
Any chance to get this, @joeyh ?

In a way, this might be related to how to fix http://git-annex.branchable.com/bugs/git_annex_status_fails_with_submodule_in_direct_mode/

**Comment by joeyh** [comment]
Benjamin Poldrack wrote:
> A call to either git status or git annex status can be very expensive in large
> submodule hierarchies. For git status there's --ignore-submodules, which can be
> used to examine just the repository we are in without inspecting its
> submodules. Since this is way faster while it often provides all we actually
> need, I'd love to see that option for git annex status, too.
> Any chance to get this, @joeyh ?
> 
> In a way, this might be related to how to fix http://git-annex.branchable.com/
> bugs/git_annex_status_fails_with_submodule_in_direct_mode/

I can't make git-annex status -- --ignore-submodules pass the option
through to git status, because the current interface treats that as
getting the status of a file with a name that happens to start with a
dash, so git-annex changes it to ./--ignore-submodules when passing it
to git status.

So, this would have to be a switch added to git-annex status. There
don't seem to be many other switches that it would make sense to need to
pass through either. Perhaps --ignored ?

But first, I wonder if passing specific files/dirs to git-annex status
and avoiding the submodule could avoid the cost. That could be hard or
easy depending on what you're doing, I suppose.

Also of course, there's no need to use git-annex status instead of git
status itself, unless the repo is direct mode or you're using its --json
feature.

-- 
see shy jo

**Comment by bpoldrack** [comment]
> Perhaps --ignored ?

In general I'm fine with any switch as long as it works. ;-) But I think the name should contain some notion of submodules. May be `--no-subs` if it is about length.

> But first, I wonder if passing specific files/dirs to git-annex status
and avoiding the submodule could avoid the cost.

Technically yes. But if I need to know the status of the superproject, that approach would mean to list all files plus the dirs, that are no submodules. I can't just pass `.`. So this would basically simply be datalad to implement that feature instead of annex. But we can do that of course. I just think, it would be a reasonable thing to have in annex as well.

> there's no need to use git-annex status instead of git
status itself, unless the repo is direct mode or you're using its --json
feature.

Right, I'm aware. But I do use the --json feature and furthermore I'd rather like to rely on annex than make the distinction on our own. It's just safer and more reliable for us to let annex decide what to do in the current mode or version of an annex repository, I think. Otherwise we tend to ignore, that there's more than just v5 indirect mode. ;-)

**Comment by joeyh** [comment]
Implemented git-annex status --ignore-submodules=when

-- 
see shy jo

**Comment by bpoldrack** [comment]
Thank you, @joeyh !
