### ISSUE TITLE
`AnnexRepo.get()` should not intercept the generator it gets from the `annex get` call

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1379]
There actual use of this low-level function should be investigated. High-level access should go through `api.get` which can return a list (among many other things). At present, however, `AnnexRepo.get` does not enable `api.get` to actually benefit from this internally provided generator.

I propose to return the generator as is, unconditionally.

Objections?

**Comment by yarikoptic** [comment]
we need quite a bit of handling on top of the `annex get --json` for absent files (done by `_run_annex_command_json`), etc which aren't provided in the output of annex get --json.    
But may be indeed logic within `get` method itself, after receiving a generator from `_run_annex_command_json` could be minimal if any?  but also `_run_annex_command_json` itself would need changes to make it a proper generator since now it just generates after receiving all of the output if I see it correctly

**Comment by mih** [comment]
Question long answered.
