### ISSUE TITLE
speed up git-annex invocation, or -- make annex a "microservice" ;-)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#139]
more and more we rely on annex to e.g. get the keys, assess if file has content etc -- if a single run of annex is negligible in terms of time -- hundreds of those bring things to a halt. 

@joeyh   I wondered, may be annex could have mode similar to how it deals with custom remotes where it would start and accept commands via stdin?  I guess that should shave off some runtime time.
or some other way (socket, etc) to provide a service/server like operation mode which would not require starting cmdline annex over and over again? (or may be there is already a way which e.g. assistant uses somehow?)

**Comment by joeyh** [comment]
A generic stdin interface would need some means to indicate when a
command had finished running (and probably its exit status). This would
seem to need some kind of serialization around commands and since they
can output anything to stdout, I don't see a good way to do that.

It would be simple to add --batch to particular plumbing commands
though. This seems to be more the way to go to me, I imagine you
probably have 2 or 3 plumbing commands that are the bulk of the
overhead.

-- 
see shy jo

**Comment by yarikoptic** [comment]
yeah -- serialization probably would be quite a bit more of work... but what about some socket, e.g unix domain sockets on linux/osx and regular tcp/ip one on windows -- this way all commands/status could be reported through it and we swallow stdout/err from the annex invocation to get them if/when we care?  if you/tools flush it upon command completion we could be right in time to get it "associated" with any given command for which we just got a status back from annex.

Batching -- would only partially resolve the issue since we would need to batch them for execution, until the point when we can't, i.e. next command depends on the output of previous one.  Whenever batching is obvious (e.g. requesting status on presence of files etc) we already can do that by providing multiple files in cmdline to call annex.  

Actually for some we should have already filed a wishlist bug report: e.g. in "annex find" it can accept multiple files as input, but if a single file among those is not under annex --  it blows, so we have to re-ask one-by-one.  Would it be reasonable to have e.g. an option "--missing=VALUE" which would then report VALUE if file is not under annex?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> Actually for some we should have already filed a wishlist bug report: e.g. in
> "annex find" it can accept multiple files as input, but if a single file among
> those is not under annex -- it blows, so we have to re-ask one-by-one. Would it
> be reasonable to have e.g. an option "--missing=VALUE" which would then report
> VALUE if file is not under annex?

This is basically the same problem being discussed in this bug report:

http://git-annex.branchable.com/bugs/regression:_behavior_when_files_to_add_do_not_exist/

-- 
see shy jo

**Comment by joeyh** [comment]
Could use a socket or extra FD as an extra data channel. It would be an
unusual interface though and make the client probably need to use a
nonblocking select loop so rather more work in the client.

Or it could use json output, at least for commands that have json
support. --json mode should disable other extraneous output to stdout.

But I'd like to investigate adding --batch to individual commands first,
since this seems more git-like, and also simpler. It would probably be
helpful to talk about the specific commands you need to call a lot.

Things like `git annex lookupkey --batch`, `git-annex readpresentkey --batch`
etc should be able to be spun up and run as long-duration servers, which
you could query as needed, not batched up all at once. This is how
git-annex uses `git cat-file --batch` etc.

There's some potential for such a long-running command to either
buffer stale data so it doesn't answer with the current state of the
repository, or for it to buffer changes and not commit them to disk
immediately. For example, a `git annex add --batch` would have the
latter problem.

That is actually an argument for only adding --batch mode to specific
commands though, since that would be an opportunity to check thier
behavior. A single `git-annex shell` interface would expose any such
problems in all commands.

-- 
see shy jo

**Comment by bpoldrack** [comment]
> Or it could use json output, at least for commands that have json
> support. --json mode should disable other extraneous output to stdout.

Indeed I didn't realize there was a "--json" option for "find", too. We only use it with "whereis" by now. Will change that.

**Comment by joeyh** [comment]
I've implemented a --batch mode for contentlocation, examinekey, and
lookupkey. This reads a line, replies with a response (typically on its
own line, but --format can change the number of lines), and repeats.

It should be easy to add --batch to other plumbing commands, and less
easy for non-plumbing commands. I suspect these plumbing query commands
are where you're seeing overhead of multiple calls though. 

1000 calls to git-annex examinekey take 45 seconds; in batch mode that
drops to 0.08 seconds. It's calculating a pure function on each key
which is quite fast; the time difference is due to git-annex's startup
overhead (mostly its need to run git config --list). 

contentlocation has a similar time profile to examinekey; runs about
half as fast since it does need to stat files.

1000 calls to git-annex lookupkey take 73 seconds; batch mode takes 
0.52 seconds. Here it's able to reuse a single git cat-file --batch,
rather than starting that up 100 times.

-- 
see shy jo

**Comment by yarikoptic** [comment]
Sweet! Now we just need to figure out how Rio use it efficiently :-) thanks!

**Comment by yarikoptic** [comment]
@bpoldrack I guess we will close this one whenever we start using --batch, reassigning to you ;-)  I guess we could do it "lazily": provide an option for those commands "batch=False", so if any of those commands requested in batch mode, they initiate a process exchange with corresponding git annex command and later requests go through it instead of the direct "git annex" cmdline invocation.  Upon 'del' those should die off and kill corresponding annex as a result

**Comment by yarikoptic** [comment]
I think we use `--batch` in majority of the cases where it could be used if not in all. will close this one for now
