### ISSUE TITLE
Mysterious segfault in #1350

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1392]
Following up on the investigation of the segfault in #1350: I made an attempt to produce a simple script that makes use of functionality that is touched by wrapt. None of my attempts lead to  anything that valgrind would label "definitely lost" or "indirectly lost".

**Comment by mih** [comment]
Switching from `install` to `clone` for this tests makes the segfault not happen.

**Comment by yarikoptic** [comment]
it also doesn't happen when I close my eyes and not look at the screen ;-)

**Comment by bpoldrack** [comment]
@yarikoptic : The point is, that Schrödinger's SegFault is most likely related to our use of wrapt, if it disappears when using clone instead of install. `Install` wasn't adapted to the new interface concept yet, while `get` and `clone` are. So, @mih's observation is a hint that we can solve it on our own, I think. An important point that wasn't clear, when we looked into it and it seemed to be some bug deep in wrapt's C implementation.

**Comment by yarikoptic** [comment]
@bpoldrack all those conclusions were made already in the course of #1382.  The question is "what should we do?". If we are to use wrapt -- it has to be fixed since we know that the problem can (and did) happen, with or without RF to use clone instead of install internally.  If we are not to use it -- then all wrapt changes should be reverted and then using clone is just an "optimization" and possibly modularization solution to make our code faster/easier to read.

**Comment by bpoldrack** [comment]
> it has to be fixed since we know that the problem can (and did) happen, with or without RF to use clone instead of install internally.

Yes and no. Apparently the RF'ing avoids it. So, this is a hint, that we can prevent the issue from happen from within python. And I'd strongly vote against not using wrapt as long as there is no proof, that we can't rely on it. But I agree - we should not ignore the issue just because it doesn't happen now, but find out what exactly caused (or triggered) it on our side and why exactly it doesn't happen when using `clone` instead of `install`. So, my answer to "what should we do?" is: Figuring out the exact point of the issue, but not giving up early on wrapt, since this makes a huge difference.

**Comment by mih** [comment]
Let's keep in mind that we have not actually identified wrapt as the cause. We just saw a debug message before the segfault that talked about identifying the class -- which is happening in the wrapper. But we don't know whether the crash was in the wrapper, or if the leak was caused by wrapt. I reported before that I failed to produce any trace of a leak using a range of wrapt code bits (#1392).

**Comment by yarikoptic** [comment]
folks, just keep an eye on or contribute to  https://github.com/GrahamDumpleton/wrapt/issues/98

**Comment by mih** [comment]
That segfault is back in another form #1544 -- and I really suspect that our particular use of GitPython contributes to this. Counter argument: not limited to PY3

**Comment by mih** [comment]
Search issues for "segfault" to get the entire story. This issue doesn't contribute anything useful anymore.
