### ISSUE TITLE
Strip `Dataset` of methods and expose them as (plumbing) commands

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1411]
The `Dataset` class is an outlier in our API, because it is only available in Python. As a result its methods are more "special" than our usual commands that are bound to the `Dataset` class. Moreover, the functionality they provide (e.g. `get_subdatasets`) is not available through the cmdline API.

We should carefully evaluate which methods could be exposed as regular commands.

#1423 
#1424

**Comment by mih** [comment]
Related to #1400

**Comment by yarikoptic** [comment]
are you saying that `.get()`, `.publish()` and other methods of the Dataset should be gone??
IMHO Dataset is not the outlier -- it is the core!  ;-)

**Comment by mih** [comment]
Those are the commands, they are only bound as methods in addition to being commands.

**Comment by mih** [comment]
`Dataset.register_sibling` is totally useless.
`get_subdatasets` should be a command.

Not yet sure about `get_containing_subdataset`.

**Comment by yarikoptic** [comment]
I know that those are commands.
ah -- you are saying to unify more -- i.e. that majority of Dataset methods should be similar commands.  

- `get_subdatasets` might indeed be useful. ATM it is just `datalad ls` which could reveal that information to the user to some degree
- `get_containing_subdataset` also not sure since it is primarily for internal usage

**Comment by mih** [comment]
Yup. PR for a `subdataset` command is coming.

**Comment by mih** [comment]
Done from my POV
