### ISSUE TITLE
save recursive saves untracked files in submodules

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1419]
while trying to fix up #1418 discovered that  it still does it .... heh... I guess manifestation of old behavior (set in stone with a test! ;) ) or that is somehow intentional @mih?

this is the test in question within test_save:
```python
    states = [d.repo.get_hexsha() for d in (ds, subds, subsubds)]
    testfname = opj('sub', 'subsub', 'saveme2')
    with open(opj(ds.path, testfname), 'w') as f:
        f.write('I am in here!')
    assert_true(ds.save(all_updated=True, recursive=True))
    newstates = [d.repo.get_hexsha() for d in (ds, subds, subsubds)]
    for old, new in zip(states, newstates):
        assert_not_equal(old, new)
```
so it checks that save indeed happens when we create a new file deep in hierarchy

**Comment by yarikoptic** [comment]
found this precious comment in the code
```
    # try to consider existing and changed files, and prevent untracked
    # files from being added
    # XXX not acting upon untracked files would be very expensive, because
    # I see no way to avoid using `add` below and git annex has no equivalent
    # to git add's --update -- so for now don't bother
```
heh heh

**Comment by mih** [comment]
Hmm, we both are well aware that `save` is a jenga tower and we should not pull on the wrong stone...

I'll look into it anyways -- frustration is my thing.

**Comment by mih** [comment]
The culprit seems to be this code in `save`:

````
        # here we know all datasets associated with any inputs
        # so we can expand "all_updated" right here to avoid confusion
        # wrt to "super" and "intermediate" datasets discovered later on
        if all_updated:
            # and we do this by replacing any given paths with the respective
            # datasets' base path
            for ds in content_by_ds:
                content_by_ds[ds] = [ds]
````

I am not sure what state of mind caused that to make sense at some point. What it seems to do is to make the case "explicitly save everything in this dataset" indistinguishable from the desired procedure. No idea yet how to address this, maybe a more explicit code....

**Comment by mih** [comment]
@yarikoptic OK, I am on this now. The issue is bigger than it seemed. Not only undesired adding of content in subdatasets, but in general. We even have a test for that :(

https://github.com/datalad/datalad/blob/master/datalad/distribution/tests/test_create.py#L160

In this test we check whether `ds.save(recursive=True, all_updated=True)` yields a clean top-level repo -- and it does -- but each dataset (incl. the top) has untracked files, which are all added at the end -- shouldn't be.

I have a draft of a new `save` implementation that doesn't do that anymore.
