### ISSUE TITLE
Use shunit2 for tools/testing/run_doc_examples

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1441]
It provides a proper test hardness and the one relevant test already supports it.

**Comment by yarikoptic** [comment]
I guess I will understand better how "test hardness" would make our world a better place whenever PR emerges.  For now all that shunt2 bits at the ends of the (two now) files makes little sense to me besides may be "if we got so far (since set -e) make a dummy shuniit2 call on this very script so it runs the testEquality which then reports that it is all Ok".    but I have difficulty to understand how really it helps us if we are anyways to use a special script to run those "example tests"

**Comment by mih** [comment]
Nobody cares
