### ISSUE TITLE
need delete-sibling (or more of 'unregister-sibling'? ;))

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1483]
now I would need to use something like ```git submodule foreach --recursive git remote rm local```.  Not too much pain but would be nice to have a little helper which conforms our API for traversal etc

**Comment by mih** [comment]
Sounds like another argument in favor of `configure-sibling`. Although, now
that we have `subdatasets` maybe just `sibling`.

On Apr 28, 2017 18:06, "Yaroslav Halchenko" <notifications@github.com>
wrote:

now I would need to use something like git submodule foreach --recursive
git remote rm local. Not too much pain but would be nice to have a little
helper which conforms our API for traversal etc

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/datalad/datalad/issues/1483>, or mute the thread
