### ISSUE TITLE
`get_paths_by_dataset()` is MAJOR source of slowdown!

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1505]
@bpoldrack @yarikoptic This is the climax of the OPT saga of the past few days:

Let me introduce you to: `get_paths_by_dataset()`, a function that runs every time a path is passed into almost any top-level command. Now watch this (with our big collection):

````
% time DATALAD_LOG_LEVEL=debug \
  python -c "import datalad.api; from datalad.interface.utils import get_paths_by_dataset; get_paths_by_dataset(['$PWD'], recursive=True)"
<snip>
DATALAD_LOG_LEVEL=debug python -c   1,31s user 1,10s system 18% cpu 12,744 total

# and now for fun and games, we give the same path twice
mih@meiner /tmp/datasets.datalad.org (git)-[master] % time DATALAD_LOG_LEVEL=debug \
  python -c "import datalad.api; from datalad.interface.utils import get_paths_by_dataset; get_paths_by_dataset(['$PWD', '$PWD'], recursive=True)"
<snip>
DATALAD_LOG_LEVEL=debug python -c   2,14s user 2,09s system 16% cpu 25,093 total
````

So this is not only slow, it is also stupid. I can say that, I wrote it.

I see no way how to make the individual pieces faster. If we ask for the full list of datasets in a tree, we have to get them at some point (which does not mean we should carefully evaluate when to ask for such a list). However, the logic purely within that function could be improved. In particular wrt the wasteful rediscovery when multiple input paths are given (even beyond a plain `unique(paths)`).

I won't have time to work on this now, but if you ever feel something is slow, consider throwing some computer science in this approximate direction first!

**Comment by bpoldrack** [comment]
Indeed. This should be possible to significantly accelerate.
But before optimizing this one, I feel the need to clarify what it is supposed to return. This is because unavailable paths are are treated as if we know nothing about them. Is this really what we want here?
We could as well return the closest (sub-dataset) availbel, that a non-existing path is in.
If we have a (sub-)dataset `/where/ever/ds` we do know, that a path `/where/ever/ds/some` does belong to that dataset in the sense that it requires this dataset.

**Comment by mih** [comment]
I would not change the semantics of this function now -- unless you are looking for some LARGE scale RF (which I would appreciate, of course). I would just make it faster at doing exactly what it does now.

**Comment by mih** [comment]
@bpoldrack Maybe a little follow-up: In order to properly answer your questions we would have to investigate how exactly the `unavailable_paths` output is used in our command implementations, identify what is being done to it afterwards that could be done cheaper right away. However, I don't have this knowledge ready, and I am afraid that means nobody has :(

**Comment by bpoldrack** [comment]
Yeah - okay.

Regarding "asking for the full list of datasets in a tree":
We can't avoid to get them, but there probably is potential for a smart caching solution.

Anyway - you're right. Optimizing just that function should save a lot already.

**Comment by bpoldrack** [comment]
Once at it, I'd like to point out another thing not so clear to me with that function.
This is the purpose of `recursive` and `sub_path` parameters. While I also don't quite get what they are for, the issue here is, that `sub_paths` can only report ONE subdataset. This seems to be incorrect no matter what purpose it is meant to serve.

**Comment by bpoldrack** [comment]
To be clear:

```python
for subdspath in ds.subdatasets(
                        fulfilled=True,
                        recursive=recursive,
                        recursion_limit=recursion_limit,
                        result_xfm='paths'):
                    if subdspath.startswith(_with_sep(path)):
                        # this subdatasets is underneath the search path
                        # be careful to not overwrite anything, in case
                        # this subdataset has been processed before
                        out[subdspath] = out.get(
                            subdspath,
                            [subdspath] if sub_paths else [])
```

The assignment to `out[subdspath]` should actually be an `append`, right @mih ?

**Comment by mih** [comment]
It cannot be an append, because it may not exist yet. So you'd need to test that before, and assign an empty list -- which is what this does.

**Comment by bpoldrack** [comment]
Sure, but if it exists it currently will be overridden instead of extended. And this is to be fixed, I think. Just want to make sure, that I got it right.

**Comment by mih** [comment]
I have seen bugs in my code before -- no surprise. If this is one, or rather an ingenious stunt, we will see ;-)

**Comment by mih** [comment]
Couldn't resist: https://github.com/datalad/datalad/issues/1506#issuecomment-300136845

**Comment by bpoldrack** [comment]
Well, it points out the quality of reviews ;-)

Next one:

```python
    out[dspath] = unique(out.get(dspath, []) + [path])
return out, unavailable_paths, nondataset_paths
```

This appends `path` to the dictionary's entry no matter whether or not it is in there already. Changing this seems to not break a test (locally). Are you aware whether or not this was intentional (for input-output-zipping or sth)? And if this is just the result of not being aware of possible duplications in `paths`: Do we want them to be contained several times in the output if they are several times in the input?

**Comment by mih** [comment]
? it has `unique`... Don't understand.

**Comment by mih** [comment]
Cannot recall, sorry.

**Comment by mih** [comment]
Note, #1507 is making this function faster in same cases already.
