### ISSUE TITLE
datalad and git annex are not in-line re whether something is an annex repo

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1560]
For my local (admittedly tortured) clone of the datalad dev repo:

````
% git annex info
git-annex: First run: git-annex init
# next call prints the associated repo instance repr for dbg purposes
% datalad siblings -s HERE
<AnnexRepo path=/home/mih/hacking/datalad/git (<class 'datalad.support.annexrepo.AnnexRepo'>)>
````

**Comment by bpoldrack** [comment]
This probably relies on whether or not an `AnnexRepo` can be constructed for the repository. This is explicitly allowed for not initialized annexes as there is `.git/annex` or a `git-annex` (remote) branch.
So, it's kind of intentional.
Can you confirm, that your datalad repo has one of those traces of an annex?

**Comment by mih** [comment]
Yes, there was `.git/annex`.

I just checked that `annex uninit` would remove that so consider this a non-issue. Thanks.
