### ISSUE TITLE
Some broken logging somewhere

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1610]
````
% datalad publish --to github
[INFO   ] Publishing <Dataset path=forrest_gump/collection> to github 
No handlers could be found for logger "git.remote"
````

Probably coming from GitPython's `PushInfo`

**Comment by bpoldrack** [comment]
Initially I aimed to add our handler to GitPython's loggers in order to avoid this. But then we actually don't need the internal GitPython logging. I then realized this issue was addressed in GitPython before - it's just missing the module `git.remote`. Therefore decided to simply address it in GitPython with a oneliner (see https://github.com/gitpython-developers/GitPython/pull/666).

**Comment by bpoldrack** [comment]
Closing, since this is addressed in https://github.com/gitpython-developers/GitPython/pull/666/commits/2b3c16c39953e7a6f55379403ca5d204dcbdb1e7

**Comment by yarikoptic** [comment]
actually I would not mind to enable GitPython debug output e.g. if our debug level < 5, and redirect to our loggers.
