### ISSUE TITLE
Why do we need to instruct GitPython to clean up?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1642]
Upfront confession: I still do not believe that wrapt is at fault re the notorious segfault.

Please help me understand why this code is required in `GitRepo.__del__`:

````
        # Make sure to flush pending changes, especially close batch processes
        # (internal `git cat-file --batch` by GitPython)
        if hasattr(self, 'repo') and self.repo is not None \
                and exists(self.path):  # gc might be late, so the (temporary)
                                        # repo doesn't exist on FS anymore

            self.repo.git.clear_cache()
            if exists(opj(self.path, '.git')):  # don't try to write otherwise
                self.repo.index.write()
````

This seem to indicate that without our explicit intervention GitPython would leave a repo in some kind of "broken" state. I somehow find that odd and unlikely.

`git blame` says that some parts of this code where added in https://github.com/datalad/datalad/commit/1aeacf711306743ef493b56928cee5062e6df831 by @bpoldrack as a "proper cleanup". I assume, it is related to our reuse approach for Repo instances, but I cannot quite grasp how exactly.

Interestingly, this also included running `precommit()`, which since then has been identified as a source of evil and was removed.

From the commit message it is unclear to me how important this is. In #1635 we can already see that the conditionals in this code are not sufficient. Please let me know what you think about this. I am inclined to simply remove this code.

**Comment by yarikoptic** [comment]
Hm... Iirc it is a line of code in wrapt where it segfaults at least in some cases. We don't have other extensions which relate and python code mustn't segfault.
As for those batched processes, I remember them haunting me, but forgot what was the evil outcome of them sticking around

**Comment by yarikoptic** [comment]
re wrapt -- kinda of a proof: with my [PR disabling extension-based implementation](https://github.com/GrahamDumpleton/wrapt/pull/104) -- does not segfault
```shell
(venv-regular) root@ae4a1f1452ef:/tmp/datalad# `which python` -m nose -s -v  datalad.distribution.tests.test_publish
datalad.distribution.tests.test_publish.test_gh1426 ... .: target(+) [/tmp/datalad_temp_test_gh1426jqm9z2 (git)]
ok
datalad.distribution.tests.test_publish.test_invalid_call ... ok
datalad.distribution.tests.test_publish.test_publish_recursive ... Fatal Python error: GC object already tracked
Aborted (core dumped)


(venv-regular) root@ae4a1f1452ef:/tmp/datalad# WRAPT_DISABLE_EXTENSIONS=1 `which python` -m nose -s -v  datalad.distribution.tests.test_publish
datalad.distribution.tests.test_publish.test_gh1426 ... .: target(+) [/tmp/datalad_temp_test_gh1426N_S1Pv (git)]
ok
datalad.distribution.tests.test_publish.test_invalid_call ... ok
datalad.distribution.tests.test_publish.test_publish_recursive ... ok
datalad.distribution.tests.test_publish.test_publish_simple ... ok
datalad.distribution.tests.test_publish.test_publish_with_data ... ok
datalad.distribution.tests.test_publish.test_publish_depends ... SKIP: Run this test by setting DATALAD_TESTS_SSH
datalad.distribution.tests.test_publish.test_smth_about_not_supported ... SKIP: Run this test by setting DATALAD_TESTS_SSH
Versions: cmd:annex=6.20170525+gitge1cf095ae-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.11.0 cmd:system-ssh=7.4p1 git=2.1.3 tqdm=4.11.2

----------------------------------------------------------------------
Ran 7 tests in 83.485s

OK (SKIP=2)
```

**Comment by bpoldrack** [comment]
To be honest I don't fully remember all the implications. But: We did get in trouble at some point, because of GitPython's git (-batch) processes still running, when we didn't have the original `*Repo` instance anymore.  I forgot the circumstances leading to the issue, but at some point we did get masses of such hanging processes connected to invalid repositories. The commit did solve the issue. 
There's a comment by @yarikoptic in PR #1091 somewhat pointing that out, but it's not very telling. I'm sure there has been a dedicated discussion on that, where Yarik was complaining about all those processes, but I wasn't able to find it yet ... :-/

The call to `precommit` was to make sure we flush in memory changes to the index before deleting it. We didn't actually have those kind of changes, I think. But it's possibile to have them with GitPython, therefore better call it. Additionally `precommit` was overwritten by `AnnexRepo` to also close `git-annex'` batched commands, IIRC.

**Comment by bpoldrack** [comment]
Re wrapt:

I hereby want to confess, that I still don't belive it's actually wrapt's fault, too. The segfault might happen in there and this might be a bug in wrapt itself, but I'm pretty sure that our use of it is somehow wrong or very unusual at some point - leading to the condition, wrapt isn't able to deal with.

**Comment by yarikoptic** [comment]
I don't know when other proof you guys need - pure Python implementation doesn't segfault, wrapt is in the traceback... Are you guys sure you aren't a president?

**Comment by bpoldrack** [comment]
I don't dispute it's wrapt, that is segfaulting. And yes: Python mustn't segfault. But this still can mean, that wrapt should lead to an exception instead of a segfault. In that sense there's a bug in wrapt - okay. But then this still wouldn't be the actual issue we have to solve. I simply suspect there is such an issue with our code. Otherwise a lot of people would experience that segfault, too. So, what I mean is, that I think it's likely to be two bugs. One within wrapt and one within our code. And if this is the case, then fixing the wrapt bug wouldn't fix ours. But fixing ours would make the wrapt's one irrelevant to us. Do you understand, what I mean?

**Comment by yarikoptic** [comment]
> I simply suspect there is such an issue with our code.

I bet we do have some issues left, can't argue ;)  Either any is related to the segfault and need to be fixed -- not sure ;) segfault is really a sign of non-sanctioned behavior/faulty logic in C code.  Finding a bug in our code which might hide wrapt bug, and again assuming that "oh -- wrapt bug is not that important since we do not see it any longer" is just again to postpone/delay pain and dealing with it.

**Comment by yarikoptic** [comment]
unrelated -- I am the master of segfaults!
```shell
$> git merge origin/master
[1]    4335 segmentation fault  git merge origin/master
```

**Comment by mih** [comment]
Putting this on record.
