### ISSUE TITLE
Online index of available collections (datalad.org)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#168]
Doesn't have to be a fancy webpage, but could just be a simple service that hands out URLs and meta data -- as a first step.

**Comment by yarikoptic** [comment]
if we get it done for the first show off -- great... but I would not sweat over it

**Comment by hanke** [comment]
This would be a ~20 line, maybe cherrypy, script that proxies requests to
a  datalad instance on the server. This instance is identical to any
datalad installation, only diff is that it has all known collections
registered.

Hence this is low hanging fruit.

**Comment by yarikoptic** [comment]
On Tue, 23 Jun 2015, Michael Hanke wrote:

>    This would be a ~20 line, maybe cherrypy, script that proxies requests to
>    a datalad instance on the server. This instance is identical to any
>    datalad installation, only diff is that it has all known collections
>    registered.

just for my education: wouldn't then the entire website be ran by
cherrypy, or we would just use it as cgi?

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by hanke** [comment]
The webSITE would not.

My concept is this: There is a webSERVICE running somewhere. The webSITE can query that SERVICE with some javascript in order to list collections or resolve other search queries. The same SERVICE can be queried by datalad installation in order to obtain information on available collections (maybe even other things).

But it really should be a thin shell around a datalad installation. The size of the DB or sluggishness of responses could force us to switch to a dedicated triple store (eventually/optionally). However, when this happens, it must not be different from the use case of a regular user-side datalad installation that has to deal with LOTS of collections/handles.

**Comment by yarikoptic** [comment]
we have the index now, the rest is for separate discussions etc
