### ISSUE TITLE
Provide nuitka-based binary packages

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1688]
@yarikoptic made a nuitka-based binary build work. thanks!

Based on that we could provide self-contained binary packages in RPM, tar (etc) format to give users an easy way to deploy on *NIX-based infrastructure. Some should be possible for Windows -- maybe even with an MSI installer, or whatever is the method of today on windows.

**Comment by mih** [comment]
I tried the nuitka branch and could build a package in ~30min. It resulted in a tarball of about 120MB size. It looks like this bundles everything (incl. Git and git-annex).

I suspect that the build setup on windows would require some adjustments to achieve the same bundling approach.

Looks good AFAICS.

**Comment by mih** [comment]
Where there any updates on this one over the past few weeks?

**Comment by mih** [comment]
Also see https://twitter.com/NeuroStats/status/916733507296043009 -- non-root deployment of Git/annex is another use case for this.

**Comment by yarikoptic** [comment]
There was! Kay did some fixes, and actually I built one yesterday! Only on Jessie for now, and we needed to do it in as old as we could, eg wheezy.
We need a tiny patch, but in general seems to work... I will share more later today so you could also check it out

**Comment by mih** [comment]
Awesome!

**Comment by yarikoptic** [comment]
you could check out http://onerussian.com/tmp/datalad-linux_0.9.1+git67-g1c55ab3.tgz, just wget , tar -xzf, and then point PATH to the bin/ within extracted directory

- it probably wouldn't work on elderly CentOS 6.9 or so since this one is build on jessie... need to reboot smaug with some kernel tweeks to be able to go back to wheezy docker
- any discovery logic relying on glob on the code (e.g. our plugins, datalad test without specifying explicit test submodule, or patoolib archivers support, and there was something in scrapy) wouldn't yet work

but otherwise seems to work more or less for basic operations (tried on search/get/uninstall)

I have now initiated a PR for the review etc https://github.com/datalad/datalad/pull/1889

**Comment by mih** [comment]
Downloaded. Will check this morning.

**Comment by mih** [comment]
Works as advertized. Great job everybody involved!

**Comment by mih** [comment]
We have  the mature #1889 with the actual progress.
