### ISSUE TITLE
Structure of user-targeted intro docs

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1689]
At the moment our docs don't do a good job at enabling visitors (and potential users for that matter) to judge whether datalad is something worth exploring. We have minimal "getting started", a substantial amount of front-loading ("principles", etc), (too) few usage scenario descriptions (but presently in too much detail to work as intro docs), and somewhat comprehensive command/module reference docs (that aim at people that already know that they want to use datalad, and how to approach it, in principle).

I am debating for a while now what structure would be most suitable for intro docs. Clearly, given the bandwidth of interesting use cases and target audience heterogeneity, a single monolithic tutorial piece would not work. Currently, I think that we would be best served with many small **standalone** demo bits that can be cross-linked into short intro bits that are targeting a specific subset of users (giving us the possibility to weight particular aspects differently). At the same time, we should be able to more easily provide adequate documentation for a specific subset of users (e.g. workshop attendees with a certain homogeneous background) without having to restructure docs each time, or to burden the generic docs with special interest topics.

Here are some initial thoughts on topics and audiences -- in no particular order (yet), and with the intention to grow based on your input. thanks!

Potential audiences (non-exclusive, letter code used for association with topics):

- Git users (G)
- Git annex users (A)
- Software developers (D)
- Scientists AKA people with data management needs (S)
- Data portal managers (M)

Topics:

- basic version control for large files [S]
- seemless subdataset handling for basic operations (add, rm, diff, ...) [G, A, D, S]
- advanced version control for a collection of datasets [S, M]
- data discovery via metadata search [S, M]
- make data available by posting the git repo on Github while benefiting from all of annex' versatility to exchange the data content (box.com, gdrive, sneakernet,...) [A, D, S]
- monitoring a non-datalad data resource on the web [S, M]
  - get PDF "attachments" #38 [S]
- data backup/archive #1600 
- extend datalad with plugins [D, M]
- "export" a datalad dataset to a regular bunch of files to give it to normal people [S, M]
- supervisor/supervisee workflow, for, e.g., let students safely work with some parts of precious (local) datasets, and to be able to easily clean up and save the essence of their work once a thesis project is done [S]

While there is no absolute need to impose a rule that all documentation should be using the command line interface, I nevertheless think we are best served with docs that demo the command line interface to a) get it more tested, and b) not limit the audience to python folk.

**Comment by yarikoptic** [comment]
Echoing brief discussion in the hangout:

- yes, having clearly defined topics would be useful

- no, I think that "a single monolithic tutorial piece would not work" is incorrect.  We could have a possibly redundant, but not as complete as specific topics, introduction to the main principles to datalad/git-annex, demonstrating the full blown workflow.  And then compliment it with points to the specific topics "to learn more".  I will try to sketch one up today/tomorrow.

- above allocation to roles is imho superficial. e.g. why "basic VC for large files" would not be relevant for G, D, and M?  depending on the coverage detail it might even be useful to A. Pretty much the same could be asked about any other topic.  So it is not really a role, but rather scope and target usecase which would identify who should read what.   That is why IMHO having an overall overview would be great to point to the capabilities of the datalad/git-annex which could be explained in greater detail in specific topics

- Python interface.   Should also be at least noted in the "introductory tutorial", since that came as a surprise to some audience and they were quite thrilled to see it happen in Python ;-)  Eventually we could make all code/script blocks be in both shell or Python based on the choice of the audience ;)  that would be neat imho. So may be it is worthwhile thinking about creating materials with BOTH annotated somehow so we could switch easily

**Comment by bpoldrack** [comment]
Re monolithic tutorial piece:
At the end, I agree with @yarikoptic , that we should aim for a single "entry point", linking more specific docs. But regarding "How do we get there?", @mih might be right: Let's build those specific (standalone) docs/demos/examples with a certain audience in mind first and only then the more general ones which link to them.

Re roles:
Allocation might not be ideal yet, but I think it's a good approach to write the pieces with those roles in mind. Not each topic has to be divided that way, though. (D) doesn't tell anything about the existing knowledge on git-annex, of course. But topics marked for (D) should not be relevant for others (contributing, how to build plugins/extensions, ...)

Re python interface:
Would be cool to always have both and let the docs render depending on user's choice (while testing always discovers both). But I'd start by writing everything based on CLI. Let's add python when we have a reasonable state of documentation.

**Comment by mih** [comment]
OK, opinions are clear, new website in-place and for further work are being made -- closing this one ...
