### ISSUE TITLE
No logging above DEBUG from low-level Runner

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1753]
This is still an issue. Unless someone stops me, I will force the change and have any Runner invocation log with DEBUG and no more. Otherwise we have conflict between low and high-level error handling. Previously, we had only low-level handling, but now we have a configurable high-level result management, and this should be used whenever possible.

**Comment by yarikoptic** [comment]
but where do you see those messages sneaking through?  the worst is whenever something does not work and hard to figure out why -- raising overall level to DEBUG makes output too cluttered to easily catch "ah command failed to run correctly when it should have".

**Comment by mih** [comment]
Check the latest PR for an example. The error I want to act on has already
flooded the scrrrn and will appear a total of three times.

**Comment by mih** [comment]
I just need a way to be able to say "shut up, I'll deal with this". The only way that I have is to swallow _any_ logs. In case of #1752 the function that logs "ERROR" (which at least is actually an error) is just a one-liner. So I could just not use it, call `git tag` myself, and set `expect_failure=True`, in which case it would do exactly what I want. So we either have a switch general switch (major RF), move to DEBUG (minimal change), or have constant pressure to avoid using inflexible low-level code.

**Comment by yarikoptic** [comment]
so you do set `expect_fail=True` (note, that not `expect_failure`) -- it shouldn't then log ERROR I believe....:

```shell
$> python -c 'from datalad.cmd import Runner; Runner()("ls lksjdf")'         
2017-08-24 10:13:20,636 [ERROR  ] stderr| ls: cannot access 'lksjdf': No such file or directory (cmd.py:352)
2017-08-24 10:13:20,637 [ERROR  ] Failed to run 'ls lksjdf' under None. Exit code=2. out= err=ls: cannot access 'lksjdf': No such file or directory
|  (cmd.py:296)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "datalad/cmd.py", line 120, in __call__
    return self.run(cmd, *args, **kwargs)
  File "datalad/cmd.py", line 297, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command 'ls lksjdf' failed with exitcode 2.
Failed to run 'ls lksjdf' under None. Exit code=2. out= err=ls: cannot access 'lksjdf': No such file or directory

2 10485 ->1.....................................:Thu 24 Aug 2017 10:13:20 AM EDT:.
(git)hopa:~datalad/datalad[enh-annex-file-has-content]
$> python -c 'from datalad.cmd import Runner; Runner()("ls lksjdf", expect_fail=True)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "datalad/cmd.py", line 120, in __call__
    return self.run(cmd, *args, **kwargs)
  File "datalad/cmd.py", line 297, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command 'ls lksjdf' failed with exitcode 2.
Failed to run 'ls lksjdf' under None. Exit code=2. out= err=ls: cannot access 'lksjdf': No such file or directory
```

as you can see in the 2nd case -- no ERROR log lines. So it might be up to the handler of that exception

**Comment by mih** [comment]
I know that, but this is the problem, not the solution. This switch is inaccessible from high-level code. I want to call GitRepo.tag() (which internally calls Runner()). I do not want to call Runner myself from high-level code -- what would be the purpose of low-level code if I cannot call that.

**Comment by bpoldrack** [comment]
Looking into this, while at logging anyway.

From my point of view, you're both kind of right. The unexpected ERROR thing is better for noticing what's wrong and on the other hand you should be able to just use low-level code, of course.
The thing is, that we need to figure out, when to expect what depending on the underlying git command.
In that particular case, the "right" way is to not complain about the ERROR logging, but to complain, that `GitRepo.tag()` isn't properly implemented yet. This is just a quick careless call of `git tag` by now.
If a method like that doesn't fit our needs, we should point out, that this method needs attention.
Originally, that's the intention to have all that parameter madness for the `Runner` and that `_git_custom_command`. To be able to have a quick implementation at `*Repo` level, that can be used upstairs and thereby have the interface for `*Repo`s we need, instead of hiding low-level calls in high level code. That way we don't have to RF, but just improve implementation within the `*Repo` classes.

As I'm going through the log swalloing in PR #1870 , I'll aim to fix those methods or at least make dedicated issues to replace this one.

**Comment by bpoldrack** [comment]
However, it might still be desirable to have a reserved log level for the `Runner` below DEBUG to avoid multiple reporting of the same issue and preserve a way to quickly recognize log messages coming from it.

**Comment by bpoldrack** [comment]
How about level 11 (above DEBUG, below INFO) for what was ERROR level and level 9 for what was DEBUG in `Runner`?
