### ISSUE TITLE
Rethink metadata parsers

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1796]
As noted in #1630 the metadata parser setup is no longer optimal for what we need to do.

Here are a few thoughts on how it should change:

Parsers should have three major modes of operation:
- report dataset-global metadata (this is what they do now)
- report metadata for a given list of dataset components (files/directories)
- dump all relevant metadata in a format that is optimal for query
   - this mode is needed for aggregation
   - homogenizing file metadata during aggregation is undesirable, as we would have to "expand" any metadata in a per-file format and possibly inflate it dramatically
   - instead I propose to let each parser chose an optimal dump format that only itself needs to be able to understand. this dump is than put into a metadata object (see #1630) and used to perform file-based queries on aggregated metadata, when needed
- consequently parser should be able to operate on an existing dataset, or on a set of metadata object files, and be able to perform the same operations

**Comment by bpoldrack** [comment]
Sounds reasonable to me.

How would a query work? Are parsers supposed to actually perform the query on dumped metadata themselfes and report the query results? If so, a point "query" is missing in the list above.
Otherwise: How exactly should parsers report on those dumps when asked for metadata to perform a query on? If they are the only ones to understand that dump, they need to report something different than just the dump. If the dump is, what is "optimal for queries" but then isn't actually used for queries, then this is confusing.

Or maybe it's just me, who is confused right now. :-)

**Comment by mih** [comment]
Yes, "query" was intended to be covered by "report metadata for a given list of dataset components (files/directories)". But that would be some "internal report" to the `metadata` command, which would be the one and only user-facing API.

**Comment by yarikoptic** [comment]
One of the growing issues with current approach seems to be scalability - already takes a while for an initial load and dump if a pickle. That is why I am not quite sure already either "dump all relevant metadata in a format that is optimal for query" ideas here are a relief or complication. "each parser chose an optimal dump format that only itself needs to be able to understand" somewhat suggest absent aggregation and unification which would delay things.

**Comment by mih** [comment]
FTR: There is no pickle anymore.

**Comment by bpoldrack** [comment]
> Yes, "query" was intended to be covered by "report metadata for a given list of dataset components (files/directories)". But that would be some "internal report" to the metadata command

If I get it right, this means, that the actual query is done by `metadata` on the data reported by the parsers. Since only the parsers understand the dump, this report is not in that "query optimized format". So in what sense is it optimized for queries? May be it's just wording. Is "optimized to answer the request on a given list of paths" (which then is used for a query by `metadata`) a valid way to alternatively put it? Otherwise I don't fully get it yet, I guess.

**Comment by mih** [comment]
Maybe better discussed in a hangout...

**Comment by mih** [comment]
Mental notes:

- Parsers need to be able to report their own metadata key definitions that are stored alongside the dataset-global metadata
- Parsers store file-based metadata as key-value mappings, where
   - keys are regex that match relative paths within a dataset (this enables efficient storage of hierarchical metadata schemes like BIDS)
   - values are key-value mappings with metadata, where
      - keys are defined, homogenized keys (see point 1)
      - values are arbitrary metadata values

- metadata aggregation of file-based metadata involves gathering all metadata from all parsers. Metadata merges are performed (in the same way it is already done for dataset-global metadata) for each unique regex (it is theoretically possible to generate regexes for all unique subsets, but that can be a CS student's contribution, as would be compacting metadata from less efficient native metadata schemes, e.g. one set per file with lots of redundancy)
- metadata access involves going through all regexes, find the ones that match the path in question and report the union of all associated metadata

This strategy enforces metadata key homogenization (we only store one set of metadata, not one per type) -- homogenized metadata should be more useful anyways.

**Comment by mih** [comment]
No final verdict from @yarikoptic still, but given that we are months into the process -> close.
