### ISSUE TITLE
datalad run  records pwd as was ran within super-dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1799]
did 
```
datalad run 'for f in sub-*/anat/sub-*_T1w.nii.gz; do d=$(dirname $f); od=derivatives/demo-bet/$d; mkdir -p $od; bet $f derivatives/demo-bet/$f; done'
```
where `derivatives/demo-bet` is a fresh subdataset
which worked out splendidly and added and saved generated files in the subdataset -- very nice! BUT, since I guess the save message is used across all datasets, now sub-dataset's record is not "rerunable" (correctly at least ;) ) if I cd to that subdataset, since it contains `cwd="."`

ideally cwd should have been adjusted accordingly in the subdatasets (not sure if feasible given current approach/implementation)

**Comment by mih** [comment]
I don't see myself trying to support rerunning commands in alternative locations and datasets. This would only succeed "by chance", because we are not doing any command introspection. That being said, I agree that the current result/message is not optimal. I simplistic fix could be to also record the ID of the dataset that the command run was originally performed on in the commit message. That way we could at least tell if a commit is just part of a set of changes of a larger tree.

**Comment by yarikoptic** [comment]
re `record the ID` -- I was thinking the same!

**Comment by mih** [comment]
@kyleam what do you think about this?

**Comment by kyleam** [comment]
I think recording the ID and then ensuring that it matches during a rerun is a good approach.
