### ISSUE TITLE
apt-get install datalad without NeuroDebian repository installs v0.2.3

### ISSUE THREAD

**Issue by sguthrie** [datalad/datalad#1807]
[Dockerfile-correct.txt](https://github.com/datalad/datalad/files/1286764/Dockerfile-correct.txt)
[Dockerfile-outdated.txt](https://github.com/datalad/datalad/files/1286763/Dockerfile-outdated.txt)

As a new user, I expected to get an error when I tried to install datalad without enabling the NeuroDebian repository; however, I installed datalad v0.2.3 instead of v0.8.1 without clear warnings. My main confusion came from the lack of the datalad-get command, but the tutorial was obviously unfollowable with such an old version.

See attached Dockerfiles for example.

Feel free to label this as user error.

**Comment by bpoldrack** [comment]
Thanks for reporting!

**Comment by yarikoptic** [comment]
Well... we never promised (since we simply can't) that released versions of official Debian and Ubuntu releases would have the most recent version of datalad available from them.  So, if you ask for datalad from official debian or ubuntu release, you would get the version which is available there, and it could be quite aged.  Because datalad is still under rapid development, in our instructions, we advise people on Debian-based systems to install it from our neurodebian, where we **can** provide most recent releases, and we do. 

Note that we have neurodebian docker images ready for all debian/ubuntu releases, so in your Dockerfile use

```
FROM neurodebian:nd16.10
```
to base it on neurodebian enabled ubuntu 16.10 and you will get the most recent release we provide.  Overview of availability across debian/ubuntu releases is available from http://neuro.debian.net/pkgs/datalad.html 

Hope this helps.  If you feel that we could somehow communicate this even better, we would appreciate a PR -- all docs and instructions are available in this and/or datalad.org repository
