### ISSUE TITLE
NEEDED: Convention for referring to a dataset vs. a directory for path arg input

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1819]
As discussed briefly during last meeting: Some commands (one of them being `publish`, another `metadata`) have to distinguish user input referring to a directory (i.e. dataset content) vs. a dataset itself. As we are only using paths this distinction is difficult and leads to inflation of the API with disambiguating options.

We should try to come up with a convention how to identify a dataset via a path, in a way that is different from the directory in is in. It has to be the dataset that gets special markup, because we do not want to be the root of a (sub)dataset to behave differently from any other directory in a dataset.

If found, this convention should then get detected during path annotation.

**Comment by bpoldrack** [comment]
How about a trailing double slash to mark a dataset? This seems to be consistent with #1810 from my point of view.

**Comment by bpoldrack** [comment]
Thinking about it ... May be in both cases (this and #1810) we should use a double path separator (`os.sep`) instead of an explicit "slash". But I'm not quite sure about this.

Pro: It has quite a similiar meaning to an actual path separator considering #1810

Con: We use `///` for the datalad super dataset on windows as well, right? Plus, if we look at it as some kind of "address" rather than a special "path", the slash makes sense even on windows (URIs).

What do you think?

**Comment by mih** [comment]
See also #1596

**Comment by mih** [comment]
Closing this old issue now. https://github.com/datalad/datalad-revolution now implements an rsync-like syntax. See description from here: https://github.com/datalad/datalad-revolution/blob/master/datalad_revolution/revstatus.py#L131
