### ISSUE TITLE
aggregate-metadata should have some --skip-aggregated

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1902]
#### What is the problem?
On a large hierarchy it is desired to update only pieces needed to be updated.  If I know that there were no changes in datalad, and metadata aggregation was already the last commit in a repo, there is no need to re-aggregate there.   Not sure if `--since` semantic kinda fits here... so may be `--skip-aggregated` would be more appropriate here... or may be skipping should be the default , and `--force` should be added to signal to re-aggregate even if meta-data aggregation was the last step.  May be it is worth storing datalad's version within aggregated meta-data so we could also trigger reaggregation automagically (and record new version) if new datalad is used

edit 1: #850 originally requested `--since` for aggregate-metadata, so changing title to list only --skip aggregated

**Comment by yarikoptic** [comment]
or ideally we should start recording "metadata version", which would reflect the status of the parsers etc... not sure though if we could rely on ourselves to keep updating it manually whenever we update parsers etc

**Comment by mih** [comment]
This issue touched upon at least three separate issues.

- `--since` logic would be simple to add and useful: Aggregate subdatasets whose state in the super dataset has changed `--since`.
- `--skip-aggregated` maybe be useful whenever one does not care about state/completeness of any existing aggregated metadata. For example, not caring that a subdataset may have changed its config since and now exposes more metadata (eg. more enabled parsers)
- storing datalad version in the metadata (which part? dataset-global? each content metadata item?) would be of very limited use. The metadata content can easily change without any change in datalad itself, due to 3rd-party changes. For a complete picture, many more versions would need to be recorded, tests and acted upon for each individual dataset(-part)

I can see myself implementing the first one, a see no real use case for the second one, as every time something updates a subdataset aggregation can be performed right away without any complicated retrospective decsision-making logic. Lastly, I don't think the 3rd one would lead to any practically usable benefits, but is guaranteed to bloat the metadata and the underlying code.

**Comment by yarikoptic** [comment]
My use case is 1 so I am ok with having only it supported ATM

**Comment by mih** [comment]
Closing in favor of a more traditional #850 (three digits!)

**Comment by yarikoptic** [comment]
And then closed that one as well... Funny

**Comment by mih** [comment]
Yeah, found an even better one.
