### ISSUE TITLE
make plugins the 1st class citizen of datalad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1945]
#### What is the problem?

This is not to be fixed right away but I just wanted to express in writing my whining a disturbance which plugins brought into the view and possibly just my not clear view on their purpose and difference in "role" from regular commands.
As far as I see them ATM, they are just the same "datalad commands" but defined differently and with the possibility for flexibly being added by the user/admin to become available.  The only argument I have heard so far on why they aren't full "blown" datalad commands, was "they are just a python function".  That is ok.  Our interfaces definitions are pretty much a "function" as well (well - glorified into a staticmethod of a class).  But those are just implementation details -- either they are full blown kids of the Interface with _args or a function with parameters described (hopefully) in a docstring. It should be e.g. possible to construct a "command" interface from a plugin definition (function) if needed.

Reciprocally I do not see why any interface command couldn't be considered a plugin and thus possibly participate in (not used by me yet) `--run-after` and `--run-before` dance.

ATM plugins are also an ugly duckling with `--show-plugin-help` and `--show-plugin-info` (bloody thing just did it and committed whenever I expected it just to show some kind of info):

```shell
(git)hopa:~pymvpa/pymvpa2-feedstock[bf]git
$> datalad plugin add_readme --show-plugin-info 
add_readme(ok): /home/yoh/proj/pymvpa/pymvpa2-feedstock/README.rst (file)
add(ok): /home/yoh/proj/pymvpa/pymvpa2-feedstock/README.rst (file)
save(ok): /home/yoh/proj/pymvpa/pymvpa2-feedstock (dataset)
action summary:
  add (ok: 1)
  add_readme (ok: 1)
  save (ok: 1)
```

What triggered my whining to condence:
Playing a bit with conda, I liked how their interface for conda command just gets extended right away if you install additional `conda-build` or `conda-smithy` packages.  I do not see why, in principle, our interface could be extended with plugins, may be groupped into another section of --help-np, and something like --help-commands  providing concise listing of all the commands (without current 2 lines per each) similar to `datalad plugins` output

#### What steps will reproduce the problem?

try to use `datalad plugin`

**Comment by mih** [comment]
I happen to create plugins for specific things from time to time. It literally takes me seconds to do one. It takes MUUUUCHH longer to create a command. Just check how many files you need to edit to get it running. Then you need to anticipate future complaints who much your new command increased the import time of datalad. The you need to come up with parameter specs. Then you need to obey the order of args to not have the test fail. Then you need to be careful to not inflate the core API with your special needs/interest.

If someone makes commands as easy as plugins -- great! For now I am good with plugins.

See #1887 for the only aspect where I personally see the need for action. But until we can test datalad in a clean config there is no point in doing that, because none of the devs will actually use it for anything.

**Comment by yarikoptic** [comment]
I am talking primarily about possibility of exposing plugins as datalad "commands".  We should retain the ease of their creation/definition and discovery. If e.g. we could simply provide handler for argparse to react to "unknown" command, we could just do plugins discovery then, and react appropriately 

- include list of plugins into `datalad --help`
- output plugins doc if `datalad PLUGIN --help`
- parse arguments and run the plugin if `datalad PLUGIN --kwargs args`

**Comment by mih** [comment]
No longer an issue.
