### ISSUE TITLE
Content indexing

### ISSUE THREAD

**Issue by kskyten** [datalad/datalad#1996]
I think searching the file contents would be a useful feature to have (e.g for book collections or NLP corpora). The hard part is creating and querying the index. It seems like [Recoll](http://www.lesbonscomptes.com/recoll/) is the closest thing I could find for this purpose. However, It does not support indexing relative paths [yet](https://opensourceprojects.eu/p/recoll1/tickets/21/).

**Comment by kskyten** [comment]
After doing some further research, it seems like adding the text content to the metadata and letting whoosh handle the indexing is the best way to go (see #1994).

**Comment by yarikoptic** [comment]
I guess to do that systematically we better get some text aggregator which would do that.

**Comment by kskyten** [comment]
What do you mean by a text aggregator? I was thinking that the metadata extractor would extract the text content as well. For example for a pdf file you could use something like the `pdftotext` utility. This is the strategy used by recoll.

**Comment by bpoldrack** [comment]
Well, your approach generally should work for a particular metadata parser, @kskyten .
But I'm somewhat worried about going down that road suggesting other parser could do as well. The reason is, that will let metadata explode in size and be heavily redundant with the actual data.

So, we might want to have a separated but very similar approach to aggregate full text data and query it. This could possibly done the very same way we do it for "real" metadata, without "polluting" metadata with actual data. I guess, that is what @yarikoptic was suggesting.
So, instead of letting the metadata extractor do it, have a separated mechnism with the same layers: customizable extractor => aggregator => search index. But don't store the extracted stuff in the dataset itself. So you can have that kind of search locally, but datasets don't ship that heavy redundancy.

Does that makes sense to you or should I be more precise?

**Comment by kskyten** [comment]
Yes, that makes sense. I actually found a better solution: [DocFetcher](http://docfetcher.sourceforge.net/en/index.html). It does pretty much what I want, is cross-platform and has support for various file formats out of the box. The only feature that I'm missing is the ability to specify how to open the files. This makes it impossible to open the pdf files on the correct page.

**Comment by kskyten** [comment]
Something that is more integrated with datalad would be very nice, but I think this will do for now.

**Comment by yarikoptic** [comment]
and with that you bring another interesting usecase to our attention:  ATM the lowest level of meta-data association is a "file".  But you are interested in associating meta-data with some location in a file (e.g. a page in the pdf document).  Could be interesting also in case of neuroimaging data: outlier volumes, which area a given volume associated with in an FSL-like probabilistic atlas. Not sure if we would ever dig that deep, but "good to keep in mind" ;) 
Cheers
