### ISSUE TITLE
Flag incorrect dataset contents

### ISSUE THREAD

**Issue by emdupre** [datalad/datalad#2069]
Using datalad 0.9.1 on MacOSX, pulling `///openfmri/ds000216/` produces an incorrect file listing as compared to the listing hosted on [OpenfMRI](https://openfmri.org/s3-browser/?prefix=ds000216/ds000216_R1.0.1/uncompressed/sub-01/func/). 

For example, in `sub-01`'s functional directory, I retrieve 8 rather than 4 scans with identical content but a different file-naming scheme, suggesting that these are from an older OpenfMRI versioning. Is there a preferred way to flag this data set and update? Thank you !

**Comment by yarikoptic** [comment]
Thank you @emdupre for the report!  The gory reason for it described and discussed in https://github.com/poldrack/openfmri/issues/9 and since noone complained yet (thus thanks again), I have not approached solving this problem via custom/manual intervention for this case:  take 1.0.1 release and consider it to be "full" release, so without overlay on top of 1.0.0.  Correct?

**Comment by yarikoptic** [comment]
anyways, I will assume so (if anything we could always do awkward git reverts) and pushed the fixed one -- now the tag 1.0.1+2 ;) -- is that how it should be?
http://datasets.datalad.org/?dir=/openfmri/ds000216
if so -- just do `datalad update --merge -r`

**Comment by yarikoptic** [comment]
ah right -- it was fixed with the above upload thus closing this issue

**Comment by emdupre** [comment]
Sorry for the delayed response on my end ! 

I was running something with the data set and wanted to wait until it finished to confirm the fix. Yes, that was exactly what I wanted ! Thank you so much for your quick response !! 😄

**Comment by yarikoptic** [comment]
great! thanks for the confirmation!  keep reports coming ;)
