### ISSUE TITLE
Toward 0.10 release of master

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2079]
#### What is the problem?

"Contribute to master vs 0.9.x" is a common point of discussion.  I think we should indeed strive to release master ASAP but IMHO here is one major issue which needs to be addressed first -- master should be usable and provide at least the same level of convenience and functionality as previous releases.  Unfortunately with the current state/view on things it was not the case on any of my attempts.  `search`, even when I aggregate all metadata for the entirety of the datasets.datalad.org was not usable

- [x]  Problem 1: "default" index building on client takes prohibitively too long - now by default dataset level

continue in #2032 
Whenever previously initial search "index" was built within a few seconds, now it could take minutes since it would build index from all metadata provided by the superdataset.  @mih 's opinion is that it should be up to the super-dataset curator to decide at which level of detail he should provide meta-data (per file, per datasets etc).   I thought about it, and in my view, I think it should be for a client to decide, and by default we should build an index based only on datasets level.  It should be fast, and it should provide again similar experience to what we already had (see 3 below), so people could just install datalad, and do basic queries.  Then, whoever feels going to the next level, could say (probably by changing config setting) -- build the index using both dataset and file-level metadata.  This way from the same datasets.datalad.org we could accommodate both types of users and at different levels they decide to do so

- [x]  Problem 2: need to autodetect/assign types of metadata parsers for the datasets.datalad.org - assigned manually to the majority if not all

continue in https://github.com/datalad/datalad/issues/2084 

It is a part of the bigger effort to provide a new aggregated metadata for datasets.  As for autodetection --
 It is a minor thing I guess, but hadn't chance yet to do so. Sure thing could start just with current state and just use those already assigned (e.g. bids) and ignore other additionally available (nifti, dicom).  Unfortunately this would delay usability/practicality testing of the datalad on our full collection of datasets.  So I would like to see if that happen before we release so we could test it nicely

- [x] Problem 3: we are switching from simple string matching to mightier whoosh - somewhat ongoing with blobmatching and rememberance of the bash in https://github.com/datalad/datalad/issues/2052#issuecomment-365717780

I did try quite a few times to search, and kept running into problems (#2052, #2018, ...) for many of which "ah -- it is smaug's fault" was the answer. Some of those were  technical (nevertheless must be addressed) but others looked more like my lack of "deep whoosh knowledge" and I kept being referred to the whoosh documentation etc which I was recommended to learn to perform the basic search.  We can't do that to the users -- we should assure that at least basic searches work as easily as before, that we have good documentation to assure that it is easy on how to accomplish what could have been done before. E.g., to provide examples such as 

   Instead of  (snippet I advocated widely before)
   `datalad search haxby | xargs datalad install`
   command now use 
   `???`

edit yoh (based on mih pointer): answer is in #2080 ... should get better visibility for mortals like me.  The rest of my problems are probably just technical issues/bugs which could be resolved

- [ ] convert all (super)datasets into annex datasets so metadata (although still not huge) does not impair their .git/objects before final aggregate-metadata.  May be setup .datalad/metadata to contain text files straight in git, which would be ds- files which should be not that big -- this way people would get all dataset level metadata right away as before
   - [ ] need manually create `.datalad/metadata/.gitattributes` to direct ds* into git and cn to annex
          Yet actually to decide what should go where

- [ ] aggregate-metadata "for real" using Python 3 (use --incremental and --update-mode)

- [x] (postponed) adjust `ls` which is used on web frontend to generate web-view metadata to use new metadata (#2403)

I would hate to release master into the wild before we address those issues above.  Potentially very powerful but unusable (too long, too difficult to specify, etc) search would repel new users, and possibly annoy a few of existing ones.  If you agree that those are indeed the problems to address, let's move them into dedicated issues and resolve them.

**Comment by mih** [comment]
Do we want to discuss the multi-issue right here, in one go? Or shall we
break this down? Some of those have been discussed before, some are issues
of the datasets we provide, some are real code issues. They dont have much
in common though.

**Comment by mih** [comment]
re 3: #2080

**Comment by mih** [comment]
re 2: I am absolute convinced that autodetection is a bad idea, infeasible from a resource-demand perspective, but at the same time absolutely doable. I will, however, not invest any time to make it happen, given my opinions ;-)

**Comment by mih** [comment]
re 1: Can we please discuss this in #2032 and not have an additional venue.

**Comment by mih** [comment]
one more: the fact that we are in this situation is proof that we cannot deal with the discrepancy of the desired need for stability vs the similarly desired need to break things in order to make progress without getting eaten up in backward compatibility duties (let's call that the Microsoft paradigm ;-) I want to express that I would have never sent a PR for the first `search` implementation, if I would have known that its presence would present such a high bar for future improvements.

Some time back I looked at the connection points of the metadata support with the rest of the code base, and there are _very_ few. We should really consider throwing it out of the core code base. There could be a separate project, Datalad core could keep its original search functionality, and any dataset provider can decide which one to use. Having an external consumer of Datalad core API should also have a beneficial effect on its general utility over time.

**Comment by bpoldrack** [comment]
> If you agree that those are indeed the problems to address, let's move them into dedicated issues and resolve them.

I agree. Those are things to discuss/address and we should split this into dedicated issues. Otherwise the discussion will be "unusable" itself. ;-)

Generally, I'd like to state, that it took me half a day to dive into whoosh and then I was able to provide fixes and extensions to Michael's PR back then, as well as I was able to perform some basic searches on my datasets. That clearly means, it's not about the "deepness of understanding". The troubles you experience have to have another reason. (Nevertheless, I'm absolutely fine with providing additional convenience, so for some basic things users don't need to lookup whoosh's language)
So, in conclusion, we should approach the discussion by first figuring out, what's the issues you apparently constantly have with the searches. Let's prepare a hangout to clarify and possibly reproduce what you are doing on other machines. Even better vice versa. We provide simple, fully defined examples and then let's whether they work for you (on smaug and elsewhere). Starting with a single, simple dataset. Then raise complexity and narrow down, where exactly it stops working. We need to be on the same page regarding here before discussing anything else, since all those discussions are influenced by that feeling, that somehow nothing seems to work for you. Or - if that would take too long for a hangout session, let's have just another issue for that.
And please split into several issues. :-)

**Comment by yarikoptic** [comment]
@bpoldrack thanks for offering examples, they would be super helpful.  And indeed lets continue in related/linked issues (thus closing this one).

**Comment by yarikoptic** [comment]
Although, @bpoldrack , I think #2032 already provides some good examples. I think quite often it is again some bugs which ruin my "experience" (like today `datalad search 'bids:participant_id:sub-01' type:dataset ` didn't work in one attempt on the `///openfmri` clone, but worked when I recreated a minimalist example)

**Comment by yarikoptic** [comment]
> Datalad core could keep its original search functionality

I think that it indeed could be our way out of a release deadlock ATM:

- what if master's `search` would become `search-whoosh`
- we reincarnate simplistic `search` of 0.9.x and RF it to support new metadata ds* aggregated metadata instead of the old one. AFAIK new ds* level metadata structure is easy and old style search is very dumb so I do not expect major problems making it actually work and creating its "search index" in reasonable time.

Having two search commands will also be the demonstration of having multiple metadata "consumers" (echoing discussion in #2082 etc) without a sacrifice of dumb/simplistic/humane search interfaces which would not require extensive index generation.

meanwhile I could aggregate metadata within our datasets.datalad.org using both 0.9.x and master (tricky but should be doable if we add `--since` handling to aggregate-metadata in 0.9.x), or (easier on me ;)) we just leave 0.9.x style metadata inplace and ask ppl to upgrade to a new flashy 0.10.

As I have noted before, and reflecting on above use case, we should also add versioning marker to all metadata files, so in the future we could inform users that a new version of metadata detected and update is recommended.  We rely on the same major.minor.patch versioning to signal breakage.enhancements.fixes with demanding.recommending.ignoring levels of the announcement demanding the datalad upgrade.

**Comment by mih** [comment]
#2127 now provides old-style string matching search -- albeit still with whoosh (I see no point in a custom approach). It also builds a default search index for datasets only as before. @yarikoptic wanted to look into a metadata autodetection helper (#2084). The rest has been dealt with before.

**Comment by mih** [comment]
#2115 is pretty much "master" from my POV. I do not know what criteria would be applicable for a merge into master. The last change to the aggregation layout is much further back, but cannot easily pinpoint a commit, and there seems to be no need to try anything older.

**Comment by mih** [comment]
Just reread this. I cannot easily see any concrete tasks that I can perform to make 0.10 a reality (please tell me if that is wrong). Once we get green light for the metadata/aggregate/search combo, they need to get a final round of doc updates to reflect whatever behavior they will exhibit at that point.

**Comment by yarikoptic** [comment]
my main obstacle remains inability to use search any time I have tried: #2262, #2316 
Overall: https://github.com/datalad/datalad/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+0.10.0%22 -- I have added those two to 0.10.0 as well.

**Comment by mih** [comment]
Hmm, my point remains. No concrete tasks for me.

**Comment by yarikoptic** [comment]
ok, here are some concrete ones: https://github.com/datalad/datalad/issues?q=assignee%3Amih+is%3Aopen+milestone%3A%22Release+0.10.0%22

**Comment by mih** [comment]
Whatever there was TODO --it is released now.
