### ISSUE TITLE
modularize meta-data handling away from the "core" datalad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2082]
A part of the "destiny of metadata support" discussion(s), originally suggested by @mih:
https://github.com/datalad/datalad/issues/2079#issuecomment-358067172 . Citing here:

Some time back I looked at the connection points of the metadata support with the rest of the code base, and there are _very_ few. We should really consider throwing it out of the core code base. There could be a separate project, Datalad core could keep its original search functionality, and any dataset provider can decide which one to use. Having an external consumer of Datalad core API should also have a beneficial effect on its general utility over time.

Heck, this could be a set of plugins...and it would be a good reason to elevate the plugin interface to behave like full-scale commands.... I start to like this... Maybe this could be a general path for additions/changes of datalad components. Implement them as plugins, bring them to people, let people decide what works and which way and only eventually move proven pieces into the core code base.

marked as belonging to 0.10 release decision for now

**Comment by yarikoptic** [comment]
I wonder, if given this idea we could/should absorb (virtually) all changes in master which do not touch datalad/metadata into 0.9.x?

**Comment by mih** [comment]
One comment: I think it is critical to distinguish two very different aspects of metadata handling that seem to be conflated in some of our discussions -- but really should not be.

- **metadata aggregation and representation in a dataset**. This has to be done right, and I doubt that anybody would want to support multiple simultaneous representations. The state in 0.9 is basically only "working" because we limit the amount of metadata to a handful of keys. Action is needed here, if any progress is desired.

- **applications that use aggregated metadata**. Everything is optional here. There could be a search implementation like there is in 0.9 that sits on top of the aggregated metadata, extracts the 5 keys that it cares about, and prints the path to the dataset. There can be a whoosh-based SQL-like search in addition, without having ANY impact on the actual dataset handling. There can also be other search implementations (graph-based, ...) inside or outside datalad that are compatible with our aggregated metadata as an input source. If somebody would want to build an external DB and fill it with our metadata for whatever queries, all they would care about it the representation of the aggregated metadata, and how to extract it from a datalad dataset, nothing else.

**Comment by bpoldrack** [comment]
That distinction is a good point.
However, that doesn't suggest a clear line what to include in the core. Metadata representation is a concept, not any code. Parsers, the `metadata` command and aggregation are producing those representations, so that would suggest to include those pieces in the core. On the other hand, it's more about a defined parser interface not actual parsers themselves. And aggregation isn't necessarily needed. So, I'm not sure yet, where to draw the line.

But generally I agree to this:

> Heck, this could be a set of plugins...and it would be a good reason to elevate the plugin interface to behave like full-scale commands.... I start to like this... Maybe this could be a general path for additions/changes of datalad components. Implement them as plugins, bring them to people, let people decide what works and which way and only eventually move proven pieces into the core code base.

**Comment by mih** [comment]
With #2115 we now have two different search modes/styles that are implemented completely separate from the metadata aggregation tools. I consider the aggregation aspect a core piece, while search is an application.
