### ISSUE TITLE
 Elevate the plugin interface to behave like full-scale commands

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2085]
#### What is the problem?
originally brought up in #2082  etc
Separate issue from metadata handling/search, so filing separately.

I personally would love if plugins would be exposed and behave as regular commands with a regular/conventional `--help` etc.  The aspect to keep in mind though is the start up time for `datalad` cmdline .  Although a "minor" thing, any increase in starting a command could have notable effects on duration of the tests battery etc due to all the sandwiching with git-annex calls etc

**Comment by mih** [comment]
Q: Where is the difference between a command and a plugin if we do that?

I think there is none. I think this issue should be about making the existing commands more flexible and breaking this monolithic beast of commands into more manageable pieces. Other than generating the list of available commands for `datalad --help` there is no need to import all commands at startup (and we can replace that by some other way to get a one line synopsis for a command). And if that is no longer done, there is also no start-up cost for adding more commands with potentially heavy deps -- may they be plugins or commands. One step further: plugins can be abandoned altogether and be replaced by proper docs on how to write a command.

The current `plugin` command can become a factory function that promotes any Python function into a full-scale command class.

**Comment by mih** [comment]
I played with this a little and looked at the amount of code that needs to run to get a proper command implementation hooked into the python or the cmdline API. Bottom line, there is not much (after I discovered that #2214 is possible). SO what I outlined above is doable: when can kill the `plugin` command and make any plugin a real command, we just need to add the ability to search a few dedicated places for commands, instead of hard-coding an exhaustive list.

Q remains: how to we deal with the lookup in order to avoid unnecessary import/startup delays. For the cmdline interface, it should be relatively easy to load a shim on startup that has just the name and a one-line synopsis on a command. However, I don't have a good idea on how to achieve a similar effect for the python api. The latter is used throughout the entire code base, meaning that any command using anything from the API, causes all of the API to be built -- which makes any/most optimizations done at the cmdline end more or less pointless.

Any ideas?

**Comment by mih** [comment]
Ok, 40min no response -- clearly nobody cares....

So here is the master plan:

1. `api` -> `coreapi`
   This will then be pruned of any command that is not super-important (or a dependency of a super-important command). This new coreapi will then be loaded the same way as we do now (hardcoded list of imports)
2. new `api`
    This will be all the rest, and will be looked up from a configurable number of locations. No hardcoded list but dynamic lookup. Any `coreapi` command must not use any functionality from `api`. `api` will become the defacto replacement of `plugin`. `api` will likely `from coreapi import *` for simplicity on the user side.
3. cmdline API will load all of `coreapi` the usual way, and discover commands in `api` dynamically, while including only a shim in the argparse instance, than will turn itself into an actual command if executed -- that latter part sound good, and should be doable, but I have no crisp idea on how to do it exactly.

**Comment by mih** [comment]
On (3): maybe we can just hand-parse `sys.argv` first, and unless there is `--help` or an alias of it, we only load commands whose name appears somewhere in the arg list.

**Comment by yarikoptic** [comment]
I would say -- pregenerate for all commands/plugins we ship, have a unittest to verify that pregenerated structure is up-to-date happen changes happen.
All the dynamically discovered (if there would be any) could be analyzed etc on the fly -- if there is none (majority of cases), no impact.

**Comment by mih** [comment]
I don't like that somehow. We would ship pregenerated content that somehow needs to be loaded, reformated to terminal size, etc -- just to save a few ms on `--help`?

**Comment by mih** [comment]
Tried a quick hack that still loads the command names, but only builds the subparsers for command if they are mentioned in the cmdline. Brings the startup time down from >250ms to about 80ms.

**Comment by yarikoptic** [comment]
sweet!  that is 80ms for running any command or just plain `datalad`?
for me it takes 100ms only to import datalad:
```shell
$> time python -c 'import datalad'
python -c 'import datalad'  0.09s user 0.02s system 97% cpu 0.109 total
```

**Comment by yarikoptic** [comment]
I am not sure if an answer to any question is still awaited or magical resolution is being cooked already per few comments back... indeed if we could avoid importing and pre-propulating all subparsers for a specific command, it could provide a remedy I guess.  For `--help` we could load them all.

**Comment by mih** [comment]
Import datalad is/was quick. The 80ms referred to datalad startup via the command line. which was >250ms for me.

**Comment by mih** [comment]
Soooo, I found the big showstopper. The beast that is `eval_func` makes very sophisticated assumptions on the origin and naming of classes, and modules they are coming from. In particular, any command MUST be properly imported so it gets `__module__`. For dynamically loaded code there is no `__module__`. @bpoldrack might remember what led to this solution. I just remember that the way towards it was painful.

It seems to be doing that in order to figure out which class provided the wrapped command function `__call__`, which in turn is needed to find default parameters etc.

ATM I see no easy way forward. Maybe a look dict (wrapped function id: class) could be managed somewhere. But right now I am at a loss where and when this information exists and could be captured.

**Comment by mih** [comment]
Done now.
