### ISSUE TITLE
failed to create second sub dataset in direct mode 

### ISSUE THREAD

**Issue by daisyburr** [datalad/datalad#2113]
#### What is the problem? 
@yarikoptic  was confused/surprised that the 2nd invocation failed whenever first one succeeded
the dataset is in direct mode due to absent posix permissions handling

```shell
dburr@discovery 1036_iaps]$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = false
	bare = False
	logallrefupdates = true
	symlinks = false
[remote "origin"]
	url = ...
	fetch = +refs/heads/*:refs/remotes/origin/*
	annex-uuid = ed4f8a31-4eea-4030-8a46-eb6cbe76ad3d
[branch "master"]
	remote = origin
	merge = refs/heads/master
[annex]
	uuid = a95e8883-5f65-43b4-8056-3e60312ed4b5
	crippledfilesystem = true
	version = 5
	direct = true
[submodule "derivatives/fmriprep"]
	url = 
	active = true
```

```shell
[dburr@discovery 1036_iaps]$ datalad create -d . derivatives/fmriprep
[INFO   ] Creating a new annex repo at /dartfs/rc/lab/D/DBIC/cosanlab/Data/1036_IAPS/1036_iaps/derivatives/fmriprep
add(ok): derivatives/fmriprep (dataset) [added new subdataset]
add(notneeded): derivatives/fmriprep (dataset) [nothing to add from /dartfs/rc/lab/D/DBIC/cosanlab/Data/1036_IAPS/1036_iaps/derivatives/fmriprep]
add(notneeded): .gitmodules (file) [already included in the dataset]
save(ok): /dartfs/rc/lab/D/DBIC/cosanlab/Data/1036_IAPS/1036_iaps (dataset)
create(ok): derivatives/fmriprep (dataset)
action summary:
  add (notneeded: 2, ok: 1)
  create (ok: 1)
  save (ok: 1)
[dburr@discovery 1036_iaps]$ datalad create -d . derivatives/^C
[dburr@discovery 1036_iaps]$ datalad create -d . derivatives/analyses
[INFO   ] Creating a new annex repo at /dartfs/rc/lab/D/DBIC/cosanlab/Data/1036_IAPS/1036_iaps/derivatives/analyses
                                                                                                                                  Failed to run ['git', '--work-tree=.', 'diff', '--raw', '-z', '--ignore-submodules=none', '--abbrev=40', 'HEAD', '--'] under '/dartfs/rc/lab/D/DBIC/cosanlab/Data/1036_IAPS/1036_iaps'. Exit code=128. out= err=fatal: This operation must be run in a work tree
fatal: 'git status --porcelain=2' failed in submodule derivatives/fmriprep
fatal: This operation must be run in a work tree
fatal: 'git status --porcelain=2' failed in submodule derivatives/fmriprep

```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
0.9.1

**Comment by mih** [comment]
This is because we are internally using a `diff` against `HEAD`, when doing an `add` if the new subdataset. The diff call does not work in direct mode. I happened to have a look at that today. With a more substantial RF we might be able to get a `ls-files`-based solution for this, but I am not sure whether it is worth the effort. Direct mode still has many other issues.

**Comment by mih** [comment]
I looked into this more. At the core of this issue is that we started to use `diff` to speed up path anntoation (incl. recursion). That is a good idea, but comes at the cost of direct mode issues. However, we might be able to work around, and possibly even speed up, this procedure. Here is my state of investigation:

In `add.py` there is `get_modified_subpaths()`. This is the core worker and is being called with `revision='HEAD'` in case of the call to `add` in `create`. Comparing to `HEAD` is the same functionality that is provided by `ls-files`, and in #2187 we are already using that to discover submodules.

It looks as if we could RF this code to not use `diff` in this case, and regain direct mode support for all use case like this.

Alternatively, we could do this special case handling inside our `diff` implementation. Haven't looked into this possibility yet.

**Comment by mih** [comment]
Looking into this further, I seems as if RFing `_parse_git_diff()` in `diff.py` could be a better choice. Possibly wrapping it into a general diff_helper that calls either this diff wraper or `ls-files` or something else in case of particular comparisons -- against `HEAD` being an obvious case. It is not yet clear to me how the behavior of `diff --ignore-submodules` (which is set to `none` by default) could be emulated.

**Comment by mih** [comment]
This turns out to be hard. Core issue is, as before, the implications of `--ignore-submodules=none`, which will evaluate the state of submodules, and crash if they are in direct mode (because `git status` fails).

**Comment by mih** [comment]
@bpoldrack you figured this all out long ago. Any chance for a fix?

**Comment by mih** [comment]
Direct mode? What was that?
