### ISSUE TITLE
AutomagicIO: OSError using pandas

### ISSUE THREAD

**Issue by adelavega** [datalad/datalad#2114]
#### What is the problem?
Opening a file with pandas fails with AutoMagicIO enabled. 
Error: `OSError: Initializing from file failed`

In particular, this object fails to initialize in pandas:
`parsers.TextReader`
Looks like this is implemented in Cython, FWIW. 

#### What steps will reproduce the problem?
Install repo, and try to open tsv file with pandas without previous unlocking. 

#### What version of DataLad are you using?
Ubuntu 16.04. Latest DataLad from github.

#### Is there anything else that would be useful to know in this context?
I'm not sure why this was working before (I made a PR regarding this before) and now it fails. I'm guessing Pandas changed how they read files recently. Currently I'm working around this by manually running `datalad unlock` on files I need, but its a bit cumbersome. 

#### Have you had any success using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
Yep!

**Comment by yarikoptic** [comment]
oh, that deep... not sure if we could monkey patch Cython's stdc.stdio within Python space.  Overall this usecase tests the boundary of applicability of the hackish Python-level auto mode of datalad and I guess the only reasonable solution would be the fuse-based generic support, if it is possible (didn't try) to have it operate over the same files hierarchy without explicit separate mount. At least should work on OSX and linux.
But I guess, since you DataLad savvy, you could just call `datalad.get(..., on_failure='ignore')` on any file which might potentially be under git-annex control and thus guarantee that it is there.  Sorry I do not have a better answer ATM

**Comment by adelavega** [comment]
I figured Cython would be a deal breaker here... Makes sense...

Yes that's indeed what I'm already doing! I do seem to have to also call `datalad.unlock()` sometimes which perhaps I shouldn't need to. But that's a separate issue. 

Thanks!

**Comment by yarikoptic** [comment]
actually, if you are using AutomagicIO anyways, and to keep code datalad agnostic, you could harness those calls to pandas with `assert os.path.isfile(filename)` beforehand.  It should then trigger getting that file if under annex in automagic mode.

**Comment by adelavega** [comment]
Good idea. Is this already in the main branch? I guess I could also check for `exists` first as well, which actually makes sense to do anyways.

**Comment by yarikoptic** [comment]
it is... 0.9.x branch is closer to the release and it is there as well
exists will not fetch the content, it would merely check if there is a file and it is under annex

**Comment by yarikoptic** [comment]
@adelavega what is your OS?  I think it might be feasible to establish tracing with auto-actions on Linux via strace.py but not yet sure on any reasonable way on OSX (if possible at all)

**Comment by adelavega** [comment]
I'm on Debian and Neuroscout is run on a Debian Docker container
