### ISSUE TITLE
Enhance run/rerun with the ability to record containers required for execution

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2158]
It is hard to autodetect if/which containers are required for the execution of an arbitrary script via `run`. We could nevertheless record such info, by having an option, such as `run --env singularity/conversion_tools`. This could be given multiple times (if multiple containers are needed) and would merely result in a run-record in the commit message that captures this information. With such info we could then allow `rerun` to obtain the necessary containers prior execution. Containers would be linked as subdatasets, hence there is no need to capture a version separately.

As discussed in #2148, the base location for containers should be configurable (i.e. `datalad.runtime.container-dir`). Using such a config layer, will also enable later restructuring of a dataset, without breaking `rerun` be invalidating `run` commit records.

@kyleam What do you think?

**Comment by kyleam** [comment]
I think I'm being dense, so apologies for what are probably silly questions.

> such as run --env singularity/conversion_tools

Even with this option, the command executed would still look something like `singularity {run,exec} <container-dir>/singularity/converstion_tools ...`?

> With such info we could then allow rerun to obtain the necessary containers prior execution

Because containers are in a subdataset, here "obtain" is running `datalad get`, right?

If so, I guess I'm wondering if this (getting a container) could be seen as a more general "get this input before the run"".

**Comment by yarikoptic** [comment]
I think it all relates to #2099 #2068 and us just supporting "runner" tools which would then take care about collecting needed provenance (be it NICEMAN or anything else like `singularity run`) and we would store that information in the record, while also committing any provenance file generated.

**Comment by bpoldrack** [comment]
> Even with this option, the command executed would still look something like singularity {run,exec} <container-dir>/singularity/converstion_tools ...?

Not necessarily. The executed command could also be a script, using (possibly several) containers inside, so you can't guess the needed container(s) from looking at the command call.

> If so, I guess I'm wondering if this (getting a container) could be seen as a more general "get this input before the run"".

That's a good point.

**Comment by kyleam** [comment]
> Not necessarily. The executed command could also be a script, using (possibly several) containers inside, so you can't guess the needed container(s) from looking at the command call.

Thanks @bpoldrack.  That was the (or at least one) obvious thing I was missing :/

**Comment by mih** [comment]
I like the idea of having a general mechanism to label certain paths as "dependencies", independent of whether they are containers or not.

One more idea: We have the situation that we need to run `datalad run` inside a container. Of course that `run` should make a record of the fact that it is running inside a container, so that reproduction is done in the right environment.

Such behavior can be achieved by providing a `datalad run --interactive`, which actually gives you an interactive shell inside a container. That shell could be prepared with a particular signal environment variable that `datalad run` inspects to see what container it is running on. Otherwise `run --interactive` would work the same way is a non-interactive run, it would still inspect the stay before and after, and commit changes. It would not be able to reproduce such a `run` -- unless `datalad run` is also used inside the container. In that case `run --interactive` exists, finds the dataset clean and nothing is commited. Obviously there is nothing inherently "interactive" about this. it could well be a script that executes `datalad run` inside a `datalad run` call that takes place in a container, but an "interactive" session might be the easiest method to get the desired behavior.

Of course one needs some kind of gyro to be able to figure out how if you are in a dream within a dream (in a dream, in a ...) -- time really slows in there...

**Comment by bpoldrack** [comment]
I'm not quite sure ATM, what we would need that shell for. However, that might be basically the same approach as I imagine.
From my point of view, `datalad run COMMAND` needs to be able to register data-dependencies (that also might be containers used by the command to run) and a container to run the command in.
At least for Singularity there's the possibility to pass any ENV variable into the container by prefixing it with SINGULARITYENV_. I guess, there's sth similar for docker.
This would allow to make the container known to a command running inside that very container. Since inside the variable doesn't have that prefix (and therefore wouldn't be passed into the next nested container) this mechanism seems to allow for chaining also.
So, datalad run COMMAND could watch out for, say DATALAD_CONTAINER_ACTIVE, and register its value as the container to run COMMAND in. Now, if we want to run `datalad run` from within a singularity container, we run that container with SINGULARITYENV_DATALAD_CONTAINER_ACTIVE being set.

So, if COMMAND itself invokes the container - nothing to do for datalad run. Otherwise use that variable when calling that container (or using it with `singularity run/exec/shell`.
For other containers, we just need to figure out, how to set DATALAD_CONTAINER_ACTIVE inside the container and rely on the same mechanic.

Does that make sense to you guys?

**Comment by kyleam** [comment]
Addressed by combination of #2464 and datalad/datalad-container#11.
