### ISSUE TITLE
datalad diff -r   to be depth first 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2161]
#### What is the problem?
ATM it first lists differences at the top level -- i.e. changed subdatasets, and then goes in detail for subdatasets.  IMHO it would be better if differences within a subdataset came right after declaring having the difference in that subdataset, i.e. instead of 

```shell
$> datalad diff -r       
   modified(dataset): ds000164
   modified(dataset): ds000177
   modified(dataset): ds000218
   modified(dataset): ds000253
      modified(file): ds000164/dataset_description.json
           deleted(): ds000177/CHANGES-ds177_R1.0.0_all_data
           deleted(): ds000177/README-ds177_R1.0.0_all_data
           deleted(): ds000177/T1w-ds177_R1.0.0_all_data.json
      modified(file): ds000218/CHANGES
           deleted(): ds000218/CHANGES-ds000218_R1.0.1_metadata_derivatives
           deleted(): ds000218/participants-ds000218_R1.0.1_metadata_derivatives.tsv
      modified(file): ds000253/.datalad/meta/meta.json
      modified(file): ds000253/dataset_description.json
```

```shell
$> datalad diff -r       
   modified(dataset): ds000164
      modified(file): ds000164/dataset_description.json
   modified(dataset): ds000177
           deleted(): ds000177/CHANGES-ds177_R1.0.0_all_data
           deleted(): ds000177/README-ds177_R1.0.0_all_data
           deleted(): ds000177/T1w-ds177_R1.0.0_all_data.json
   modified(dataset): ds000218
      modified(file): ds000218/CHANGES
           deleted(): ds000218/CHANGES-ds000218_R1.0.1_metadata_derivatives
           deleted(): ds000218/participants-ds000218_R1.0.1_metadata_derivatives.tsv
   modified(dataset): ds000253
      modified(file): ds000253/.datalad/meta/meta.json
      modified(file): ds000253/dataset_description.json
```

**Comment by mih** [comment]
Yes, I agree this is weird -- and unintentional AFAICR.

**Comment by mih** [comment]
Quick look at the code suggests this explanation: What we are seeing is the submodule entries in the parent being reported as modified, and then it goes into the actual subdatasets and reports why they are modified. Datasets are processed in the order in which (recursive) path annotation discovers them -- however, the confusion does not come from the order, but from the order of the *report* from each dataset. 

I am not sure how we could easily achieve the desired result, as we would (ironically) have to stop reporting dataset-by-dataset, but somehow postpone the report of a modified subdataset in a parent, until we are actually diffing the subdataset. So we would need some kind of cache dict in which we push to-be-reported things and for each new subdatasets, we check whether we can pop an entry off the cache.

Alternatively, we could stop reporting modified subdatasets altogether, but rely on the content report instead (I don't like that) -- we would have to be careful with a `--recursion-limit` though, otherwise we can easily report no diff, despite subdatasets being modified.

**Comment by mih** [comment]
Revolution diff is merged now that has the desired behavior.
