### ISSUE TITLE
What will be the next release?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2219]
0.9x or 0.10?

I am asking, because I have a tutorial upcoming and need to decide whether to talk about the dev version or a release. It will definitely be nothing earlier than current master, it is just about how to call things.

**Comment by yarikoptic** [comment]
There will be 0.9.2 and 0.10.0, not sure yet in which progression but most likely 0.9.2 would come out first  since it is an easier target to get while building debian packages etc).  Having both -- more "stable" 0.9.2 and flashy 0.10.0 would be beneficial to provide a safe fallback (for users) in case of some grave show stoppers emerge in 0.10.  That is why it is also likely for 0.9.2 to come out first so we could have a debian package for it in the archive (if only for a bit and then migrating to snapshots)

Some of the issues toward the releases are listed in the milestones:

- [0.9.2](https://github.com/datalad/datalad/milestone/47)
- [0.10.0](https://github.com/datalad/datalad/milestone/48)

with 0.10.0 dependent on 0.9.2 (i.e. all 0.9.2 should be fixed before 0.10.0). 
I hope I spelled it out correctly and it makes sense 
Cheers

**Comment by mih** [comment]
Ok, so 0.10 by Mar 9 is unlikely. I'll prepare docs to use master of our imaging project fork then.
