### ISSUE TITLE
Search usecases

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2257]
This issue is to collect and possibly provide answers on how `datalad search` query could/should/does look like to answer formulated question if it could do that.  And if not ATM -- why, e.g.
- **MISSING-META** we have not extracted such metadata yet, but if we adjust/provide needed extractor - should be possible.
- **DESIGN** - we cannot address the usecase because of our metadata extraction/aggregation approach. 
- ???

#### Level 1: Datasets:

- [ ] **RN1.1** Give me datasets which have a subjects with autism who are adolescents and have genetic data
    - MISSING-META
- [ ] **RN1.2**  Give me all datasets that have MMSE and tell me (return) what types of imaging was performed
    - MISSING-META
- [ ] **RN1.3** Give me all datasets with a visual task where the age of the subject is greater than 60 years
    - MISSING-META (nothing that defines the union of all visual tasks)
- [ ] **RN1.4** Give me all datasets that have multiple time points or multiple sessions (longitudinal data).
    - MISSING-META (I assume this refers to a BIDS dataset, not ANY dataset, but even there I think there is nothing extracted at this point)
#### Level 2: Imaging sessions/scans
- [ ] **RN2.1** Give me images for all typically developing subjects 10-15 years old who have structural scans at 3T
    - MISSING-META (what is typically developing?)
- [ ] **RN2.2** Give me images all right handed subjects with autism who have resting state data with a TR between 1 and 3 seconds in the age range of 18-25 and have ADOS assessment. [and then tell me how many are ‘severe’ (ADOS > 20) and ‘mild’ (ADOS < 20)]
    - MISSING-META (what is right handed?)
- [ ] **RN2.3** Give me the images for subjects that have 2 resting state sessions within a 2-day time frame.
    - MISSING-META (there is no generally used concept of a resting state session). I guess this query wants to discover multi-session datasets, but there is no guarantee that such data would be organized this way.

#### Level 3: Derived Data
- [ ] **RN3.1** Give me all typical subjects that have a corpus callosum volume with freesurfer. [NIDM-R]
    - MISSING-META (i guess NIDM would provide it)

### To be extended

**Comment by mih** [comment]
Structurally, these queries are pretty similar (content of unit that matches X and Y).

FTR: Most of these queries require some kind of knowledge graph (any visual task, normally developing, autism, ...). DataLad will likely never compose such information, but should query such a graph that represents the current state of art for a given community. 

Given the amount of queries necessary and their variability across dataset origins (communities), this list is evidence for an increasingly complex procedure to build a properly queriable body of information. This is the exact opposite direction of the one we where going over the past weeks (no index, no terms, simple matches of literal terms, instead of chunking/stemming/...). I guess this can serve as a guideline how much work should go into each search mode.

**Comment by yarikoptic** [comment]
> queries require some kind of knowledge graph ... DataLad will likely never compose such information...

For starters -- Let's assume that such annotation ("any visual task, normally developing, ") is available in BIDS datasets:  `group` column in participants.tsv for subject group, and task type as `CogAtlasID` in the _task.json file(s).   What usecases and how (with what search query) could then be answered?

**Comment by mih** [comment]
Note to myself:
`datalad search --mode autofield bids.participant.sex:female bids.participant.age(years):'[19 TO 26]' bids.type:t1w`

**Comment by yarikoptic** [comment]
eh, I do need a new harddrive -- tried above autofield search, filled up the last 3GB of my drive space and died ... heh

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by mih** [comment]
Discussion has stalled. I will close this until it becomes relevant again.
