### ISSUE TITLE
Unlock performance issue

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2354]
Situation: ~22k small files about 24KB each.

```
action summary:
  unlock (ok: 21840)
datalad unlock functional  252.34s user 17.42s system 97% cpu 4:36.33 total
```

for context on the general performance of the FS: when I actually load all these files, modify them with a command and store copies into another folder it takes a total of ~12s.

Using the annex cmdline is actually slower than using datalad (which generates the same number of lines on stdout) -- no sure how we managed to achieve that.

```
git annex unlock functional  296.57s user 49.33s system 101% cpu 5:40.28 total
```

for comparison an fsck run (actually iterating over even more files, hence more output on stdout):

```
git annex fsck  75.89s user 10.30s system 101% cpu 1:24.95 total
```

When I bypass unlock with a bash for-loop (likely not the fastest approach), I am 4-5x faster -- and seemingly achieve the same result:

```
% time bash -c 'for i in $(find functional/dicoms -type l); do cp --remove-destination $(readlink -f $i) $i; done'
bash -c   39.21s user 13.70s system 103% cpu 51.339 total
```

@joeyh is unlock doing something in addition to replacing the symlink with a copy of the annexed file?

Moreover: Putting the modified files back into annex is also slow. While that actually requires some more work, it should not be *much* more than what fsck does, and probably not more than fsck and unlock combined, but that is the case here:

```
% git add .
git add .  10.31s user 1.57s system 99% cpu 11.929 total
...
git commit --amend  588.24s user 46.04s system 100% cpu 10:28.18 total
```

**Comment by yarikoptic** [comment]
Is that in v6 since you used git add in the last command?

**Comment by mih** [comment]
No V5.

**Comment by joeyh** [comment]
Michael Hanke wrote:
> When I bypass unlock with a bash for-loop (likely not the fastest approach), I
> am 4-5x faster -- and seemingly achieve the same result:
 
Unlock has different code paths for v5 and v6, so it matters which one
you're using. Probably v6 is faster; I'll assume you're using v5 for now..

One significant thing unlock does is it looks to see if the file
has been committed to HEAD. This had to be done to avoid a complex
situation with the pre-commit hook, as explained in commit
fd55563b02dd8fedbb2420f440603be7192d94dc. Without that HEAD lookup,
I benchmark unlock as running approx 300% faster.

So I think that's the main overhead compared to cp. Unlock also does a
few little things like statting the symlink to find the key, etc.

I suppose unlock could check once if the working tree is all committed
to HEAD, and so avoid the per-file checks. If that can be done
cheaply enough. (git status --porcelain). There would be a slightly
wider potential race than the one that already exists around the check.
It might make sense to only have --fast enable that, with appropriate
warnings in the documentation.

> Moreover: Putting the modified files back into annex is also slow. While that
> actually requires some more work, it should not be much more than what fsck
> does, and probably not more than fsck and unlock combined, but that is the case
> here:
> 
> % git add .
> git add .  10.31s user 1.57s system 99% cpu 11.929 total
> ...
> git commit --amend  588.24s user 46.04s system 100% cpu 10:28.18 total

That's kind of the least efficient way to do it, since you're staging
the whole file content into the index and then letting the pre-commit
hook convert that back to annexed symlinks. git annex add would probably
be faster.

-- 
see shy jo

**Comment by mih** [comment]
FTR: Re-evaluating the situation with annex 6.20180913+git33-g2cd5a723f-1~ndall+1 and a different dataset (5.4k files @ 21kb each)

> unlock in v5
git annex unlock .  24.07s user 3.87s system 103% cpu 27.027 total
> for reference
git annex fsck  14.24s user 1.66s system 108% cpu 14.704 total
> straight cp
% time bash -c 'for i in $(find . -type l); do cp --remove-destination $(readlink -f $i) $i; done' 
bash -c   9.91s user 3.27s system 104% cpu 12.569 total

Factor 2x for unlock vs. fsck/cp. I assume git annex has been optimized in areas that affect this functionality. Thanks!

Closing...
