### ISSUE TITLE
Add ssh/sftp support to download-url

### ISSUE THREAD

**Issue by satra** [datalad/datalad#2369]
i would like to create a local dataset with a remote scp target.

essentially any time i get a file/directory from a remote ssh server, i would like it to be staged for addition locally into my datalad repo.

potential api example:
```
datalad stage scp://satra@hostname:port/path/to/file_dir [local_path_in_repo]
```

is something like this possible now?

more generally, can i do this for any remote:
```
datalad stage [protocol]://[credentials]@hostname:port/path/to/file_dir [local_path_in_repo]
```
where protocol: http(s), (s)ftp(s), ssh, s3, dropbox, box, ... 

i'm using `stage` to differentiate from `get` for now.

**Comment by yarikoptic** [comment]
So is it git annex addurl but with ssh/SFTP support? (Later I could find issue I filed with git annex about that). Or is it something different?

**Comment by aqw** [comment]
@loj just gained access to a dataset that offers rsync/sftp/scp access. Ideally, these files could be imported, with all the wonderful metadata and handles on where they came from. I looked at download-url and downloaders/providers.py, but I can't find sftp support.

Am I looking in the wrong place/missing something/doing it wrong, or is this still a todo?

---Alex

**Comment by jbpoline** [comment]
@yarikoptic @joey : sounds like something that would be super useful for us (with @tglatard) - any news / plan on this ?

**Comment by yarikoptic** [comment]
what are the details of your usecase @jbpoline ? I wonder if it would be sufficient of having support in `datalad download-url` (ie our downloaders; may be could be done via `sftp` CLI) or "full fledged" sftp special remote  -- then https://git-annex.branchable.com/todo/add_sftp_special_remote/ is probably the right issue to chime in...  

But also there is https://rclone.org/sftp/ - i.e. support for sftp in rclone. So if you do need special remote, then in principle you could do it through rclone git annex special remote (https://github.com/DanielDent/git-annex-remote-rclone; I use it for dropbox quite "heavily") if that would be allowable (a bit inconvenient since would require "manual" rclone configuration for that remote first).

**Comment by mih** [comment]
https://github.com/datalad/datalad-next/pull/124 aims for non-http support and to make the extensible via extensions https://github.com/datalad/datalad-next/issues/129

**Comment by mih** [comment]
`download_file()` in https://github.com/datalad/datalad-next/pull/124 now has support for `ssh://` URLs.

Given that it is unlikely to see the support appear for `download_url()` here, I think it would be OK to close this issue as a 'wontfix' + 'fix-implemented'
