### ISSUE TITLE
issues with downloading `ds000114` derivatives from inside a docker image

### ISSUE THREAD

**Issue by miykael** [datalad/datalad#2472]
@mih told me that you would love to have more issues to solve (and also that I should put my issue here, too). As discussed in https://github.com/miykael/nipype_tutorial/issues/79, we have problem to download the `workshops/nih-2017/ds000114` deriviatves, from inside the docker image. Outside, it doesn't create any problem.

I've set up a docker image `miykael/datalad_test`, with which you can recreate the issue. It installed `datalad_neuroimaging` via `pip` and installed the openfmri dataset with `datalad install -r ///workshops/nih-2017/ds000114`. Some more information:
```
git-annex version: 6.20180416+gitg86b18966f-1~ndall+1
datalad 0.10.0.rc1
```

 So, to open the docker image to recreate the issue, just use

```
docker run -it --rm miykael/datalad_test
```

And once inside, try:
```
datalad get ds000114/derivatives/fmriprep/sub-01.html
```

Which will give you the error:
```
[ERROR  ] from web...                                                                                 
| from web...
| Unable to access these remotes: web
| Try making some of these repositories available:
| 	0000...0001 -- web
|  	b8b7...8eb9 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives/fmriprep
|  [get(/home/neuro/ds000114/derivatives/fmriprep/sub-01.html)] 
get(error): /home/neuro/ds000114/derivatives/fmriprep/sub-01.html (file) [from web...
from web...
Unable to access these remotes: web
Try making some of these repositories available:
	0000...0001 -- web
 	b8b7...8eb9 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives/fmriprep
```

I'm sorry to annoy you with this issue, but I'm really stuck with the problem and don't see how to solve it.

**Comment by yarikoptic** [comment]
Thank you for the report and all the effort you have gone through to make it reproducible!  but it seems that the docker image is not available from the hub:
```

 $> docker run -it --rm miykael/datalad_test
Unable to find image 'miykael/datalad_test:latest' locally
docker: Error response from daemon: repository miykael/datalad_test not found: does not exist or no pull access.
See 'docker run --help'.
1 10915 ->125.....................................:Fri 04 May 2018 04:44:04 PM EDT:.
smaug:~
$> docker pull miykael/datalad_test
Using default tag: latest
Error response from daemon: repository miykael/datalad_test not found: does not exist or no pull access
```

if it is not on the hub, may be you could save it and share the resultant tar one way or another?

**Comment by miykael** [comment]
I prepared the docker image but forgot to push it... so close. But now it should be accesible via
```
docker run -it --rm miykael/datalad_test
```

**Comment by yarikoptic** [comment]
Thank you @miykael !  The issue is of two aspects and I was afraid that "bug ran away" but having that docker container saved the situation -- so, once again, great that you have it -- could you please tag/keep it for a bit :
1. To provide a copy of those files from our datasets.datalad.org I just did `get` straight on the server and forgot that it is a "dummy http git" transport setup and requires running "git update-server-info" which is invoked by `post-update` hook, which doesn't get invoked if non-checked out `git-annex` branch gets updated (by `get` command).    So, just regenerate the container or run `datalad update -r` on top of the dataset so it fetches all updated `git-annex` branches.  Then `get` should work and fetch data from the server
2.  in short: problem accessing files from docker smells to be docker specific!  To be continued here: http://git-annex.branchable.com/bugs/get_from_the_web_remote_fails___40__redirect__63____41___-_lack_of_further_debug_info/?updated

**Comment by miykael** [comment]
@yarikoptic - Wow, thank you! It finally works again :+1:
I will leave the docker image `miykael/datalad_test` on my docker hub indefinitely.
