### ISSUE TITLE
`run` could support call placeholders for input/output

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2512]
I started using the input/output spec feature intensely (thanks @kyleam!) and I find myself doing variants of this pattern all the time (pretty much):

```
datalad run -m "Import stimulation events" \
   --input inputs/rawdata/events.tsv \
   --output sub-02/func/sub-02_task-oneback_run-01_events.tsv \
   cp inputs/rawdata/events.tsv sub-02/func/sub-02_task-oneback_run-01_events.tsv
```

Admittedly, this is the extreme case, but here and in related cases it would be nice to be able to say:

```
datalad run -m "Import stimulation events" \
   --input inputs/rawdata/events.tsv \
   --output sub-02/func/sub-02_task-oneback_run-01_events.tsv \
   cp {input} {output}
```

such that `run` would transparently inject the (unexpanded) input and output specifications into the command list (multi-item extension, if there are multiple inputs/outputs, like done for `--call-fmt` in the `containers-run` command). We already support shell-style globbing, so this should work in a wide range of cases.

Additionally it could support placeholder expansion like `{input[3]}` (standard format() syntax) to reference individual items.

**Comment by yarikoptic** [comment]
Sounds like a good idea... but I wonder if that shouldn't be done automagically since cmdline invocation for a tool might have `{...}` in it?

**Comment by kyleam** [comment]
Yeah, that's quite close to the syntax used in Snakemake:

With inputs of "a" and "b", `{inputs}` -> "a b" and `{inputs[0]}` -> "a".  Same for outputs.

> such that run would transparently inject the (unexpanded) input and output specifications into the command list

Assuming a non-compound (i.e., `shell=False`) command, injecting the unexpanded values will fail because the command won't be able to deal with the globs that used to be expanded by the user's shell.

@yarikoptic:
> but I wonder if that shouldn't be done automagically since cmdline invocation for a tool might have {...} in it?

Yeah, that'd be a problem, though I'd say we should do it automatically and have a flag to disable it.
