### ISSUE TITLE
Disable batched annex on windows? (also on inability to rmtree etc due to locked files)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2518]
__del__ handling there is a common failure reason (windows is very attached to open files). It would be useful, if it could be turned off to see whether underlying functionality works, albeit slower
 Is that possible?

**Comment by yarikoptic** [comment]
IIRC there might be some commands where we ATM do not have/use `--json` output for non-batched versions... IIRC @kyleam even had to fix some recently for `run` functionality.  But there might be more

**Comment by kyleam** [comment]
> IIRC there might be some commands where we ATM do not have/use --json output for non-batched versions

Quickly grepping/scanning, I didn't spot any other offenders aside from the one fixed by 0181a70e0 (ENH: annexrepo: Make add_url_to_file always return json output, 2018-04-16).

**Comment by mih** [comment]
I am not following. Does this mean there is a switch, or that soemthing could be RF'ed in some way, but there is no switch?

**Comment by mih** [comment]
;-) Thanks for the translation!

**Comment by mih** [comment]
It seems to me that we should have a switch that turns on/off batched processing, and it should default to off on windows.

**Comment by yarikoptic** [comment]
I thought to suggest the same.  I am afraid though that many operations will literally "crawl" (and not `datalad crawl`) with a per-file invocation of git-annex.  May be it would be worth exploring the initial problem (original description is "too concise" IMHO to deduce anything) and see if it could be addressed without removing the use of batched processes?  I think that git-annex itself uses batched versions of some git commands on windows as well, and I guess it works ok, isn't it @joeyh?

**Comment by yarikoptic** [comment]
I wonder if at least some of those aren't real issues of us (or GitPython) not closing some files before trying to annihilate them/directories.  E.g. on linux this one works "just fine" (too many python opens since was playing around, file could be generated outside):

```shell
$> rm -rf /tmp/test; mkdir /tmp/test; python -c 'f=open("/tmp/test/1", "w"); f.write("1"); f.close(); f2=open("/tmp/test/1"); import shutil; shutil.rmtree("/tmp/test/"); print("READ: %s" % f2.read())' 
READ: 1
```
and I guess should fail on Windows?

**Comment by mih** [comment]
Probably, Q is just how would change the code? Not remove?

**Comment by yarikoptic** [comment]
I can only reply with another Q: who would change/remove what code?

If I cared about Windows, I would have tried to check if it is possible to see which files are still open in that directory before trying to remove it -- and if there are some, then deduce what module/process might still keep them open... actually it could probably be done even first within our code on Linux where we do have utilities such as `lsof` to see that  eg at `c:\projects\datalad\datalad\utils.py", line 325, in rmtemp` point

**Comment by mih** [comment]
Which seems to bring us back full circle. Have a switch to turn it off and see whether the underlying functionality is working or can be made to work at all. And if, try to make it faster....if.

**Comment by joeyh** [comment]
Michael Hanke wrote:
> [00:12:49] PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp-page2annexjkinu2k6'

If it helps, Windows has this fun behavior where opening a file for
read implicitly locks it, preventing a concurrent write.

(Bear in mind that Windows virus scanners may open any file for read at
any time..)

Naturally, this caused all manner of fun in git-annex on windows.

The general approach used in Windows to get around this seems to be to
busy-wait when a write fails, in hopes that the readers will get out of
the way. I kid you not. Busy-waiting is built into Windows api's 
such as createFile. There are also some less-used read modes that don't
lock the file.

This also causes problems with recursive directory removal, since if 
anything has a file in the directory open for read, removing it may fail
and then deleting the directory fail.

Enjoy your Windows Experience (TM)!

-- 
see shy jo

**Comment by joeyh** [comment]
Have you guys considered using WSL (aka "bash for windows") instead of
trying to support native Windows? I would kind of prefer to go that
direction with git-annex.

-- 
see shy jo

**Comment by mih** [comment]
@joeyh Yes, that is a parallel effort: https://github.com/datalad/datalad/issues/2475

**Comment by yarikoptic** [comment]
(possibly) relevant issues within GitPython (of which there are many): https://github.com/gitpython-developers/GitPython/issues?utf8=%E2%9C%93&q=label%3Atag.leaks+ , just now detected the one for cat-file --batched with #2542 helper

**Comment by yarikoptic** [comment]
In this particular case (not that things would work right away, but it is a step forward), I think it was our genuine mistake: https://github.com/datalad/datalad/pull/2791/commits/369d21fc5b37dd05e8bae478b82005d3ca9dfe6a

**Comment by mih** [comment]
Things are in a less desolate state on windows now that enable less radical approaches. Closing...
