### ISSUE TITLE
Option to store run records in annexed sidecar files

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2576]
Here is a scenario that might always lead to leakage of private information into a run record (TL;DR: identifying information somewhere in the path names): https://github.com/psychoinformatics-de/datalad-hirni/issues/16

As a general solution to the issue of sensitive information in file names (in subdatasets, that could be detached and stay private) with respect to leakage in run records, it would be nice to be able to GPG-encrypt run records.

There is already a place for the necessary config in git: `user.signingkey=...` so we could use that too.

`re-run` would then need to decrypt on-access.

@kyleam @yarikoptic

**Comment by mih** [comment]
Excellent idea. I had thought of this already in another context, but didnt made the connection that it would also help here.

I would very much be in favor of such a development.

**Comment by kyleam** [comment]
I too like the idea of being able to point to a file, and it's nice to see that it'd address this issue too.

---

Only slightly related: I've been thinking about whether using the `git notes` mechanism to store run information would be something worth exploring.  This is essentially a file pointing to a commit rather than a commit pointing to a file, but it shares some features with the file pointer: (1) you can modify the run information without changing the commit (could be seen as both good and bad, I guess) and (2) you could share the repo without sharing the run information, though it's at the level of the entire run history rather than per-file.  One benefit of the notes over files is that you could still see the information in the git log.  A major downside is that the user would have to fetch a non-standard refspec in order to  work with the notes ref.

**Comment by mih** [comment]
The notes option keeps coming back -- I still lack the intuition to make any useful step in this direction.

My plan would be to put the runinfo sidecar files into their own folder `.datalad/runinfo` (adjustable via config setting). The filenames would be some hash of the content (no real additional info, when the exact same command runs 10k times). Files would use JSON stream format (easy to concat without having to parse). Commit messages would replace runinfo dict with just the filehash, to be able to relocate the storage inside the dataset and still be able to find it. Actual sidecar storage can be triggered via a config flag (use case: always do this), or via cmdline option(use case: just this one).

Please stop me if that sounds wrong.

**Comment by kyleam** [comment]
> The notes option keeps coming back -- I still lack the intuition to make any useful step in this direction.

Yeah, I don't think all things considered that it's a direction worth going.  It just has enough there to make it interesting to consider.

> My plan would be to put the runinfo [...]
>
> Please stop me if that sounds wrong.

That all sounds in line with my current thinking.
