### ISSUE TITLE
Make order of keys in `run` record deterministic

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2581]
Appear to be random on running two consecutive commands.

**Comment by kyleam** [comment]
It's just a `json.dumps` call with a dictionary, same as it has been since run was first added.  It seems weird to label this as a bug, since it's never specified that these fields will be in some particular order within a message or the same order across messages. But I agree that it'd be better to sort the keys so that there's a consistent order when inspecting the logs and so that someone overriding dates can will get the exact same commit when running identical commands.

**Comment by mih** [comment]
@kyleam you are right, this is not a bug

**Comment by kyleam** [comment]
> @kyleam you are right, this is not a bug

Never mind, I was wrong!  It was the intention to sort the info keys, since from early on there has been  a `sort_keys=True` there,  but `run` has never actually sorted them because `sort_keys=True` has always been dropped as part of the `format` call due to a misplace ')'.

**Comment by yarikoptic** [comment]
one note -- json.dump with indent breeds trailing spaces, while at it you might want to add `separators=(',', ': ')`
```
$> python -c 'import json; print(json.dumps({1:2, 3:4}, indent=1));' | sed -e 's, $,-,g'
{
 "1": 2,-
 "3": 4
}
$> python -c "import json; print(json.dumps({1:2, 3:4}, indent=1, separators=(',', ': ')));" | sed -e 's, $,-,g' 
{
 "1": 2,
 "3": 4
}
```

**Comment by kyleam** [comment]
> one note -- json.dump with indent breeds trailing spaces, while at it you might want to add separators=(',', ': ')

Thanks, I wasn't aware of that.  Git cleans them up for us though:

```bash
% printf 'subj\n\n' > message
% python -c 'import json; print(json.dumps({1:2, 3:4}, indent=1));' >> message
% cat message | sed 's/ $/-/g'
subj

{
 "1": 2,-
 "3": 4
}
% git commit --allow-empty -F message
[master 1c46a2f] subj
% git cat-file commit HEAD | sed 's/ $/-/g'
tree 32b97a7332f485ca3b3fd33067b39c1ccd422ae2
parent 24c75a77c51a4a33cc7e3357c6647508df371ae8
author Kyle Meyer <kyle@kyleam.com> 1527608241 -0400
committer Kyle Meyer <kyle@kyleam.com> 1527608241 -0400

subj

{
 "1": 2,
 "3": 4
}
```
