### ISSUE TITLE
FOI: iter_entry_points requires "proper" installation since relies on having .egg-info

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2596]
#### What is the problem?
TL;ML (too long more later ;-) )  Debian package build fails, since dh-python helper runs tests within .pybuild/cpython2_2.7_datalad/build while datalad.egg-info is only within the main source codebase... that causes entry points for the extractors, even though shipped alongside with the main codebase, to not be found and tests to fail.

overall should be fixed in dh-python probably one way or another, but I also wondered if we should be more resilient to such cases and make sure that "entry points" provided within the main code base are guaranteed to be found in either case.  Moreover such centralization would be desired for "isolating" the build, so that it doesn't pick up something (older datalad?) installed system wide and possibly registering entry points as well -- then we could explicitly state to not include "outside" entry points while running package build tests

**Comment by yarikoptic** [comment]
ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900526  Piotr super quickly told howtoworkitout .  My concerns about entry points leaking from system wide installation still is in effect so keeping open

**Comment by mih** [comment]
That depends on how you desire the test "concept" to be. For the longest time we had tests that would not allow a user running them to alter any datalad-specific configuration items  that changed datalad's default behavior in their config, or the tests would fail. That was crap and got changed.

This is another flavor of this. Now, some tests may assume that you only have installed what comes with datalad core and may fail otherwise. I think this is a bug. Tests are not only for CIs and packages builds. We have a `test` command that *users* can use to test an installation. If our tests cannot handle a real installation, I think those tests are broken.

**Comment by mih** [comment]
Closing FOI
