### ISSUE TITLE
local caching of annexed files

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2668]
I am running many different analyses that use the same input. Each analysis result is a datalad dataset that captures the results, and link the input data as subdatasets, and potentially a container image as an annexed file.

It would be useful to have some kind of caching layer that makes it possible to resolve requests for annex objects **across** datasets. This is not the same as a local registry of previously downloaded datasets, as many such dataset might contain the same files (input and output).

@joeyh is there any way that I can inform git annex to consider another (local) object store/cache to obtain content from?

**Comment by yarikoptic** [comment]
I think this goes inline with what we briefly discussed in Montreal earlier this year.  Indeed, would be nice 
- to have a way to add (specify in git config, per repo or globally) that there is a "caching" remote which should be used as read-only (checked before `get`ing) or read-write (so also freshly fetched keys could be `copied to` upon successful get).  The only complication for RW access is some kind of locking would be needed I guess to prevent possibly two git-annexes writing the same key?
- there will be no records about presence/absence of keys in that remote within `git-annex` branch, so it would not anyhow have an impact on `git-annex` branch, `git annex` would merely check if key is present there for every key (so we would assume that the check is not too costly. which is the case if cache is local)
- it would be up to a "cache maintainer" to just run some `find -mtime +XXX -delete` or `find -atime +YYY -delete` in that cache location from time to time to trim some long unused items.
- not much of settings is needed for such `caching remote` and in most of the cases it would be just a path (or file://) prefix + mode (read-only or read-write), but in principle it could be more sophisticated with separate get/copy settings, e.g. `get`'ing prefix being an http:// url prefix, while (optional) `copying` url being an ssh:// url. Altogether, could probably support any protocol used/supported by annex.
- it would be super-awesome on a BTRFS system with COW support, where a simple `cp --reflink=auto` would be very efficient in "get"ing or "copying" into cache without wasting any space etc.

I think this would also make @satra happy ;-)
What do you think @joeyh ?

**Comment by joeyh** [comment]
I suppose that the simplest implementation is to make
Remote.remoteLocations speculatively include the uuid of the cache,
and make the cache have a special, low cost (eg 1).
That would make the get/copy/move/mirror/sync commands all try to get
content from it. If the cache lacks content it would nicely fallback to
other remotes without even an error message.

(The assistant seems to not use that, and perhaps there's some other
command that I'm overlooking that gets content and doesn't use that..)

If the admin is going to manually delete stuff from the cache, it would
need to be set as an untrusted remote, since Remote.remoteLocations is
also used by the numcopies code, and we wouldn't want git-annex to
count the cache as a copy.


Automically populating the cache after getting content would need to
hook into Annex.Content.moveAnnex somehow in order for it to work no
matter what code path got the content. That feels like quite a
layering violation though. Or it could hook into Annex.Transfer.download 
which is less of a layering violation but not used by every possible
code path.

Either of those lead to behavior changes though; you would not expect a
long pause after downloading a file while it's sent to the cache,
let alone a second progress bar for that upload. Hmm, it might be better
to just run the assistant in the background with preferred content set up
to make it want to send everything to the cache.

-- 
see shy jo

**Comment by joeyh** [comment]
Implemented remote.name.annex-speculate-present and also a 
--accessedwithin useful in cleaning such caches. Everything documented
here works:
http://git-annex.branchable.com/tips/local_caching_of_annexed_files/

Currently when content is copied into the cache, the location tracking
for the cache does get recorded. Might not be desired, or it might not matter.
And copying content into the cache is a manual affair unless the
assistant is used. So perhaps more to do around getting content into the
cache. Try it and see what more is needed for your use case.

-- 
see shy jo

**Comment by yarikoptic** [comment]
just uploaded 6.20180720+gitg03978571f-1~ndall+1 (don't get confused by the version ;-) ) which has that implementation to debian-devel of neurodebian.  Will test ride it locally before replacing current version in neurodebian?

**Comment by yarikoptic** [comment]
Lets consider this abstract one superseded by a more concrete #2763
