### ISSUE TITLE
Put a .noannex file in repo with `create --no-annex`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2669]
This is annex's way to mark a repo is not intended to have an annex, which that option indicates.

**Comment by mih** [comment]
This issue was moved to datalad/datalad-revolution#35

**Comment by yarikoptic** [comment]
I would really like to keep such issues open here until either get their fix in this codebase or -revolution gets absorbed in this code base, thus reopening with a label.
That is also an example of an issue where fix could've been implemented in this repo and benefit "revolution" (upon merge) if it was just a regular branch/fork instead of an extension.

**Comment by mih** [comment]
I wont touch issues anymore, promised.

Fork is still mutually exclusive with co-installation, hence still not an option.

**Comment by yarikoptic** [comment]
please do touch/annotate/etc the issues, just instead of closing add a label
what do you exactly mean by "co-installation"? e.g. do you want to use both `create` and `rev-create` commands?

**Comment by mih** [comment]
With #3383 merged, this is now fixed in master.
