### ISSUE TITLE
--no-drop for datalad remove

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2673]
#### What is the problem?
ATM `datalad remove` would also drop the content.  In my usecase, I just want `git rm` but with all our paths handling across subdatasets, and I think it is not possible (according to review of the cmdline options)

**Comment by kyleam** [comment]
> ATM datalad remove would also drop the content. In my usecase, I just want git rm but with all our paths handling across subdatasets

The content isn't dropped if `--nocheck` is used.  Since you're after the same behavior as `git rm ...`, the fact that a check isn't performed should be fine, right?

**Comment by yarikoptic** [comment]
So I think that the logic then needs to be fixed up as well.  I see (and read the doc of) `--nocheck` as a flag for `drop` action. And I think that is what it should be, it should not decide between `drop` and `no-drop`.  What do you think @mih?

**Comment by mih** [comment]
This was and is a complicated topic, hence the unsatisfactory situation. Which is even more complicated and unsatisfactory than what is described in this issue.

We need to consider that remove not just operates on files, but also on subdatasets. It is save to always git rm any file, because nothing is lost, and we can easily undo this action. The same isnt true for subdatasets. If we rm them, we rm the entire thing including its annex. If we do not drop in this case, we will see very unfortunate things being reported ;-)

So what do you want remove --no-drop to do in case of a subdataset? Just rm -rf ?

While thinking about this, I want to re remind the pending discussion on changing the location of the .git dir of subdatasets to lie within the parent and not within the subdataset, which would mitigate the problem to some degree.

**Comment by yarikoptic** [comment]
Just a note that IMHO changing location of storage to parent dataset would only complicate things, since now we would need to have even 1 more scenario where you would really remove it also from parent. Once again, imho, now we could just refuse to remove subdataset if --no-drop is provided and subdataset contains some annexed load. For regular files it seems to be a no brainier overall

**Comment by kyleam** [comment]
> The same isnt true for subdatasets. If we rm them, we rm the entire thing including its annex. If we do not drop in this case, we will see very unfortunate things being reported ;-)
>
> So what do you want remove --no-drop to do in case of a subdataset? Just rm -rf ?

Yeah, I was just looking into what the actual [change] could look like and quickly hit into the subdataset issue.  The best approach I could think of is to not propagate --no-drop to the subdataset uninstall calls, but from a user standpoint that's confusing and seems inconsistent (--nocheck to avoid checking and dropping with subdataset arguments but --no-drop to avoid dropping with regular path arguments).

[change]: https://github.com/datalad/datalad/compare/master...kyleam:enh-remove-nodrop

**Comment by yarikoptic** [comment]
re

> So what do you want remove --no-drop to do in case of a subdataset? Just rm -rf ?

Overall "remove subdataset" is similar to "uninstall subdataset; git rm subdataset", so it might be worth adding `--no-drop` to `uninstall` which would do the logic of checking if anything to be dropped, and if there is something reporting "impossible".  Then at the level of `remove` it would then be all consistent

**Comment by kyleam** [comment]
> so it might be worth adding --no-drop to uninstall which would do the logic of checking if anything to be dropped, and if there is something reporting "impossible"

I'm confused.  By default doesn't `remove` already abort if something can't be dropped?

```bash
%> git -C blah annex whereis
whereis foo (1 copy)
        5fceccd8-2f32-4327-906a-13f9e831626b -- kyle@hylob:/tmp/dl/blah [here]
ok

%> datalad remove blah
[WARNING] Running drop resulted in stderr output: git-annex: drop: 1 failed

[ERROR  ] unsafe; Could only verify the existence of 0 out of 1 necessary copies; Rather than dropping this file, try using: git annex move; (Use --force to override this check, or adjust numcopies.) [drop(/tmp/dl/blah/foo)]
drop(error): /tmp/dl/blah/foo (file) [unsafe; Could only verify the existence of 0 out of 1 necessary copies; Rather than dropping this file, try using: git annex move; (Use --force to override this check, or adjust numcopies.)]
[WARNING] could not drop some content in /tmp/dl/blah ['/tmp/dl/blah/foo'] [drop(/tmp/dl/blah)]
drop(impossible): /tmp/dl/blah (directory) [could not drop some content in /tmp/dl/blah ['/tmp/dl/blah/foo']]
action summary:
  drop (error: 1, impossible: 1)
```

That check happens in `_uninstall_dataset`:

https://github.com/datalad/datalad/blob/8dbe463255cb74bb208daca164eebe6faf0f1964/datalad/distribution/uninstall.py#L43-L56

> Then at the level of remove it would then be all consistent

How so?  What I showed is the default behavior, but that seems to be what you're proposing as the  `--no-drop` behavior?  But then if you skip the drop check in `_uninstall_dataset` by default, `remove` becomes much less safe because, unlike the plain path case, you can't recover from the operation since the dataset will then be removed.

IMO the best approach is still the one I mentioned above: don't propagate --no-drop to the dataset uninstall calls, documenting that `--no-drop` doesn't apply to dataset arguments.

**Comment by kyleam** [comment]
> With --no-drop it would just right away say "impossible" to remove that subdataset

So you just want --no-drop to fail if the subdataset to be removed has any annexed files?  That doesn't sound like a useful option to me, but I think it is what you're suggesting because otherwise it doesn't matter whether the files are dropped or not after a check since the dataset will be removed anyway.

**Comment by yarikoptic** [comment]
> So you just want --no-drop to fail if the subdataset to be removed has any annexed files?

yes (just to make sure, to be precise --"has any annexed files with content for them available locally"). 
As for a usecase for having --no-drop in uninstall -- I would quickly uninstall all subdatasets which I've might installed but for which I didn't even bother getting any data files.  If I did get some files -- might mean that I needed them for analysis and thus better retain that subdataset.  Consider e.g. someone installing (yet to be provided) hcp dataset which will have thousand(s) subdataasets, and then ending up analyzing only a few.
As for remove -- could be similar -- I point to `--no-drop *` which might expand to some subdatasets and files with intension to "wipe it out from the current tree in git". If any of subdatasets have still load in them, I then could decide on one by one case either I want to drop their load (thus will run rm without --no-drop) or just keep them in the tree for now.

**Comment by kyleam** [comment]
Thanks for explaining your use case.  With my (limited) knowledge of remove/uninstall/drop, I don't have any major objections, but I do have some minor comments.

On a conceptual level, I find the --no-drop distinction between regular path arguments and dataset arguments unintuitive.  For regular paths, it would simply mean "don't call drop".  For dataset, it means "don't call drop" superficially, but in my view it's more accurately "change uninstall's check from a try-to-drop to this other thing". 

On a technical level, it will involve deeper changes than those in [enh-remove-nodrop] because a second type of check has to be added to `uninstall`.

[enh-remove-nodrop]: https://github.com/datalad/datalad/compare/master...kyleam:enh-remove-nodrop
