### ISSUE TITLE
More flexible substitutions for `run`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2684]
So far we have been adding supported place holders one by one. However, I think we need more and we shouldnt implement them ourselves. Current use case:

I need to provide license info to a command call that is different depending on where the execution is happening. Ideally, there would be a way to put this info in the config, and have it be overwritten by user config if needed.

That could be achieved by something like: have a dedicated cfg namespace datalad.substituions.LABEL, where LABEL can be any valid config name and can be used in any  call like {LABEL}. Run would simple take this namespace and pass it on for string formating.

What do you think?

**Comment by kyleam** [comment]
> What do you think?

You have a need for it and the implementation seems straightforward enough, so that sounds fine to me.

> However, I think we need more and we shouldnt implement them ourselves.

Hmm, I think there are three categories of placeholders: (1) run-specific placeholders (`inputs`, `outputs`), (2) installation-specific placeholders for which there is a shared way to determine a unique value (`pwd`, `dspath`), and (3) installation-specific placeholders for which the value is flexible.  The method you propose would add support for (3).
