### ISSUE TITLE
Provide mechanism to easily set up .datalad/providers/ configurations on a dataset level

### ISSUE THREAD

**Issue by driusan** [datalad/datalad#2750]
#### What is the problem?

When someone is setting up a new dataset in datalad to use the datalad crawler, by default only the configs which are provided with the datalad install are known. If using something like the a LORIS providers to crawl other server users need to know to copy the config file from datalad's source to the right directory for the dataset and then tweek the urls (datalad only knows demo.loris.ca in the default install.)

It would be useful to have a well documented datalad subcommand which easily sets up authentication schemes in a dataset (ie. manages the `.dataset/providers` directory) from the command line rather having to know that they need to copy a file from a subdirectory of a subdirectory of the datalad repo and tweak the URLs.

#### What steps will reproduce the problem?

Sit with someone who knows nothing about datalad and help them set up a crawler for their dataset which isn't included in the base datalad install.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.10.2

#### Is there anything else that would be useful to know in this context?

Not really a bug, just a suggestion. (There may be some config command that I'm overlooking which already does this.)

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

Some.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2272 (DataLad requires git configuration), https://github.com/datalad/datalad/issues/2189 (How .datalad/metadata/dataset.json to be born?), https://github.com/datalad/datalad/issues/405 (datalad install of a subdataset into a dataset fails since provides None to git submodule call), https://github.com/datalad/datalad/issues/1193 (datalad mv), and https://github.com/datalad/datalad/issues/2345 (datalad search --help should provide what it asks for).

**Comment by driusan** [comment]
I'm giving @yarikoptic-gitmate a score of 2/5 on that one.

**Comment by yarikoptic** [comment]
please have a look at https://github.com/datalad/datalad/pull/2708  - it lost its original focus and introduced a basic interface to add new providers when we detect some new non-authenticated access.   Could you @driusan give it some test run?
I would like to add some tests next to the logic in all that authentication handling since I am afraid it is far from an ideal one. 
Also eventually I  guess I better add support for HTTP authentication "realm" which I totally ignored.

**Comment by yarikoptic** [comment]
I believe we did address the original issue (providers at dataset level) in #2708 which was included in 0.10.3.  Please reopen if not the case
