### ISSUE TITLE
Documentation - dataset.siblings() does not have result_renderer to None by default

### ISSUE THREAD

**Issue by simon-dube** [datalad/datalad#2762]
#### What is the problem?
In the [documentation](http://docs.datalad.org/en/latest/generated/datalad.api.siblings.html), it is said that "sibling information is rendered as one line per sibling following this scheme". However, next to the `result_renderer` parameter, it is said to be `None` by default. However, it is required to manually set it to `None` in order to hide the siblings rendering.
#### What version of DataLad are you using?
Datalad: datalad 0.10.1
OS: Ubuntu 18.04.1 LTS

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/779 (`uninstall` doesn't uninstall dataset), https://github.com/datalad/datalad/issues/2449 (`install()` returns None not Dataset instance), https://github.com/datalad/datalad/issues/1273 (create-sibling --since doesn't "recurse" correctly), https://github.com/datalad/datalad/issues/1400 (Dataset class should get some basic documentation), and https://github.com/datalad/datalad/issues/2005 (datalad create-sibling-github doesn't support oauth).

**Comment by andycon** [comment]
Indeed the available parameters for this are ['default', 'json', 'json_pp', 'tailored', or None].
The actual default behavior is 'tailored', in conflict with the documentation which says its None. And the option 'default' is a poor name most likely a relic left in place so not to break anything. Simple fix will be to change the doc string to reflect current reality.
