### ISSUE TITLE
[question] levels of a dataset

### ISSUE THREAD

**Issue by vsoch** [datalad/datalad#2825]
This is another follow up question from:

https://github.com/datalad/datalad/issues/2814#issue-359426631

On the Github repository for datalad, I am able to explore many levels into a dataset, e.g.,: http://datasets.datalad.org/?dir=/adhd200/RawDataBIDS/NeuroIMAGE

When creating datasets, in that you can create subfolders with their own datasets, at what level is (traditionally) appropriate to initialize? Is the standard to call git init at the root, and then define a datalad dataset at each level? Just the top level?

Given this decision, what makes it possible to interactively click into all those levels?

Is this website just another remote for the actual dataset and this is possible because you are using a module to browse the file system?

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1028 (Dataset singletons), https://github.com/datalad/datalad/issues/656 (ADHD200 dataset), https://github.com/datalad/datalad/issues/36 (Mitchell's dataset), https://github.com/datalad/datalad/issues/2801 ([question] the "dataset id" is meant to be the same for all siblings, correct?), and https://github.com/datalad/datalad/issues/824 (how to uninstall a dataset???).

**Comment by mih** [comment]
Let me add one more, rather conceptual, aspect. There is no need to decide on a single order/nesting of datasets. Maintaining a hierarchy, such as http://datasets.datalad.org, comes with costs. For example, changes in the nesting (because you feel like grouping by topic, instead of origin) require extensive operations.

It is important to realize that only direct parent/child (super/subdataset) relationships actually exist, and all other relationships are indirect. Hence it is often more practical to limit subdataset organization to a plain list (pretty much the model Github uses, there is the one list of repos in your account and everthing else is done via some kind of tags).

If you have subdatasets in a plain list, the URLs through which they are exposed is also unaffected by any semantic/conceptual relationship between datasets (that might change over time).

At the same time, nothing prevents users from maintaining *additional* topical collections of dataset's, e.g. all datasets from openfmri vs. all datasets on face perception. Also, nothing prevents a dataset from being part in more than one of those collections (at the same or different versions).

**Comment by vsoch** [comment]
Oh I didn't know about [git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) this is super cool! +1 to what you said above, and the general idea of not enforcing some strict thing beyond pretty high level `parent/child`. Closing.
