### ISSUE TITLE
[question] What determines the naming of the superdataset? The datasets within?

### ISSUE THREAD

**Issue by vsoch** [datalad/datalad#2826]
This is another follow up question from:

https://github.com/datalad/datalad/issues/2814#issue-359426631

What are the naming conventions used for describing a superdataset? A dataset? Is the Github namespace used to ensure uniqueness, and how can I be sure that my "brains" dataset isn't a bad idea because someone else also has one named the same thing?

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/35 (ENCODE datasets), https://github.com/datalad/datalad/issues/754 (published datasets with spaces in the names are not shown in webview), https://github.com/datalad/datalad/issues/660 (BALSA datasets), https://github.com/datalad/datalad/issues/1715 (inconsistent use or translation of name/title(shortdescription?) among datasets), and https://github.com/datalad/datalad/issues/2462 (`install .` within a subdataset with + in its name errors out).

**Comment by yarikoptic** [comment]
I think there might be some confusion since I think you referred to our superflashy http://datasets.datalad.org/ as Github on a number of occasions I think.  Nothing in there relates or instructed by  github pretty much.  It is just a plain static website with an `index.html` we upload when `--ui true` is provided to `create-sibling`.  Because of that we can have an arbitrarily deep hierarchy of subdatasets (git submodules), which is not possible on github.

There is no strict/clear convention we (or I to get all the blame for that) use for including datasets on datasets.datalad.org, besides that we try to group by a hosting project (hence `openfmri`), or a project itself if dataset has the life of its own, or a lab (under `labs/`) or workshop (under `workshops/`) etc.  I hope it makes some sense ;-)
In your "superdataset" you could have your "brains/" if you really like, but indeed it might be hard to "identify" such a dataset, although it might be an appropriate name for some subdataset with a study, along with other subdatasets such as "intestines/" and "undefined/" ;)

**Comment by mih** [comment]
> What determines the naming of the superdataset?

@yarikoptic does. ;-) (for http://datasets.datalad.org)

This is a collection of datasets maintained by him, hence he makes the decisions. Not just regarding the names of superdatasets, but also regarding the levels of nesting etc. A different maintainer of a different collection can easily go for a different model. Your dataset, your choice.

There is one special aspect here, as http://datasets.datalad.org is not just a re-mix of datasets presented in a specific view, but in fact the actual origin of many of its datasets (but not for all of them). However, that does not change the fact that each dataset in this collection is its own entity, and it would probably be less then an hour to create a new superdataset that has all datasets from http://datasets.datalad.org re-mixed in a different way (e.g. a flat list) and post that on github.

**Comment by vsoch** [comment]
Ah ok, understood, all hail @yarikoptic master of the data! This is something that is good to know that I'll think about as I develop stuffs. I think likely a strategy we can somewhat hope for is that the organization and naming doesn't matter **so** much because the metadata and search of it can provide the discoverability that a user needs.
