### ISSUE TITLE
[question] default superdataset location

### ISSUE THREAD

**Issue by vsoch** [datalad/datalad#2827]
This is another follow up question from:

https://github.com/datalad/datalad/issues/2814#issue-359426631

How do I change some default location from `$HOME/datalad`? If I create it there, does this mean that I cannot install another superdataset without overriding that one?

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2826 ([question] What determines the naming of the superdataset? The datasets within?), https://github.com/datalad/datalad/issues/2825 ([question] levels of a dataset), https://github.com/datalad/datalad/issues/2032 (What should search do different by default?), https://github.com/datalad/datalad/issues/222 (Stop being scary by default), and https://github.com/datalad/datalad/issues/2799 (question: what is .datalad/.gitattributes).

**Comment by yarikoptic** [comment]
oh @yarikoptic-gitmate , I really wish you would have found the #2792 ;-)  
For now you can probably just symlink your desired location as `~/datalad`.  But #2792 is a nice/easy issue to get your hands dirty in datalad code.  Should be just a matter of defining one more config variable defaulting to that location.  Then you could redefine it at any level (system/user/dataset) via git config.

At some point, we actually excercised the idea of making it possible to have multiple registered superdatasets, so instead of `///` as identified you would use `//mysuper1/` where it would correspond to some known location etc.... not there yet either since were not much demand yet.

**Comment by vsoch** [comment]
I think it could mirror how golang does it, `$GOHOME` points to the root. That way, you could define a custom root. And then for individual commands, given that you want a different home, you could also just do it for the command, e.g.,

```
DATALAD_ROOT=/tmp/test datalad...
```
or I would say supporting a custom flag is also nice usability wise?

```
datalad --root /tmp/test ...
```

**Comment by vsoch** [comment]
Is the convention that the superdataset is always after the double slashes? E.g.

```
//<super>/<dataset>
```
So are users always needing to do a triple slash to specify a default?

```
///<dataset>
```
We just wouldn't want to confuse these two things:

```
///<dataset>/<subfolder>
```
with
```
//<superdataset>/<dataset>
```
or something like that :P

**Comment by yarikoptic** [comment]
re `DATALAD_ROOT` -- such name would be a bit too ambiguous, since might be considered as the path for the current dataset root or alike.  In our case we just want to specify location for the "canonical" superdataset, if you aren't in any dataset ATM... so not sure

as for passing them to datalad call: all is there already -- see http://docs.datalad.org/en/latest/generated/datalad.config.html.  So pretty much any config variable could come from git configuration, .datalad/config or being specified in the command like `datalad -c ` (similarly to git), and even passed via an environment variable
