### ISSUE TITLE
[datalad] put action

### ISSUE THREAD

**Issue by vsoch** [datalad/datalad#2829]
This is the final follow up question from https://github.com/datalad/datalad/issues/2814#issue-359426631

Assuming I've added data and have metadata defined, I then want to get it onto Google Cloud. I know that I could do the equivalent of a clone and then get, but is there a put action? I would want an integration with Google Cloud Storage (or another git annex remote) to "put" data there? Based on a version? From a third place I would then want to be able to do the equivalent of:

 1. `datalad search` ... find my dataset and version
 2. `datalad get gc://...`  get a particular version
 3. And then I can create an archive on my server. It's probably beyond the responsibility of datalad to do that, but I can maintain the file structure or use the powers of gzip or similar.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/227 (datalad get  barfes), https://github.com/datalad/datalad/issues/562 (datalad create   booms), https://github.com/datalad/datalad/issues/2693 (datalad aliases), https://github.com/datalad/datalad/issues/2828 ([question] Validation and Datalad), and https://github.com/datalad/datalad/issues/1193 (datalad mv).

**Comment by yarikoptic** [comment]
Such places where data could be "put" (but which are not git repositories themselves, like if you just had a git clone available over ssh) are called ["git annex special remotes"](https://git-annex.branchable.com/special_remotes/).  git-annex internally provides support for a [number of data hosting solutions](https://git-annex.branchable.com/special_remotes/) to be connected this way, but not all of the existing ones unfortunately.  The "most used"/developed is AWS S3. But git annex allows to extend itself with support for pretty much any new type of similar special annex remote.  That is how we made it possible to e.g. obtain files from tarballs whenever some websites (such as crcns.org, figshare, etc) provide their datasets as a set of tar or zipballs.  git-annex then talks to our custom special remote (called `datalad-archives`) and that one extracts files git annex asks for.

For google cloud, you would need to install/use an additional special remote: https://github.com/DanielDent/git-annex-remote-rclone  which provides access to Google cloud storage.

Then `datalad get FILES` (via `git annex get` underneath) should automagically obtain them from GC or whereever else they are available for that particular version as you have in your current commit.

On DataLad side we could potentially
- provide some (convenience) interface for initializing such special remotes
- "bundle" rclone + git-annex-remote-rclone in our distribution (well, pretty much probably just package for conda, since it might be eventually the easiest non-NeuroDebian way to install datalad. Already works for Linux ;) )

For the archive on your server, you can already get nearly 100% replica of http://datasets.datalad.org simply by `datalad create-sibling --ui true -s myserver  myserver:/path` if you have datalad installed on the `myserver` and `/path` is served via http. Then whenever you `datalad publish --to=myserver -r`, it would populate the index to be used to browse your repository on your server via http.
Quick google lead me to some "3rd party" notes adopted from our asciinemas at https://www.datalad.org/features.html which might be of interest as well for more details/complex scenarios (e.g. to publish data to myserver while also pushing git repo itself to github):
https://github.com/khanlab/datalad/wiki#4-make-a-remote-to-actually-store-the-files

**Comment by mih** [comment]
I think this can be closed for now. Feel free to reopen if there is need for more clarification and progress in any direction.
