### ISSUE TITLE
"add" vs "save" and unlocked files in v6

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2862]
#### What is the problem?

I guess it all depends on either we might want to treat the ability of committing "unlocked state" into git/git-annex as a pointer file (when file is unlocked, and you do `git commit file` or `git add; git commit`, also depending on .gitattributes config) as a "feature" we should use/embrace or try to avoid.  
So far IMHO in all use cases I would prefer to commit the actual git annex symlink into git, even if file was unlocked.  And may be in some cases leave it unlocked in the tree for further changes.  I really see no point of committing a pointer file really.  What do you think?

And that is what we are getting (committing the annex symlink) if I do `datalad add unlocked_modified` (which internally likely does `git annex add` to make it happen).
But we are committing the pointer file if I do just `datalad save`, and annex symlink if I specify the file `datalad save unlocked_modified`.

Overall this dichotomy between annex symlinks and pointer files could cause the next level of confusion for regular users.

**Comment by mih** [comment]
I would prefer to go one more step back and talk about the default representation of a datalad dataset on the file system. There is a case to be made to use the (equivalent of) v6 unlocked form on any system as the (or at least the default) representation on the file system. The reason being simply that dereferencing symlinks by 3rd-party software is a real usability issue for datalad dataset (`git annex add` the output of an FSL FEAT analysis and try to view the `report.html` for one example, but this is just the tip of the iceberg).

> So far IMHO in all use cases I would prefer to commit the actual git annex symlink into git, even if file was unlocked. And may be in some cases leave it unlocked in the tree for further changes. I really see no point of committing a pointer file really. 

Counter question: Where is the real difference between committing one or the other?

In datalad still too much code and logic is (falsely) based on the semantics of symlinks on the file system. If those shortcuts are found and removed, what difference would it make?

There are two advantages one has with symlinks:

1. Immediate failure on `open()` for any program, even those not aware of git-annex.
2. Protection against accidental overwriting of data.

I'd argue that 2) is a non-issue, if the default usage paradigm of datalad is "always-clean". And I'd argue that the impact of 1) is massively different depending on whether we are looking at the data consumer case (I obtained a dataset from elsewhere) vs. the data producer case (I work with my own/already available data locally). In the latter case, data files without content are an exception (hence (1) is a non-issue), whereas in the former case they are the rule (and (1) is an issue.

I am asking myself:

- are there legitimate reasons to mix locked and unlocked files on symlink-capabale FSs? I think so, for the reasons of additional disk space demand alone (ignoring `annex.thin` and its implications for now).
- do usability issue from dereferencing symlinks outweigh usability issue from not easily seeing absent content from missing symlink targets? Here I am leaning towards preferring to see the former to be no longer an issue, as it affects inspecting the "final" state of a dataset, where the latter is mostly a concern of (inappropriately) working with a dataset.

**Comment by mih** [comment]
Loosely related #2867 (what is it, that should be published, in relation to what is locally checked out)

**Comment by bpoldrack** [comment]
The different behavior of `save` and `add` as @yarikoptic pointed out, is something to clean up - yes. But  how to do it does indeed depend on figuring out a logic, that is valid for v6. That's currently not the case. 

I don't see how we could or why we should possibly avoid having those pointer files. First, it's standard behavior of `git-annex` for an unlocked file with no content present in v6. If we want to stick to the paradigm of being able to use `git/git-annex` with datalad datasets (which I think we should!), we need to be able to deal with that anyway. Datalad logic, that can't handle it, is invalid for v6. Simple as that in my opinion.
Second, it's needed for file system with no symlinks. So again - we need to be able to deal with that.
Third, at some point v6 might become default mode of operation for `git-annex`, which leads to the same point: We would behave unpredictable for `git-annex` users at some point, if we were enforcing a different representation and we suddenly wouldn't be able to handle a perfectly fine annex repository.
I simply cannot see how we wouldn't get into deep trouble, if we tried to somehow enforce symlinks.

So, to me it pretty much boils down to: Do we want to go for a default usage paradigm, where we lock (or unlock) files when committing by default pretty much similar to the always-clean-approach?
We would still need to be able to deal with mixed repos (at the very very least be able to detect it - instead of mistake a pointer file's content for the actual content - and fail with "please lock/unlock everything") and the always-lock default behavior would need to come with a `--dont-lock` switch, analogous to `--no-save` (or in case of an always-unlock-approach, it would be `--lock`).

> I am asking myself:
> - are there legitimate reasons to mix locked and unlocked files on symlink-capabale FSs? I think so, for the reasons of additional disk space demand alone (ignoring `annex.thin` and its implications for now).

I agree. Also committing an unlocked (and locked for other files) state might help with `run`, particularly if a complex thing to be run is to be called by a user who can't easily tell what are the output files that need to be unlocked and can't easily automatically be detected either. If he can be pointed to a readily mixed state to base the call on, that might help.

> - do usability issue from dereferencing symlinks outweigh usability issue from not easily seeing absent content from missing symlink targets? Here I am leaning towards preferring to see the former to be no longer an issue, as it affects inspecting the "final" state of a dataset, where the latter is mostly a concern of (inappropriately) working with a dataset.

I don't think I entirely got your thoughts here, @mih . In what sense is the state concerned with the first issue "final" and how does this make the issue disappear?
Regarding the second issue: All depends on what "easily seeing" means. Since I think we need to be able to detect those files anyway, we can make them visible via `datalad ls` or something similiar.


> There are two advantages one has with symlinks:
> - Immediate failure on open() for any program, even those not aware of git-annex.
> - Protection against accidental overwriting of data.
> I'd argue that 2) is a non-issue, if the default usage paradigm of datalad is "always-clean". And I'd argue that the impact of 1) is massively different depending on whether we are looking at the data consumer case (I obtained a dataset from elsewhere) vs. the data producer case (I work with my own/already available data locally). In the latter case, data files without content are an exception (hence (1) is a non-issue), whereas in the former case they are the rule (and (1) is an issue.

I'd argue that (2) doesn't necessarily become a non-issue just because you can clean it up. You might really want to fail early instead of discovering you changed files you shouldn't have changed days after a huge data processing pipeline was started. This may remain at big annoyance even if you started clean.
I agree with what you said about (1) though.

Conclusion for me: Make always-lock the default behavior (which can be turned off per call as well as entirely via config), but way more importantly be able to accept mixed repositories and not mess them up.

**Comment by bpoldrack** [comment]
Just to be clear: I do think, that always-unlock would be more intuitive for a lot of potential users. But I'd rather like them to know how to avoid issues by unlocking files, than require them to know how to clean up if things went wrong.

**Comment by kyleam** [comment]
@bpoldrack:

> Conclusion for me: Make always-lock the default behavior (which can be turned off per call as well as entirely via config), [&#x2026;]

I lean towards that default too, but regardless of the default I agree that being able to control it globally and per-call (e.g., `--lock=(default|yes|no)`) is important. I think which approach makes sense&#x2014;always/mostly locked or always/mostly unlocked&#x2014;will vary a lot between users or even between a user's different projects (e.g., one project frequently uses software that doesn't play well with symlinks).

**Comment by mih** [comment]
Going with the title this issue can be closed: `add` no longer exists.
