### ISSUE TITLE
RF GitRepo.get_git_dir() to use rev-parse call

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2888]
See https://github.com/datalad/datalad/pull/2886#pullrequestreview-160396142

**Comment by bpoldrack** [comment]
I'm actually quite sure we used `rev-parse` (may be in a different function) before and there was a reason to switch. I remember, that we generally got into trouble with `.git` either being a symlink or a ".git-file" in submodules, since git itself failed to fully support both (which it is supposed to and joey complained). Not sure whether this is still the case.

**Comment by kyleam** [comment]
> I'm actually quite sure we used rev-parse (may be in a different function)

Yes, must have been a different function.  `get_git_repo` has remained nearly unchanged since its introduction in f880d6688 (ENH: Finishing --create option for install, 2016-03-08).

`git log -S'-git-dir' -- datalad/support/{annex,git}repo.py` point to
6dc4c31f5 (BF: get_toppath didn't actually work in direct mode yet, 2017-06-01) and eeedc728a (BF: get_toppath used wrong Runner class and therefore system-git instead of bundled one BF: older git versions don't support git-rev-parse's option --absolute-git-dir, 2017-06-06).

Those probably aren't what you're thinking of though because neither of those avoid `--git-dir`.  Perhaps the issue was discussed in a PR/issue but never made its way into master.

>  I remember, that we generally got into trouble with .git either being a symlink or a ".git-file" in submodules,

OK.  Quick testing on my end (git v2.19.0) suggests `git rev-parse --git-dir` identifies what (I think) is a reasonable git directory in all three submodule cases (submodule as gitfile, as symlink, and plain .git/), but perhaps older versions of git don't.

Anyway, there's no reason to change something that's working and risk introducing issues.
