### ISSUE TITLE
Exclude 'notneeded' messages in default result renderer

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2930]
I somewhat remembered that @yarikoptic had proposed that before, but I cannot find the issue.

**Rational**: `notneeded` results are reported when there is nothing to do or nothing was done, so from the perspective of an activity log there is nothing to report.

**Counter argument**: When there is no progress bar, those message could serve as (the only) activity indicator. OTOH it is even simpler to send log messages feeding a progress bar than to compose a result record, so such cases could easily be RF'ed.

**Clarification**: I do NOT propose to stop emitting `notneeded` results (those are essential, at least for me), but I want to suppress their rendering in the default renderer. This will not affect any custom rendering that may be implemented by particular commands.

**Comment by yarikoptic** [comment]
I think that originally I was whining about not `notneeded` but `ok` ones since they flood the screen upon any reasonably sized dataset `get`.  Actually I have now
```shell
$> git config --global datalad.report.status 
failure
```
but I guess it (not longer?) in effect since I do get all the `ok` and `notneeded` messages reported.

I voted for not reporting `notneeded` - they are indeed not needed .

Re UI progress bar of some kind for activity indication.  I think we should indeed get some generic progress indicator which would "spin" (or "scroll" in one line) upon receiving any result, and may be even ideally also upon any log message if we decide eventually to swallow them by default.

**Comment by kyleam** [comment]
> I think that originally I was whining about not `notneeded` but `ok` ones since they flood the screen upon any reasonably sized dataset `get`. Actually I have now
> 
> ```shell
> $> git config --global datalad.report.status 
> failure
> ```
> 
> but I guess it (not longer?) in effect since I do get all the `ok` and `notneeded` messages reported.

s/report.status/runtime.report-status`
