### ISSUE TITLE
Sufficient test condition to collect data for progress bars

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2962]
Which conditional could I run to see whether a progress bar would actually be displayed that covers all circumstances?

Reason for asking is that in -revolution I am trying top minimize the number of git/annex calls to achieve faster operation, and there is no point in figuring our file-sizes (e.g. for `add`), if in the end that information is not used for something visible.

**Comment by yarikoptic** [comment]
"actually be displayed" -- I think there is no way to figure that out 100% since it might even be not displayed by tqdm if it is too short lived.  Also to figure out if we (in our datalad code) will display or not a progressbar - not sure if possible.  So may be one of the

- for that specific function you are talking about it could get an option `get_filesizes` or a like to explicitly ask for them?  then the function which has an idea that progress bar would be used could ask for it?
- instead of actual size(s) provide a callback which would query for the size for that entry?

Sorry if nothing of those seems like a good choice
