### ISSUE TITLE
Error: type object got multiple values for keyword argument 'name'

### ISSUE THREAD

**Issue by adelavega** [datalad/datalad#3000]
#### What is the problem?
Trying to create a sibling dataset on TACC, in a folder that will be publicly visible on the web. The idea is to host preprocessed (fmriprep) datasets for neuroscout on there. 

`datalad create-sibling -s test delavega@ls5.tacc.utexas.edu:/corral-repl/utexas/neuroscout/neuroscout-data/SherlockMerlin --as-common-datasrc tacc`

The following error occurs during the process:
```
[INFO   ] Connecting ... 
[INFO   ] Considering to create a target dataset /home/alejandro/datasets/neuroscout-datasets/SherlockMerlin at /corral-repl/utexas/neuroscout/neuroscout-datasets/SherlockMerlin of ls5.tacc.utexas.edu 
[INFO   ] Fetching updates for <Dataset path=/home/alejandro/datasets/neuroscout-datasets/SherlockMerlin> 
[ERROR  ] type object got multiple values for keyword argument 'name' [siblings.py:_configure_remote:543] (TypeError)
```

It seems to work without the `--as-common-datasrc` argument. I'm assuming this is necessary for others to be able to do `datalad install` with this dataset. The plan was to also add a `target-url` (once the web server is turned on), and publish to github. 

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.11.0 (on workstation)
0.11.0 (on TACC, installed through conda, due to lack of admin)

**Comment by bpoldrack** [comment]
First of all, I want to clarify the idea of `--as-common-datasrc`, since this indicates that it might not be entirely clear (or may be it is - just want to be sure):

> I'm assuming this is necessary for others to be able to do datalad install with this dataset. The plan was to also add a target-url (once the web server is turned on), and publish to github.

You don't need `--as-common-datasrc` in order to be able to `datalad install` from the sibling you're creating. Instead, this is for letting *other* siblings know about this one as a source to fetch actual data from. What I think you want to do is: `datalad create-sibling` with `--as-common-datasrc` as you tried to (you got that right), then `datalad create-sibling-github` (probably with `--publish-depends`). This would result in a user who installs from github to have a dataset that also knows about the sibling on `ls5.tacc.utexas.edu`. Since you can't (easily) provide data on github itself, you can use github to distribute the dataset while providing the actual data somewhere else. Using `--publish-depends SIBLINGNAME` (`test` in your case)  for your github sibling would then make sure, that whenever you publish to github, publishing to that other sibling providing the data is automatically done first.
But: configuring that common data source requires a URL, that can be recorded as the one to use for fetching data from that source. And since fetching would be done when this special remote `tacc` is configured, you would probably need that web server to run already. I'm not entirely sure ATM, but I guess, if you provided a valid `--target-url` at the same time, the call should work.

However, there clearly is a bug here. At the very least the failure should look differently.So, thanks for finding it!
@datalad/developers:  The code path taken within `create-sibling` is wrong. This is not just a misleading error message. It leads to a trial to configure sibling `test` and special remote `tacc` at the same time within the same call to `configure_sibling`. Need to dig deeper though. 

@adelavega : Note, that you don't necessarily need to use `--as-common-datasrc` on creation of that sibling. You can set it up and use `datalad siblings configure` to declare it a common data source later on.

**Comment by yarikoptic** [comment]
yeap, a bug... we should fix it and also adjust and/or extend our examples at https://www.datalad.org/for/data-publication .  IMHO ideal "setup" should include use of following flags
- `--with-ui true` so you could also get similar simplistic but quite functional for navigation/exploration setup as http://datasets.datalad.org on your http server
- `--annex-wanted "not metadata=distribution-restrictions=*"` to state that you would like, by default, to publish all data (but the ones with `distribution-restrictions` annex metadata flag set to any value)
- `--target-url` and `--as-common-datasrc someuniquename` so that this sibling/clone would become known to any clone of this repository from any other location (e.g. github) without requiring adding it manually as a git remote

**Comment by adelavega** [comment]
Perfect. Thank you for your clarification @bpoldrack, that was very helpful. What you said is indeed what I planned to do. I'm just waiting on the URL to be functional (previously trying w/ broken URL threw an expected error). Should be by this afternoon so I can test adding that flag. 

Yes, docs for this would be very helpful. I was going off what @mih  had sent me over email. I think it's a very cool use case that should be highlighted!

The only question that remains is the second of @yarikoptic 's suggestions. It's not clear to me why that's necessary. Why wouldn't "all data" be published with `datalad publish`?

**Comment by bpoldrack** [comment]
> It's not clear to me why that's necessary. Why wouldn't "all data" be published with datalad publish?

It's not necessary and `datalad publish` would publish all data by default. But what @yarikoptic is pointing out is that docs should show how to set it up in a way, that allows for marking data to not be published by default (for legal reasons for example).

**Comment by adelavega** [comment]
Ah! Thank you for the clarification

**Comment by yarikoptic** [comment]
> > It's not clear to me why that's necessary. Why wouldn't "all data" be published with datalad publish?
> 
> It's not necessary and `datalad publish` would publish all data by default. 

I don't think it is correct.  
Unless you point to what data (files/paths) to be published (could be as simple as `.`), or state `--transfer-data all`, no data must be published since the default mode for `--transfer-data` is "auto" and that means that unless you setup "annex-wanted" (or group-wanted etc), no data should be published.  
If it doesn't behave that way -- it would be a bug and I would have all TBs of data shared directly from http://datasets.datalad.org

**Comment by yarikoptic** [comment]
> The only question that remains is the second of @yarikoptic 's suggestions. It's not clear to me why that's necessary.

See above about `publish`... IMHO `--annex-wanted` is the best way to clearly prescribe what data should be published to the remote when you don't need "piece meal" publishing (just some manually picked files but not the others).  This way you don't need to remember to use `--transfer-data all` or point to specific paths.

**Comment by bpoldrack** [comment]
> Unless you point to what data (files/paths) to be published (could be as simple as .)

Well, yes. I should have written sth like `datalad publish .` actually. I thought that was probably clear from doc.
My point was, that @adelavega seemed to assume that a configuration was needed to publish all data, which would be misleading. Anyway, I agree we should come up with a full setup example as you described.

**Comment by adelavega** [comment]
Okay makes sense. The command I planned to use has `--transfer-data all`. From an outsider perspective that is more clear what its doing, although I think I understand why you'd prefer to set which data to transfer when you create the sibling dataset.

**Comment by yarikoptic** [comment]
I would consider the original issue "addressed". Feel welcome to reopen @adelavega if I am wrong
