### ISSUE TITLE
failed run: provided command to run is insufficient

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3072]
I was instructed to run `datalad save  -r -F .git/COMMIT_EDITMSG .` to save changes of unsuccessful run (see #3071), but because my command produced new files a mere `save` is insufficient (might be sufficient in the post-revolution world) - some `add` needs to  be done.
```shell
$ git status                                                             |
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   logs (untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
$ datalad diff -r
   modified(dataset): logs
     untracked(file): logs/validator-BPA2-0.20181206.0-0-g2d479a3.out

$ datalad save  -r -F .git/COMMIT_EDITMSG .                              
action summary:
  save (notneeded: 19)
```

**Comment by kyleam** [comment]
> I was instructed to run `datalad save -r -F .git/COMMIT_EDITMSG .` to save changes of unsuccessful run (see #3071), but because my command produced new files a mere `save` is insufficient

Based on testing, I don't think it is just new files, but rather new files within a subdataset.

> (might be sufficient in the post-revolution world) - some `add` needs to be done.

Yes, just tested and `datalad rev-save -r -F .git/COMMIT_EDITMSG .` handles it fine.

I'm never able to keep add/save differences straight in my head, but I'm baffled why I chose to report `save` in the error given that I know `run` uses `add` underneath.

Given the uncertain revolution timeline, I'd say we should

  * move --message-file/-F to common options and expose it in `add` as well.
  * report `datalad add -r -F [...]` instead [*].

Thoughts?


[*] Because we now have a `saver` argument,  perhaps it would be worth tailoring the message a bit more.  If we don't recognize it, just say something generic about commit the change and the presence of  the .git/COMMIT_EDITMSG file.
