### ISSUE TITLE
run: be able to say --output={inputs}

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3075]
Might be RTFM, then please label as a `question`.  I want to be able to avoid specifying the same path(s) whenever inputs are the same as outputs (inplace modifications):
```shell
$> datalad run --explicit -m "Replace leftover datalad_revolution in the API bindings spec" --input datalad/revolution/__init__.py --output '{inputs}' sed -i -e 's,datalad_revolution,datalad.revolution,g' '{inputs}'
[INFO   ] Making sure inputs are available (this may take some time) 
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
[WARNING] path does not exist: /home/yoh/proj/datalad/datalad/{inputs} [add(/home/yoh/proj/datalad/datalad/{inputs})] 
add(impossible): {inputs} [path does not exist: /home/yoh/proj/datalad/datalad/{inputs}]
```

**Comment by kyleam** [comment]
No, there isn't.

**Comment by yarikoptic** [comment]
just a bump on having this desired feature.  Currently particularly desired since i believe we do not support fancy globbing like `**` so I need to specify multiple inputs and then would hate to duplicate all of them as outputs

**Comment by mih** [comment]
I have implemented a fix for this request. However, I came to realize that supporting `--input={outputs}
` rather than `--output={inputs}` is more generally useful, because there can be processes without inputs, but not without output for any given run-record. Not talking about the possibilities of not-specifying either of them, but about the structural reality of them.

**Comment by mih** [comment]
There is nothing that prevents this in the implementation proposed in #6424
