### ISSUE TITLE
`Runner` incapable of "logging" while letting executed command prompt for input 

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3103]
Use case needed here: https://github.com/datalad/datalad-revolution/pull/71

Ideally `git commit` should be able to exhibit its normal behavior, i.e. ask for a commit message when none was provided (by launching an editor), even when executed through DataLad's runner. However, when we run `git commit`, we also need to be able to act on a variety of error conditions, hence we need to capture stdout/err. ATM runner can capture the output streams XOR let them through. In shell lingo, we can do

`git commit` and `git commit > log`, but for the desired behavior we need `git commit | tee log`

Looking through the Runner code it is not immediately clear to me where/if such feature could be added, but here is a sketch of the concept: https://shallowsky.com/blog/programming/python-tee.html

**Comment by yarikoptic** [comment]
AFAIK 
- runner supports commands with prompts e.g. asking for credentials. But that is usually done via directly talking to /dev/tty, so it is presented to the user even from within datalad sandwiched within git annex remote call, which is done by datalad itself. We use getpass.getpass for that. see dialog.py
- `| tee log` can also be done 
```
 log_stdout: bool or callable or 'online' or 'offline'
```
so if it is a callable -- you would get line as soon as it is received. That is what we use for e.g. capturing progress reports from git-annex

I could be wrong, but in the context of `git commit`, to display an entire editor, we probably need to surrender any opportunity to receive stdout, and use smth like `os.system` or `pty.spawn` instead of popen..., e.g.
```shell
$> python -c 'import os; os.system("vim 2>/tmp/2")'            
$> ls -ld /tmp/2
-rw------- 1 yoh yoh 0 Jan  5 17:54 /tmp/2
```
but again -- I could be wrong and missing what is needed

**Comment by mih** [comment]
It is perfectly OK to use `vim` through Runner.

```python
from datalad.cmd import Runner
Runner().run('vim', log_stdout=False, log_stderr=False)
```

OTOH using a callable to intercept and pass on anything that comes through the pipe does not work.

```python
Runner().run('vim', log_stdout=lambda x: sys.stdout.write(x), log_stderr=lambda x: sys.sterr.write(x))
```

The reason for that is still unclear to me. I suspect that it never gets to see "a line".

**Comment by bpoldrack** [comment]
FWIW:
Just tried and it seems to me, that - at least for this use case - it works if only stderr is logged. Meaning

```python
from datalad.cmd import Runner
Runner('.').run('git commit', log_stdout=False, log_stderr=True)
```
Will launch `vim`.
Not sure though whether stderr is all we currently need.

**Comment by mih** [comment]
That is true, but when I tried this, it could not act on any error, as Runner always returned `''` as stderr.

**Comment by mih** [comment]
This is no longer a technical issue (we have an async runner now), it just needs some procedural work to have convenient support for recursive saving. No need to keep this open.
