### ISSUE TITLE
upstream git annex build causes rm: loadlocale.c:129: _nl_intern_locale_data: Assertion ....

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3159]
Travis cron job tests upstream snapshot build of git-annex and fails upon `git config` call with

```
rm: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
```
travis: https://travis-ci.org/datalad/datalad/jobs/484480690#L1022
with matrix run `_DL_UPSTREAM_GITPYTHON=1 _DL_UPSTREAM_GITANNEX=1 NOSE_OPTS= _DL_CRON=1`
that happened 16 days ago and 2 days as well (https://travis-ci.org/datalad/datalad/jobs/490668239) - didn't check for how long it was going on.  We use this script https://github.com/datalad/datalad/blob/master/tools/ci/install-annex-snapshot.sh for installing the annex snapshot

on which google leads to https://unix.stackexchange.com/questions/444102/loadlocale-c-nl-intern-locale-data-assertion-error  suggesting as a workaround setting LANG to point to the locale path, not just name... something feels not right, @joeyh might know more .

**Comment by kyleam** [comment]
I have very little understanding of this issue, but that looks like the same error from gh-2769.  I also ran into this with [Travis testing for magit-annex][m].  The same `export LOCPATH=` I used there seems to [fix our build][t].  Based on discussion in git-annex's 42842ea0eaa and within gh-1921, that sounds like it might cause pain down the road, but it's the only way I could get things working on Travis.  And using `LOCPATH=` for the `_DL_UPSTREAM_GITANNEX=1` run should match what you're doing with the Neurodebian build because the system locales are used when GIT_ANNEX_PACKAGE_INSTALL=1 (42842ea0eaa).

[m]: https://github.com/magit/magit-annex/commit/8975cbc10d5639163029e0bb9b1e08c2b72096ef
[t]: https://travis-ci.org/datalad/datalad/builds/491706265

**Comment by joeyh** [comment]
See http://git-annex.branchable.com/bugs/Assertion___96__cnt___60_____40__sizeof___40____95__nl__95__value__95__type__95__LC__95__TIME__41_____47___sizeof___40____95__nl__95__value__95__type__95__LC__95__TIME__91__0__93____41____41____39___failed./

-- 
see shy jo

**Comment by yarikoptic** [comment]
@joeyh URL no longer works : 

```
The page ?Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed. does not exist.
```
but IIRC the summary was that you expect users to do some configuration of their environment variables to make stock build of git-annex usable on their system?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> @joeyh URL no longer works :
> 
> The page ?Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed. does not exist.
> 
> but IIRC the summary was that you expect users to do some configuration of
> their environment variables to make stock build of git-annex usable on their
> system?

Page moved to
http://git-annex.branchable.com/bugs/loadlocale_error_with_standalone_build/

-- 
see shy jo

**Comment by yarikoptic** [comment]
satus quo (of not testing upstream build) seems has worked for everyone ;)
