### ISSUE TITLE
git-annex suggestion for universal batch mode

### ISSUE THREAD

**Issue by notestaff** [datalad/datalad#3161]
Would this be useful for DataLad?  https://git-annex.branchable.com/todo/universal_batch_mode/

**Comment by yarikoptic** [comment]
May be eventually... ATM we do use batch modesper command quite a lot. May be we coughs refactor it for the generic batch interface to git annex, but it would be nice first to see concrete use cases. I can see may be a bunch of get and unlock pairs.

**Comment by notestaff** [comment]
@yarikoptic "it would be nice first to see concrete use cases" -- e.g. lightweight smudge/clean filters, as suggested at [here](https://git-annex.branchable.com/todo/split_off_clean__47__smudge_filter__63__/).  More generally, I think scalability of git-annex (and tools built on top of it) would be improved if one did not have to run many parallel git-annex processes (git-annex binary being pretty large).  Some [types of parallelism-related bugs](https://git-annex.branchable.com/todo/only_allow_one_git_queue_to_be_flushed_at_a_time/) would be avoided.

@joeyh said "Datalad did request something like this, but IIRC I shot the idea down with a good reason. I can't remember why or where we discussed it.. @yoh might."  Do you remember what the reason was?

**Comment by yarikoptic** [comment]
I wish! ;)
may be because it would have been easier to approach "piece meal" and/or to mimic how git does it (some commands have it some don't, no centralized git-batch). 
But if "git does it that way" was the argument, we could counteract it now with the fact that there is git support "library" implementations in various languages making it possible to interact with git via a single process (well -- GitPython does gitdb management directly IIRC but for actions resorts to git calls, so mitigated at least partially in this case).

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
