### ISSUE TITLE
Mysterious INFO log message from search

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3195]
```
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/crcns[master]git
$> datalad --version
datalad 0.11.3

$> datalad search aaaaaa
[INFO   ]  

$> datalad search aaaaaa | cat
[INFO]  

```

**Comment by kyleam** [comment]
I think you're the source of your own mystery: a66261a60 (ENH: if search resulted in no hits due to wrong keys used, log an INFO msg with suggestions, 2018-12-13)

https://github.com/datalad/datalad/blob/083665a855111c7319edce84dcae4f4ab6d39c8d/datalad/metadata/search.py#L1263-L1264

Perhaps '' should be replaced with 'no hits'.

**Comment by yarikoptic** [comment]
THANK YOU @kyleam for digging. Indeed, "no hits" would be the right thing to have.  you/me?

**Comment by kyleam** [comment]
I'll open a PR.
