### ISSUE TITLE
download-url --nosave documentation contradicts itself

### ISSUE THREAD

**Issue by driusan** [datalad/datalad#3203]
The `--nosave` option documentation at http://docs.datalad.org/en/latest/generated/man/datalad-download-url.html reads:

```
by default all modifications to a dataset are immediately saved. Giving this option will disable this behavior. [Default: True]
```

The English text and the parenthesis contradict each other.

**Comment by bpoldrack** [comment]
True. This is confusing.
@datalad/developers : This is generally true for the `--nosave` option. That's because it's assign to the former `save` option (where that default value in the parenthesis is coming from). We should iron that out indeed.

**Comment by yarikoptic** [comment]
it is for any option like that where `action="store_false"` and `dest` is a variable without `no` prefix, e.g.
```
$> datalad drop --help | grep -A2 '^ *--nocheck'
  --nocheck             whether to perform checks to assure the configured
                        minimum number (remote) source for data. Give this
                        option to skip checks. [Default: True]
```

well, in principle, I think we should not include default for flags since it makes little sense to me.  In Python API docs it should match intended default, even when the variable is the "flipped" one (like here variable `drop` for `--nodrop`).  I will see if quick PR would happen ;-)
