### ISSUE TITLE
rev-save -r doesn't save full dataset hierarchy

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3248]
I'm working on switching `run` over to using `rev_save` and bringing in -revolution's run tests.  In the process, I was replacing a `.add(".", recursive=True)` call in `test_run_inputs_outputs` with `.rev_save(recursive=True)` and couldn't get `rev_save` to save the entire dataset hierarchy.

I've isolated the setup from that test to the script at the bottom of this post.  Here's an overview of the differences:

```
% datalad status -d saved-with-add -r
% datalad status -d saved-with-rev_save -r
 modified: s0 (dataset)
untracked: s0/s1_0 (directory)
untracked: s0/s1_1 (directory)
untracked: s0/ss (directory)

% datalad subdatasets -d saved-with-add -r
subdataset(ok): s0 (dataset)
subdataset(ok): s0/s1_0 (dataset)
subdataset(ok): s0/s1_0/s2 (dataset)
subdataset(ok): s0/s1_1 (dataset)
subdataset(ok): s0/s1_1/s2 (dataset)
subdataset(ok): s0/ss (dataset)
action summary:
  subdataset (ok: 6)
% datalad subdatasets -d saved-with-rev_save -r
subdataset(ok): s0 (dataset)
```

So, `rev-save` adds s0 to the root dataset (save-with-rev_save) but doesn't seem to register the subdatasets further down the tree.

<details>
<summary>script</summary>

```python
#!/usr/bin/env python3

import os.path as op
import tempfile

from datalad.api import Dataset
from datalad.tests.utils import create_tree

tempdir = tempfile.mkdtemp()


def add(ds):
    ds.add(".", recursive=True)


def rev_save(ds):
    ds.rev_save(recursive=True)


for savefn in [add, rev_save]:
    root = op.join(tempdir, "saved-with-" + savefn.__name__)
    create_tree(root,
                {"s0": {"s1_0": {"s2": {"a.dat": "a",
                                        "b.txt": "b"}},
                        "s1_1": {"s2": {"c.dat": "c",
                                        "d.txt": "d"}},
                        "ss": {"e.dat": "e"}}})

    for subds in [("s0", "s1_0", "s2"),
                  ("s0", "s1_1", "s2"),
                  ("s0", "s1_0"),
                  ("s0", "s1_1"),
                  ("s0", "ss"),
                  ("s0",)]:
        Dataset(op.join(*((root,) + subds))).rev_create(force=True)
    ds = Dataset(root).rev_create(force=True)
    savefn(ds)

print(tempdir)
```

</details>

**Comment by kyleam** [comment]
I'm guessing the answer here is that saving more than one level of untracked datasets isn't supported.  Looking at the code, my understanding is that we see the the first-level subdataset (s0 above) as an untracked directory in the `git ls-files -o` output (all the way down in `GitRepo.get_content_info`).

**Comment by mih** [comment]
Correct. Cannot respond right now. Will do later.

**Comment by mih** [comment]
Your analysis is correct, it is not supported. I felt that doing that breaks the semantics of `--recursion` -- which is the recursion into subdatasets, but not any datasets that are lying around. The rational for the exhibited behavior therefore is: `rev-save` finds the first-level (not-yet-sub)datasets and saves them, as it is told to save the entire dataset, and those datasets are content items within the top-level dataset. However, recursion is happening once and at first while discovering what datasets to touch, hence it will not see any content (not just further subsubdataset) within datasets that are not yet actual subdatasets.

I actually thought about the case of `run` when making the decision to implement this behavior. AFAICS this is a non-issue, except for the case where a command wrapped by `run` actually creates dataset *hierarchies*. If there is a command that does that I cannot see, why it would not be the responsibility of this command to actually produce a proper hierarchy instead of a pile of standalone datasets (and properly commit the content within it too), because clearly it already understands the concept of a VCS.

That being said, I could understand the desired to have a "clean-up-my-mess" tool. However, I think such a tool should be developed on top of `rev-save` not within it.

I am adding "wontfix" to this issue for posterity, but of course I am open for further debate.

**Comment by kyleam** [comment]
Thanks for laying out your thoughts on this.  

>  If there is a command that does that I cannot see, why it would not be the responsibility of this command to actually produce a proper hierarchy instead of a pile of standalone datasets (and properly commit the content within it too), because clearly it already understands the concept of a VCS.

When I was thinking about this yesterday, I was trying to come up with a realistic case where I'd need the behavior of `.add(".", recursive=True)`, and I reached a similar conclusion to your statement above.
