### ISSUE TITLE
Command hooks

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3264]
There is a dilemma between the desire to have a compact API and some customizability of command behavior. Example: `rev-create` does not have  `--text-no-annex`, but it can come handy to be able to get such a setup conveniently.

I believe a "hook" mechanism is one way to have this. Here is an example how a command invocation could look like that could be supported to run a dedicated configuration procedure
after a dataset got created:

  `datalad -c datalad.hooks.create-done=cfg_text2git rev-create`

This uses our tooling to have a temporary config setting, but of course such a setting could also become part of a dataset/user/system configuration.

Using this mechanism would be nice, because we already have a need to improve config override handling for better control of Git/Git-annex behavior within low-level commands (#3246, and various failed attempts along the lines of #3204, #2851, #2818, #905). There we face the exact same issue: desire to fine-tune, without the willingness or ability to explode the API to be able to pass through tons of special-purpose options.

TODOs if we want to move forward with this:

- agree on a nomenclature of such config keys. Proposal: as above, with last key segment being `command`-`custom slot name` (where each command describes its slots in its docs)
- agree on a syntax of such config values (plain procedure names, or stringified Python list of  arguments for run-procedure, or ...

ATM we do have `--proc-pre`, `--proc-post` arguments at the cmdline API level, but those do not scale and are hard to use for a specific customization within a larger command. I think they should be removed.

Eventually, we should have the ability to define criteria to detect specific results that pass through our main "event-loop", and to trigger specific actions/hooks. However, until we have that, I see no problem in implementing the execution of an initial set of hooks (like the example above) within individual command implementations. Importantly, those should merely define the position of a hook within the processing flow of a command, but not the nature of an intervention. So in the above example we simply have a loop over `ds.config.get('datalad.hooks.create-done')` where `run-procedure` is called for each value.

Possible use-cases to inform development
- populate git-annex metadata for added files (e.g. annotate with `distribution-restrictions` key=value pairs).  ATM [there is no way AFAIK](http://git-annex.branchable.com/git-annex-metadata/#comment-fde59930f108af0fff842f5e25351e93) to do so via `.gitattributes`

**Comment by yarikoptic** [comment]
If we consider `create` for now since it is a immediate use-case in question. Where would you store such configuration setting - globally? in the super dataset where you are creating it? Neither of those locations really relates to the fact that I want **new** dataset having this property, and possibly not any other within this dataset.  In some cases though I see them probably being useful - e.g. when I know that the entire hierarchy of datasets should have consistent "settings" across.  It would relate not only to `--text-no-annex` but possibly to annex backend, annex init options, etc.  But because we have no configuration inheritance from the super-datasets, I do not see how this would help beyond one level.

As for `--text-no-annex` specifically it really boils down to be able to specify for a given invocation of `create` and relate it to the created dataset (not its super etc).   Unfortunately even `--proc-post` is not sufficient since newly created dataset is not what it operates on (can't find that reported issue issue - if it was reported - but I remember discussing it), so you have to use `-d newdataset` to be able to run a `--proc-post` procedure on it.  It just becomes a mouthful of a cmdline specification to achieve what I find using frequently, and which thus should have a concise command line specification.  Internally, sure thing, it better uses the procedure to not reimplement the same action.  But at the user level - common modes of operation should be clearly presented in `datalad operation --help` (procedures aren't listed) and have concise syntax to trigger them. procedures/plugins/hooks/... make things more flexible and versatile, but also more obfuscated to the user.

**Comment by mih** [comment]
For this use case I would not store it at all, but use exactly the command that I gave above.

**Comment by yarikoptic** [comment]
yes, so have a mouthfull of `datalad.hooks.create-done=cfg_text2git` for what should IMHO be a short option.

**Comment by yarikoptic** [comment]
Ideally that short option should be homogeneous with the procedure it runs... since you went for a new name `cfg_text2git`, we no longer have harmony there.  I am ok if it would become `--cfg-text2git` option.  Which gives me a crazy idea -- may be (all? or appropriately annotated as applicable) procedures could be exposed as cmdline options to the command(s)? listed in a separate subsection in `command --help`.
the only immediate problem I see - order might matter and iirc we do not have ordering information

**Comment by mih** [comment]
Let's keep in mind that this issue is about hooks in general and not about a specific option of create.

**Comment by bpoldrack** [comment]
>  Where would you store such configuration setting - globally? in the super dataset where you are creating it?

What's wrong with  `~/.gitconfig`?

**Comment by yarikoptic** [comment]
> Let's keep in mind that this issue is about hooks in general and not about a specific option of create.

It would then be useful to provide other than `create` + `cfg_text2git` example in the description, otherwise it is hard to envision what hooks and when and where I might like to run.

> What's wrong with `~/.gitconfig`?

Hardly applicable to the only example in question ATM - I do not want all my datasets to have text2git setup.

**Comment by bpoldrack** [comment]
> Hardly applicable to the only example in question ATM - I do not want all my datasets to have text2git setup.

Ok. Probably misinterpreted your desire to store it.

**Comment by bpoldrack** [comment]
Generally, I like the idea of such hooks. I'm just wondering whether we could design it more generally. Referencing procedures is something obvious that should be possible and configuring it is nice as well. But may be we can come up with something that melts this idea with the hook concept git uses. Just a thought - need to think that through.

**Comment by kyleam** [comment]
>  Unfortunately even `--proc-post` is not sufficient since newly created dataset is not what it operates on (can't find that reported issue issue - if it was reported - but I remember discussing it) ...

#2732

**Comment by yarikoptic** [comment]
FWIW, modified original description - added a section to collect possible use cases (in my case -- bids and git-annex metadata)

**Comment by mih** [comment]
An alternative, and IMHO superior, feature is now available in `master`. Result hooks are more flexible than command hooks, and additionally could operate reliably regardless of which command is the cause of a targeted result -- possibly easing the transition from one command to another as the main workhorse for a particular action, as long as the results remain structurally identical.

Hence, I am considering this issue obsolete and will close it now.
