### ISSUE TITLE
Change run record markup

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3370]
This is not a call for immediate action, but a collection of implications/observation found during the work on #3359 

- there is some desire for some kind of tagging (e.g. "preprocessing") to indicate the purpose of a recorded command (via @yarikoptic )
- #3062 asks for changes in the commit subject line (more free space)
- #3062 also points out that the lines
  ```
     === Do not change lines below ===
     ^^^ Do not change lines above ^^^
  ```
  on which we rely on to be able to load a record (via sidecar or commit message) do not contain an indication that this is actually a run-record.

ATM it seems it would be best to give up any mandatory content in the subject line, and with it remove the implicit suggestion that "RUNCMD" could be used reliably to discover run records. Instead, the actually mandatory lines should be extended to identify them as run records, e.g.:

  ```
     ==CMD= Do not change lines below ===
     ^^CMD^ Do not change lines above ^^^
  ```
or `s/CMD/RUN/g`. With this change it would be as convenient to discover such commit (via `git log`). Moreover, the subject line is now free to include other meaningful tags for human consumption.

Such a change would have minimal transition costs.

**Comment by yarikoptic** [comment]
sounds reasonable!  Given that commit message is kinda static and we do not show up a dialog to have commit message tuned up before recording it, I wonder what value is in `Do not change lines below`? Even if we showed the commit message, we could use git way to annotate it with comments regarding the block which shouldn't be modified.

**Comment by yarikoptic** [comment]
As for tagging - started a dedicated https://github.com/datalad/datalad/issues/3371 . As we agreed, shouldn't be a part of the commit record.

**Comment by kyleam** [comment]
I'm in favor of modifying the record markup lines to be more specific for run as well as detecting run commits with those markers alone.  For the specific markup, I'm OK with the one above (with a slight preference for s/CMD/RUN/), but it's worth thinking about more because we're committed to it even if we switch to something else.

Even without requiring the subject prefix for detection, there's the question of whether we want to use it at all.  I agree with the suggestion here to drop it when there is a user-supplied message.  If there isn't, presumably we should use one of the suggestions from #3062?

**Comment by kyleam** [comment]
@yarikoptic:

> Given that commit message is kinda static and we do not show up a dialog to have commit message tuned up before recording it, I wonder what value is in `Do not change lines below`?

Given that we need some sort of markup for detection and readability, I think we might as well use that markup to make it clear that those lines shouldn't be touched because there's is nothing wrong with a user doing something like 'git commit --only --amend' to adjust the message (with all the usual caveats about rewriting published history).

**Comment by kyleam** [comment]
I said:

> [...] there's is nothing wrong with a user doing something like 'git commit --only --amend' to adjust the message (with all the usual caveats about rewriting published history).

To add to that: Even outside of run, I use the above to work around DataLad's lack of support for popping up a proper editor for writing the message.

**Comment by ypid-geberit** [comment]
I am starting to use reproducible execution for my everyday git workflows in software development and as sysadmin because I am not aware of another tool that supports reproducible execution with git. In those fields, DataLad is not yet known. I would really like to see a hint in the commit message which program is needed to actually rerun the command, so rather make it explicit in the commit message body. Something like:

```
==RUN= DataLad: Do not change lines below ===
^^RUN^ DataLad: Do not change lines above ^^^
```

This would be self-explanatory when I contribute patches for example (on review and later on in the git history).

**Comment by bpoldrack** [comment]
> I would really like to see a hint in the commit message which program is needed to actually rerun the command, so rather make it explicit in the commit message body.

While this somehow didn't mak it into this issue, the current state of affairs is, that the commit message starts with `[DATALAD RUNCMD]`. Note, that due to the `--sidecar` feature an explicit marking in the message body is probably not what you want.

**Comment by mih** [comment]
I actually like the suggestion. Didn't a sidecar commit also have the same markup, but only has the id in the body? I think, it would be good to leave the space in the title line to a user.

**Comment by bpoldrack** [comment]
> Didn't a sidecar commit also have the same markup, but only has the id in the body?

Right, I thought it was the entire body that was moved to the sidecar file. Should have looked it up ;-)
So, yeah - no objection then. `[DATALAD RUNCMD]` could be part of default message instead.
