### ISSUE TITLE
Check with git folks if pre-add hook is feasible and if so -- do it

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#34]
That could allow use of largefiles or whatever else to simplify interactions with annex -- they would just automagically added to annex (instead of index) in 'pre-add' hook, and/or may be user be alerted that he is trying to commit a large file directly to git, while it is not matching largefiles selection, ...
Or am I dreaming @joeyh? ;-)

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> That could allow use of largefiles or whatever else to simplify interactions
> with annex -- they would just automagically added to annex (instead of index)
> in 'pre-add' hook, and/or may be user be alerted that he is trying to commit a
> large file directly to git, while it is not matching largefiles selection, ...
> Or am I dreaming @joeyh? ;-)

I tried to add some hooks around git-fetch back in 2011-2012, and fell
down a rabbit-hole where the git devs wanted to rework their
whole hook API before adding new hooks -- but had conflicting ideas
about what the new API should look like. My patches did not get
accepted.

So, while I think that a pre-add hook would be great and would be happy
for git-annex to use it, I don't know if I'm the one to get such hooks
into git.

BTW, If the hook interface doesn't involve communication on stdio,
that rabbit hole could perhaps be avoided, since that's where the
current git hook API is weak.

-- 
see shy jo

**Comment by yarikoptic** [comment]
Thank you @joeyh.
May be someone would get excited enough to look into that some time again. may be @bpoldrack ? ;-)  Theoretically we might not need stdio communication if all magic is just done deterministically by the hook

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> May be someone would get excited enough to look into that some time again. may
> be @bpoldrack ? ;-) Theoretically we might not need stdio communication if all
> magic is just done deterministically by the hook

Well, the hook could be run once per file added, and exit 1|0 to tell
git whether or not to go ahead with adding the file. This would be
pretty innefficient though for "git add largedir"

-- 
see shy jo

**Comment by bpoldrack** [comment]
Well, I don't think this should be my first priority for now, but I can have a look at it later of course. However, I don't see why I should be the one getting this into git, when Joey isn't. Since I have no record in open source development at all, I'd be surprised by seeing them accepting a patch from me, but not from Joey. Do I miss something here?

**Comment by yarikoptic** [comment]
priority -- nope.  But I thought that if you like to get a better "insight" into git, investigating originally proposed solution by joey, checking if their hooks API didn't change since then (it was a bit awhile ago), and raising the question/discussion on git mailing list/forum might be beneficial. Also, as joey pointed out, such a hook implementation might be quite inefficient, so the whole issue would be an attempt into a wrong direction, unless efficient way could be figured out.
Cooking up an acceptable patch is a whole other level ;-) but who knows -- may be revived joey's would provide a good base (I didn't find it on a quick google -- @joey: do you have a pointer?)

**Comment by yarikoptic** [comment]
re @joeyh: "and exit 1|0 to tell git whether or not to go ahead with adding the file" and meanwhile just "git annex add" it to transform to a symlink and return 0 in cases of git-annex controlled files, right?

**Comment by bpoldrack** [comment]
You're right. From that point of view it really makes sense.

**Comment by yarikoptic** [comment]
now that largefiles respected by 'annex add' and there is that new smudge-based mode of operation for v6, I will close this one to not drag alone.
