### ISSUE TITLE
Avoid platform.dist (removed in py3.8)

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3417]
We use platform.dist() in setup.py and wtf.py (see gh-3406).  The recommendation is to use https://pypi.org/project/distro/ instead, but that of course doesn't work well for setup.py.

**Comment by effigies** [comment]
You can consider using `pyproject.toml` ([PEP 518](https://www.python.org/dev/peps/pep-0518)) to declare dependencies for building. We've been moving to a `pyproject.toml` + `setup.cfg` config to replace much of `setup.py` in https://github.com/poldracklab/fitlins and https://github.com/poldracklab/fmriprep.

**Comment by yarikoptic** [comment]
I think we should just avoid any platform specifics in setup.py.  I/we was/were already burnt by deciding `requires` based on python version in setup.py.  It was very wrong since the same distribution uploaded to pypi used for ALL systems.
Looking at what we are using it for I think we could safely decide 
- to depend on colorama  even if not on windows
- Debian check for downgrading demand on keyring... that is for debian wheezy which is by now EOLed even in LTS.  We can rip it out

I will submit a PR following that shortly
