### ISSUE TITLE
Destiny of `publish --missing`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3419]
I was trying to get myself to like what `publish --missing` aims to do, but I keep failing on that. All it can to is nothing (`skip`), or call `create_sibling` (`inherit`). It fails for any other kind of remote, and of course cannot do anything if a superdataset has nothing in common with a subdataset in terms of  remotes.

That all comes at the price of an API argument slot, and a TODO list that nobody has tackled: #1344, #1491, #1673 in two years.

I am not convinced that mixing tasks (push content vs. create publication targets) is anyhow superior to a dedicated command whose purpose is to create publication targets for datasets that don't have one. It certainly runs counter to my desire to come up with a reasonably minimal core API.

Another aspect is the implied dependency of `publish` on `create_sibling`. Taking one step back, I'd  consider `create_sibling` as more of a leaf command, as there are plenty of publications targets that have nothing to do with this functionality (all kinds of web/storage services) and even within the Git world (GitHub, GitLab) `create_sibling` is pretty much irrelevant.

Taken all together, I think we should not fold `create_sibling` functionality into `publish`.

**Comment by bpoldrack** [comment]
`create-sibling` should be disentangled from `publish`, I agree. However, a recursive `publish` still needs to react somehow to such a missing publication target. To me values like `skip`/`ignore`, `report` and `fail`come to mind, where `report`could be used to get a list of those datasets, that can be used to fix for it or double check to call again with `ignore`.
Either way, I think one would at least want to be able to decide whether to ignore those (since somehow intended) or to fail upon the encounter.

**Comment by mih** [comment]
There is not need for that, because we can simply report the results as with any other command, and rely on `--on-failure {ignore,continue,stop}`. There is nothing special about `publish`.

**Comment by bpoldrack** [comment]
True. A result filter and/or formatting will do. Agreed.

**Comment by yarikoptic** [comment]
> I think we should not fold `create_sibling` functionality into `publish`.

I think I would not call it "fold"ing but delegating -- there is only a single call out to it.  Either the location for that call is the best one (see below) is indeed at question.

- I do rely on this functionality every time I am publishing updates for datasets.datalad.org (and that is why/how it was introduced).

> It fails for any other kind of remote

I think that is the main problem causing distress here (and at the heart of referenced #1344) -- we do breed `create-sibling-*`s because we 

- have no other good API for uniform creation/initialization of siblings of different kinds (like e.g. git-annex has for its special remotes, although I would not call that one particularly user-friendly)
- neither make any record nor have analysis for what type of a sibling remote and   ...
- ... how to "inherit" from it

So, the proposed "take it out" (re)solution is pretty much a suggestion to resolve it by offloading it upon user's shoulder -- to figure out which `create-sibling*` command to use to establish remote repositories first. So, as anti-Gael would say it, "solve technical problem socially" ;)

> TODO list that nobody has tackled

#1491 ("subdatasets of new subdatasets") and probably #1673 (subdatasets with their supers not yet having that remote).    May be with the mighty `status` information about absent remotes could first be obtained, creation of remotes be delegated to `create-sibling` and then publication would proceed as normal.  Again seems to be a technical problem, which IMHO could and should be solved without offloading to the user for "two-step procedure". If we (developers) know the correct sequence of commands to run, why don't we run it?

> cannot do anything if a superdataset has nothing in common with a subdataset in terms of remotes

sounds like a use case where NOT to use `--missing=inherit`

**Comment by mih** [comment]
> I think that is the main problem causing distress here (and at the heart of referenced #1344) -- we do breed create-sibling-*s because we have no other good API for uniform creation/initialization of siblings of different kinds (like e.g. git-annex has for its special remotes, although I would not call that one particularly user-friendly)

It will be very difficult to come up with a uniform API to create a sibling on an arbitrary service that is then also forward compatible with any future service. I am currently implementing `create_sibling_gitlab`, and I thought it is basically a tuned copy of `create_sibling_github`, but the possibilities are vastly different and I would not want to be limited to the API of the predecessor. And I also don't see the advantage.

You did not make a statement as to why `publish` has to call `create_sibling` in your workflow, as opposed to making a dedicated call to `create_sibling`.

In general I'd like to break the cycle of: "this command needs to be complicated, because all the other ones are stupid". I understand that it may not be possible, but I would step down from the "publish" job, if it means improving all the `create_sibling*` commands first. I am not a good person for those, as I don't use any of them.

**Comment by yarikoptic** [comment]
> You did not make a statement as to why `publish` has to call `create_sibling` in your workflow, as opposed to making a dedicated call to `create_sibling`.

because 
- it better fits the paradigm/promise of making it easy to work with dataset collections and not to worry about dataset boundaries.  I get/have a hierarchy.  I work with it (add/save/create). I publish it.  Rinse repeat.
- probably for the same reason that  explicit `save` does not have to be called upon every `add`, `remove`, `crawl`, `create`, ... -- automation of routine tasks
- without it it would be either
  1. the loop of
   - try `publish` 
   - fail (possibly leaving remote site, possibly publicly visible in the semicooked state) to recall that you did create new subdatasets since some time ago
   - `create-sibling -r`, again with the same `--since` to avoid lengthy wait,
   - try `publish` again 
  2. the sequence 
  - `create-sibling -r --since ...` (just to be safe) 
  - `publish`.

    Feels like a job for some automation and datalad to do then.

> In general I'd like to break the cycle of: "this command needs to be complicated, because all the other ones are stupid".

once again -- call out to `create-sibling` is a single location ATM. I do not see it complicating `publish` much.  It is indeed not entirely correct location/functioning though as you pointed out

>  if it means improving all the create_sibling* commands first.

for the ultimate solution - probably.  If you feel that `publish` RF cannot proceed without removing that single call logic, please remove (in a separate commit with a clear message), and proceed.  We could revisit/reintroduce this issue later.

> ... create_sibling* commands first. I am not a good person for those, as I don't use any of them.

hm... you are the one who made them ;-)  just curious -- you are just doing it all manually (ssh, datalad create, exit, datalad siblings --add ...) then?  use them then -- they are magically cool (when they work).  I find myself using `create-sibling` even for regular git repos to "copy" repos to other remote hosts ;-)

**Comment by mih** [comment]
> because it better fits the paradigm/promise of making it easy to work with dataset collections and not to worry about dataset boundaries.

I don't see where `create-sibling -r` makes me worry about dataset boundaries where `publish -r` doesn't. I would be curious to have an exchange with people that operate a workflow that actually relies on manipulation of a dataset tree (apart from the setup on smaug). So far I have only seen subdatasets being used as (input) dependencies.

> once again -- call out to create-sibling is a single location ATM.

Once again, the status quo is irrelevant for me. If the status quo is good enough, why would one start talking about a publish RF to begin with. The issue is that "just" calling `create_sibling` in this "single  location" ATM is the problem. Because it only works for this type of sibling. So it would need to be generalized to call any of those, which means type tracking, switching logic, parameter adjustments per type of sibling etc. Nobody will do it, because it is a huge undertaking with questionable outcome.

> hm... you are the one who made them ;-)

If that gives me any powers I'd like to use them to delete my sins of the past. ;-)

> you are just doing it all manually (ssh...

I rarely use remote locations that I can SSH into. And in most collaborative scenarios a full-blown decentralized network of repos is a bit hard on the working memory of people, so star-shaped setups are the norm and the center is a (semi-)public location, or at least a service that anybody relevant can have an account on -- that is normally not an SSH accessible machine for me.

**Comment by yarikoptic** [comment]
> I would be curious to have an exchange with people that operate a workflow that actually relies on manipulation of a dataset tree (apart from the setup on smaug). 

Yes, it is my (our original) use-case

> So far I have only seen subdatasets being used as (input) dependencies.

I have those too

> Because it only works for this type of sibling.

the one I (and others, like Adina and a few others) use to collaborate.  AFAIK covers > 90% of real-life use-cases  ;-)
I am not publishing hierarchies to github yet.

> I rarely use remote locations that I can SSH into.

I do.

If you want to generalize it all so it works for a hypothetical crowd but stops working for us (me in this case), well -- I would not call it an optimal strategy.

Anyways, as I have already said, if you feel that the call needs to go to achieve desired purity -- rip it out, together with the tests in a single commit, so it would be easier later one to reconsider bringing it back.

**Comment by bpoldrack** [comment]
How about some "plugin switch"?
Via CLI would take a string to be executed (via `datalad-run`?)  `--on-missing="datalad create-sibling ...."

And via Python API could also be a callable.
All logic regarding that creation can go into what is called there (may be needs to get a few parameters to be filled by publish - can't tell from the top of my head waht's required), while it would still be possible to provide what Yarik wants and using plugin/procedure/whatever it would also be easier to tailor your own routine for such cases.

**Comment by yarikoptic** [comment]
hm, interesting idea @bpoldrack ! it would clutter API but would open the door for flexibility...  sounds promising. Would require passing through the (sub)dataset under consideration...  Could even retain compatibility to cover my 90% of the cases by keeping `"inherit"` (with pre-hardcoded invocation of `create-sibling`) and just trying to execute a command in case the value does not match any of the pre-defined 'cases' ;)

For full resolution (e.g. to address #1491) in hierarchies it would still need be invoked in top-down fashion (unlike publish operating bottom-up) so probably would require RF to be called after some initial "pre-analysis".  So it would need to be different from more intuitive "do along the way of publish" reactivity to the discovery of having sibling missing.

**Comment by bpoldrack** [comment]
> So it would need to be different from more intuitive "do along the way of publish" reactivity to the discovery of having sibling missing.

True, but this also would be less likely to cause to-be-cleaned-up mess in case of failure within creation routine.
However, it's just an idea and should be thought through conceptionally amd regarding API. If it causes trouble within publish it fails to serve its purpose.

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
