### ISSUE TITLE
remove: warns about removing files which are gone already when rm'ing directory

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3441]
```
$> mkdir subdir2; echo 124 > subdir2/124; datalad save -m "added 124 to subdir2" --to-git subdir2/124
add(ok): subdir2/124 (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

$> datalad remove subdir2                                                                            
remove(ok): subdir2/124  
[WARNING] path does not exist: /tmp/testds-remove/subdir2/124 [save(/tmp/testds-remove/subdir2/124)] 
save(ok): /tmp/testds-remove (dataset)
action summary:
  drop (notneeded: 1)
  remove (ok: 1)
  save (ok: 1)
```

datalad 0.12.0rc4.dev5

Got flooded with those warnings, `git reset --hard` within each submodule, and did "revolution" way with just a regular `rm` and then `datalad save` -- worked out nicely (besides again flooding the terminal with thousands of "delete(ok)" messages).

Since I think `remove` is still to stay in the API (or not?) decided to file an issue

**Comment by yarikoptic** [comment]
@kyleam would you be so kind to check this one out?  I kept waiting for probably over 30 min already for these WARNINGS to finally exhaust themselves on two sizeable repos.  (in my case UX pains were amplified also by #2673)

**Comment by kyleam** [comment]
I think fixing this on master comes down to rewriting remove.py to use core/local/save.py.  I'll check, but I imagine that, if it were as simple as "substitute the new save in, passing string paths rather than annotated paths", it would have been done with the rev-save to save rename.  So the best path forward may be to strip annotate_paths() usage from remove.py (which would move gh-3368 forward).

Re: datalad/datalad-container#59
