### ISSUE TITLE
Expand `clone --reckless` with modes for a symlinked annex or a plain worktree

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3528]
The purpose is to streamline the re-use of resources that already exist locally, and to minimize impact on file system performance or quotas.

Background: https://github.com/datalad/datalad/issues/3521

IMHO we should

- [ ] implement the scenario of a `.git/annex` directory that is symlinked to a source repository as an immediate solution
- [ ] re-evaluate our own support for worktrees, and support this scenario (too) if and when we can handle it (see https://github.com/datalad/datalad/issues/753)

**Comment by kyleam** [comment]
> IMHO we should
> 
>     * [ ]  implement the scenario of a `.git/annex` directory that is symlinked to a source repository as an immediate solution

Makes sense.

>     * [ ]  re-evaluate our own support for worktrees, and support this scenario (too) if and when we can handle it (see #753)

I agree it'd be nice to support worktrees (ideally just by removing gitpython use rather than adding a kludge), but this comment is about expanding `install --reckless` with something for worktrees, right?  That seems like a weird fit to me, given that `git worktree ...` is designd to be called from within the main, _local_ repo.

**Comment by mih** [comment]
> install --reckless with something for worktrees, right? That seems like a weird fit to me

I was thinking along the lines of first supporting worktrees, and then using that feature in `install` to represent a subdataset as a worktree of a local repository that is located outside the dataset directory tree. But this is not fully cooked in my brain yet.

**Comment by mih** [comment]
FTR: https://github.com/datalad/git-annex-ria-remote/pull/31 contains a dataset procedure that covers most of what is asked for in here.

**Comment by kyleam** [comment]
Now that gh-4172 pruned the last remnants of gitpython (thanks @mih), we have the ability to finally see where we stand with worktrees.  (That is, we no longer get to point to gh-753 and use gitpython as an excuse for not being compatible with worktrees. :]) I've done a bit of experimenting today.  I'm not at the point where I think I can do a proper write-up, but a few high-level comments:

  * For plain git repo with no submodules: Basic things seem to work.  I think it'd only take a bit of targeted poking to get a failure though, as worktrees of course use a gitdir file and spots in datalad hard code the ".git/" (gh-3529).

  * For annex repos with no submodules: To be compatible with worktrees, git-annex replaces the gitdir file with a `.git -> <path to main wtree>/.git/worktrees/wtree` link and 
`.git/annex -> ../../annex`.  Although we should still fix places where we hard code ".git/", annex's adjustments should resolve the gitdir file issues from above.

    From light testing, things seem to work.

  * For repos with submodules (plain or annex): This is where things start to get tricky.  Starting from the level of git, [at the time worktrees were added][0], it wasn't clear how submodules and worktrees should play together, and `git worktree` still carries a warning about this:

    ```
    BUGS
           Multiple checkout in general is still experimental, and the support for
           submodules is incomplete. It is NOT recommended to make multiple
           checkouts of a superproject.
    ```

    Then on the git-annex level, you have the linking adjustments mentioned above, but AFAICS these break down for submodules in worktrees.  On top of that, we have our `.gitdir -> embedded .git/` conversion to consider.

Anyway, that's not a full (or even good) description of the problem (partially because I don't have a good understanding of all the details), but it seems like we'll have substantial aspects to figure out if we want to promote using nested dataset hierarchies with worktrees.

[0]: https://lore.kernel.org/git/1420278087-14613-4-git-send-email-pclouds@gmail.com/

**Comment by mih** [comment]
We have `--reckless ephemeral` now.
