### ISSUE TITLE
stderr: 'fatal: protocol error: bad line length character: usag' [cmd.py:wait:412] (GitCommandError) 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3596]
Appeared while testing what should have been an unrelated change in datalad-neuroimaging (https://github.com/datalad/datalad-neuroimaging/pull/72):
https://travis-ci.org/datalad/datalad-neuroimaging/jobs/570915772
```

[INFO   ] Considering to create a target dataset /tmp/datalad_demo_nipype.VAKc/datasets-tests.datalad.org at /tmp/datalad_demo_nipype_published.ivQE of localhost 
[INFO   ] Fetching updates for <Dataset path=/tmp/datalad_demo_nipype.VAKc/datasets-tests.datalad.org> 
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
|   cmdline: /usr/lib/git-annex.linux/git fetch --progress --prune --recurse-submodules=no -v public
|   stderr: 'fatal: protocol error: bad line length character: usag' [cmd.py:wait:412] (GitCommandError) 
I: done running docs/examples/nipype_workshop_dataset.sh: failed
The command "$NOSE_WRAPPER tools/testing/run_doc_examples" exited with 1.
```

couldn't reproduce yet locally.  didn't see any obvious difference in version of git/git-annex between smaug and travis.

**Comment by kyleam** [comment]
That build uses the latest GitPython (v3.0.0), which has issues (gh-3598), so perhaps this is another one.

**Comment by yarikoptic** [comment]
uff, indeed smells like one more indeed

**Comment by yarikoptic** [comment]
still failed to reproduce locally while using GitPython from git (so v3), grr :-/

**Comment by yarikoptic** [comment]
and really the error is a mystery since invocation seems to be correct, so not clear why `git` vomits with its "usage:" output upon running
```
/usr/lib/git-annex.linux/git fetch --progress --prune --recurse-submodules=no -v public
```
the only possible reason is outdated (system?) git, but according to versions:
```
cmd:bundled-git=2.20.1 cmd:git=2.20.1 cmd:system-git=2.21.0
```
so the only difference is that system git is actually NEWER!  I do not have 2.21.0 readily available but installed `1:2.23.0~rc1-1` from debian - no problem running 
```
git fetch --progress --prune --recurse-submodules=no -v origin   
```
and also above it is full path  to bundled git... mystery mystery

**Comment by kyleam** [comment]
> and really the error is a mystery since invocation seems to be correct, so not clear why `git` vomits with its "usage:" output upon running

Yeah, it's odd.  I found [a hint][0] about what's going on.

So I think the `git-{receive,update}-pack` call from remote (localhost here) is failing (with some message that starts with "usage" :).

Anyway, I've tried to debug this on origin/scratch/receive-pack (tldr: I really didn't figure anything out but do have a bit more of an error message).  I switched to using `_git_custom_command` directly to remove gitpython from the equation.  I also followed up with the debugging command suggested in that stackoverflow question.

<details>
<summary>details</summary>

Here's the output I'm seeing in those runs:

```
# https://travis-ci.org/datalad/datalad/builds/572016409#L1242
CommandError: command '['git', 'fetch', '--progress', '--prune', '--recurse-submodules=no', '-v', 'public']' failed with exitcode 128
Failed to run ['git', 'fetch', '--progress', '--prune', '--recurse-submodules=no', '-v', 'public'] under '/tmp/datalad_demo_nipype.jZwf/datasets-tests.datalad.org'. Exit code=128. out= err=[ERROR] unknown arguments: ['-o', "git-upload-pack '/tmp/datalad_demo_nipype_published.xRIA'"] 

fatal: protocol error: bad line length character: usag

[ERROR] unknown arguments: ['-o', "git-upload-pack '/tmp/datalad_demo_nipype_published.xRIA'"] 
fatal: protocol error: bad line length character: usag
00926b154b78dfe892d7a1938cbe31acdf6b732a71b4 refs/heads/git-annexreport-status delete-refs side-band-64k quiet atomic ofs-delta agent=git/2.21.0
0000
```

It's hard to distinguish because I stupidly printed stdout/stderr again, but it looks like the direct `ssh localhost git-receive-pack "$PUBLISHDIR"` call isn't showing the error.  Swapping in `ssh localhost git-update-pack "$PUBLISHDIR"` also doesn't trigger the issue:

```
# https://travis-ci.org/datalad/datalad/builds/572016409#L1242
CommandError: command '['git', 'fetch', '--progress', '--prune', '--recurse-submodules=no', '-v', 'public']' failed with exitcode 128
Failed to run ['git', 'fetch', '--progress', '--prune', '--recurse-submodules=no', '-v', 'public'] under '/tmp/datalad_demo_nipype.jZwf/datasets-tests.datalad.org'. Exit code=128. out= err=[ERROR] unknown arguments: ['-o', "git-upload-pack '/tmp/datalad_demo_nipype_published.xRIA'"] 

fatal: protocol error: bad line length character: usag

[ERROR] unknown arguments: ['-o', "git-upload-pack '/tmp/datalad_demo_nipype_published.xRIA'"] 
fatal: protocol error: bad line length character: usag
00926b154b78dfe892d7a1938cbe31acdf6b732a71b4 refs/heads/git-annexreport-status delete-refs side-band-64k quiet atomic ofs-delta agent=git/2.21.0
0000
```

So I guess the new thing from above is `[ERROR] unknown arguments: ['-o', "git-upload-pack '/tmp/datalad_demo_nipype_published.xRIA'"]`.  I don't know where that's happening.

Two other things to note:

  * The failure in the -neuroimaging repo seems to correspond with Travis's switch from Trusty to Xenial. 
  * It hasn't started yet, but I pushed a change to that branch to see what happens if we use the latest Git: https://travis-ci.org/datalad/datalad/builds/572091590

</details>

[0]: https://stackoverflow.com/questions/8170436/git-remote-error-fatal-protocol-error-bad-line-length-character-unab

**Comment by kyleam** [comment]
I took another look at this hoping I could trigger it with the a xenial docker image (rastasheep/ubuntu-sshd:16.04).  I installed git-annex-standalone and then Git 2.21.0 (from source) in that container.  That's of course not exactly the setup on Travis, but I figured that had a chance of catching a weird interaction between the remote and bundled git versions.

I tried to

  * fetch locally using the git bundled with git-annex (7.20190730+git2-ga63bf35dc-1~ndall+1)
  * `ssh HOST git-{receive,upload}-pack REPO`.
  * call `create-sibling`

I didn't have any luck triggering an issue with any of those.

**Comment by yarikoptic** [comment]
I feel like we should eventually move away from magical travis environments to something more "reproducible".  Either running on travis but all steps in a container or just migrate to circle-ci altogether since docker image  to run tests in just a part of the spec, and it is possible (IIRC) get those original circle-ci images locally as well.  For this one probably we are doomed to backdoor travis again to get into that environment

**Comment by mih** [comment]
Yes ^^^

**Comment by bpoldrack** [comment]
Found this last week:

https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by yarikoptic** [comment]
did you try it @bpoldrack ? it used to
- be at least available only for .com (paid) travis subscriptions.
- drop into terminal before actually running any commands so you had to manually invoke all those steps as described in https://docs.travis-ci.com/user/running-build-in-debug-mode/#things-to-do-once-you-are-inside-the-debug-vm
- just crashed on me when I tried (it was probably a year or two ago)

**Comment by yarikoptic** [comment]
Since it started to infect other projects (reproman), we better differ it out. if we  get one test to reliably fail, we could try checking if downgrade of gitpython doesn't resolve it

**Comment by kyleam** [comment]
> if we  get one test to reliably fail, we could try checking if downgrade of gitpython doesn't resolve it

It's not a test, but as I mentioned above I've put the failing -neuroimaging example into the [scratch/receive-pack][0] branch.  All the other tests are removed.  In that branch, I switched the failing fetch call in update.py to use _git_custom_command(), but the failure still happens.  That indicates that it's probably not related to the newer gitpython.

But for completeness, today I updated that branch to downgrade the gitpython version.  The same failure happens:  https://travis-ci.org/datalad/datalad/builds/575331371

[0]: https://github.com/datalad/datalad/compare/0.11.x...scratch/receive-pack

**Comment by yarikoptic** [comment]
Thanks! Sorry I have missed it.
Then it must be git (installation) problem. We could at least check if it is a standard Ubuntu provided git they have, or may be they have some shim git script in addition

**Comment by yarikoptic** [comment]
Hey - reproman trace the beast?!! ;-)

**Comment by bpoldrack** [comment]
Re travis debug: @yarikoptic, didn't try yet, no. It's just news to me that the feature is available at all. And the docs say one can request it for public repos as well.

**Comment by kyleam** [comment]
OK, some progress.  It's some interaction with `GIT_SSH_COMMAND='datalad sshrun'`.

---

As mentioned above, the "usag" bit is some output being taken as part of the protocol.  In the error message, we can see

```
[ERROR] unknown arguments: ['-o', "git-upload-pack '/tmp/datalad_demo_nipype_published.xRIA'"]
```

Starting with "[ERROR] ", that is very likely coming from datalad and almost certainly not coming from git or git-annex.  The only place we call log.error() with  "unknown arguments: " is cmdline/main.py:

https://github.com/datalad/datalad/blob/9846080f7c011ae024bef5f274096c87bf097e64/datalad/cmdline/main.py#L463-L469

To verify that that is the stop, I printed something to stdout before `cmdlineargs.subparser.print_usage()`, and the first four printed characters showed up in the protocol error instead of "usag": https://travis-ci.org/datalad/datalad/builds/575364833#L1220

And the mostly likely datalad command to be running with a fetch/push is "datalad sshrun".  Setting `GIT_SSH_COMMAND` to "ssh"

https://github.com/datalad/datalad/blob/a2bbe84b8b1da6920f20550afa3f1cc935ca98e5/datalad/consts.py#L65

removed the failure: https://travis-ci.org/datalad/datalad/builds/575373273

That of course doesn't explain what is actually triggering the failure, what about the Travis switch to Xenial is making it show up, or why it isn't showing up in the other spots where `datalad sshrun` is used with localhost (e.g., the create-sibling tests).

**Comment by kyleam** [comment]
> That of course doesn't explain what is actually triggering the failure,

The ssh call that is failing is

```
# https://travis-ci.org/datalad/datalad/builds/575409570#L1226
['/home/travis/virtualenv/python3.5.6/bin/datalad', 'sshrun', '-o', 'SendEnv=GIT_PROTOCOL', 'localhost', "git-upload-pack '/tmp/datalad_demo_nipype_published.3E6l'"]
```

We need to update sshrun to understand `-o` if we want to substitute it for `GIT_SSH_COMMAND`.

> what about the Travis switch to Xenial is making it show up,

Trusty had Git 2.15.1.  The use of `-o` seems to have been added in Git v2.16.0, specifically 0c2f0d2703 (connect: tell server that the client understands v1, 2017-10-16).

> or why it isn't showing up in the other spots where `datalad sshrun` is used with localhost (e.g., the create-sibling tests)

Dunno.

**Comment by kyleam** [comment]
> We need to update sshrun to understand `-o` if we want to substitute it for `GIT_SSH_COMMAND`.

Confirmed with c80b9c16a that this resolved the issue: https://travis-ci.org/datalad/datalad/builds/575428381

Later today I'll clean up those sshrun changes and submit a PR.

**Comment by yarikoptic** [comment]
Well done detective @kyleam!!!
