### ISSUE TITLE
Take a look at RF'ing SSHManager to use https://www.fabfile.org

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3609]
It seems to provide most, if not all functionality as a standard lib. @bpoldrack What do you think?

Additional functionality:

- enables remote ENV configuration
- sftp

**Comment by bpoldrack** [comment]
At a first glance - looks good. Need to dig a bit into paramiko in addition.

**Comment by yarikoptic** [comment]
it has its gotchas.  Since it is pretty much independent implementation of ssh client, there is no out of the box treatment of ssh agent/keys, control paths/sockets support is not implemented at all (see e.g. https://github.com/paramiko/paramiko/pull/1341 et al).  So, I would say it would be first to identify the problem(s) which it would solve and see if trade-offs wouldn't be too high ;)

**Comment by mih** [comment]
For https://github.com/datalad/git-annex-ria-remote we considered it, and ended up deciding that a straight-up `ssh` client is the more robust choice.
