### ISSUE TITLE
diff drivers

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3670]
This relates to the generic need for `diff --content` (#2160) but more of an "extended" issue on top of it.  We (core and extensions) should be able to 

- provide/register "differs" to be used with our `datalad diff`,  e.g. 
  - datalad-neuroimaging would provide the ones to diff neuroimaging files
  - datalad-containers could provide `container-diff` which would use https://github.com/GoogleContainerTools/container-diff
- we might have a priority list of which differ to use for which group of files where possible to deduce (e.g. `["nib-ls", "fsleyes",...], for `*.nii.gz` files), not unlike to how git-annex asks external enabled special remotes either they could handle a specific URL IIRC

Attn @dnkennedy

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.

**Comment by mih** [comment]
Linking the related git-docs here, because it makes sense to match the API of external diff helpers: https://git-scm.com/docs/git#Documentation/git.txt-codeGITEXTERNALDIFFcode

As an alternative/supplement, it would make sense to consider git's textconv feature too (or rather provide an analog), which is a way to use a custom tools to turn a file into a diff'able textual representation.
