### ISSUE TITLE
Remove UI support functionality from Repo classes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3738]
The most intrusive thing in this category is low-level code trying to figure out how many files to `get` in order to render proper progress bars. Given that in many cases (now) high-level code has executed `status()` or some of its lower-level helpers, this information is likely to be present already, and duplication in low-level code is just slowing things down (and also needlessly complicating the logic).

I believe that we should RF this to just yield the relevant progress log messages, which can either be ignored by a caller, or put to use in a progress bar that is properly configured by the caller already.

**Comment by yarikoptic** [comment]
Elevating progress reporting to higher level `get` sounds like a good idea. It should also help to provide more adequate progress reporting - now it is just per dataset. But implementation should be cautious to not actually introduce slow downs due to additional log messages passing etc.

**Comment by mih** [comment]
I looked into this, and it is essentially impossible right now. From the `Repo` helper for running commands down to the `Runner` methods nothing supports yielding output, hence all processing would need to happen inside `Runner` (which would be straight-up insane).

The only alternative I can see is a fundamental overhaul of the `Runner`, or more likely an implementation of a (partial) replacement.

I will get in line behind the other volunteers.

**Comment by yarikoptic** [comment]
probably not directly applicable here (I already forgot that kitchen) BUT I today found https://github.com/eric-wieser/generatorify when I needed to turn "function with a callback" into a generator, so I could yield progress indication within `dandi-cli`.  Here is relevant use code abomination:
https://github.com/dandi/dandi-cli/pull/26/files#diff-74f6c2c900ab727dbb2c5c3ac2bd83d5R470

Ideally we should avoid such workarounds, but wanted to share since who knows - might come handy

**Comment by mih** [comment]
Runner can yield now. There is no major blocker for quite some time now. However, there is no interest/time to work on this. No point to keep this open. Closing this issue of mine.
