### ISSUE TITLE
Standard layout for Examples in docstrings

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#3757]
I started to work towards a DataLad "cheat sheet" [here](https://github.com/datalad-handbook/book/pull/157). @mih stressed that this should be best done in close interaction with the actual docstrings, and @yarikoptic voiced interest in short examples for such a cheat sheet. Given that, I want to try to provide examples for commands for the docstrings. For this I would like to get some input on a standard format for examples, because whenever examples exist, their layout is quite diverse, and I assume its best to settle for a standard in advance and then stick to it & adjust those that use a different one. Below I've included examples of all different layouts I have found (I've only checked on the master branch):

<details>
<summary>Layout as used in save, rerun, search </summary>

```
    Examples:

      Save any content underneath the current directory, without altering
      any potential subdataset (use --recursive for that)::

        % datalad save .

      Save any modification of known dataset content, but leave untracked
      files (e.g. temporary files) untouched::

        % dataset save -u -d <path_to_dataset>

      Tag the most recent saved state of a dataset::

        % dataset save -d <path_to_dataset> --version-tag bestyet

```
</details>

<details>
<summary>Layout as used in drop and uninstall</summary>

```
    Examples:

        Drop all file content in a dataset::

            ~/some/dataset$ datalad drop

        Drop all file content in a dataset and all its subdatasets::

            ~/some/dataset$ datalad drop --recursive
```
</details>

<details>
<summary>Layout as used in clean, download_url, ls, extract_metadata</summary>

```
    Examples:

        $ datalad clean
```
</details>

<details>
<summary>Layout as used in support/gitrepo.py</summary>

```
          Examples:
          no_commit=True => --no-commit
          C='/my/path'   => -C /my/path
```
</details>

<details>
<summary>Layout as used in support/param.py, support/path.py, support/strings.py, tests/utils:with_testrepos, utils.py</summary>

```
        Examples
        --------
        Ensure a parameter is a float
        >>> from datalad.support.param import Parameter
        >>> from datalad.support.constraints import (EnsureFloat, EnsureRange,
        ...                              AltConstraints, Constraints)
        >>> C = Parameter(constraints=EnsureFloat())

        Ensure a parameter is of type float or None:
        >>> C = Parameter(constraints=AltConstraints(EnsureFloat(), None))

        Ensure a parameter is None or of type float and lies in the inclusive
        range (7.0,44.0):
        >>> C = Parameter(
        ...         AltConstraints(
        ...             Constraints(EnsureFloat(),
        ...                         EnsureRange(min=7.0, max=44.0)),
        ...             None))
```
</details>

<details>
<summary>Layout as used in support/third/nosetester.py
</summary>

```
    Examples
    --------
    Adding the following::

            if __name__ == "__main__" :
                    run_module_suite(argv=sys.argv)

    at the end of a test module will run the tests when that module is
    called in the python interpreter.

```
</details>

<details>
<summary>Layout as used in tests/utils:with_tempfile:
</summary>

```
    Examples
    --------

    ::

            @with_tempfile
            def test_write(tfile):
                    open(tfile, 'w').write('silly test')

```
</details>

<details>
<summary>Layout as used in datalad/customremotes/archives:get_file_url
</summary>

```
        Examples
        --------

        dl+archive:SHA256E-s176--69...3e.tar.gz#path=1/d2/2d&size=123
                when size of file within archive was known to be 123
        dl+archive:SHA256E-s176--69...3e.tar.gz#path=1/d2/2d
                when size of file within archive was not provided


```
</details>

Is there any argument against [PEP-287 (reStructuredText Docstring Format)](https://www.python.org/dev/peps/pep-0287/), i.e., 

```

>>> print 'Python-specific usage examples; begun with ">>>"'
Python-specific usage examples; begun with ">>>"
>>> print '(cut and pasted from interactive sessions)'
(cut and pasted from interactive sessions)
```
?

Also, I don't know which branch that would be done on best. Does anyone have an opinion on that?

**Comment by kyleam** [comment]
I think it's worth classifying the different types of examples you posted.  The two main types I see are CLI invocation and python code, with the remaining being examples of miscellaneous things like argument handling and return values.

> Is there any argument against [PEP-287 (reStructuredText Docstring Format)](https://www.python.org/dev/peps/pep-0287/), i.e.,
> 
> ```
> 
> >>> print 'Python-specific usage examples; begun with ">>>"'
> Python-specific usage examples; begun with ">>>"
> >>> print '(cut and pasted from interactive sessions)'
> (cut and pasted from interactive sessions)
> ```
> 
> ?

IMO this should be the preferred form for Python code.  Something to keep in mind is that these snippets will be executed through doctest unless explicitly disabled.  In general that's a good thing, though I've been tripped up a few times by `python -m nose --with-doctest ...` working without an import of the module itself while sphinx seems to require it (e.g., 75e0b8d91).

But using `>>>` for the CLI examples would be confusing because many readers would take `>>>` as the python interpreter prompt.  Also, we'd have to prevent them from being run as doctests.

That means that for the CLI examples the style to use is less clear-cut.  I don't have a strong preference, but agree that using a consistent style would be a good thing. I have a slight preference for the save/rerun/search style you showed, and I think the drop/uninstall examples could be switched to it without losing anything.  In my view examples like the `clean` one, which has no accompanying text, don't add any information and should be avoided.

> Also, I don't know which branch that would be done on best. Does anyone have an opinion on that?

My opinion is that this should happen on the master branch.

**Comment by kyleam** [comment]
@mih Yep, I'd be happy to see things move in that direction.

**Comment by yarikoptic** [comment]
+100 on the issue/effort

+1 on the master branch choice

+10 on the @mih's idea on using a data structure. There we could prescribe both cmdline and python examples.  

Some notes, which might or not be useful ;-):

- cmdline examples are rarely if ever applicable to non-Interface derived classes
- regular Python style examples could be built on the fly and (I hope, didn't check how they are picked up) become subject to doctests
- corresponding cmdline vs Python choice (in Interface-derived classes) could be made dynamically depending on the use (from cmdline vs Python API)
- implementation should keep in mind possible performance penalty, i.e. specific examples should not be processed until actually needed/used (e.g. we have [a basic benchmark](http://datalad.github.io/datalad/#core.startup.time_help_np) for timing `datalad --help-np` which could be of guidance here as well)

**Comment by kyleam** [comment]
Thanks for looking into this.  I think it'd be a nice improvement.

> Example-wise I'm thinking of easy, short examples, such as ( `%` denoting CMD and `>>>` denoting Python API examples):

Unlike python examples used in non-command docstrings, most (if not all) of the examples for commands don't actually stand on their own and couldn't be executed (both because they have place holders and because they aren't surrounded by sufficient setup/teardown).   We might eventually want to extend the dictionary to provide this setup/teardown for some of the examples, but even then I don't think we'd want to put all of that in the docstring. 

Because of this difference, it might be better to replace the conventional `>>>` with something else.  `py>`?

> It might be a bit inconvenient to specify both examples for the command line and the Python interface with the `[PY: PY]`/`[CMD: CMD]` notation (however I would try to do that for as many commands as I can, and I wouldn't mind), but maybe it is possible to "translate" from CMD API to Python API automatically - I would start doing it without the translation first though, and if I can make that work, I might feel adventurous enough to try smile.

Why not put the python and command-line variants under separate keys (e.g., "cli" and "python")?  The appropriate one could then be injected based on what is being rendered.

**Comment by adswa** [comment]
There is the  ``autorunrecord`` Sphinx extension @mih wrote that we use in the handbook to create code snippets + output. It executes code snippets locally in a specified directory and captures the output. 
For example, this is how it looks like for a ``datalad create`` command:
```
.. runrecord:: _examples/DL-101-101-101
   :language: console
   :workdir: dl-101

   $ datalad create --description "course on DataLad-101 on my private Laptop" -c text2git DataLad-101
```

and this is what is captured and included in the handbook:

```sh
$ datalad create --description "course on DataLad-101 on my private Laptop" -c text2git DataLad-101
[INFO] Creating a new annex repo at /home/me/dl-101/DataLad-101 
[INFO] Running procedure cfg_text2git 
[INFO] == Command start (output follows) ===== 
[INFO] == Command exit (modification check follows) ===== 
create(ok): /home/me/dl-101/DataLad-101 (dataset)
```

It further has the option ``realcommand`` to "hide" commands, for example like this:

```
.. runrecord:: _examples/DL-101-108-114
   :language: console
   :workdir: dl-101/DataLad-101
   :realcommand: echo "$ datalad rerun $(git rev-parse HEAD~1)" && datalad rerun $(git rev-parse HEAD~1)
```

and here is what is captured from this:

```sh
$ datalad rerun dc6dcbf29d34a13677ae53e2163afae4ee3c357f
[INFO] == Command start (output follows) ===== 
[INFO] == Command exit (modification check follows) ===== 
add(ok): recordings/podcasts.tsv (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (notneeded: 1, ok: 1)
  unlock (notneeded: 1)

```

We could use this for this purpose. Setup and teardown could be handled with the ``realcommand`` option, and the captured output could be included in the docstrings.

**Comment by mih** [comment]
Fix has been merged. Closing.
