### ISSUE TITLE
`datalad` special remote not auto-enabled

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3830]
Just reporting it, no research yet:

```
% datalad install -s mih@brainbfast:/somepath/HCP
[INFO   ] Cloning mih@brainbfast:/somepath/HCP into '/tmp/HCP' 
[INFO   ] access to 1 dataset sibling datalad not auto-enabled, enable with:                                                 
|               datalad siblings -d "/tmp/HCP" enable -s datalad 
```

why is it not being auto-enabled? A recursive install would give me 5k subdatasets to tune.

**Comment by bpoldrack** [comment]
Hm. Looking at that part of `clone`'s code, I think we just notice here, that our call to `git-annex-init` did not result in the special remote being autoenabled (which suggests a clearer message here). I am, however, not currently clear whether that detection is correct. It's based on what we find or don't find in the config. Not sure that annex would indeed necessarily write that on auto-enabling a special remote, since that value has to be set via `enableremote` and stored in git-annex branch anyway if it was to have any effect.
Did you check whether it's really not enabled, @mih?

**Comment by mih** [comment]
No, I did not check.

**Comment by mih** [comment]
OK, the cause was user error. Thx @bpoldrack !
