### ISSUE TITLE
remove() should announce `annex dead`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3887]
Did not investigate, but it occurred to me that with short-lived one-off clones of a dataset, we might track tons of annexes that are long gone and can never come back.

**Comment by yarikoptic** [comment]
yes, it will be the case.  It might be impossible to "announce" back in origin (e.g. I am offline, I should be able to "remove" without being able to talk back).  There should be analysis if "origin" (its git-annex branch) or actually any sibling, knows about this UUID. If not -- it should be ok to just kill it without announcing it dead to anyone.

In addition to announcing removed dataset, I wondered if we could provide `--throw-away` option to `install` which could help preventing proliferation of `git-annex` branch with records for all those deadly ones somehow.

May be we could 
- mint a new git annex UUID for the clone deterministically (so - all such clones would have the same UUID) based on the UUID of the original one
- give that UUID to annex instead of the one it would create
- pronounce that clone untrusted

There is a flaw in above -- git-annex might become unhappy if from some other clone it inherits information about availability of that clone.

Just an idea

**Comment by mih** [comment]
FTR: We are already working on an implementation of such a thing, but using a different approach. Will report once complete and found successful.

**Comment by mih** [comment]
Ping https://github.com/datalad/datalad/issues/3528
