### ISSUE TITLE
git-annex --help  is using unix-style filenames thus not working on windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#39]
http://www.onerussian.com/tmp/gkrellShoot_01-29-15_103025.png

**Comment by joeyh** [comment]
This behavior is not git-annex at all, it's msysgit, apparently trying
to use html man pages on windows, since there's probably no man command.

To see git-annex's behavior, without involving git, instead run
"git-annex --help" or just "git annex"

I don't see any changes I can make in this area, other than maybe
shipping a Program Files/Git/doc/git/html/git-annex.html file. 

(Windows doesn't much care which way the slashes go. Although down not
across is subtly encouraged by the whole Windows OS.)

-- 
see shy jo

**Comment by joeyh** [comment]
BTW, I think it would be better to file such bug's in git-annex's own bug tracker, unless this imacts datalad in some way I am not seeing.
