### ISSUE TITLE
[ERROR] not available; Try making some of these repositories available

### ISSUE THREAD

**Issue by soichih** [datalad/datalad#3923]
datalad get on openneuro datasets(?) often fails with these error messages.

```
[ERROR] not available; Try making some of these repositories available:; 	30982af9-1bcd-4f66-8e56-79cc3143b587 -- root@79cd556289f8:/datalad/ds001219 [get(/mnt/datalad/datasets.datalad.org/openneuro/ds001219/sub-07/anat/sub-07_T1w.nii.gz)] 

[ERROR] not available; Try making some of these repositories available:; 	30982af9-1bcd-4f66-8e56-79cc3143b587 -- root@79cd556289f8:/datalad/ds001219 [get(/mnt/datalad/datasets.datalad.org/openneuro/ds001219/sub-06/anat/sub-06_T1w.nii.gz)] 

[ERROR] not available; Try making some of these repositories available:; 	30982af9-1bcd-4f66-8e56-79cc3143b587 -- root@79cd556289f8:/datalad/ds001219 [get(/mnt/datalad/datasets.datalad.org/openneuro/ds001219/sub-08/anat/sub-08_T1w.nii.gz)] 

[ERROR] not available; Try making some of these repositories available:; 	30982af9-1bcd-4f66-8e56-79cc3143b587 -- root@79cd556289f8:/datalad/ds001219 [get(/mnt/datalad/datasets.datalad.org/openneuro/ds001219/sub-10/anat/sub-10_T1w.nii.gz)] 
```

When I try it on a later day, I am often able to "get" the entire dataset. I think there is something wrong on openneuro/s3 end, but I am not sure.. Should I contact OpenNeuro instead?

Also, is there a way to crawl through all datalad datasets to make sure which dataset are currently assessible? I guess I can just try dataset get/drop on a random file from each dataset periodically?

**Comment by yarikoptic** [comment]
Unfortunately there is a growing number of openneuro datasets which are "broken" one way or another.  I [have reported on a number of them/issues](https://github.com/OpenNeuroOrg/datalad-service/issues/created_by/yarikoptic), only some were fixed up. 

> When I try it on a later day, I am often able to "get" the entire dataset.

oh, that is interesting.  not sure if I have observed such behavior yet.  Also I [do not see any issue against http://github.com/OpenNeuroDatasets/ds001219](https://github.com/OpenNeuroOrg/datalad-service/search?q=ds001219&unscoped_q=ds001219), please join the "whiners on datalad-service" team.  

<details>
<summary>Here is the files I see missing in that dataset (the others I `datalad get`ed ok)</summary> 

```shell
(git)smaug:/mnt/scrap/tmp/ds001219[master]git
$> git annex list | grep '^_' 
_____ sub-02/anat/sub-02_T1w.nii.gz
_____ sub-03/EEG/EEG_events_sub03.mat
_____ sub-03/anat/sub-03_T1w.nii.gz
_____ sub-04/EEG/EEG_events_sub04.mat
_____ sub-04/anat/sub-04_T1w.nii.gz
_____ sub-05/EEG/EEG_events_sub05.mat
_____ sub-05/anat/sub-05_T1w.nii.gz
_____ sub-06/EEG/EEG_events_sub06.mat
_____ sub-06/anat/sub-06_T1w.nii.gz
_____ sub-07/EEG/EEG_events_sub07.mat
_____ sub-07/anat/sub-07_T1w.nii.gz
_____ sub-08/EEG/EEG_events_sub08.mat
_____ sub-08/anat/sub-08_T1w.nii.gz
_____ sub-10/EEG/EEG_events_sub10.mat
_____ sub-10/anat/sub-10_T1w.nii.gz
_____ sub-11/EEG/EEG_events_sub11.mat
_____ sub-11/anat/sub-11_T1w.nii.gz
_____ sub-12/EEG/EEG_events_sub12.mat
_____ sub-12/anat/sub-12_T1w.nii.gz
_____ sub-13/EEG/EEG_events_sub13.mat
_____ sub-13/anat/sub-13_T1w.nii.gz
_____ sub-14/EEG/EEG_events_sub14.mat
_____ sub-14/anat/sub-14_T1w.nii.gz
_____ sub-15/EEG/EEG_events_sub15.mat
_____ sub-15/anat/sub-15_T1w.nii.gz
_____ sub-16/EEG/EEG_events_sub16.mat
_____ sub-16/anat/sub-16_T1w.nii.gz
_____ sub-18/EEG/EEG_events_sub18.mat
_____ sub-18/anat/sub-18_T1w.nii.gz
_____ sub-19/EEG/EEG_events_sub19.mat
_____ sub-19/anat/sub-19_T1w.nii.gz
_____ sub-20/EEG/EEG_events_sub20.mat
_____ sub-20/anat/sub-20_T1w.nii.gz
_____ sub-21/EEG/EEG_events_sub21.mat
_____ sub-21/anat/sub-21_T1w.nii.gz
_____ sub-22/EEG/EEG_events_sub22.mat
_____ sub-22/anat/sub-22_T1w.nii.gz
_____ sub-23/EEG/EEG_events_sub23.mat
_____ sub-23/anat/sub-23_T1w.nii.gz
_____ sub-24/EEG/EEG_events_sub24.mat
_____ sub-24/anat/sub-24_T1w.nii.gz
_____ sub-25/EEG/EEG_events_sub25.mat
_____ sub-25/anat/sub-25_T1w.nii.gz
```
</details>


> Also, is there a way to crawl through all datalad datasets to make sure which dataset are currently assessible? I guess I can just try dataset get/drop on a random file from each dataset periodically?

AFAIK openneuro team has plans to establish such QA, but also AFAIK it has not happened yet.

That is partially why I thought that if you just built on top of `datalad search` or `datalad metadata` output (instead of redoing metadata extraction independently), then you could have avoided these issues, since we would share only the metadata for the datasets/files we did manage to obtain from openneuro.
 
Ping: @effigies @nellh @franklin-feingold

**Comment by soichih** [comment]
Oh, so datalad search/metadata is aware of the data access issue and it won't show results if something is wrong? That is handy! Yes, I am planning to incorporate search results from datalad search/metadata while indexing all data items. Right now, I can't figure out a way to search all matching entries.. Like looking for fmap only shows 1 entry, among other issues..

> datalad -f json -c datalad.search.index-egrep-documenttype=all search bids.type:fmap

Also, when I import the references to brainlife, I need to map between BIDS file structure and brainlife datatypes. For this, I am using part of brainlife CLI script (https://github.com/brainlife/cli/blob/master/bids-walker.js) that can walk through BIDS structure and converts them to brainlife data-object entries. I believe I can use both bids_walker, and argument information from datalad metadata to populate richer metadata? 

Whatever we do, however, I think it's confusing to other datalad users that openneuro datalad repo will show files that aren't accessible at the file structure level. I think something needs to be fixed on OpenNeuiro ends, or broken file entries to be removed (or datalad to filter them out - based on what it shows from datalad metadata?)

**Comment by yarikoptic** [comment]
> datalad -f json -c datalad.search.index-egrep-documenttype=all search bids.type:fmap

Eh, this is the result of us not harmonizing on top of pybids which was (or still is) in flux, if you use `bids.modality` not `bids.type` you would get some (but I am not sure if all) hits... 
Looking back at the https://github.com/datalad/datalad-neuroimaging/blob/master/CHANGELOG.md#020-feb-09-2019----am-i-compatible-with-you-honey I am confused, since I do not see any "suffix" field in the results, and that is what it should have become for some datasets.

I think, if you decide to go this (datalad) way, I (or you are most welcome to try) would invest time into trying current pybids and adjusting if needed `datalad-neuroimaging`, on some sample datasets making sure we get all the fields we (you) would need, reaggregate (download where needed/possible, extract, drop upon complete if was downloaded) the entire hierarchy of datasets where bids was one of the extractors.  That would be useful overall (beyond integration with brainlife).
It might also be worth me finally trying datalad-metalad, unless @mih says that I better don't touch/whine yet ;)

> I believe I can use both bids_walker, and argument information from datalad metadata to populate richer metadata?

I believe that if datalad metadata missing anything you need, we need to add it, so actually datalad would provide "richer" set, sufficient for brainlife (and others) to get the subset they need (without requiring them to actually download all of those datasets).  @mih could correct me if I am wrong ;)

>  I think it's confusing to other datalad users that openneuro datalad repo will show files that aren't accessible at the file structure level. I think something needs to be fixed on OpenNeuiro ends, or broken file entries to be removed (or datalad to filter them out - based on what it shows from datalad metadata?)

yes, it is confusing!  Depending on the underlying issue, removing some of them in those datasets (we have no control over them) might be the way to go, but I hope that it would just require going through all those datasets, fixing identified issues, and then establishing/improving QA to identify issues which arise before publishing dataset to their github organization.

**Comment by nellh** [comment]
@soichih This is definitely an OpenNeuro bug, looks like we managed to push the main branch for the dataset but not the git-annex branch, leaving this one in a confused state. I've fixed this dataset and we'll add a check for this in the next release to catch others. Feel free to [report issues with OpenNeuro datasets on our repo](https://github.com/openneuroorg/openneuro/issues) and we'll sort/forward them if it's not an OpenNeuro problem.

It might look like you can later get the dataset without error because git-annex ignores this remote for those files once they've failed once. @yarikoptic Do you know how to ask Datalad/git-annex to try these URLs again? I am not seeing how to do that.

**Comment by bpoldrack** [comment]
@nellh : There should be an `annex-ignore = true` line in the respective remote section within `.git/config`. I think you could just delete that line and trigger an explicit update of availability information via `git annex fsck --from <remote name> --fast`.

**Comment by adswa** [comment]
Closing this issue as I think it is directed and has been addressed at OpenNeuro's end. Please reopen if I am mistaken.
