### ISSUE TITLE
Silent failures due to interaction between custom_result_renderer() and log.result-level

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3953]
Some of our `custom_result_renderer` definitions return early if a `status` other than "ok" is encountered.  For example, here's the beginning of the `RunProcedure.custom_result_renderer`:

https://github.com/datalad/datalad/blob/b1f33d17bd2630bf202dcf584d94acb9670c6cd1/datalad/interface/run_procedure.py#L468-L474

As the comment suggests, these checks exist to avoid double reporting of errors and warnings, things like

```
$ datalad run-procedure not-there
[WARNING] Cannot find procedure with name 'not-there' [run_procedure(not-there)]
run_procedure(impossible): not-there [Cannot find procedure with name 'not-there']
```

In response to the same double reporting concern, 60d088feb (ENH: Introduce datalad.log.result-level config switch, 2019-10-06) made it easy to demote the logging messages.  While both the `custom_result_renderer` check and `log.result-level` seem fine enough on their own, they can squelch all messages when combined.  To continue with `run_procedure` as an example, running

```sh
#!/bin/sh
set -eu
cd "$(mktemp -d --tmpdir dl-XXXXXXX)"
datalad create >/dev/null 2>&1

git config datalad.log.result-level debug
datalad run-procedure not-there
```

leads to no log message being shown and no result being rendered.

With the introduction of `log.result-level`, we should revisit these `custom_result_renderer` checks.

---

Based on some quick grepping, here's a list of commands with a `custom_result_renderer` that returns early when given a status other than "ok":

- `metadata`
- `run_procedure`
- `siblings`
- `status` (also used by `diff`)

**Comment by mih** [comment]
FTR: I noticed yesterday a related pattern where results are not re-emitted by intermediate code in order to prevent flooding the output with pointless messages. This is (now if not always) a problem, because such action cannot be acted upon anymore (think result hooks). Decisions in UI behavior and logs should be made by UI code and not by the respective result handling code.

**Comment by mih** [comment]
> With the introduction of log.result-level, we should revisit these custom_result_renderer checks.

I am uncertain what action is best. If we are OK to start treating *any* logging as optional and not part of the main/mandatory communication with a user, things are clear and we unconditionally operate on any result, regardless of configuration. If we cannot agree on that, we would have to query the configuration for each result and infer what would be best.

IMHO the former is the only sensible way to go. Otherwise we would say that critical information *on a result extracted from a particular result record* does not make it to a result renderer (i.e. does not make it outside the command, hence cannot be acted upon in any way).

A complication comes from the combination of result renderer selection and `result_xfm` settings. It looks as if presently setting a `result_xfm` (which is done by default in cases like `install`) turns of any execution of "tailored" result renderers (and possibly also renders hooks unusable, because `result_xfm` is applied before any evaluation of original result records is done).

**Comment by kyleam** [comment]
> If we are OK to start treating _any_ logging as optional and not part of the main/mandatory communication with a user,

Yes, that matches my view of logging, though my impression is that this is far from datalad's approach.

> things are clear and we unconditionally operate on any result, regardless of configuration.
> If we cannot agree on that, we would have to query the configuration for each result and infer what would be best.

My opinion is that we should unconditionally operate on any result.  That might lead to some double reporting, but `log.result-level` allows those to be demoted.

> IMHO the former is the only sensible way to go. Otherwise we would say that critical information _on a result extracted from a particular result record_ does not make it to a result renderer (i.e. does not make it outside the command, hence cannot be acted upon in any way).

I agree.

**Comment by mih** [comment]
OK, I will address this with the following approach. This is already done by `siblings`, and I will extend it to the rest of the list above.

Whenever there is a custom result handler that is being presented with an error result that is was not built for, it will pass it to `generic_result_renderer()` and return afterwards.

Otherwise, we can follow the plan laid out above for any specific situation where this will lead to message duplication. The key point is:

*Any result given to a renderer should be processed regardless of whether (at some point) there was a log message on it (in addition).*
