### ISSUE TITLE
provide user accessible (API) interface to credentials

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#396]
Should allow to list, add, remove, modify credentials "managed" by datalad one way or another.

**Comment by mih** [comment]
Seems as if this could be a plugin.

**Comment by mih** [comment]
As discussed in #4981, the key issue that prevents work on this for 5 years now is the inability of the credential system to list all known credentials, and by extension making it hard for users to even know what credential should be edited in order to impact a particular service/functionality.

https://github.com/datalad/datalad/issues/4981#issuecomment-705706777 argues that this is not necessary, because `Provider`s can report the IDs of the credentials they require.

However, this leaves out any credential relevant beyond plain download authentication (pretty much any service auth: github/lab and friends, OSF, webdav).

**Comment by mih** [comment]
https://github.com/datalad/datalad-next now provides a `credentials` command, which does exactly that.
