### ISSUE TITLE
Establish core `*Repo` classes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3988]
Following the plan from https://github.com/datalad/datalad/issues/3192 I want to approach the move of the `Dataset` and `*Repo` classes under `datalad/core` in the source tree.

Having done a fair amount of digging through the code layers over the past few months, I am playing with an idea already mentioned in #3192:

> move core dataset and repo classes into dataset/ (or rather core/dataset/). it might make sense to split Git/AnnexRepo into a core and an extended interface also (via inheritance), the number of rarely used methods is substantial ATM

While from a technical angle this may cause more trouble then benefits, I believe the potential for strategic development is substantial. I am thinking about issues like #3714 that are both hard to see and hard to tackle, because everything is so intertwined.

So what about the following plan:

- establish new base classes for `GitRepo`, `AnnexRepo`, `Dataset`, each with the name prefix `Core`, and place them, and only these new classes under `datalad/core`. The original classes will then derive from the new bases while keeping there API 100% intact.
- adjust all code under `datalad/core` to exclusively use the new classes, and populate them with any functionality that is actually required by code in `datalad/core`. When moving code to the base classes, make sure strategic development goals are met (GitPy removal, `normalize_paths` removal, result communication rather than error handling in low-level code, etc.)

This is likely to become a lengthy process (slow transition of code from super into the base class), but it should be a process that minimizes the impact on users and functionality, while still providing the wiggle room necessary to tackle a number of long-standing issues.

What do you think @datalad/developers ?

**Comment by bpoldrack** [comment]
I think, this is generally the right way to go. However, as you pointed out in the second point, it should involve a major review of those classes, definition of the goals, etc.
My issue here is, that this might well lead to a redesign that would simply not have the ´*Repo` classes. I'm not yet sure about this, but it seems to me, that - while being intuitive - subclassing `GitRepo` for `AnnexRepo` isn't particularly useful.

I'm not clear whether start transitioning to core that way is helping that process or making it harder.

**Comment by yarikoptic** [comment]
a minor comment on one aspect:

> * establish new base classes for `GitRepo`, `AnnexRepo`, `Dataset`, each with the name prefix `Core`, and place them, and only these new classes under `datalad/core`. The original classes will then derive from the new bases while keeping there API 100% intact.

I would probably recommend to avoid `Core` prefix.  Since not all classes of the `.core` would have `Core` prefix, better to not introduce such only to some but not the other.  Modular Python structure already allows for unambiguous imports (from unambigous `.core` vs `.support`), and it would only be a question of which ones are exposed as part of the `datalad.api` (and keeping a mental note to keep an eye on imports while coding).  For `.api`, we could keep it `.support` ones to start with, and switch later on to the `.core` without requiring any code tune up.  Also it would make it easier for downstream projects to not require adjusting code (`GitRepo` vs `CoreGitRepo`), and only `import` statements.

**Comment by mih** [comment]
I will close this. The first steps are made and there is nothing in this issue that informs future steps.
