### ISSUE TITLE
get() should rename 'origin' of a subdataset to match superds remote is was cloned from

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4005]
Aspect of original #1956 reported by @mvdoc on behalf of @yarikoptic 

If a subdataset is found to be available as a subdataset underneath a superdataset's clone/remote, and ends up being installed from that location, its origin remote should match the one of the superdataset's remote.

Implementing such a behavior will counteract the fix for https://github.com/datalad/datalad/issues/3926 in #3966

**Comment by kyleam** [comment]
> on behalf of yoh

You just confused some poor user with no connection to datalad :]

---

I think this issue boils down to the same issue @dorianps raised in gh-3968.  As suggested by my [comment][0] there, I'm not sure this a good direction to go, but it seems it has come up enough that perhaps I'm missing something.

[0]: https://github.com/datalad/datalad/issues/3968#issuecomment-569822527

**Comment by dorianps** [comment]
Pardon if I am out of line here, but I don't understand the conceptual problem with having remotes in subdatasets match the remote in the parent dataset where it came from. This strategy looks more sensible to me than leaving [origin] remotes around when the user never intended to create [origin].

In terms of use cases, we can imagine a master dataset and multiple researchers working on different [remotes] to produce new data. For example, John works on applying fmri pipelines to produce new subdatasets in his fmri parent dataset, while Brian works to  produce structural mri morphometric data. At the end, the master location needs to be updated with these two new sources of data. They cannot be both [origin] in subdatasets as they are conceptually different sources. Thus, when pulling John's changes it should be as simple as `datalad update --merge --sibling john && datalad get .` and the same for `--sibling brian`.

I find collaborative data processing to be the strength of Datalad, so I would facilitate this scenario and avoid having [origin] when is neither needed nor requested by the user... even this means the logic of remotes changes from git.

**Comment by dorianps** [comment]
Fyi, this issue continues for me at v.0.12.2 (installed from github some days ago). If updates are pulled from another location and there is a new subdataset, you cant get the files from the new location because the remote for that location does not exist yet. One needs to add the remote manually before attempting `get`, but this causes massive errors when there are hundreds of subdatasets most of which already have the remote. Seeing the errors is concerning, but at the end it works.

I think this behavior of datalad makes very little sense. The user works on a sibling and does not need to know what is origin, and why git puts origin on newly pulled subdatasets, and why the sibling the user is working on does not exist despite pulling the data from that location. I think datalad should take care of this to avoid multiple iterations just to pull the changes (and the data) from location A to location B.
