### ISSUE TITLE
Now that revolution is here, are "fixed-in-revolution" addressed?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4012]
There is a good number of open issues 
https://github.com/datalad/datalad/labels/fixed-in-revolution
I guess many of which could be closed.  @mih would be the one to know.

Since revolution is here AFAIK, probably label itself should be dissolved.

**Comment by mih** [comment]
I keep monitoring all issues (hence the number is an issue for me). All open issues of this kind need to stay open. The majority is concerned with metadata, and those fixes were once in -revolution, but where then moved to -metalad in order to increase the changes of a -revolution merge. Metadata is next up on my list...

**Comment by mih** [comment]
Label dissolved now.
