### ISSUE TITLE
Q: what config(s) should  datalad command -d /super /super/sub1/sub2/file load? 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4076]
Relates to #4072, but decided to not side track it with my possibly naive question:
 
Besides the global/system/user configuration files, what configuration files a

   datalad command -d /super1/super2 /super1/super2/sub1/sub2/file 

should load

a. of  sub2/ (if already available, if not and `command` `get`s it first, it would get reloaded in the process)
b. of /super2
c. of /super2, and sub2/
d. of /super2, sub1/, and sub2/
e. of /super1, super2/, sub1/, and sub2/
? 

Should (could) it be independent of which specific datalad `command` it is (i.e. uniform behavior) ?

Relates: https://github.com/datalad/datalad/issues/3905

**Comment by bpoldrack** [comment]
sub2 only. (Well, plus --global, --system obv.)

I wouldn't even know how to start building a mechanism, that reasonably can deal with including superdatasets' configs. It would require the ConfigManager to interpret config keys semantically in that it needs to decide whether or not it makes any sense to read a particular key, since a lot of them quite obviously can't be valid for the sub (like `core.something`, `annex.something`, `remote.something`, `datalad.dataset.id`, ...). This would be a mess unless you introduce a prefix declaring what dataset a key belongs to. And that doesn't make sense either, because if you just want to know about super's config, you can and should simply ask super's `.config`.

**Comment by mih** [comment]
I agree with @bpoldrack (if he meant`super2` not `sub2`)

In general, however, this makes it sound that such a command would not read additional config -- which is obviously not the case, and very much depends on what that command actually does inside and what datasets it touches in addition. What remains true, though, is that config is per-dataset and follows Git's inheritance mechanism only (plus `.datalad/config` handling). If we want superdataset config affect subdataset behavior, we have to put it into the subdataset config -- and we do that in many places.

**Comment by bpoldrack** [comment]
Oops. Yes, `super2`, of course.

**Comment by yarikoptic** [comment]
Thanks for the responses but it was a bit too many words and corrections, sorry, I was asking for one letter answer a-e + possible yes/no ;)

If I read correctly, you both suggest that `b. of /super2` is the answer.  If so -- YODA principle is violated since in effect, it would ignore configuration within `sub2/` (any custom url remappings, procedures, etc), commands would operate differently (and possibly incorrectly) from when executed within that `sub2/` dataset, and would diverge from git behavior which cares about config of the repository operation is performed on.  Or have I misread your answer(s)?

**Comment by mih** [comment]
> Or have I misread your answer(s)?

You have possibly missed this part: ;-)

> In general, however, this makes it sound that such a command would not read additional config -- which is obviously not the case, and very much depends on what that command actually does inside and what datasets it touches in addition.

**Comment by yarikoptic** [comment]
Ok, I think it is all ok ;-) sorry for the noise.  I guess nothing is to be spelled out
