### ISSUE TITLE
DOC: use short versions of options in code_cmd examples

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4105]
spotted while reviewing https://github.com/datalad/datalad/pull/4104

I do see that some examples use shortened options (e.g. `-m` not `--message`) but majority (or at least those @kyleam has tuned, while retaining original form) seems to use long ones. 
I myself also short versions, especially for the most common ones.  So I wondered why should we provide examples with long ones, even if we ourselves use short options... I would have voted to use short ones (`-r`, `-m`, etc) in the `code_cmd`, especially for the common and most obvious ones.  Even in the cheat sheet short ones are more "prevalent" (well, due to lack of space ;)) : http://handbook.datalad.org/en/latest/basics/101-136-cheatsheet.html

**Comment by kyleam** [comment]
I suppose I have mixed feelings about using short options in the CLI examples.  I think the long options are better for clarity, even for options that experienced users might take as obvious.  (And, for scripted command-line calls, my view is that the longer form is almost always preferable for this reason.)

But, as you point out, using long options doesn't really match how most people use any command-line tool interactively.  For users that are comfortable on the command line, I don't think our unrealistic use of long options will really be a big deal.  They'd just think "this feels like a common option that should have a short variant, ... scrolls and finds it ... ".  On the other hand, users that are being reluctantly dragged into the command line by DataLad might not realize there are shorter options and come away with the wrong impression ("guh, that's tedious, why do I have to type all of that").

That of course is assuming a blanket use of short or long.  Perhaps it's worth deciding case-by-case how likely the option is to be clear based on things like `text` and the placeholder names used for option values.

So I dunno.  Ultimately I think whatever judgment @adswa makes here is fine.

**Comment by yarikoptic** [comment]
+1 on @adswa making a hard decision here ;)  I agree with you @kyleam that it is a stick of two ends.  I am myself leaning toward the middle-ground (use short ones only for common -d -r ... as per cheatsheet) and long ones for the others.

**Comment by adswa** [comment]
-1 on me making a hard decision here ;-) 
(as for the cheatsheet: short options were solely used for a blatant lack of space)

I'm torn in the same way as @kyleam, and I think there are too many things to consider to make a general rule easy or possible. I have a few thoughts (but they were not part of my thought process when I created the examples, so they will likely contradict what I might have done so far ;-) ):

- The main thing an example should be is understandable and work when tried out
- There are known and lesser known command options. I would consider things such as ``-m`` (because its just like Git's ``-m``), ``-d`` (because it is used so often) or ``-r``, ``-f`` (because there are so many standard commands that use it) to be understandable in long and in short form. Other command options are not so common across commands (e.g., ``-u/--updated`` for ``save``) or their abbreviation is not immediately connected to the short version (e.g., ``-s/--name`` for ``siblings`` ). In my opinion, such "known" options can (but do not necessarily need to) be abbreviated without causing confusion/hinder understanding/lead to long searches for what these options mean. For "lesser known" commands, my personal understanding would benefit from seeing the long option at least once. 
- In some cases the long options can help to understand what is going on. Personally, I would need to memorize ``-n`` for ``get``, whereas ``--no-data`` requires no memorizing - I can understand right away what will happen. The same is true for ``-s/--name`` or even ``-i/--input``/``-o/--output`` and I'd like to make this connection by seeing the long option at least once
- I don't mind mixing long and short versions across examples. It a very subjective opinion, but the mild confusion this causes in me helps me understand and engage with the command more. Only in the context of a succession of examples that get increasingly complex, I think it is helpful to keep repeating options specified in the same way to highlight whatever new options gets added to the command.
- Some examples will get a large number of options. I bet it looks different from case to case, but if I see 5 short options (that keep the length of the example shorter) I may not understand or parse that example as well as opposed to, say, a line-broken, structured example that is longer because of double-dash options


So I think the middle ground @yarikoptic is proposing works for me, but in general I'm reluctant to make general rules ;-)

**Comment by yarikoptic** [comment]
> So I think the middle ground @yarikoptic is proposing works for me, but in general I'm reluctant to make general rules ;-)

I would then treat it as +1 and that would make +2 vs 0 of other explicit votes ;)

**Comment by yarikoptic** [comment]
removed "feedback-desired" since the decision was reached ;) we just need takers to make it happen

**Comment by andycon** [comment]
I am happy to be a taker here. So the plan to is to go through code_cmd examples and change obvious long options, e.g., --message --> -m, and the like, and for obscure option pairs, -s/--name, to go in general with long.
