### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4238]
Here is what I would consider a sensible release management strategy that is suitable for the workforce we have and is compatible with my personal development pace. Please let me know what you think @yarikoptic @kyleam @bpoldrack @adswa 

For clarity, I am using the example of an upcoming 0.13.0 release for everything below.

1. When the time is ripe a `maint/0.13` branch is split from `master`. From this new branch a 0.13.0 release will be made eventually. This event imposes no constraints on further development in `master`. The timing of this event is either *subjective* (enough new stuff in `master`), or *objective* (a certain time time has passed since the last release). Only bug fixes are allowed into `maint/0.13`, ever. They must not be mixed with API changes, beautifications, or minor additions. It is important to maintain this rule to keep development focused on `master` and the "pressure" to release high.

2. All developers now devote a reasonable fraction of their time to manual (i.e. additional) testing of the `maint/0.13` code. This period is kept reasonably short (e.g. one week, but no more than two) to ensure that the testing effort goes towards quality control of an impending release (otherwise efforts will diffuse and commitment vanish). Newly discovered issues are reported and tagged with a `rc-0.13.0` (release-critical) milestone whenever they reflect regressions with respect to the last release. A initial issue "update changelog for 0.13" is filed, and tagged accordingly. This milestone is **not** populated with existing issues (except for those with severity *critical*, or regressions with respect to the last release) that would also be nice to get fixed. They could have been fixed before the start of the 0.13 release process, but were not, which is enough evidence that a fix is not considered valuable enough to invest, or is not possible with the given resources. This is not to say that these issues should not get fixed, just that the lack of the fix does not impact a 0.13.0 release.

3. All fixes merged via PR into `maint/0.13`. When new issues are discovered the `rc-0.13.0` milestone is continued to be populated, according to the criteria listed in (2). It may be necessary to untag originally release-critical issue. Reasons could be systemic problems that are not manageable at the moment, or developers conclude that the relative importance of an individual fix does not outweigh the need for a release.

4. Whenever the `rc-0.13.0` milestone is empty after the test period in (2), `0.13.0`is tagged in `maint/0.13` and released immediately. There is no need for further deliberation. It will take as long as it takes to fix the release critical bugs.

5. After a `0.13.0` release, the `maint/0.13` branch is kept and continued using the rules in (1). Strictly for fixes only. Further maintenance releases can be made at any time.

6. Developers should consider proposing PRs for fixes to be merged in `maint/0.13`. However, this is not mandatory. As long as we have dozens of conceptual/systemic issues open, development focus should be on the next major release, not another maintenance release.

**Comment by yarikoptic** [comment]
Overall - would be glad to see workflow (including releases) being formalized nicely as drafted above.

Note that if you just replace `maint/0.13` with `maint` and `rc-0.13.0` with `0.12.3` -- it would already describe current flow, besides the IMHO critical "All developers now devote" (in 2.) part.  I would be truly happy to see that happen!

I am Ok to reintroduce `0.MINOR.x` branching in any form (note that here suggested `maint/...` would require renaming current `maint` into `maint/0.12` or `0.12.x`, ok with me ;-) ).

I really do not see a point in having a dedicated `rc-0.13.0` milestone instead of `0.13.0` milestone + issue labels (e.g., `severity-critical`).

`... and released immediately` -- do we have a bot to prepare changelog and release immediately, or whose responsibility for the "immediate release" would it be?

**Comment by kyleam** [comment]
> For clarity, I am using the example of an upcoming 0.13.0 release for everything below.
>
> 1. When the time is ripe a `maint/0.13` branch is split from `master`. From this new branch a 0.13.0 release will be made eventually. This event imposes no constraints on further development in `master`. The timing of this event is either *subjective* (enough new stuff in `master`), or *objective* (a certain time time has passed since the last release).

By doing this split at an undetermined time along `master` rather than always having a dedicated maintenance branch (no new features, only pure bug fixes), you unnecessarily couple maintenance and feature releases.  Instead, my preference is to always have a maintenance branch (`maint`).  `master` is a superset of this branch, and, when a release is made from `master`, `maint` gets fast-forwarded to `master`.

> Only bug fixes are allowed into `maint/0.13`, ever. They must not be mixed with API changes, beautifications, or minor additions.

I prefer the same for `maint`.

> 2. All developers now devote a reasonable fraction of their time to manual (i.e. additional) testing of the `maint/0.13` code. This period is kept reasonably short (e.g. one week, but no more than two) to ensure that the testing effort goes towards quality control of an impending release (otherwise efforts will diffuse and commitment vanish).

It's not clear to what that would mean in practice, but it's sounds like an unnecessary burden.  Most of the fixes that land there will get testing through our use of `master`.  Sure, maybe the code in question was rewritten in `master`, or there could be interactions.  But we're talking about restricted fixes that are coming in on the maintenance branch.  There's no reason to take the focus away from `master`.

> Newly discovered issues are reported and tagged with a `rc-0.13.0` (release-critical) milestone whenever they reflect regressions with respect to the last release. A initial issue "update changelog for 0.13" is filed, and tagged accordingly. This milestone is **not** populated with existing issues (except for those with severity *critical*, or regressions with respect to the last release) that would also be nice to get fixed. They could have been fixed before the start of the 0.13 release process, but were not, which is enough evidence that a fix is not considered valuable enough to invest, or is not possible with the given resources. [...]

This seems to be conflating milestone and release decisions with branch management.  Putting bug fixes on `maint` doesn't mean that there has to be a maintenance release; given `master` is a superset of `maint`, those fixes can just be released as part of the next feature release.  Of course, if there is a particularly bad bug (e.g., say the issue I spotted and fixed with e8c5d70690 right after 0.12.0 had instead been noticed after `master` had progressed much farther), then we have the freedom of being able to quickly release `maint` without worrying about it being intertwined with other changes.

Also, in the context of a maintenance branch, I don't think "release critical" deserves all this attention and ceremony.  The maintenance branch has fixes on top of the last release, so, as you mention, the only things that are "release critical" are regressions introduced by those fixes. That of course happens, but when we're not doing large changes and rewrites in that branch, the odds of that go way down.  In almost all cases what we'd cut from any point on `maint` is in better release shape than the last release we made.  If our maintenance branch is filled with new regressions, we have serious issues with our review process to be concerned about.

> 5. After a `0.13.0` release, the `maint/0.13` branch is kept and continued using the rules in (1). Strictly for fixes only. Further maintenance releases can be made at any time.

So... then we get to where we already are with the current `maint` (which is based off of 0.12.2).

> 6. Developers should consider proposing PRs for fixes to be merged in `maint/0.13`. However, this is not mandatory. As long as we have dozens of conceptual/systemic issues open, development focus should be on the next major release, not another maintenance release.

It's not a big deal if a fix that applies to `maint` but doesn't go there; we can consider cherry picking it if we decide it's worth it, but in many cases it's fine to just let it be.  At the same time, deciding whether a change is a fix that applies to `maint` doesn't take that much focus or time away from the major release.

And if a major rewrite is the way that a whole slew of bugs is fixed in master, that's great.  `maint` is in no worse shape than the last release it is based off of.

---

I'm trying to disentangle having a maintenance branch from any release management issues woes and frustrations.  Keeping a maintenance branch, and being somewhat mindful of putting changes on top of there, keeps a separation so that we can easily and readily make maintenance releases, but it's not inherently tied to how often we decide to make feature releases from master.

**Comment by mih** [comment]
> I'm trying to disentangle having a maintenance branch from any release management issues woes and frustrations. Keeping a maintenance branch, and being somewhat mindful of putting changes on top of there, keeps a separation so that we can easily and readily make maintenance releases, but it's not inherently tied to how often we decide to make feature releases from master.

I am not confident that I got all your points correctly, but I feel that you were more focused on the nature of the maintenance branch, while I was more focused on a process that gets us to release, while dealing with the constant worry that `master` is not in a releasable state. I would consider it valuable, if you would write down the complete story of how things should work (release and maint) rather than contrasting it with my proposal. I think we are relatively close, and I am not married to the details of my proposal. As long as I can find my key concerns in your procedure, I would be happy to adopt it. Thanks in advance!

**Comment by kyleam** [comment]
>  but I feel that you were more focused on the nature of the maintenance branch, while I was more focused on a process that gets us to release, while dealing with the constant worry that `master` is not in a releasable state.

Yeah, I'm focused on the nature of the maintenance branch because that's a tangible thing that I care about, and in your proposal it's getting moved in a direction that I wouldn't like to see and that I don't think helps what you're concerned about ("the constant worry that `master` is not in a releasable state").

> I would consider it valuable, if you would write down the complete story of how things should work from your perspective (release and maint) rather than contrasting it with my proposal.

It's not that your second concern isn't the more important concern, but I have no proposal that will somehow fix disagreements (particularly the ones I've seen between you and Yarik) about whether master is release ready.  That's a squishy problem that I don't know how to solve, though with the 0.12 release I think I certainly played some role in moving it along and making it happen sooner.

So, for triggering a feature release, I really have no other proposal than "someone want to get a feature release out because it's been a while or there's something that's hit master that they want released soon.  Communicate that, and give people time to object or point out what they think are regressions. [... deal with that ...]".  This was obviously painful for 0.12, where the incompatible changes were widespread and extreme.  For 0.13, I'd hope it will mostly be smooth sailing.

**Comment by yarikoptic** [comment]
> For 0.13, I'd hope it will mostly be smooth sailing.

refs:
- https://github.com/OpenNeuroOrg/datalad-service/issues/116#issuecomment-594655007
- I am yet to see if `heudiconv` managed to touch any of the removed APIs

**Comment by mih** [comment]
Here is the protocol of the verdict after discussion in a call with @yarikoptic @kyleam and @bpoldrack 

1. At minimum the latest (but if desired also any other) release has an associated `maint` branch.
2. All developers are asked to direct bugfix PRs to a `maint` branch when possible, but cherry-picking fixes into a `maint` branch is equally acceptable.
3. Any developer can push a merge of `maint` into `master`. It is left to the individual developer to decide whether it is necessary to open a PR for such an update.
4. When approaching a release:
    1. A release preparation cycle is started with a RC release from `master` that bumps the version, and includes a complete changelog. With the public announcement of the RC release, developers (and users) are explicitly asked to evaluate the RC and file issues as necessary.
    2. After the first RC release, `master` is temporarily treated like `maint` branch. Feature PRs are no longer merged into `master` (the necessity for a temporary integration branch is evaluated on a case by cases basis)
    3. The initial RC might be followed by additional RCs, depending on the severity of the problems discovered. But there is a general understanding to limit the time window until `master` can accept new features again.
5. The final release is made by tagging `master`. Afterwards, the main `maint` branch is fast-forwarded to the release, and `master` is open for new features again.
