### ISSUE TITLE
Remove GitRepo.checkout()

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4246]
It looks like this:

```
    def checkout(self, name, options=None):
        """
        """
        # TODO: May be check for the need of -b options herein?
        cmd = ['git', 'checkout']
        if options:
            cmd += options
        cmd += [str(name)]

        self._git_custom_command('', cmd, expect_stderr=True, updates_tree=True)
```

Little value or no added value over a plain `call_git()`, undocumented, unconditionally reloads config (which is relatively expensive).

**Comment by yarikoptic** [comment]
again - the value is of not having/using a generic `call_git` and have common operations interfaced via API (a method), so 
- while coding we could just `.repo.command` instead of `.repo.<figure out if we interfaced that command or I should just craft a direct call_git>`
- troubleshoot incorrect behavior of a `command` without chasing it around multiple `call_git` invocations

We should really settle this aspect -- did we ever agree to break API and replace all simple inside `.command`s with direct `call_git`?

**Comment by mih** [comment]
> We should really settle this aspect -- did we ever agree to break API and replace all simple inside `.command`s with direct `call_git`?

No, we did not agree to break the API. We agreed to not use incomplete, inflexible wrapper methods that unconditionally enforce (slower) behavior. The "break API" is just me, because I get to figure out each time whether I should be using one of these unmaintained, undocumented, untested wrapper, or whether I should make a direct git call. And I personally think it is better to not have a method than have one that needs maintenance that it doesn't get, and performs poorly on top of this.

**Comment by yarikoptic** [comment]
so just fix/refactor the wrapper to use `call_git` -- that is the beauty of centralizing access to a command in such interfaces.  I really do not get the "slower" and "inflexible" argument here. If some special need arises for a kludge (direct mode, adjusted branch, etc) or special handling of outputs (e.g., --json mode is added in case of an annex command) -- you would immediately might have a place to do it instead of fishing out all individual `call_git` calls, refactoring them back into a method, which you might later again decide to dissolve when kludges are gone, etc.

**Comment by mih** [comment]
I am now convinced that the status quo is less effortful. I can perfectly make direct call, and ignore the wrapper. I am sure the grand rewrite will come at some point. Although it seems pretty perfect already:

```
cb2978a0a7 (Michael Hanke          2016-09-27 10:16:01 +0200 2744)     def checkout(self, name, options=None):
64a4fd6202 (Benjamin Poldrack      2015-04-23 11:28:25 +0200 2745)         """
64a4fd6202 (Benjamin Poldrack      2015-04-23 11:28:25 +0200 2746)         """
82ff9c5186 (Benjamin Poldrack      2015-07-30 14:34:19 +0200 2747)         # TODO: May be check for the need of -b options herein?
cb2978a0a7 (Michael Hanke          2016-09-27 10:16:01 +0200 2748)         cmd = ['git', 'checkout']
cb2978a0a7 (Michael Hanke          2016-09-27 10:16:01 +0200 2749)         if options:
cb2978a0a7 (Michael Hanke          2016-09-27 10:16:01 +0200 2750)             cmd += options
cb2978a0a7 (Michael Hanke          2016-09-27 10:16:01 +0200 2751)         cmd += [str(name)]
91a8d22715 (Benjamin Poldrack      2015-04-23 12:38:40 +0200 2752) 
7fda144547 (Yaroslav Halchenko     2018-11-02 14:50:21 -0400 2753)         self._git_custom_command('', cmd, expect_stderr=True, updates_tree=True)
```

or it is what they call "technical debt".
