### ISSUE TITLE
Unlike Git, Datalad doesn't complain when removing an unknown sibling

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#4249]
I'm not sure if its known or on purpose, but I found that datalad stays silent when I attempt to remove a sibling that does not exist - Git on the other hand talks to me when I remove a non-existent remote.

```sh
(handbook) ╭─adina@muninn /tmp/ds on master
╰─➤ datalad siblings remove -s nonexistent
(handbook) ╭─adina@muninn /tmp/ds on master
╰─➤ git remote remove nonexistent
fatal: No such remote: 'nonexistent'
```

Personally, I would find it helpful if DataLad says something similar to Git, but that's just a subjective opinion :)

**Comment by kyleam** [comment]
> a subjective opinion

Sorry, only objective opinions allowed around here :]

**Comment by kyleam** [comment]
My preference matches yours.

When the remote doesn't exist, it's cast as a "notneeded" result, which is filtered out here:

https://github.com/datalad/datalad/blob/8a174f5cf67c8917392de7001cc0e412d93a0b0f/datalad/distribution/siblings.py#L302-L306

These filters are related to a larger issue (see gh-3953).  (On top of that issue, the example here indicates a related problem: these filters should not catch "notneeded" results because, even when `datalad.log.result-level` is left at its default value, the "already logged" comment doesn't apply.)

Anyway, for the purpose of addressing _this_ issue, I think it'd be sufficient to adjust `Siblings.custom_result_renderer` to explicitly handle a `{"action": "remove-sibling", "status": "notneeded"}` result and give an appropriate message through `ui.message`.  Would you like to give that a try?

**Comment by adswa** [comment]
> Would you like to give that a try?

I would love to (some time in the next few days), thanks, and thanks for the pointers! :)
