### ISSUE TITLE
Possibility to change general logging behavior

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#425]
I am not an expert wrt to our logging setup so let me ask this:

Is it possible to stop putting "ERROR" logging output on the terminal immediately, and simply collect it until we know for sure that an actually relevant error or exception has occurred (for example when an exception reaches the cmdline entry-point)?

Our current approach is the manually mark steps where an ERROR is no error, but who know how long that stays valid and under which circumstances we may still be interested in the logs we just swallowed. Delaying the output could be a solution that scales better.

Am I wrong?

**Comment by yarikoptic** [comment]
not sure how that could be feasible to achieve really, besides may be for the top user-level interface to instruct to swallow all the ERROR logs until the function finishes and then spit them out only if it finishes not abnormally (e.g. doesn't through exception)... at such level should probably be doable but would delay/complicate logging output I guess (since you wouldn't be able to print any logging msg until function is done), which could at times undermine the purpose of logging.  IMHO it remains correct to mark those executions which expect output in stderr as such
