### ISSUE TITLE
Delete annex files of past commits + other questions

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4307]
#### What is the problem?
A few questions as we learn more how to use datalad:
1. How do I delete annex files from ALL past commits? Yes, I know that I can't roll back to earlier commits anymore, but I don't need to keep around old file versions that are corrupt.
2. Related to the first but more specific. I plan to distribute the data every once in a while, and I plan to mark version tag the released commit so we know exactly at which points we gave the data out. Thus, I need to keep annex content of some (tagged) commits so I can roll back as needed if someone asks for that specific version of the data. But I do not need (or like) to keep file content for commits between the released commits. Is there a way to drop all content linked to commits between two commits A and B?
3. It is still unclear to me what happens when I install a dataset from somewhere and get the files? Does the `get` command get all the content even from past commits, or just the current one? I am asking because I will need to just distribute a version of the data from a specific commit, not all past annex content.

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.2

#### Is there anything else that would be useful to know in this context?
NA

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes

**Comment by yarikoptic** [comment]
Before the actual answers:  I got confused by

> Yes, I know that I can't roll back to earlier commits anymore...

why you can't?  `git checkout PASTCOMMIT && git annex drop whatIwant && git checkout -` should still work ;-)

Re 1.+ 2. -- what you need is `git annex unused` and `git annex drop --unused` tandem.  See e.g. https://git-annex.branchable.com/git-annex-unused/ and https://git-annex.branchable.com/walkthrough/unused_data/ .  `git annex unused` has

```
  --used-refspec REFSPEC   refs to consider used (default: all branches)
```
so by default it would drop all keys not referenced by any current  branch.  https://git-annex.branchable.com/devblog/day_285__tuning_git-annex_unused_refs/ gives a nice  complicated example:

```
+refs/heads/*:+HEAD^:+refs/tags/*:-refs/tags/old-tag
```
to retain current content pointed in branches and all (but `old-tag`) tags.

`3.`  `datalad get` gets paths in current tree.  If they were last committed in the past commits -- it would be content as known to the current tree but as committed from the past commits.  It will be only that last version, not some versions prior (but since git annex indexes by content checksum, if the content from some older commits is now present in some other file, the key would be the same, and thus in effect by fetching current version of the other file, you might be fetching "older" version of another).

 You can use `git annex wanted` and `git annex get --auto` to accomplish flexible and more complicated setups which would fetch keys possibly for other commits etc.

**Comment by dorianps** [comment]
@yarikoptic  Thank you for helping.

The example you gave above did not work, but I ran this:

```
git annex unused --used-refspec +refs/heads/*
git annex dropunused all
```

This seems to have brought the folder size down to what I was expecting. But I am not very familiar with refs, did I do the right thing?

P.s. What I meant by cannot go to past commits is that those commits do not have annex file content, so they are useless.

**Comment by yarikoptic** [comment]
> The example you gave above did not work, but I ran this:
> 
> ```
> git annex unused --used-refspec +refs/heads/*
> git annex dropunused all
> ```
> 
> This seems to have brought the folder size down to what I was expecting. But I am not very familiar with refs, did I do the right thing?

I think so ;)  branches, tags -- are all "refs".  branches are "heads".  you can see them all under `.git/heads`.  It is quite fun actually to learn "git inside out".   For some good night sleep, I would recommend reading something like a "git parable" and/or ["git foundations"](https://matthew-brett.github.io/pydagogue/foundation.html) by nipy's Matthew Brett to see how to "build up to git".

**Comment by dorianps** [comment]
Thanks. I have read the Git Pro book advised in the datalad book as well. But will have a look at the other resources. Have been using also Udemy, but that Git Pro book is still the best.
