### ISSUE TITLE
Question: Ability to push only current (new) branch to upstream

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#4312]
I'm writing a chapter on ``datalad push`` and was trying to outline how to do "common" workflows. It occurred to me that one standard workflow I use Git for is not possible solely with DataLad:

Push a new, local branch (and only that branch) to a sibling (i.e., what I would use ``git push -u <remote><branch>`` for.

I wanted to raise the question on whether such a functionality would be desired. I'm myself more or less indifferent about it - my take is that anyone who would make use of such a workflow probably knows how to do it with Git, and I only very rarely use branches in my datasets. I'm just planning to write about ``push`` in detail and outline what is possible and what is not, so it would help to know if not being able to do what's described above is a conscious decision. :)

**Comment by mih** [comment]
Just FTR: I did not put this into the API, because

1. I am not aware of standard workflows that involve branching as a critical component (except for the three-branch crawling setup we use for HCP or openfmri) -- which affects few users on push
2. `push` honors git's configuration of upstream branches, so whenever there is any branch configured for push, it will push those, and all of them
3. if there is nothing configured for push at all, it will push the active branch (and `git-annex` if needed)

I think that covers more than 80% of the use cases, and the added complexity to make `datalad-push` match `git-push` more in terms of flexibility is not worth the cost.

That being said, I am open for discussions on this point.

**Comment by yarikoptic** [comment]
since it was just a question, I mark it answered and closed

**Comment by mih** [comment]
Fair enough to. But for the record, in the past month I have learned that there is indeed a workflow that needs this, and I am using a dedicated git-push in it, to achieve what was being asked for here (UKB processing)
