### ISSUE TITLE
ria vs ora: I am confused.

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4377]
I need to get clear understanding of difference between `ria` and `ora`, and see what commands, API, and tests should be renamed to reflect new naming... I thought that `ora` is to be a "correctly named ria" ("ria" is for "remote indexed archives", so should have nothing to do with the hierarchy of UUID based named datasets).  
But what is "ora"?  
Special remote is actually "ora" not "ria", but commands are "-ria".  `create-sibling-ria` only mentions "ora" config variable without even mentioning what ora is:
```
 $> datalad create-sibling-ria --help | grep -1 '\<ora\>'
by setting the configuration variable
"annex.ora-remote.<storage-sibling-name>.ignore-remote-config".
```
hard to search for "ora" on http://handbook.datalad.org/en/latest/search.html?q=+ora since it is part of "st**ora**ge"

**Comment by bpoldrack** [comment]
>  ("ria" is for "remote indexed archives", so should have nothing to do with the hierarchy of UUID based named datasets).

First off - forget that "translation" of RIA. It's nowhere anymore. We can come up with another explanation of what it stands for, if we feel the need.

RIA: Keeping the name for existent stores (and files/configs therein). It names the concept of such stores which may or may not come with datasets using the special remote. It's merely about the organization of those stores (as is everything that still contains that name as in `create-sibling-ria` RIA is about what kind of thing to talk to - `github/gitlab/a RIA store`.

ORA - "Optional remote archive": The actual special remote. Has conceptually nothing to do with those stores, which is why we separated both from eachother in naming.

**Comment by kyleam** [comment]
FWIW I'm also confused.  I've read @bpoldrack's comment a few times, and I still don't grasp the difference.

I suppose this is the key point I'm missing:

> ORA - "Optional remote archive": The actual special remote. Has conceptually nothing to do with those stores, which is why we separated both from eachother in naming

Isn't this special remote the provided to interact with the stores?  Doesn't that mean it does conceptually have something to do with it?  Perhaps I need an analogy.  `git commit` : commit object :: ora : ria ?

**Comment by yarikoptic** [comment]
Ok - ria is the collection of datasets bars on their uuid. So RIA will be "Remote uuId Archive" in my mind now. It (optionally) can be ORA it have content be collated in the .xz archives.
I guess the closest git analogy would be - ria is our way to store git repos (which could be submodules). ora is the compressed object store

**Comment by bpoldrack** [comment]
Yes, @yarikoptic. Trying to be a bit more clear, @kyleam (and yes there's a relation between the two, but they are not the same thing):

RIA is merely the way datasets are organized in a store (including ID based URL resolution as supported by clone). 

RIA can support multiple layouts at two levels:
- where is a dataset repo based on its ID - that is: the location `git` needs to talk to
- where/how to store `annex/objects` (where: that dir could theoretically be completely elsewhere; how: currently dirhashlower vs. dirhashmixed)
This doesn't require a special remote. As long as `datalad-clone` resolves the RIA URLs, standard mechanics work if there's just a bare repo for example.

ORA is the special remote, which can access `annex/objects` over SSH and deal with an archive at the remote end instead of keys in `annex/objects`. Both can be mixed (it will look up a key in archive when it doesn't find it in standard location.

Relation between the two is that ORA does understand RIA URLs and reads the store's layout settings to find above mentioned locations. So, ORA is intended for those stores, but the stores can work without it. BTW: That's true the other way around as well: One can have a RIA store, that only works with ORA and has no git repositories at all.

Just another way to put it: RIA is about how to resolve `ria+` URLs (like `ria+http://mystore.org#d4745371d`) to let `git` and `git-annex` know whom to talk to.

**Comment by kyleam** [comment]
All right.  Thanks, @bpoldrack and @yarikoptic.

**Comment by kyleam** [comment]
> > ("ria" is for "remote indexed archives", so should have nothing to do with the hierarchy of UUID based named datasets).
> 
> First off - forget that "translation" of RIA. It's nowhere anymore.

http://store.datalad.org/ says, "Welcome to the DataLad Remote Index Archive (RIA) Store."

**Comment by bpoldrack** [comment]
Good point actually, @kyleam. Wasn't aware.This needs to be fixed then.

**Comment by mih** [comment]
There is no mentioning of RIA outside URLs on that page anymore. I hope it is now sufficiently obscure.
