### ISSUE TITLE
autoenable=yes is not understood by git-annex - should we mitigate?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4379]
Issue filed in git-annex: https://git-annex.branchable.com/bugs/does_not_understand___34__yes__34___as_boolean_true_value_for_autoenable/

Original issue reported on neurostars: https://neurostars.org/t/datalad-install-problem-ds002393/6544/3

Installing such a dataset leads to datalad quetly (well - inform at DEBUG level only)
```
[DEBUG  ] configuration for 1 special remote s3-PUBLIC added because of autoenable, but no UUIDs for them yet known for dataset /tmp/ds002396 
```
and do nothing.  I wonder if we (for our precious users) should mitigate such cases and explicitly invoke `git annex enableremote` for such cases?  

openneuro's datalad-service switched (I guess without due testing, but somewhat logically) from using `true` to `yes` early January 2020, so quite a good number of recent datasets are effected.
(TODO: will file an issue with them and adjust here)

**Comment by bpoldrack** [comment]
>  I wonder if we (for our precious users) should mitigate such cases and explicitly invoke git annex enableremote for such cases?

I'd rather avoid such dances. This is (kind of) a twofold third-party bug.
- OpenNeuro used an annex configuration that annex doesn't work with. They need to fix their datasets.
- annex doesn't behave quite git-conform here - probably to be fixed by Joey. 

We could mitigate, but: We build upon annex and say so. So any user who knows annex should be able to rely on whatever git-annex does, particularly with configurations. Interpreting annex configs differently than `git-annex` itself seems a troublesome principle to me, although *probably* not really threatening a legit usecase in this particular case.

**Comment by kyleam** [comment]
As I mentioned in the git-annex bug report, git-annex 7.20200202.7 or later would have rejected the invalid value.  Assuming resolution on the OpenNeuro side, I agree with @bpoldrack that I'd rather not add the proposed workaround on our side.  I do think it's worth considering logging some information at the warning level.

**Comment by yarikoptic** [comment]
ok, decided then -- we do nothing ;)  related: #4383
