### ISSUE TITLE
Inode requirement datalad installation on HPC

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4403]
Following the handbook, using conda, a datalad installation (core + -containers, + git-annex + p7zip) ends up being more than 40k inodes. Quite a chunk!

**Comment by mih** [comment]
FTR: a deployment as a singularity image might be a workable alternative (see e.g. https://github.com/ReproNim/containers#installation) for the handbook @adswa . Maybe @kyleam and @yarikoptic could comment on its utility when the goal is to execute a containerized pipeline (that is provided by a third party). AFAICS this would lead to nested container execution, and may have limits in an HPC context.

**Comment by kyleam** [comment]
> AFAICS this would lead to nested container execution

I don't have any direct experience with trying this, but I recall there being an issue running singularity from within singularity.  My initial search just turned up me saying the same thing in [gh-3745][0], but I didn't provide any links.  Digging a bit more now, perhaps I'm thinking of <https://github.com/sylabs/singularity/issues/1245>.

[0]: https://github.com/datalad/datalad/issues/3745#issuecomment-537196608

**Comment by yarikoptic** [comment]
since it is impossible to run singularity within singularity, then `datalad-container` cannot be used, which might be a boomer.  Ideally HPC has a centralized deployment of datalad (e.g. via environments modules) thus not impacting per-user inodes limitations... or could be deployed (what does it take -- a minute or two?) installed upon demand somewhere under `/tmp`, we could provide some helper to do something like `source install_one_time_datalad.sh` ;)

**Comment by mih** [comment]
Ha, that is a cool idea. We could have a single `datalad` script that people can place in their PATH. It would need to be configurable (which extensions to pull), but otherwise this could work.

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
