### ISSUE TITLE
parse_url_opts() broken -- I think

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#441]
I may be missing something, but

1. This function is not tested at all, albeit used in the crawler
2. It is not clear how it could work, because it splits a URL by '#' to get to the parameters, although this should almost certainly be '?'

I guess it should use `urlparse` to split the URL, and postprocess `query`.

**Comment by yarikoptic** [comment]
YES.  And it is simply wrong since for some obnoxious (it wasn't late but was Friday!) reason I thought that `#` is used to separate out options in the url (should be `?`).  So should be fixed, may be RF'ed to use urlparse, and unittests provided

**Comment by yarikoptic** [comment]
Maan... I am really not sure what bright idea I had there to use '#' instead of '?' in the urls, but I did use it in construction of urls pointing to data within archives to embed information about the size of the file, e.g. currently for openfmri we have 
```
dl+archive:MD5E-s2527262329--bd3ea399057c529b37b09dcecec1ca60.0raw.tgz/ds001_R1.1.0/sub001/BOLD/task001_run001/bold.nii.gz#size=47241449
```
as an example "url" to point to the content within file, while giving us also information about the file size.  I don't see any conscious note from myself to ourselves on why I have chosen `#` over `?`, so may be I indeed just mixed up at that point, or may be I wanted to use explicitly the portion after '#' which is not processed by webservers (unlike url options after `?` being passed into the request) to provide a supplementary information which we could use.  Usually `#id` is used within urls to point webbrowsers to specific id within the page, so I don't think there is any RFC/standard regulating what should or should not be in there.
Since we do not have any really publicly consumed annexes yet, we could RF (as @glalteva did in #491) to use "correct" `?` but I wonder if we should do it; or just keep `#` for this specific case (internal supplementary information) ?  @hanke -- I will let you decide ;) and we will do it (I might still provide compatibility for now so we don't need to recrawl all test datasets for now).

**Comment by yarikoptic** [comment]
ok -- read more on it. 
In general there is no ultimate standard of what should or should not be in the fragment and various RFCs etc describe different usages for `#fragment` for different mime types, see https://en.wikipedia.org/wiki/Fragment_identifier .
In the original RFC (https://tools.ietf.org/html/rfc3986) the "#fragment" is described as

   The fragment identifier component of a URI allows indirect
   identification of a secondary resource by reference to a primary
   resource and additional identifying information.  The identified
   secondary resource may be some portion or subset of the primary
   resource, some view on representations of the primary resource, or
   some other resource defined or described by those representations.

So theoretically this could be the most conformant way to actually point to the file within the archive.  It also sounds legit for specifying the size ("additional identifying information") or checksums (I did see emails using fragment specifying e.g. checksum like `#md5=xxxxxx`, which is what lead me to this use of `#` here).  So ideally I guess instead of 
`dl+archive:SHA256E-s176--69...3e.tar.gz/1/d2/2d#size=123`
we could have used
`dl+archive:SHA256E-s176--69...3e.tar.gz#path=1/d2/2d;size=123`
This way we could theoretically even generate/support urls like `http://example.com/bla.tar.gz#path=1/d2/2d;size=123`.

I think I will take over #491 from @glalteva , RF it for use of `#path=` while providing compatibility with 'old' more custom specification format so we don't need to regenerate all those annexes for now.  But eventually we might regenerate them anyways so they all would get more 'compliant' urls.

@hanke what do you think?

**Comment by bpoldrack** [comment]
Sounds reasonable to me.
Nevertheless, I think one can see it two ways. It's either specifying a
secondary ressource within the archive or it's a query to the special
remote. I'd still prefer the latter, but it's a matter of taste, I guess.

2016-06-01 16:27 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
>    Sounds reasonable to me.
>    Nevertheless, I think one can see it two ways. It's either specifying a
>    secondary ressource within the archive or it's a query to the special
>    remote. I'd still prefer the latter, but it's a matter of taste, I guess.

indeed... especially given that the special remote is the one which
provides that piece... but size is nohow used by it really ATM -- I
added it so later we could get a sense of size even without relying on
parsing annex key which we might not have at the point of url
handling. I guess remote could use it as well to verify the size of
extracted file.
eh heh -- now I am again undecided ;)

**Comment by yarikoptic** [comment]
@joeyh please share your wisdom!  Which of the 3 url "schemes" you would prefer to refer to the content coming from an archive

1. (current) `dl+archive:SHA256E-s176--69...3e.tar.gz/1/d2/2d#size=123`
    - pros: objectively none, but that is what I have already in few annexes
    - cons: somewhat adhoc which wouldn't be understood by anyone else
2. (server options) `dl+archive:SHA256E-s176--69...3e.tar.gz?path=1/d2/2d;size=123`
   - pros: more inline with the fact that extraction atm happens within special remote (alike on server)
   - cons: `size` is not really anything for server to worry about besides may be for checking, but then may be  it could as well become `#size=123` (see 3)
3. (fragment) `dl+archive:SHA256E-s176--69...3e.tar.gz#path=1/d2/2d;size=123`
   - pros: somewhat inline with the idea of a `fragment`, we can theoretically use it for some regular public urls (e.g. `http://example.com/bla.tar.gz#path=...`) and theoretically other "clients" could support understanding of the 'path' and 'size' arguments here for mime types corresponding to archives
   - cons: it is not really handled by 'annex' as a client, but I guess could be paraphrased that special remote is the client which annex delegates the processing

or neither of those? ;-)

**Comment by joeyh** [comment]
As far as git-annex is concerned, these should all be fine, since it
just passes the url along and does not try to parse it. (And if it did,
it would treat urls differing only in #fragment as different.)

I sort of like your thinking in #3.

-- 
see shy jo

**Comment by yarikoptic** [comment]
so let it be #3 upon @joeyh 's blessing ;)  will do that, while still supporting 1. style urls for compatibility at least for now (they might need to go later when I would need to analyze/extend available per key urls)
