### ISSUE TITLE
Reinvestigate if wrapt is still needed

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4432]
Idea came up in a call that it might be an artifact of a previous necessity for PY2.

**Comment by bpoldrack** [comment]
Note:  It was introduced when I build the basis for the command decorator machinery (`@datasetmethod`, `@eval_results`, `@build_docs`, ...). AFAIR the problem was, that regular decorators wouldn't completely get the desired signature which we need to inspect. I'm not sure what aspects of the signature had that issue.
So, when reconsidering: Don't forget to check the generated docs for ALL arguments. Particularly the result related ones.

**Comment by mih** [comment]
There is evidently no capacity for doing so.
