### ISSUE TITLE
Point docs.datalad.org to last release?

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#4451]
A couple of recent issues were caused by https://docs.datalad.org/en/latest landing on a version of the docs that is for the tip of master.  Repeating what I said in [gh-4356][0]:

> I'm not very familiar with our docs.datalad.org setup, but I think a few things are worth considering to make things clearer:
> 
> * visiting a bare docs.datalad.org should land on the last release, not the development version
> 
> * The "latest" label is unclear. I would have guessed it was the latest release, but it's some point along the master branch. So perhaps we should come up with a clearer label ("master" or "dev"?).
    
What do others think?

[0]: https://github.com/datalad/datalad/issues/4356#issuecomment-606077900

Re: #4450
Re: #4356

**Comment by yarikoptic** [comment]
done. (just did it, someone with strong opposing opinion could undo):

Now we have 
- stable (default) -- corresponding to the most recent tagged release
- latest -- `master` branch
- maint -- `maint` branch just in case

**Comment by yarikoptic** [comment]
A little clarification since I rushed to close I think addressing the title of the issue -- what we have now is that `docs.datalad.org` points to `stable`.  But  https://docs.datalad.org/en/latest will remain pointing to the `master`.   We do reference `/latest` in the CHANGELOG.md (which  might want to change?) but README.md points to just docs.datalad.org so we should be good.

**Comment by adswa** [comment]
Stupid question: is a release candidate* a release?

*e.g., 0.13.0rc1 from yesterday?

**Comment by kyleam** [comment]
> is a release candidate a release?

I'd say no (i.e., in this context, https://docs.datalad.org should continue to land on 0.12.6).

**Comment by adswa** [comment]
Thx!
