### ISSUE TITLE
Q: push --since setup 

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4582]
The following is/seems the case ATM:

- `--since=None` -> entire state (diff against pre init commit state)
- `--since=''` -> diff against last recorded state of a tracked remote, on a if-there-is-any basis, otherwise like `--since=None`
- `--since='something' -> diff against this commit

I dislike `push --since ''`. What about changing that to a more expressive `push --since ^` to indicate "previous/last" state.

I briefly considered making `^` AKA `''` the default, but that would require introducing a cmdline compatible symbol to indicate "since ever" or "everything".

@datalad/developers Please let me know what you think. Thx!

**Comment by kyleam** [comment]
Starting off fresh, I think replacing an empty string value with `^` would be a good move.  I'd have an easier time recalling that `^` is the value that corresponds to the "diff against last recorded state of a tracked remote" option, and I'd guess that'd be true for most users.  I think the context is different enough that `^` already being used as a `Dataset` shortcut wouldn't be confusing.  However, if that is a concern, we could also go with `:` (vaguely refspec-y :).  And if we're worried about those being too cryptic, we could also append additional characters (e.g., `:sibling`).

I'm not sure how to weigh the above against consistency with `publish`, though.  I know `push` is free to do its own thing, but a slightly different value for `--since` seems like it's inviting unnecessary confusion among users that are already familiar `publish`s `--since`.

**Comment by yarikoptic** [comment]
my git rotten soul agrees better with `^` to mean previous state (do not even want to look ATM into our discussion for `^` to be used in `Dataset`).  But also it does mean exactly that -- "previous state" i.e. commit one before current.  FWIW git uses `^NUMBER` to point to specific subtree in case of the merge, so if we were to just support any "commitish" specification here, I would vote against using `^` for meaning something entirely different.

`:` - sounds like a good alternative!  it seems that there cannot be a tag or branch `:[something]` (I guess in general forbidding having `:` there to not mix up with ssh urls?), and indeed it would leave the possibility to specify which `:sibling` to consider.  So if to change to anything, could be `:`.  I would have added it to `publish` as of 0.13 with a note (warning?) that `""` is being deprecated (to be removed in 0.14 or 1.0 whichever comes first ;)) and ':' should be used instead.

**Comment by kyleam** [comment]
> But also it does mean exactly that -- "previous state" i.e. commit one before current.  FWIW git uses `^NUMBER` to point to specific subtree in case of the merge

You're talking about the `<rev>^` -> first parent case or more generally that `<rev>^N` names the Nth parent of `<rev>`, which is fair, but it seems a little strong to say `^` alone means exactly that.  0 is special-cased to peel to the commit object named by `<rev>`.  There are also various `^{}` forms, including `<rev>^{/<text>}`.  And `^<rev>` means something very different.

> it seems that there cannot be a tag or branch `:[something]` (I guess in general forbidding having `:` there to not mix up with ssh urls?)

The first thing that came to my mind was avoiding ambiguity with refspecs.  `man git-check-ref-format` mentions that and also mentions `<rev>:<path>`.

**Comment by yarikoptic** [comment]
> but it seems a little strong to say `^` alone means exactly that.

yes, I was imprecise in my description, indeed should have been `<rev>^[N]` the one I had in mind.  Yet to learn about `^<rev>`

**Comment by mih** [comment]
I would conclude from this discussion that I can go for `^`. I think we have plenty of time to make such a change to `publish` as well before the 0.13 release.

**Comment by yarikoptic** [comment]
Hm, I felt that discussion actually favored `:` over `^`

**Comment by mih** [comment]
Emoji vote to clarify

:tada:  -> `^`
:rocket:  -> `:`
:eyes: -> no change, stay `''`

Please vote @datalad/developers

**Comment by mih** [comment]
Vote confirms `^`
