### ISSUE TITLE
Prevent `run` from crashing due to another `run` process

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4606]
Scenario: I have an output dataset that needs to capture the outcome of 100k SLURM jobs. Each job adds one subdataset each to two intermediate superdatasets that are subdatasets of the output dataset. The is complicated, but a reality with fmriprep (it builds two disjoint subject trees, one for freesurfer and one for fmriprep, from a single invokation). The fmriprep container is configured in the superdataset, as is the single input raw dataset.

Ideally, there is a run record for each subject (which matches a single SLURM job). Ideally, all SLURM jobs can be submitted at once.

At the moment, SLURM jobs would randomly fail whenever two jobs exit simultaneously and `datalad run` attempts a `save`.

This is a concrete realization of #4401 

I have looked at `containers-run` and I see no way to mitigate the issue outside `datalad run` itself. It would already help, if `run` places a PID-identifying lockfile in the dataset that indicates that a `save` operation is running (which can take quite a while). Alternatively, we could investigate, if two simultaneously running `save` operations could succeed, if we only protect the final `commit`.

**Comment by bpoldrack** [comment]
> It would already help, if run places a PID-identifying lockfile in the dataset that indicates that a save operation is running

Why `run` rather than `save` itself?

**Comment by mih** [comment]
> Why `run` rather than `save` itself?

I suggested that as an alternative above, even to have it run in parallel within `save` as well. The question is: which other pieces would break? For `run` only explicit mode execution makes sense at all. For `save` it is unclear to me if there are technical constraints in the present implementation that prevent us from treating a call to `save` as being an "atomic" `commit`.

**Comment by bpoldrack** [comment]
Ok. Then I'd think we should try to treat `save` as atomic first. Only locking `commit` seems likely to only work in less cases, since the modifications to a file - say `.datalad/config` or `.gitmodules` - may already have changed at that point. And this would prob. not even lead to failure but to committing the wrong thing. The funny part seems to be to figure out when to lock subdatasets from within `save` (when do we even know which ones?). However, even having a "total lockdown" (lock all subdatasets no matter what) for `save` right at the beginning seems to me to be safe and already contribute a lot to concurrency issues although not being optimal. We should try that first, since it would cover more cases than `run` only.

Thinking about it, on the other hand: `run` prob. still requires its own lock, indeed - both `explicit` and not. Leading to the next thought (long term): If we lock a dataset for `run` makes sense to me even non-explicit to prevent concurrent modifications to be recorded. This suggests to me, that it may be useful to have the lock not be `run` specific, but rather something like having an "ongoing modification detection" lock and an "ongoing save" lock as a generalization to aim for.

**Comment by yarikoptic** [comment]
I am afraid that there is no ultimate winning solution: the safest/best approach is to lock at the level of the "top" invoked datalad `command` and the dataset it operates on - be it a `run`, `save`, `remove`, and lock the entire dataset(s) subtree.  
That is IMHO the only way IMHO to guarantee "atomic" operation for a `command` without introducing complicated solution and performance hit.

It would definitely not work for `run` in parallel execution setting where independent top level `run`s will be invoked. So it would require special config or option to explicitly surrender such protection.  It is somewhat orthogonal to the purpose of `--explicit`, so I do not think it should be "mixed in" into that "mode" of operation; but it is also usable **only** in the case of `--explicit` mode of operation (since we do not want arbitrary outputs being saved among racing `run`s). 

**The idea**: for `run` I think it would be sufficient to avoid locking the entire `run` command but to lock each subcommand separately (`get`, `unlock`, `save`).  There could be a generic config setting then - "datalad.lock.subcommands" which if set would not lock at the top command (which would overload this config while executing the top command).  And yes -- it will introduce run time penalty.  But I think it should be negligible in comparison to the other commands invocations.
 
**Full tree locking**: It is not feasible to lock each individual subdataset, **but** acquiring the lock for an operation (as an independent not yet locked command, "subcommands" just proceed upon a quick check that the process has a lock already for the tree for the command's dataset) could check if any superdataset has the "subtree" lock ATM.
Such lock should also be "respected" by top level datasets, which while considering such locked subdataset should not plow forward (they could fail or wait with timeout, depending on the setting expressing desires of the user).

**Comment by yarikoptic** [comment]
FWIW,  I had to workaround a "parallel running" issue during attempts to establish a sanitized $HOME while running a container, while setting up with git information, which is not sure you are trying to pursue in your parallel `run`s. My workaround was to just try a few times for now ;) https://github.com/ReproNim/containers/blob/master/scripts/singularity_cmd#L44

**Comment by mih** [comment]
Replaced by #6593
