### ISSUE TITLE
travis: neurodebian-devel git-annex cron job

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#4747]
The neurodebian-devel cron job run for git-annex was dropped in a462a4dcd (RF: .travis.yml - install annex using script, switch to conda-forge build, 2020-06-18).  @yarikoptic, was that intentional?

**Comment by yarikoptic** [comment]
I don't think so, I guess I got lost in yaml. Thanks for spotting it!

ATM though NeuroDebian devel build isn't really useful, so may be let's let it RiP at least for now... I think in the longer run, before updating NeuroDebian version of annex I will issue a through away PR which would switch to use it instead of conda so we have a full sweep
