### ISSUE TITLE
datalad subdatasets output should not just suppress output (or provide info on how to expand)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4770]
```
~/proj/nuisance$ datalad subdatasets -r
subdataset(ok): /home/chrispycheng/proj/nuisance/code/simple_workflow (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/QA (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/QA-mriqc (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/bids (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/mriqc (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/simple_workflow (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/sourcedata/dbic-BIDS (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/sourcedata/dbic-BIDS/Chang (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/sourcedata/dbic-BIDS/Chang/Chang (dataset)
  [53 similar messages have been suppressed]
action summary:
  subdataset (ok: 63)
```
the whole point of running the command is to see subatasets, so not sure if just suppressing without giving a hint on how to avoid that is a good UX

**Comment by mih** [comment]
@DisasterMo A possible strategy to address what is suggested in this issue, would be to amend the command class https://github.com/datalad/datalad/blob/master/datalad/local/subdatasets.py#L93 with a `custom_result_renderer()` method similar to the one in `run()` https://github.com/datalad/datalad/blob/master/datalad/core/local/run.py#L280-L291 (but even simpler).

It basically wraps the standard `default_result_renderer()`. Calling this function directly,  will bypass all result suppression logic, which only applies to the `default` result renderer (confusing name, it is not only default in most classes, but actually called `default`).

In order to make this custom render the new "default", the command class needs a `result_renderer = "tailored"` member, like here https://github.com/datalad/datalad/blob/master/datalad/core/local/run.py#L180

**Comment by mih** [comment]
Not sure why it did not close this one, but this issue is fixed.
