### ISSUE TITLE
`update --sibling` but `get --source` ??? 

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4946]
#### What is the problem?
The concept of sibling is key to datalad. Yet, when working with collaborators becomes a hit and miss which commands requires `--sibling` (i.e., update) and which command needs `--source`. Both refer to the same underlying concept of a remote in git, if my understanding is correct. May I suggest you unify the sibling and source concepts, perhaps by making aliases of each other if you want to keep the compatibility with previous versions. 

#### What steps will reproduce the problem?
No need.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.13.1

#### Is there anything else that would be useful to know in this context?
no

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
yes

**Comment by kyleam** [comment]
Grepping around, `install` and `get` use `--source`:

```
datalad/distribution/get.py:760:            args=("-s", "--source",),
datalad/distribution/install.py:150:            args=("-s", "--source"),
```

And `update` is the only command with `--sibling`:

```
datalad/distribution/update.py:94:            args=("-s", "--sibling",),
```

---

So, assuming a switch from `--source` to `--sibling`, `get` and `install` are the two candidates.  In the case of `install`, source is a URL or local path, so it wouldn't make sense to say `--sibling` there.

`get` documents `--source` as this:

```
  -s LABEL, --source LABEL
                        label of the data source to be used to fulfill
                        requests. This can be the name of a dataset sibling or
                        another known source. Constraints: value must be a
                        string
```

I'm not sure, but I think "another known source" is referring to git-annex special remotes.  If so, that's a bit confusing because `siblings` documentation says "enable' can be used to complete access configuration for non-Git sibling (aka git-annex special remotes)".  Anyway, I think `--sibling` could have safely been used here, or `--from=SIBLING`, which would align with both git-annex and `datalad publish/push`

However, as you mention, compatibility is a concern here.  In my view, this consistency isn't important enough to break anyone's script by deprecating `get --source`, but I'm okay with the idea of adding an alternative spelling that's advertised and recommended if others agree that `get --sibling=` or `get --from=SIBLING` would be an improvement.

**Comment by yarikoptic** [comment]
eh, a known but not resolved :-/ : https://github.com/datalad/datalad/issues/3832 .

**Comment by adswa** [comment]
I will close this issue in favor of #3832, which has a more complete set of commands to harmonize. Maybe #6215 will get there some point soon.
