### ISSUE TITLE
idea: amputate helper/procedure

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4992]
Came up in a chat with @effigies and @franklin-feingold

Given a dataset, produce a derivative dataset which

- would have only the files (directoris, subdatasets) I care about
- be fully YODA compliant (eg `sourcedata/` points to original dataset, history of modification is preserved etc)
- doesn't have shared git history with the original one, and `git-annex` branch contains only information about the keys of relevance
- has operation and resultant dataset "rerunnable" 

I think could be implemented via a helper which would have two stages of operation:

- `stage 1` 
  - create a new dataset
  - install original one as subdataset (e.g. under `sourcedata`)
- `stage 2` - interfaced as `datalad amputate --only-stage2 ...`
  - add original dataset as a remote (e.g. `original`)
  - populate current tree with tree from the `original/master` (we do that for `incoming-preprocessed` by crawler from `incoming`)
  - rm all files which you don't need
  - `git add` the rest (explicit to have stage 2 `datalad re-run`able)
  - git remote --remove original
  - do `git-annex forget` (and may be other extra steps) 

Then
- `datalad amptutate` internally does both stages (unless --only-stage2) while running `stage1; datalad.run(stage2)`

This would result in a dataset which could be `datalad rerun` to re-amputate (e.g. sourcedata/ has changed) while keeping proper RUNCMD commits etc.

For datasets which are super-datasets, it would need to just do it while traversing the hierarchy of subdatsets bottom up, not bothering instantiating datasets which are "amputated".

**Comment by mih** [comment]
While the implementation is completely different, the results shared all of the desired properties:

- [x] would have only the files (directoris, subdatasets) I care about
- [x] be fully YODA compliant (eg sourcedata/ points to original dataset, history of modification is preserved etc)
- [x] doesn't have shared git history with the original one, and git-annex branch contains only information about the keys of relevance
- [x] has operation and resultant dataset "rerunnable"

https://github.com/datalad-datasets/hcp_MNI_T1w and all other special interest views of the HCP dataset are programatically generated with `copy-file` (https://github.com/datalad-datasets/hcp_MNI_T1w/commit/52019f0be1dc86543c0cb580ea2f0e27d5310196) in a rerunnable fashion -- that @adswa uses routinely to update them.

The big difference is a more positive world-view in which we prefer not to amputate anything, but to assemble something new from different pieces.

ATM `copy-file` deals with URLs only (because we do not want to rehost anything), but it is easy to extend it to care about other sources.

**Comment by yarikoptic** [comment]
yeap, sorry forgot to mention `copy-fie` in the description. Indeed if we have also support for "full annex information" transfer more (formalized in https://github.com/datalad/datalad/issues/4995), this alternative implementation would probably be not needed -- could be achieved via `copy-file`.  closing this one.
