### ISSUE TITLE
SSHConnection: No git-annex inference by default

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5039]
By default, each `SSHConnection` is set to `use_remote_annex_bundle=True`. This means that upon command execution an additional command is executed remotely (which only works on POSIX SSH servers) that determines where git-annex is installed.

Issue 1: This implies an unconditional runtime cost whether or not git-annex commands are to be executed on the remote.

Issue 2: Once the the install dir is figured out, it is used to alter the remote PATH and make it searched first. This can be problematic (e.g. #5030).

Issue 3: This PATH setup is for POSIX servers only.

Issue 4: For non-multiplexed connections (which we will need to support for windows), two connection attempts are needed, unconditionally, to determine the install path.

**Comment by mih** [comment]
I missed the `SSHManager.get()` parameter that can pass this info down. So it can be turned off, at least. It is still messing with the path otherwise.

**Comment by bpoldrack** [comment]
I think in the remote case (more so than generally in the local case) we kind of know what are the executables we actually need. So, this should probably change altogether (independent on remote system) to not mess with PATH but only find them and execute them directly.
Also detection should be postponed until we know we actually need it, of course. However, that's a bit more difficult, since we probably still want to fail early within a datalad command execution and not start doing things only to then realize we can't finish. Declaring everything we will need when we "open" (or rather "prepare") a connection might become a bit messy, though. Any better idea?

**Comment by mih** [comment]
Done with #6533
