### ISSUE TITLE
Datalad push to github via google drive won't show file structure

### ISSUE THREAD

**Issue by nicolocin** [datalad/datalad#5055]
Not sure why but in the past when I push a dataset to github I can still see the file structure ([from this repo](https://github.com/Hoda1394/test_data_gd)):

![Screen Shot 2020-10-20 at 10 07 20 PM](https://user-images.githubusercontent.com/30167129/96597696-b4e94600-1320-11eb-8187-aa3b03c64bf4.png)

But now I only get the git-annex files ([repo](https://github.com/nicolocin/datalad-testing2)).  I can't pull data from github with this.

![Screen Shot 2020-10-20 at 10 09 58 PM](https://user-images.githubusercontent.com/30167129/96598012-0560a380-1321-11eb-8f37-88ba963701e5.png)

To recreate:
This is in a conda environment, and I exported the `https://github.com/DanielDent/git-annex-remote-rclone.git` to the bin path already.  My remote is called `gd-sig`.

```bash
mkdir user1
cd user1
touch file1.txt
touch file2.txt

datalad create --description 'testing' -f
datalad save -m 'add files'

git annex initremote gdrive-testing type=external \
   externaltype=rclone target=gd-sig \
   prefix=projects/bonsai/testing2 chunk=50MiB encryption=none

datalad create-sibling-github --publish-depends gdrive-testing datalad-testing2

# at this point output from "datalad siblings" looks normal
# .: here(+) [git]
# .: gdrive-testing(+) [rclone]
# .: github(-) [https://github.com/nicolocin/datalad-testing2.git (git)]

datalad push --to github
```

Datalad version 0.13.4, python 3.8.5, rclone 1.53.1, macOS 10.14.6

**Comment by adswa** [comment]
Hi @nicolocin, this looks like you're viewing the git-annex branch of the repository. This is due to a recent change introduced by GitHub (see also #4997), as they do not treat the ``master`` branch as the default anymore. You should be able to configure ``master`` to be the default again for all your repositories (either user or organization-wide) in your settings (https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/), but switching  to ``master`` via the small branch tab on the upper left corner prior to cloning should fix your immediate issue.

**Comment by nicolocin** [comment]
Ahhh I see.  Thanks so much!
