### ISSUE TITLE
RIA/ORA backup helper

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5059]
Use case: Ingest a non-DataLad project into a DataLad dataset for the purpose of storage in a RIA store and registering it with an `archived/` superdataset, which in turn can be searched for archived studies.

Problem: A large number of files can make this needlessly slow when going through a standard workflow.

First, here is a sketch of what I do:

1. `datalad create` a dataset on the source system for the to-be-archived project
2. Place in metadata on authorship and associated publications
3. `git annex dead here` as it will be gone shortly
4. `git annex forget --drop-dead --force`
5. `datalad create-sibling-ria -d . --trust-level trust ria+ssh://archivehost.de/ds/archive/srv`
6. `datalad push --to archivehost`
7. On the archive host, compress the annex store into a 7z archive
8. Drop/remove everything on the original host

With a large number of (small) files (6) is rather slow, likely due to the accumulation of latencies in the datalad+git-annex process ping-pong.

I was wondering, whether it would be worthwhile to combine 3-7 into a helper that performs everything locally, and in the end just rsyncs a RIA store item to the storage host.

The purpose of such a helper would be to transform a folder into a RIA store item. Given that the local dataset clone is short-lived, there is really no need to go through an expensive git-annex repository clone network setup. 

@bpoldrack What do you think?

**Comment by bpoldrack** [comment]
@mih 
Re performance: 6. not needed - we have `export-archive-ora`.

Otherwise, might be worth it. So, create that dataset and `save`. Then the following could be turned into a command/plugin:
`create-sibling-ria`, `export-archive-ria`, put the archive in that store and fix up availability by 3. + `annex fsck` and finally push w/o data.
Questions are: How sophisticated should it be? Option to use or not use an archive? Drop option? Remove local dataset afterwards?

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this.
