### ISSUE TITLE
save taking forever (or so it seems)

### ISSUE THREAD

**Issue by satra** [datalad/datalad#5115]
i'm trying to organize some dicom datasets, so i started with one (it has about a million files). 

```
datalad create -f .
git-annex add S*
datalad save -m "some message"
```

the save has now run for over 24 hours much longer than it took to run git-annex add. also can i interrupt the save process? is it atomic? and if not and i interrupt it how do i recover from it?

should i have used git/annex to commit instead of datalad save?

datalad 0.13.0rc2 
git-annex version: 8.20200522-g92e3ab8
on linux (all data mounted over nfs)

**Comment by yarikoptic** [comment]
Do you have an idea on how long it takes for pure `git-annex add`?
Depending on where it is ATM, interrupt might be of different "dirty state" left, but I think (although would not bet all my money) it should be safe since subsequent `save` or pure `annex add` should pick up where it is left, but might need `annex fsck`.

I do not remember any performance enhancements in 0.13.x series (current `maint`) since 0.13.0rc2  but `master` might have a trick or two done ;)  BTW -- there is `-J` which might speed up `annex add`.  In current master it should also save in cases of multiple subdatasets (million files does push the limits)

**Comment by satra** [comment]
the git-annex add took about 6-10 hours i think with no-parallel flag. interrupted the `datalad save` and now just doing `git commit`. then i will do datalad save in case it needs to do anything.

**Comment by mih** [comment]
There are a number of performance enhancements, specifically for large N datasets that are in master, but have not made it into the 0.13 branch. I stopped using 0.13 myself for this type of work for that reason, but I lost track which specific changes make a difference.

**Comment by satra** [comment]
git commit took less than 1 hour. i will upgrade to master before doing `datalad save`

**Comment by satra** [comment]
running datalad save took about 12 minutes. so perhaps that would be the best option moving forward. to first do git commit followed by datalad save.

**Comment by yarikoptic** [comment]
> running datalad save took about 12 minutes. so perhaps that would be the best option moving forward. to first do git commit followed by datalad save.

nah... there would always be some overhead from `datalad save` but it should not be as major, and we should be able to improve (reduce overhead) it faster (or may be eventually go into 'overdrive' mode with negative overhead ;) ) whenever we have reports like this etc ;)  So -- no shortcuts @satra! ;)

**Comment by mih** [comment]
I am closing this issue in favor of #4630, which had slightly older but more detailed information. Overall it would be nice to get feedback on the performance improvements since 0.13. It should be substantially faster now.
