### ISSUE TITLE
Desirable server-side permissions for ORA uploads

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5130]
When moving files out of a local annex the permission are retained server-side. It is unclear to me whether that is desirable. In my concrete use case, I am uploading files that shall be accessible by a webserver process. The UNIX umask server-side is set up in a way that sets the desired permissions for new files (660 in my case). However, uploading a 400 file via `scp` or `sftp`, retains the 400 permissions (even without `-p`).

An alternative approach would be to `touch` each upload server-side and then overwrite it with an upload. In this case the default permissions are inherited. This solves my problem, but I am unsure whether such behavior is desirable in the general case.

**Comment by yarikoptic** [comment]
hm, didn't know... verified that it is the case for me as well (with scp and rsync, well over ssh so likely scp).  I wonder if git-annex does some explicit chmod'ing after `copy`ing to remote, since I think I never experienced this with datasets.datalad.org , and if not -- how then they are publicly available (my umask is stringent on smaug, from which I `publish` to falkor which is the datasets.datalad.org)

**Comment by bpoldrack** [comment]
Note, that if I find a way to have ORA stream the content on upload in a similar fashion as with download, the issue should resolve itself. However, currently not sure whether that will be possible.

**Comment by bpoldrack** [comment]
In light of #6254, I think we can close this. Keeping the permissions is actually exactly what we (now) want.
