### ISSUE TITLE
Windows: should we "restrict" usage to "only within git bash"?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5149]
May be it is a non-issue, then we would just close.
But IMHO on windows we keep battling issues (e.g. `sh -c` in #5002) which largely arise from heterogeneity of possible windows setups/invocations (from "git bash" or from native windows terminal, e.g. anaconda terminal; may be installed via pip or via conda) and their differential effects on run time. My utopian idea was to just make everything self-contained within conda distribution but I think it would not provide full solution anyways due to intricacy which entering MSYS2 bash entails (filters PATH, changes HOME, etc).  So I think it might benefit if we establish (and ensure by crashing if not so) for now the one and only way `datalad` runtime is used on windows -- in "git bash", so no Windows `$HOME` is expected to be consulted etc, git bundled tools come from git distribution (not e.g. from `m2-bash` under conda).

We can identify that we are running within "git bash" by inspecting `MSYSTEM` env var to be "MINGW64", and `SSH_ASKPASS` be `/mingw64/libexec/git-core/git-gui--askpass`.  `which git` should resolve to `/mingw64/bin/git`.  If not -- kaboom and tell people to run within "git bash" terminal.

edit 1: if we see that `bash` is coming from WSL (and somehow not `/usr/bin/bash`), the battle @adswa was fighting?, we also just fail for starters.

We would need to check what is that `bash` environment used in [github actions](https://github.com/datalad/git-annex/blob/master/.github/workflows/build-windows.yaml) on windows, and if "suitable", retire appveyor setup which I believe runs "windows natively"

later we could explore crazy idea to support "native" windows execution: If `datalad` is executed within a regular Windows command line, (no `MSYSTEM`) -- we can locate `git`, and see if it has `bash` and re-spawn the process as `C:\Program Files\Git\bin\bash -c datalad "$@"` of a kind (with any necessary MSYS2 env var flags and possibly as login shell) thus ensuring that whatever `sh` or any command would be ran in a consistent "git bash" environment.

**Comment by mih** [comment]
FTR: I am working in the exact opposite direction. I think I can conclude that whenever I decided to focus on something else then plain windows, it was only a matter of time till I discovered how my choice (almost-like-unix) safe-haven wasn't working.

I am working in `cmd.exe`, I have datalad installed via conda (for now), and I do have `m2base` installed. But I am moving further and further away from it.

**Comment by yarikoptic** [comment]
> I have datalad installed via conda (for now)

what other viable alternative you have in mind?  interesting that `m2-base` is not 'interfering' for you.  IIRC I had all kinds of problems, but I was a windows newbee then ;-)

**Comment by mih** [comment]
> > I have datalad installed via conda (for now)
> 
> what other viable alternative you have in mind?

I think it *should* work without problems to take a win10 machine, install Python (e.g. from the windows store), install Git (via the git4win installed), install git-annex into the Git location (via installer), grab pip (via get-pip) and install datalad. AFAICS this is the standard windows experience, and I don't see why it should not work. Whether we recommend it or not, is a different thing from basic technical compatibility.

> interesting that `m2-base` is not 'interfering' for you. IIRC I had all kinds of problems, but I was a windows newbee then ;-)

The only two things that I am aware of re m2-base interference are:

- the secret HOME -- that is a bummer, no windows user will want to maintain two different identifies -- whenever we have to say things like "also copy your SSH keys into the location too", we are doing it wrong IMHO
- the PATH "sanitization" that happens with `sh -lc` vs `sh -c` -- but as reported elsewhere using `sh -c` anywhere is already a problem, and when we stop that entirely, the other issues goes away with it.

Overall, I feel that we are still to heavily rely on platform assumptions rather than capability testing (https://github.com/datalad/datalad/issues/2553). There is no "on windows" IMHO, it is an extremely unstructured platform. While this is annoying, I think it makes us more robust in the long run -- there are also differences in the UNIX world.

**Comment by yarikoptic** [comment]
> Overall, I feel that we are still to heavily rely on platform assumptions rather than capability testing (#2553).

totally agree (again) on that ;-)

> I think it should work without problems to take a win10 machine, install Python (e.g. from the windows store), install Git (via the git4win installer), install git-annex into the Git location (via installer), grab pip (via get-pip) and install datalad...

+ install 7zip (and forgot what else, didn't try `pip install datalad[full]` on windows in awhile might need some extra wheels... 

I am not arguing either it *should* or *should not* work -- it *should*. What I was aiming at is to narrow the battle field to breakthrough faster to the target -- a fully (or nearly fully) functional installation of datalad on windows. Sure thing, the battle front could remain wide and we could be victorious at the end, but it could take longer.  Those two aspects (HOME and PATH) are indeed two aspects which we could avoid/delay addressing if we concentrate on a single scenario (i.e. "already in MSYS2 environment).  But I am ok either way, it was just an idea, seems to be not the one to be pursued, thus closing -- let the battle go on as it is across the wide front.
