### ISSUE TITLE
explicit `gc --prune=now`?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5159]
`git` might indeed be doing `gc` when it feels it is the right time, but as my recent fiasco showed (ran out of inodes, running `gc --prune now` freed up about 20% of all available),  in scenarios with many subdatasets it might be of great benefit not to wait.

Sure thing it could be added/duplicated in corresponding "crawling/update" scripts but I wonder if we should provide at least some convenience.  E.g. could be some `datalad.runtime.gc=auto|save` with "auto" leaving it to git, and `save` to trigger it upon each save so no (rarely accessed) subdataset is left with garbage laying around.

Or may be we should just add an option (or just document?) to "proxy" adjustment of `gc.autoPackLimit` to become such that `git gc --auto` kicks in more often?  what would be a good number?  (I have not tested though if it would be as as good of an effect as `gc --prune=now`)

**Comment by kyleam** [comment]
I think we should be careful about making it easy for users to call `gc --prune=now` without understanding what it's doing.  `gc --prune=now` shouldn't lose objects from recent rewrites, because those are referenced by the reflog entries, but, as mentioned in `man git-gc`, there's risk of corruption with concurrent operations.  This [comment][1] from Joey is also relevant:

```
Yeah, --prune=now is bad news when using git-annex. At least, if
you might be doing it at the same time that git-annex is staging
objects in the index.

Using it in combination with annex.alwayscommit=false is a particularly
foot-shootish thing. I've added a warning to its documentation.
```

[1]: https://git-annex.branchable.com/bugs/Corrupted_.git__47__annex__47__index_when_running_assistant/#comment-b24c25880b923065d50bf43c8c71e8d0

> Or may be we should just add an option (or just document?) to "proxy" adjustment of `gc.autoPackLimit` to become such that `git gc --auto` kicks in more often? what would be a good number? (I have not tested though if it would be as as good of an effect as `gc --prune=now`)

It'd be interesting to know how the problematic cases you've hit into would have been improved with a plain `git gc`.  If so, then I think overriding `gc.auto` to a lower number would be a sensible thing to do, especially for operations like `addurls` that may add a bunch of objects.

<details>
<summary>Example with file from gh-5184</summary>

With explicit `git gc` call:

```sh
datalad create
datalad addurls -x '' --key='{key}' /tmp/longnow-podcast-info.json '{url}' '{file}'
echo "----------------------------------------------------"
find .git/objects | wc
git gc
find .git/objects | wc
```

```
[...]
action summary:
  addurls (ok: 236)
  save (ok: 1)
----------------------------------------------------
   1442    1442   69249
     11      11     383
```

With `gc.auto` set to lower number:

```sh
datalad create
git config gc.auto 500
git config gc.autoDetach false  # to see effect without sleeping
datalad addurls -x '' --key='{key}' /tmp/longnow-podcast-info.json '{url}' '{file}'
echo "----------------------------------------------------"
find .git/objects | wc
```

```
[...]
action summary:
  addurls (ok: 236)
  save (ok: 1)
----------------------------------------------------
     11      11     383
```

</details>

**Comment by yarikoptic** [comment]
yeah, probably just a plain `gc` would have been good enough.  As your example demonstrates -- it is already of great help even without `--prune=now`.  I will try to avoid using `--prune=now` and also test on some case if it gives any "extra benefit".

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
