### ISSUE TITLE
Issue with pulling datalad singularity image

### ISSUE THREAD

**Issue by jbwexler** [datalad/datalad#5165]
(base) jbwexler@nid00011>singularity pull shub://datalad/datalad
FATAL:   While pulling shub image: failed to get manifest for: shub://datalad/datalad: the requested manifest was not found in singularity hub

**Comment by yarikoptic** [comment]
Gy, I guess I (or someone else)  "refactored away" plain Singularity so we were left only with tags, so `shub://datalad/datalad:fullmaster` would still work.
I have pushed a commit fd226aaef19d0cee3089baa6d7519f35c8220e88 (to maint with a follow up merge to master) which would close this issue but also trigger a rebuild with pure `pip install datalad[full]` of latest version, so if succeeds, it would make above work

But 
- we cannot stress singularity hub to build it for every commit and thus not automated and thus they are all outdated now :-/  Thus I would advise to just:
- follow http://handbook.datalad.org/en/latest/intro/installation.html?highlight=hpc#linux-machines-with-no-root-access-e-g-hpc-systems and install using miniconda if you do not have `conda` already available (since then it is just `conda install -c conda-forge datalad`).
