### ISSUE TITLE
`datalad clone "ria+file:/some/store/#~myds"` leads to undesired establishment of an "annex"

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5186]
After such a clone, the config of the dataset in the store gets an `[annex]` section that it should not have:

```
% cat config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = true
[datalad "ora-remote"]
        uuid = 08ba549c-2991-4b7f-94c2-0fbfed0914d3
[annex]
        uuid = 37f33fa8-4eff-4c90-bc83-597b3aa16224
        version = 8
```

I suspect this is `git-annex` automatically doing this, because the clone is on the same filesystem and the user had write permissions. As a consequence, the `config` file also has a different owner now (the cloner).

This is a problem. `git-annex` should not become aware of that remote as having an annex directly, because its availability is recorded in the corresponding ORA special remote. In such a configuration, git-annex will now push to the remote directly, and not via ORA. This leads to confusion at minimum, and to data loss in the worst case.

The full list of modifications is here:

```
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/sentinal
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/index
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/journal
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/journal/uuid.log
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/othertmp
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/sentinal.cache
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/journal.lck
./14a/5e5b6-d30d-11ea-8836-b4969157768c/annex/othertmp.lck
./14a/5e5b6-d30d-11ea-8836-b4969157768c/config
```

**Comment by bpoldrack** [comment]
Confirmed. It's annex itself.

```
ben@tree in /tmp
❱ datalad create some
[INFO   ] Creating a new annex repo at /tmp/some 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/some (dataset)
ben@tree in /tmp
❱ cd some
ben@tree in /tmp/some on git:master
❱ echo bla > file1
ben@tree in /tmp/some on git:master
❱ datalad save
add(ok): /tmp/some/file1 (file)
save(ok): /tmp/some (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
ben@tree in /tmp/some on git:master
❱ cd ..
```

Now, a bare clone w/o local annex:

```
ben@tree in /tmp
❱ git clone --bare some bare
Cloning into bare repository 'bare'...
done.
ben@tree in /tmp
❱ ll bare
total 80
drwxr-xr-x   7 ben  ben   4096 Nov 27 16:48 .
drwxrwxrwt 106 root root 36864 Nov 27 16:48 ..
drwxr-xr-x   2 ben  ben   4096 Nov 27 16:48 branches
-rw-r--r--   1 ben  ben    101 Nov 27 16:48 config
-rw-r--r--   1 ben  ben     73 Nov 27 16:48 description
-rw-r--r--   1 ben  ben     23 Nov 27 16:48 HEAD
drwxr-xr-x   2 ben  ben   4096 Nov 27 16:48 hooks
drwxr-xr-x   2 ben  ben   4096 Nov 27 16:48 info
drwxr-xr-x  24 ben  ben   4096 Nov 27 16:48 objects
-rw-r--r--   1 ben  ben    167 Nov 27 16:48 packed-refs
drwxr-xr-x   4 ben  ben   4096 Nov 27 16:48 refs
```

And finally clone from bare and git-annex-init:

```
ben@tree in /tmp
❱ git clone bare dest
Cloning into 'dest'...
done.
ben@tree in /tmp
❱ git -C dest annex init
init  (merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)
ok
(recording state in git...)
ben@tree in /tmp
❱ ll bare
total 84
drwxr-xr-x   8 ben  ben   4096 Nov 27 16:49 .
drwxrwxrwt 107 root root 36864 Nov 27 16:49 ..
drwxr-xr-x   3 ben  ben   4096 Nov 27 16:49 annex
drwxr-xr-x   2 ben  ben   4096 Nov 27 16:48 branches
-rw-r--r--   1 ben  ben    218 Nov 27 16:49 config
-rw-r--r--   1 ben  ben     73 Nov 27 16:48 description
-rw-r--r--   1 ben  ben     23 Nov 27 16:48 HEAD
drwxr-xr-x   2 ben  ben   4096 Nov 27 16:48 hooks
drwxr-xr-x   2 ben  ben   4096 Nov 27 16:48 info
drwxr-xr-x  27 ben  ben   4096 Nov 27 16:49 objects
-rw-r--r--   1 ben  ben    167 Nov 27 16:48 packed-refs
drwxr-xr-x   4 ben  ben   4096 Nov 27 16:48 refs
```

**Comment by bpoldrack** [comment]
I'll play a bit with `sameas` config to figure out, whether that would help us (in fixing up existing ones as well)

**Comment by bpoldrack** [comment]
So, `sameas` isn't technically correct since the special remote as access to archives and `origin` hasn't. And we can't really prevent users from running `fsck` on `origin` and mess it up.
The only thing I found so far is to set `origin` to `annex-ignore = true` right after cloning (before `annex-init`). This seems to work, but provides no solution for fixing up existing stores (and their clones). In addition the question is, whether or not "we" (that is `datalad clone`) can correctly detect the situation and set that config. Issue here is, that we can detect we are cloning from a RIA store, but the store's design actually allows for the repos to have local annexes (possibly instead of an ORA special remote). It's just not what we want to have normally. So, I wonder whether it should be up to the repos in the store to tell us (a flag within their `ria-layout-version` file seems to be the obvious spot).

Alternatively we could assume that their is no way to avoid it entirely and just do a local `git-annex-init` within store ourselves (`create-sibling-ria`), but instantly declare it dead. For same reason as above should be an option, of course.

For now, I don't see a better solution (or a faster and more convenient way to fix existing ones other than the obvious `dead` and `fsck` on clones). What do you think, @mih?

**Comment by mih** [comment]
I agree, `sameas` is not a good fit.

I think we should focus on avoiding the problem in the future, and the `annex-ignore = true` seems the most appropriate and conceptually cleanest approach.

While it is theoretically possible that people use RIA without ORA, I do not want to support such use cases -- I was even among the people that did not want to support the conceptual distinction that enables this though ;-)

**Comment by kyleam** [comment]
I also don't see any better option than setting `annex-ignore`.

It looks like a longstanding behavior, but I think this is worth filing on the git-annex tracker (I'll do so later today), particularly because 1) there is a discrepancy  between the treatment of bare and non-bare remotes and 2) it's getting triggered by the autoenable logic.

<details>
<summary>demo</summary>

```sh
set -eu

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

echo "$(git annex version --raw)"  # echo for newline
git init a
git -C a commit --allow-empty -mc0
git -C a annex init a

git clone --bare a b.git
git -C b.git remote rm origin

git clone b.git c
git -C c annex init

set -x
git -C b.git config annex.uuid
```

</details>

<details>
<summary>output, master</summary>

```
8.20201128-ga9ade9e6f
Initialized empty Git repository in /tmp/dl-e1MSojB/a/.git/
[master (root-commit) 1f8d322] c0
init a (scanning for unlocked files...)
warning: Not setting branch master as its own upstream.
ok
(recording state in git...)
Cloning into bare repository 'b.git'...
done.
Cloning into 'c'...
done.
init  (merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)
warning: Not setting branch master as its own upstream.
ok
(recording state in git...)
+ git -C b.git config annex.uuid
4f0da806-afc2-466c-b554-52d136d27754
```

</details>

<details>
<summary>output, patch</summary>

```diff
diff --git a/Command/Init.hs b/Command/Init.hs
index 179a21e04..a9d6448d7 100644
--- a/Command/Init.hs
+++ b/Command/Init.hs
@@ -73,7 +73,7 @@ perform os = do
 	initialize
 		(if null (initDesc os) then Nothing else Just (initDesc os))
 		(initVersion os)
-	Annex.SpecialRemote.autoEnable
+	-- Annex.SpecialRemote.autoEnable
 	next $ return True
 
 performAutoEnableOnly :: CommandPerform
```

```
8.20201128-ga9ade9e6f
Initialized empty Git repository in /tmp/dl-dNct0Km/a/.git/
[master (root-commit) 4799fc2] c0
init a (scanning for unlocked files...)
warning: Not setting branch master as its own upstream.
ok
(recording state in git...)
Cloning into bare repository 'b.git'...
done.
Cloning into 'c'...
done.
init  (merging origin/git-annex into git-annex...)
(scanning for unlocked files...)
warning: Not setting branch master as its own upstream.
ok
(recording state in git...)
+ git -C b.git config annex.uuid
```

</details>

**Comment by kyleam** [comment]
> 1) there is a discrepancy between the treatment of bare and non-bare remotes

Doh, never mind.  That's just a consequence of the demo script removing the remote after the clone.  In the case of a non-bare repo, removing the remote removes the git-annex branch, but for a bare repo it's of course still there under `refs/heads/`.

**Comment by kyleam** [comment]
> I think this is worth filing on the git-annex tracker (I'll do so later today)

Sorry, I take that back.  I can't convince myself that it's not the expected behavior for a remote that has a git-annex branch ([related comment]( https://git-annex.branchable.com/forum/how_to_force_read-only_in_enableremote__63__/#comment-acde3a14f88953f1f5dc207d52e85679)).
