### ISSUE TITLE
Clarify name of `datalad.install`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5234]
The purpose of this helper seems to be mostly (but not exclusively) to install git-annex. Should it be named `install-git-annex`?

Right now things may make an invalid impression.

`python -m datalad.install neurodebian`

neither installs datalad via NeuroDebian, nor does it install NeuroDebian, but installs git-annex via NeuroDebian (which must be configured already).

**Comment by yarikoptic** [comment]
It is because it is based on the script we had for installing git-annex. But ultimately it will be used to install either git-annex or datalad or both ... see/chime in to https://github.com/datalad/datalad/issues/5181 -- it is the right time 'now' before I spec-ed out gory details to @jwodder  per [his request](https://github.com/datalad/datalad/issues/5181#issuecomment-742651567).

As such I would consider this issue closed -- feel free to reopen if above doesn't address it
