### ISSUE TITLE
Support read URL separate from write URLs in ria special remotes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5273]
Inspired by a support request in the DataLad chat room, where one and the same dataset needs to be readily configured to copy to a storage sibling via one URL, and copy from via another one.

**Comment by yarikoptic** [comment]
Like we have for ssh + http tandem ? Isn't it just a matter of having two remotes (with the same uuid)?

**Comment by aqw** [comment]
I had the exact need for this with the workflow for a debian repository. @bpoldrack has the details, and `--sameas` was used.

**Comment by bpoldrack** [comment]
I'm looking into this (adding an optional `push-url` to the existing `url`. However, this surgery is a bit bigger, since we establish a persistent "execution layer" during PREPARE rather than using an URL as parameter for single operations. So, need to think about how to refactor and take into account other open issues.

**Comment by bpoldrack** [comment]
Working on it (in conjunction with #5396 ) this raises a question regarding a possible attempt by `clone` to reconfigure the ORA remote. Do we consider both `url` and `push-url` for reconfiguration or only `url`? I'd argue only `url` makes sense, since it's perfectly possible to have a `push-url` that isn't "working" in a clone and still be the correct one (that restriction may well be the reason to have a separate `push-url` in the first place). Adjusting to the URL we cloned from probably only makes sense for the fetch url. However, there may be some corner cases where reconfiguring the `url` but not the `push-url` would at least be a surprising behavior. Mainly the question is how to communicate the issue and what users may or may not have to do in addition?
Just check whether there is a `push-url` whenever we decide to reconfigure an ORA remote and spit out a message reading that we don't deal with it and what's the command to use if reconfiguration is required? I imagine that to be somewhat noisy for some usecases where users would neither know what to make of this nor ever actually need it. Quietly ignoring it on the other hand doesn't seem quite right either. What do you think, @mih?

**Comment by mih** [comment]
Quick response without much thinking: A primary motivation for doing any reconfiguration was that an initial access configuration necessary in workflows that we observed required *push* access, but subsequent (and more frequent) access was of *pull* type for most clones. Once we have a dedicated `push-url`, I would challenge the need for dynamic (often heuristic-base, hence sometimes wrong) automatic reconfiguration.

**Comment by bpoldrack** [comment]
Good point, @mih, but push access isn't the only reason, I think. You could have a store on the same file system accessed via a `ria+file://` URL, while the same store is served via HTTP to a broader audience. Now, there are of course many ways to approach this and not need a reconfiguration, but the idea still was to have that one special remote, that could record the `file://` URL but would be reconfigured to HTTP when cloned on a system where local access wouldn't work. This is not only about push. Fetching will likely also be faster when using local FS access rather than unnecessarily go via HTTP.

I agree that (with a separate `push-url`) it probably makes sense to rethink those usecases and possibly make use of non-autoenabled same-as remotes, etc. but removing the reconfiguration on clone would still break existing approaches. And keeping it while ignoring `push-url` altogether is an UX issue, I think.
We could allow for reconfiguration only if there's no push-url basically saying "if you are that specific, you prob. don't want us to screw it up". But that too requires some communication. Otherwise the behavior of `clone` would seem rather unpredictable.
