### ISSUE TITLE
FAIL: datalad.support.tests.test_parallel.test_gracefull_death

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5296]
```
Traceback (most recent call last):
1267  File "C:\Python38-x64\lib\site-packages\nose\case.py", line 198, in runTest
1268    self.test(*self.arg)
1269  File "C:\Python38-x64\lib\site-packages\datalad\tests\utils.py", line 263, in _wrap_skip_if
1270    return func(*args, **kwargs)
1271  File "C:\Python38-x64\lib\site-packages\datalad\support\tests\test_parallel.py", line 195, in test_gracefull_death
1272    assert_greater_equal(6, len(results))
1273AssertionError: 6 not greater than or equal to 9
```

https://ci.appveyor.com/project/mih/appveyor-datalad/build/job/vo8qjdi5n4pwqwdm

**Comment by mih** [comment]
The offending test code is

```py
    # we will get some results, seems around 4 and they should be "sequential"
    assert_equal(results, list(range(len(results))))
    assert_greater_equal(len(results), 2)
    if info_log_level:
        assert_greater_equal(6, len(results))
```

This sounds as if the threshold is somewhat arbitrary, and getting 9 is no necessarily wrong, just "unusual".

@yarikoptic please advise how I shall proceed.

**Comment by yarikoptic** [comment]
well, I guess it is ok although somewhat almost diminishes the test altogether since max is 10 as far as see it.  surprising that it was not failing before (or was it not ran on windows?) but that log conditioning added in 796d56387499089eaed67748c20b5ffad0afa900 indeed suggests that slow/erratic instances could experience greater than 6 values to appear.
Since we have not seen failures otherwise, why not to make it 9 only on so special appveyor for now?

**Comment by mih** [comment]
So it needs machine specific tuning? In that case, I would rather turn it off on this special appveyor. I do not think there is a CI service that we use that has a guaranteed performance.

**Comment by mih** [comment]
I can confirm that `9` is not an uncommon result for a win10 box, even outside the cloud sphere.

**Comment by mih** [comment]
FTR: in a macosx cloud instance the result is ~7.
