### ISSUE TITLE
Stop using .gitattributes for annex.largefiles config

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5383]
A `create` leaves the following config in the default branch:

```
% cat .gitattributes 
* annex.backend=MD5E
**/.git* annex.largefiles=nothing%                                                         

% cat .datalad/.gitattributes 
config annex.largefiles=nothing
metadata/aggregate* annex.largefiles=nothing
metadata/objects/** annex.largefiles=(anything)%                                           
```

The fact that this config is branch-specific is generally a disadvantage for datalad.

I propose to stop using `.gitattributes` for this and switch to `git annex config`. This will yield a subjectively cleaner dataset on create, translates to all branches, and causes less pain when additional configuration is done by users (or dataset procedures) that need to take a datalad-created starting point into account.

Unfortunately, there is no way to replace `annex.backend` settings in this way.

**Comment by yarikoptic** [comment]
> The fact that this config is branch-specific is generally a disadvantage for datalad.

#5390 is going forward to achieve this, but I kept thinking if that is what we want really, and either it is possible of an advantage.  I do see benefit for some use cases (and possible tiny OPT for `create`) to have such configuration to be just global and not require re-merging `master` branch where the `.gitattributes` setting was adjusted.  Also, I had to do that a good number of times while preparing openfmri and other datasets for datasets.datalad.org, so it is not a new "procedure" for me.

BUT, unlike files availability and special remotes configuration, I think that keeping such configuration within git-annex's branch config could lead to surprises without clear idea on why and when a dataset started to behave differently all of a sudden after you do `datalad update` and thus merge changes into git-annex branch for this setting (possibly from some semi-trustful remote where malicious user set largefiles to nothing, and you kept your passwords in the annexed file)... Since git-annex branch has no relationship to any other branch (besides temporal sorting by the date), it would make it hard and eventually impossible (after `annex forget`) to figure out the "provenance" of points in time where datalad starts to behave differently.

So, in general, I would actually prefer to keep largefiles configuration visible in .gitattributes and for it to be less "viral" as it would happen within `git annex config`. In a typical dataset, even if it gets branches, datalad operations would remain more consistent.  But I do see for some use cases an advantage of having it "global". So it might be up to the user to decide which way he/she would like such configuration to be handled.  

NB `.gitattributes` overrides `git-annex config` setting, so my desire of keeping it *as is* could be achieved with some additional command/change, but I do not see why it should not stay default.

In exposing this possibility of having this setting either in `.gitattributes` OR `git annex config` we are getting back to `git-annex` scope (#5363 and yes - only for this particular setting ATM) and #5120 or an explicit option (or at least configuration variable) to be able to specify to which scope apply that configuration (i.e. `-c text2git`), or just coming up with e.g. `-c text2git_viral` or alike.

**Comment by yarikoptic** [comment]
and setting of `largefiles` is also tightly coupled with us setting also a backend for git-annex. Unlikely you want to start annexing using default backend (SHA256E) if your master branch uses MD5E -- may side effects.  So it is more high level conceptual question of where do we store annex-behavior tuning settings like that - in master branch (as we had done since nearly inception of datalad) or git-annex (but `git annex help config | grep backend` is empty ATM)?

With aforementioned "backend" aspect it feels that a better (re)solution ATM is for the functionality which relies on having multiple branches, to establish `.gitattributes` in those branches, likely using the copy from the base (`master`) branch at the point of their initiation.  That would also allow for informed decision making on how behavior should change happen any branch introduces changes and merge of such branches results in conflicts.

**Comment by yarikoptic** [comment]
@mih do you still feel this needs implementation?

**Comment by mih** [comment]
I recorded a pointer. It can be closed here. Thanks for the ping.
