### ISSUE TITLE
postclonecfg_ria() sets publication dependency to surprising remote

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5396]
I have two dataset stores (A and B). They both contain the same dataset (with different commits, A has less than B). The dataset has an ORA special remote configured that points to the dataset store B.

Now, when I `datalad clone` from store A via a `ria+file://` URL, I get a publication dependency on the ORA special remote for `origin`. And that happens despite the fact that this remote points to an entirely different store (which is store B, also configured via a `ria+file://` URL in the special remote).

I noticed this behavior, because I did `datalad push --to origin` after a local modification in the clone, which led to annex keys being transferred -- but NOT to store A (aka origin), but to store B -- which is rather confusing behavior.

Ping @bpoldrack

**Comment by bpoldrack** [comment]
1. Clarification: This should happen only if you have a single ORA remote but two stores. If `postclonecfg_ria()` finds several ORA remotes, it shouldn't configure any publication dependency.
2. Agree that this is confusing and surprising behavior. It is, however, hard to avoid while keeping the idea of reconfiguration around. This is because the point of reconfiguration on clone is, that a usable URL for the special remote might be different from what is stored in `git-annex:remote.log` but can be derived from the RIA-URL we cloned from. Plus: We have no identification of a physical store. Hence we have nothing really to tell the difference. Should the discovered functional ORA remote be configured to be a publication dependency or not? What would be the criterion? It's functional and points to a RIA store containing this dataset. URL can't be it, since we have the reconfiguration idea based on the fact that the URL isn't that solid a thing. We could add a check that the "correct" store also needs to have the commit(s) we just cloned, but this still isn't an actual solution - just hiding the issue in a few more cases.
3. With an URL based approach we could, however, rather err on the side of not configuring a publication dependency: If URL of a functional ORA remote is different from clone URL then don't configure it. Would imply that an actually correct pair of git+ORA remotes don't get the config in case of something like: clone from `http://ds.home.de` but ORA: `ssh://home.de/srv/ds`.


Conclusion: Seems to me an actual solution requires UUIDs for stores.

What do you think, @datalad/developers?

**Comment by mih** [comment]
To me this has little to do with the configuration of the ora remote (no change in my case), but we unconditionally setting any ORA special remote as a publication dependency, whenever there was a clone from any RIA store.

To me it only makes sense to configure a dependency when the URL of the stores match.

**Comment by bpoldrack** [comment]
> To me this has little to do with the configuration of the ora remote (no change in my case),

It does insofar as the approach (partially) relies on the same underlying assumptions and questions (What exactly can we identify?)

> To me it only makes sense to configure a dependency when the URL of the stores match.

So, that's 3. "err on the side of not configuring a publication dependency". I'm generally fine with that.

However, looked at the code once more. We actually do have a way of identification. With reconfiguration we do identify the special remote rather than the store. And that's sufficient. We could do the same thing for publication-dependency. We have a look into the store and check `datalad.ora-remote.uuid`. If we have an enabled ORA remote with that UUID, we set the config, otherwise we don't. A little more expensive, but might not matter much within `clone`. And it's more convenient in cases like the mentioned `http://ds.home.de` vs `ssh://home.de/srv/ds`.

**Comment by bpoldrack** [comment]
This can (and probably should) of course be enhanced to: first check matching URL and only check the UUID match if when the former failed, in order to be cheaper in the easy cases.
