### ISSUE TITLE
datalad-deprecated extension

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5403]
In the light of #5376 and #5379 I think that it would benefit the "core" to get rid of functionality which we do not (that) actively use/maintain but which adds burden.  Instead of breeding dedicated extensions for such, which increases the maintenance and distribution burden, I think we might better just initiate an extension to which such functionality would be moved, and we would alert the user (upon using it within datalad core "old interfaces") that not only they need to install that extension to regain it, but also to let us know that the functionality is used so we consider either moving it back (if really heavily used ;)) or just minting a dedicated extension for it.  

Could also be `datalad-deprecated` or `datalad-extras` or smth along the lines.

WDYT?

**Comment by bpoldrack** [comment]
I like the notion of `datalad-extras` better than a `datalad-graveyard` with zombies that may or may not return to core.

**Comment by mih** [comment]
General +1 for a retirement home from me.

From my POV it would be nice to distinguish the notions of up'n'coming features from outgoing/deprecated/obsolete features. I am already using the term "extra" for the former meaning, so I am biased (https://github.com/mih/datalad-mihextras). Here are a few extension names and associated opinions:

- graveyard: not quite fitting, the features are not dead, hence the extension
- undead: "beings are deceased but behave as if they were alive" <- I like that, because it is funny
- deprecated: this is what it is at the core, and the driest way to put it -- good choice
- unmaintained: also possible, if it would be accurate
- fossils: matches the most likely reasons for us being motivated enough to move things there

and a bunch of these ones "assistedliving", "hospice", "nursing"...

**Comment by yarikoptic** [comment]
The same here, I would see `extras` as optional additional features. `deprecated` is indeed best fitting.  As I have mentioned we can announce that they could gain their 2nd life (back in the core (unlikely) or as an extension) if enough of user interest is shown.

**Comment by mih** [comment]
I instantiated the extension template at https://github.com/datalad/datalad-deprecated

**Comment by mih** [comment]
Now acting on #5379

**Comment by mih** [comment]
This can be closed. We have -deprecated in production for a while now.
