### ISSUE TITLE
Number of commits for subdataset addition doubled

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5412]
https://github.com/datalad/datalad/pull/5346 by @bpoldrack  added an additional commit to record another URL for a subdataset. However, there is no need to keep that in a dedicated commit, and it adds a lot of commits in datasets with a lot of subdatasets.

All URLs should be consolidated in a single commit.

**Comment by bpoldrack** [comment]
Looked into this and it turns out a bit more complicated than it sounds.
#5346 added a `subdatasets` call in `clone` to set the `datalad-url` for the cloned subdataset. This call is invoked right after `clone`'s call to `save`, thus creating an additional commit after `save`.
I thought to just move that `subdatasets` call up and add a `--nosave` option to `subdatasets` in order to resolve this issue. However, it's not that easy. If such a `clone` call doesn't come from a `get` but actually creates the subdataset,  `subdatasets` has another issue: `datalad subdatasets not-yet-existing-submodule --set-property some value` does nothing. Zero-exit with no results whatsoever. Now, if you look at `subdatasets` as a standalone command, this should probably yield an error. Using it the way I intended to, we would need it to just create an entry in `.gitmodules` for a submodule, that doesn't exist yet, suggesting some kind of `--force` option for `subdatasets`. I'm not sure though what exactly this `force` should do under what circumstances if we look at the `subdatasets` command as a whole. Opinions, @datalad/developers?
An alternative could be to call `git-config` directly from within `clone` instead of `subdatasets` in order to set `datalad-url`. But this seems more troublesome as it requires to duplicate internal logic from `subdatasets`. Especially properly parsing `.gitmodules` if it already exists and figuring the correct submodule entry if `clone` was called by `get` (submodule name vs path).

Any suggestion for a different approach?

**Comment by mih** [comment]
For a minimal change, I would move the `subdatasets` call to immediately before the `save` call, `git reset HEAD`1 the result, if there was a change in response to the call, add `.gitmodules` to the `path` that is given to `save`.

For a more involved change: RF `subdatasets` to provide an internal helper that performs the modifications, but not the `save`.

I think the minimal change would be sufficient to achieve the immediate goal without causing much cost.

**Comment by bpoldrack** [comment]
> For a minimal change, I would move the subdatasets call to immediately before the save call, git reset HEAD1 the result, if there was a change in response to the call, add .gitmodules to the path that is given to save.

Would still require some `force` option for `subdatasets` since it would need to create `.gitmodule` (or an entry for the submodule respectively) whenever that `clone` call is creating the submodule instead of merely getting it.

**Comment by bpoldrack** [comment]
To be clear: Not saving isn't much of an hassle. `--no-save` for `subdatasets` seems easy - no real RF required. The not so obvious thing is when and how to fail/not-fail on call like `subdatasets <is-not-(yet)-subdataset> --set-property ...`, @mih .

**Comment by mih** [comment]
Ah, true!

I very much dislike introducing `--nosave` options anywhere. A better paradigm would be to *amend* a commit. Having `subdatasets` work on not-subdatasets, also seems like an undesirable approach. The amend does not require this stretch of semantics. Which brings flashbacks: https://github.com/datalad/datalad/issues/3244

**Comment by bpoldrack** [comment]
Yes, the trouble I see with amending in this case is performance. I think it would be faster if we could stage the modification of `.gitmodule`. `--no-save`, however, could be introduced to `subdatasets` internal worker function only if we don't want it in `subdatasets`'s interface.

However, I agree - having `--amend` for `save` seems cleaner.

**Comment by yarikoptic** [comment]
FWIW my 1c (although without any ideas on how to address initial IMHO minor issue): Any `--amend`'ing should be done with extreme caution to not alter unrelated to the operation history -- safe guards would need to be added.  Also I bet it is quite more performance heavier than "nosave" approach in particular on heavyish indexes. Overall I just would not call "amend" approach "cleaner" than "nosave" one (`save --amend` thought could be handy indeed, but to be invoked by a user and not for "internal" operations IMHO).

**Comment by mih** [comment]
Just FTR: `save` used commit-amend already and for a while in normal operation, so this is not a new paradigm. I think the concern of "heavy index" problems came up repeatedly (and also in the context of the change that introduced the original use of `--amend` for merged split commands), but never was found to have a real-life impact.

The present functionality used `commit --amend` to alter a commit that the same command just made. This issue is a scenario of the same nature. So if safe-guards are needed (not sure what you have in mind), the same safeguard would be needed in the existing implementation -- worth a dedicated issue.

**Comment by bpoldrack** [comment]
Not quite sure yet, but there might be a needed safeguard in this usecase indeed. If we are getting a subdataset rather than creating it by that `clone` call, the `save` call shouldn't do anything, right? So, `--amend` the `subdataset` call only, if we got a save result indicating that something was indeed committed.

**Comment by mih** [comment]
@bpoldrack we have `--amend` now, this should be doable now, right?

**Comment by bpoldrack** [comment]
Looking into it it turns out, that a RF'ing of `subdatasets` in a meaningful way that exposes internal parts via public helpers is not thatstraightforward w/o making things less efficient. For the purpose of this issue went for a simple git-config call when amending instead in PR #5480. `subdatasets` needs some more attention in a separate effort, I think, in order to come up with reasonable public functions.
