### ISSUE TITLE
Working with different branches

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#5414]
#### What is the problem?
We are finalizing a BIDS dataset tracked with datalad. We just realized that our approach to remove images that failed QC is not a good strategy. So, we are not integrating the bad data anyway and marking them with BAD\* prefix. Someone on neurostars gave us the interesting idea of [keeping different datalad branches](https://neurostars.org/t/adding-failed-qc-scans-to-bids-dataset/18103/8) for data with or without bad data. This can be a good solution, but we have not used branches before in datalad. There does not seem to be a lot in docs and the book either. My original idea was simply to tag the current version of good data and then add/commit the new bad data. This way I can go back in time to having just the good data. But this approach is probably not very smart; it would prevent us to make any changes to the good commit without compromising the commit history, ot it will need branching later anyway. I wanted to get your opinion on what is the best way to proceed. How should I work with the collaborators, move between branches, etc? Do we need to use git to move and create branches?

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.13.1 until yesterday, and 0.14.0 from now on

#### Is there anything else that would be useful to know in this context?
NA

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
:)

**Comment by yarikoptic** [comment]
>  This can be a good solution, but we have not used branches before in datalad.

FWIW, branches are GREAT, and seems to be what you need, and if anything you could always establish a branch later from an earlier point, but ...

> There does not seem to be a lot in docs and the book either.

to a limited degree because if you have subdatasets (git submodules) -- you might hit difficulties: DataLad makes it easier to work with hierarchies of datasets, but if subdatasets committed in different states, `git checkout somebranch` would not be sufficient to switch the entire tree to the corresponding "other state".  And that use case, although trivial for trivial use cases is actually not trivial generally (see e.g. elderly #1424 for some thoughts ATM).

BUT if you do not have any submodules/subdatasets which are likely to be different (or to appear/disappear)  across branches - you can easily use branches!  We actually use them actively in some scenarios e.g. in datalad crawler where `incoming` branch represents files as downloaded, `incoming-processed` - processed somehow (e.g. extracted archives), and `master` -- the ultimate version we provide.  I think every dataset from old http://datasets.datalad.org/?dir=/openneuro is like that.

So - overall -- if no subdatasets, NOTHING stops you to use branches, you will just need to use `git checkout` commands directly to switch between them.

**Comment by dorianps** [comment]
Thanks @yarikoptic 

You confirmed what I suspected, that's why I was hesitant to jump to branches. We use subdatasets a lot. In fact, the entire collection of studies is a superdataset. But fortunately this particular subdataset that contains the BIDS raw data for this study is a single end-leaf subdataset. There are no subdatasets under it. 

What I don't understand is what would happen if I go in this subdataset, switch to the branch "baddata" and forget switching back to "master", then  go back and save the parent dataset. Would the parent dataset think that its child/submodule/subdataset is completely new (because the commit history may not match) or will it just think it is just the same old subdataset with a new latest commit and just register the new commit?

I guess I should google the relationship between branches and submodules to understand these scenarios, but you may know much better how they interact with the datalad world.

**Comment by yarikoptic** [comment]
> What I don't understand is what would happen if I go in this subdataset, switch to the branch "baddata" and forget switching back to "master", then go back and save the parent dataset. Would the parent dataset think that its child/submodule/subdataset is completely new (because the commit history may not match) or will it just think it is just the same old subdataset with a new latest commit and just register the new commit?

its super dataset cares primarily about the commit .  If that commit is available from the url recorded in superdatasets .gitmodules, it would be able to fetch and check it out and would be (somewhat) happy.  Somewhat because it might not know what branch it should be and you might end up in a detached HEAD if you install a clone of it.  You could use `submodule.<name>.branch` there to prescribe, but I am not sure if we anyhow treat that -- it might just work (or not).

**Comment by dorianps** [comment]
Thanks @yarikoptic 

I am willing to give it a try. But to start with, our collaborator will create the branch in a clone. He will work on the branch and when done I will pull the changes in a master location where we keep datasets. How do I pull the changes of a newly created remote branch using datalad update? Is it possible at all?

I was thinking to not venture with git fetch/pull commands unless datalad has a way to work in my scenario.

**Comment by yarikoptic** [comment]
Datalad has spoiled you ;-) I think you will still need to do git merge after either git fetch it datalad update

**Comment by dorianps** [comment]
Spoiled indeed, but expecting more spoiling in the future. Thanks @yarikoptic .
