### ISSUE TITLE
Authentication failures are not propageted to the user when authenticing via keyring

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5469]
This is something @tacticfox stumbled upon with the human connectome open access dataset:
He had stored mistyped AWS credentials in his keyring. Upon a ``datalad get`` of a file, he was asked to authenticate to his keyring (successful), but the subsequent failing authentication with AWS credentials is nowhere visible. Instead, we get a "try making these remotes available" error.
Could you paste the terminal output in here, @tacticfox? Thanks in advance!

**Comment by tacticfox** [comment]
This is the error message 

` datalad -l debug get 100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz                          1 !
[DEBUG  ] Command line args 1st pass for DataLad 0.14.0. Parsed: Namespace() Unparsed: ['get', '100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz']
[DEBUG  ] Discovering plugins
[DEBUG  ] Building doc for <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Building doc for <class 'datalad.core.distributed.clone.Clone'>
[DEBUG  ] Building doc for <class 'datalad.distribution.get.Get'>
[DEBUG  ] Parsing known args among ['/usr/bin/datalad', '-l', 'debug', 'get', '100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz']
[DEBUG  ] Async run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
[DEBUG  ] Launching process ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
[DEBUG  ] Process 2720921 started
[DEBUG  ] Waiting for process 2720921 to complete
[DEBUG  ] Process 2720921 exited with return code 0
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.get.Get'>
[DEBUG  ] Resolved dataset for get content: /home/lruecker/hcp
[DEBUG  ] Async run ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG  ] Launching process ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG  ] Process 2720922 started
[DEBUG  ] Waiting for process 2720922 to complete
[DEBUG  ] Process 2720922 exited with return code 0
[DEBUG  ] Async run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/home/lruecker/hcp/.datalad/config']
[DEBUG  ] Launching process ['git', 'config', '-z', '-l', '--show-origin', '--file', '/home/lruecker/hcp/.datalad/config']
[DEBUG  ] Process 2720923 started
[DEBUG  ] Waiting for process 2720923 to complete
[DEBUG  ] Process 2720923 exited with return code 0
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Resolved dataset for subdataset reporting/modification: /home/lruecker/hcp
[DEBUG  ] Query subdatasets of None
[DEBUG  ] Async run ['git', 'config', '-z', '-l', '--file', '.gitmodules']
[DEBUG  ] Launching process ['git', 'config', '-z', '-l', '--file', '.gitmodules']
[DEBUG  ] Process 2720924 started
[DEBUG  ] Waiting for process 2720924 to complete
[DEBUG  ] Process 2720924 exited with return code 0
[DEBUG  ] AnnexRepo(/home/lruecker/hcp).get_content_info(...)
[DEBUG  ] Query repo: ['ls-files', '--stage', '-z']
[DEBUG  ] Async run ['git', 'ls-files', '--stage', '-z']
[DEBUG  ] Launching process ['git', 'ls-files', '--stage', '-z']
[DEBUG  ] Process 2720925 started
[DEBUG  ] Waiting for process 2720925 to complete
[DEBUG  ] Process 2720925 exited with return code 0
[DEBUG  ] Done query repo: ['ls-files', '--stage', '-z']
[DEBUG  ] Done AnnexRepo(/home/lruecker/hcp).get_content_info(...)
[DEBUG  ] Determine what files match the query to work with
[DEBUG  ] Async run ['/usr/bin/python3', '--version']
[DEBUG  ] Launching process ['/usr/bin/python3', '--version']
[DEBUG  ] Process 2720926 started
[DEBUG  ] Waiting for process 2720926 to complete
[DEBUG  ] Process 2720926 exited with return code 0
[DEBUG  ] Async run ['git', 'annex', 'version', '--raw']
[DEBUG  ] Launching process ['git', 'annex', 'version', '--raw']
[DEBUG  ] Process 2720927 started
[DEBUG  ] Waiting for process 2720927 to complete
[DEBUG  ] Process 2720927 exited with return code 0
[DEBUG  ] Async run ['git', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', '100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz']
[DEBUG  ] Launching process ['git', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', '100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz']
[DEBUG  ] Process 2720934 started
[DEBUG  ] Waiting for process 2720934 to complete
[DEBUG  ] Process 2720934 exited with return code 0
[DEBUG  ] Async run ['git', 'annex', 'get', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', '100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz']
[DEBUG  ] Launching process ['git', 'annex', 'get', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', '100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz']
[DEBUG  ] Process 2720947 started
[DEBUG  ] Waiting for process 2720947 to complete
Total:   0%|                                                                                      | 0.00/997M [00:00<?, ? Bytes/s]Please enter password for encrypted keyring:
[DEBUG  ] Process 2720947 exited with return code 1
[DEBUG  ] received JSON result from annex: {'command': 'get', 'wanted': [{'here': False, 'uuid': '5435893f-9dce-4098-98ec-82d825391bbd', 'description': '[datalad]'}], 'note': 'from datalad...\nfrom datalad...\nfrom datalad...\nUnable to access these remotes: datalad\nTry making some of these repositories available:\n\t5435893f-9dce-4098-98ec-82d825391bbd -- [datalad]\n\n(Note that these git remotes have annex-ignore set: origin)', 'skipped': [], 'success': False, 'key': 'MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz', 'error-messages': [], 'file': '100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz'}
[ERROR  ] from datalad...; from datalad...; from datalad...; Unable to access these remotes: datalad; Try making some of these repositories available:;   5435893f-9dce-4098-98ec-82d825391bbd -- [datalad]; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/lruecker/hcp/100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz)]
get(error): 100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz (file) [from datalad...; from datalad...; from datalad...; Unable to access these remotes: datalad; Try making some of these repositories available:;   5435893f-9dce-4098-98ec-82d825391bbd -- [datalad]; ; (Note that these git remotes have annex-ignore set: origin)]
[DEBUG  ] could not perform all requested actions: Command did not complete successfully. 1 failed:
[{'action': 'get',
  'annexkey': 'MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz',
  'message': 'from datalad...; from datalad...; from datalad...; Unable to '
             'access these remotes: datalad; Try making some of these '
             'repositories available:; \t5435893f-9dce-4098-98ec-82d825391bbd '
             '-- [datalad]; ; (Note that these git remotes have annex-ignore '
             'set: origin)',
  'path': '/home/lruecker/hcp/100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz',
  'refds': '/home/lruecker/hcp',
  'status': 'error',
  'type': 'file'}] [utils.py:generator_func:457]`
  
  The problem was that I stored my credential for the service"aws-s3" instead of the "datalad-hcp-s3

**Comment by adswa** [comment]
fixed by  #6242
