### ISSUE TITLE
Underscores in config names

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5503]
I feel like the issue was discussed before, but I fail to find it: With datalad-hirni (see https://github.com/psychoinformatics-de/datalad-hirni/issues/177) I need to pass procedure configs via env vars. Problem: They are `datalad.procedure.NAME.something`. Names of procedures are their filenames (w/o extension). Now, one naturally can have such a procedure named with an underscore in it. When translating this to the respective env var and then back via `ConfigManager`, the underscore becomes a dot, thus the resulting config var does not match the procedure name and isn't considered. The same thing applies to names of run substitutions.

We do translate `-` to `__` in env vars already. Should we have an additional convention for underscores, like triple underscores in the env vars, @datalad/developers ?

**Comment by kyleam** [comment]
> Should we have an additional convention for underscores, like triple underscores in the env vars

Hmm, that'd make the current replacement a little more complicated because we'd have to prevent the other replacements from messing with the `___ -> _` mapping (e.g., using a regexp-based approach instead of simpler `str.replace` calls), but I don't have any better/prettier ideas for the specific problem.

However, even with the above triple underscore handling, the environment variable transformation still has issues: it doesn't retain the case of the original procedure file name, and it only allows a limited set of characters.  So, given the need to pass the call format via an environment variable, maybe it's worth coming up with a more reliable ad hoc approach.  Perhaps we could introduce an environment variable (`DATALAD_PROCEDURE_SOMETHING`) whose value is a series of json lines or null-delimited values that specify the name and call format of one or more procedures.

**Comment by bpoldrack** [comment]
> Perhaps we could introduce an environment variable (DATALAD_PROCEDURE_SOMETHING) whose value is a series of json lines or null-delimited values that specify the name and call format of one or more procedures.

Hmm. Since the issue - at least in theory - also applies to configured substitutions for run format strings and pretty much anything where users can specify names that need to be included in config vars, may be enhance that approach and go to the bottom of it: inter-process config overrides. So, may be a `DATALAD_CONFIG_OVERRIDES`, that takes a JSON dict, that would be digested by ConfigManager and applied as an override for arbitrary configs?

**Comment by kyleam** [comment]
> may be enhance that approach and go to the bottom of it: inter-process config overrides

Good point.  I was ready to discard everything else as "not needed, still not supported" (not sure if that first part is even true), but I don't see any reason not to take the more complete approach.
