### ISSUE TITLE
`datalad install` is installing an older commit, why?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#5524]
#### What is the problem?
I am encountering an issue I can't find a reason for. I have a nested structure of datasets, say parent A with children B and C. When I install A recursively (`datalad install -r --source /PATH/TO/A`) I end up with an older copy of A which does not contain some of the subdatasets (say, missing C which was added at a later commit). I can't understand why is this happening, any idea?

As a result, also the subdatasets are outdated, example below:

```
### original source location
[dorian@mri STUDY1]$ git submodule
+5c62264b5d7ebe119deeeb2a08ebc8f1d49afd63 data/bids (v0.9-GoodImages)
 8a3f036fdbd18092661d4fe16071d3f962627ab5 data/processed (v0.5)
### new install location
[dorian@mri STUDY1]$ cd /DATA/dorian/datasets/STUDY1/
[dorian@mri STUDY1]$ git submodule
 2e335c4720e60b0408f9496fb51b23a6dbb1e521 data/bids (v0.5~22)
 8c38621bd1925baabd69953e2c114b438eda8ab5 data/processed (v0.5~7)
```

#### What steps will reproduce the problem?
Hopefully this does not need a reproducible example.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?   
`datalad 0.14.0`

#### Is there anything else that would be useful to know in this context?
No

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes

**Comment by dorianps** [comment]
Here is the check of the last commit on the source and the newly installed datasets. Note, for some reason they don't match:

```
[dorian@mri STUDY1]$ echo ------------- new installation location ---------- && git log -1
------------- new installation location ----------
commit b3474b0f764a5a2469aac54ca9c6b26d896f8cef (HEAD -> master, origin/master, origin/HEAD)
Author: SD <noreply@gmail.com>
Date:   Sat May 23 23:50:10 2020 -0400

    Added documentation about adding missing imaging data in May 2020


[dorian@mri STUDY1]$ cd /DATA/FEDERATED_DATASETS/STUDY1/
[dorian@mri STUDY1]$ echo ------------- sourcedataset ---------- && git log -1
------------- sourcedataset ----------
commit 02e1b753d114bb799fe9cf89e1f1f3f1190a1e60 (HEAD -> master, tag: v0.5)
Author: Dorian P <xxxx.xxxxx@xxxxx.com>
Date:   Sat Aug 29 02:41:27 2020 -0400

    Save all STUDY1 subtree
````

**Comment by bpoldrack** [comment]
Hm. It does look like you actually installed from elsewhere, since `origin/HEAD` in the new location also is on that commit. I don't see how we can possibly end up fetching an old state of HEAD from origin. I may miss something, but I suspect that the actual installation command was slightly different than `--source /DATA/FEDERATED_DATASETS/STUDY1/`.

**Comment by dorianps** [comment]
I can't fully replicate the parent dataset screwup, but what I noticed is this:

When I start to install a parent dataset, all subdatasets will be installed at the commit registered in the parent dataset. If a subdataset has advanced, it will not be on the latest commit. The `bids` subdataset below is formally behind origin even though I just installed it. In fact, the branch GoodImages was never registered in the parent dataset, it just happens that it has the commit that was in the `master` branch once, which was recorded on the parent dataset, and it switches to that. 

```
[dorian@mri bids]$ git checkout GoodImages
Already on 'GoodImages'
Your branch is behind 'origin/GoodImages' by 27 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
[dorian@mri bids]$ git log -1
```
Anyway, I had to save the entire dataset tree in `origin` for things to be in sync. Is there a way to install a dataset tree at a dirty state, i.e., without having to save the entire tree in the source location, but keep all subdatasets at their latest commit? That is, how to install a clone of the current status of the source with all latest commits independently if they are registered in the parent dataset or not? Maybe a for loop in bash can do it, or even a git foreach, but the question is how to do this with datalad using perhaps a single liner (or a flag)?

Thank you.

**Comment by bpoldrack** [comment]
> Is there a way to install a dataset tree at a dirty state, i.e., without having to save the entire tree in the source location, but keep all subdatasets at their latest commit?

No, I don't think there is. @datalad/developers: Correct me if I'm wrong.
A dirty state is not for cloning. That's intentional. You install the superdataset (that is: it's HEAD) recursively. The state (commit) of a subdataset is referenced in that superdataset. It explicitly says: This is the version of the subdataset I'm referring to. If you want it to point to another/newer version of a subdataset, you need to save that. 

You could install newer versions of those subdatasets directly, though (i.e. not going through superdataset recursively). 
Or do a recursive update on the receiving end and save that new state there (but nothing gained that way really, I guess).

Where does the need come from? What prevents you from saving a state that you want to be available for cloning?

**Comment by yarikoptic** [comment]
@dorianps You could follow up your `install -r` with `update -r --merge ff-only` if you do not want subdatasets to jump to some non-fastforward state, or `update -r --merge any` to merge any such "divergence" in the history, and unfortunately we do not have yet `--merge reset-hard` -- please chime in on #5498

**Comment by yarikoptic** [comment]
I echo @bpoldrack 's response that "it is by design".  In theory an option could be added to not "go back to the state known to the parent".  May be we should actually generalize the option of `update`: `--follow {sibling|parentds}` and just make it a reverse for `install`: `--follow {parentds|sibling}` which would reflect the current|desired-here behavior?

**Comment by dorianps** [comment]
I am done with this issue. I can close it, but I see @yarikoptic left some ideas in the last message. So I am not closing, but feel free to close on your end.

**Comment by yarikoptic** [comment]
in the spirit of closing stale issues which found no traction, I will just close this one even though indeed some ideas were expressed ;)
