### ISSUE TITLE
Accelerate deprecations with -deprecated

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5561]
I occurred to me that we could accelerate deprecations via the -deprecated extension. Instead of just moving large pieces (commands etc.) we could set it up to monkey-patch the `Repo` classes or similarly low-level pieces. This would give us a place to move tests for such functionality too, and offer users a more controlled way of co-evolution, without slowing development in the main development branch.

**Comment by bpoldrack** [comment]
I think there's a more fundamental underlying issue. At that is a lack of architecture and with it a well thought-through approach of separating what is considered datalad's python API that requires deprecation cycles and under that abstraction layer the workhorse piece that we are free to RF to any extend we want at any time w/o worrying about deprecation/breakage. RF'ing should actually be constant process for most part of the code. Instead we associate RF'ing instantly with breakage (b/c of lack of a design). I think this is a major mistake that we need to get rid of in a longterm planned effort.

That will need some talk about process, utilization of projects etc. - otherwise we will just have yet another bunch of issue that nobody really keeps track of and more attempts to address parts of this, that will stay unfinished and become obsolete by the next attempt that will see the same fate.

While the approach you outline is an improvement in a way and therefore may be a temporary neccessity, ultimatetly I'm afraid, it just makes it a little easier to keep doing the wrong thing.

**Comment by mih** [comment]
@bpoldrack I can get behind that, but is this a +1 or a -1 on this approach?

**Comment by yarikoptic** [comment]
I like the appeal of been able to move entire tests into deprecation more easily. But I wonder if that would blur the "surface" of datalad "core" too much - if something goes wrong, might get harder to figure out if we haven't monkey patched something which had a "proper" implementation etc.  
Also I do not see it as better alternative to proper deprecation/removal cycles if we want to keep datalad "ecosystem" going forward, instead of clinging to elderly code available in `-deprecated` and thus making that extension a common one to have installed by downstream users/developers.  So, by enabling possibly a faster way forward, we might just end-up contributing to making "core" less robust (not by itself, but in combination with -deprecated since that is what people would keep installing).

So -1 from me at this point at least

**Comment by bpoldrack** [comment]
@yarikoptic 

> So, by enabling possibly a faster way forward, we might just end-up contributing to making "core" less robust (not by itself, but in combination with -deprecated since that is what people would keep installing).

Guess, that's another flavor of my "makes it a little easier to keep doing the wrong thing", that I didn't even think of!

@mih I think in this form a -1. But: I have a feeling somewhere in there is an approach that can actually help us transition into something significantly better. Needs to be part of what I outlined. I thought about about this during the weekend and one of the big problems in redesigning is, that the design itself requires a "shape", that allows for an intermediate design, that in turn lets us properly deprecate the current stuff and then can easily be turned into the "target". Patch via `datalad-deprecation` might be a very helpful mechanism to make use of, when really thinking this through.

**Comment by mih** [comment]
Idea has been shot down.
