### ISSUE TITLE
Should we annex.dotfiles=true by default?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5582]
We do add .gitattributes configurations for cases where we do want to keep files (dot or not) under git.

Recently while adding 10TB of shub into annex which I intentionally created without `-c text2git`, thus assuming that everything would go into annex, I saw it reporting that `.shub-log (non-large file; adding content to git repository)` and some of which where quite damn large (so I ended up with 600MB .git/objects).

So I wondered if it wouldn't be less of cognitive load on users if we just treat any general .dotfile as a large file (unless `-c text2git` and alike)?

**Comment by yarikoptic** [comment]
probably the easiest would be to come up with `cfg_allannex` procedure, which would set that config option (with `annex config`) thus leaving default mode "as is" to stay with current, possibly a bit confusing to a regular mortal but expected by a knowledgeable git-annex user, behavior?

**Comment by kyleam** [comment]
We have set `annex.dotfiles=true` unconditionally since 97c28c7bc5 (RF: annexrepo: Adjust for removal of --include-dotfiles, 2020-02-26).

https://github.com/datalad/datalad/blob/e57a2a27479c27322ade9614df098c8baff09a28/datalad/support/annexrepo.py#L221-L221

However, for repos where cfg_text2git has configured `annex.largefiles`, the `((mimeencoding=binary)` condition overrides the `annex.dotfiles=true` behavior.

So, to change the behavior you're describing, I think you'd need to adjust `annex.largefiles`.

**Comment by mih** [comment]
I am closing this issue, because the desired change is already a reality.
