### ISSUE TITLE
git-annex version 

### ISSUE THREAD

**Issue by samuelgarcia** [datalad/datalad#5771]
Hi datalad team,
I have installed datalad from master branch to fix an issue before a release.

datalad is not working anymore on my mahcine because of the constrain on git-annex version.
I have a very standard ubuntu 20.4 with git-annex 8.20200226 inside.
I appears that now datalad need version>=8.20200309
Which make dattalad not compatible with my system.
I known that I can install git-annex with conda but I use only pip and debian package.
Is there abig reason to constrain this git-annex version ?

Thanks a lot for helping.

**Comment by yarikoptic** [comment]
> I known that I can install git-annex with conda but I use only pip and debian package.

we provide `git-annex-standalone` build via neurodebian: http://neuro.debian.net/pkgs/git-annex-standalone.html 
you can `apt-get install neurodebian && apt-get update && apt-get install git-annex-standalone` 

that build of git-annex would be a bit slower than "stock" one (via conda or otherwise) but likely you would not notice.

> Is there abig reason to constrain this git-annex version ?

we only establish the lower bound, not really constraining/pinning.  Typically whenever we stop supporting some functionality in git-annex which was deprecated in git-annex, or whenever we do need some newer functionality from git-annex and adding kludges to support older versions would be too much work for little gain.

Feel free to reopen if there is anything else we could do.

Just in case: there is `pip install datalad-installer` which could be handy to assist in installing git-annex and/or datalad in various desired "setups".

**Comment by samuelgarcia** [comment]
Hi Yarik.
Thank you for this clear anwser.
And thank you for the tips of datalad-installer.
