### ISSUE TITLE
ria-store, git-annex get fails on bare-git.

### ISSUE THREAD

**Issue by bpinsard** [datalad/datalad#5779]
#### What is the problem?
I have the following use-case: on an HPC I want to install a dataset in a shared ria-store for other lab members to use.
I datalad install the repo in a scratch space, then create a sibling in the ria-store, then I want to prefetch files for the lab members to use.
Ideally, I wouldn't pull the data in the scratch to then push it to the shared storage space. Luckily git-annex seems to work on bare-git https://git-annex.branchable.com/bare_repositories/ .
But when I try to run `git annex get --branch main` while in the bare-git in the ria-store, I get the following error.
```
$ git annex get
git-annex: This repository is not initialized for use by git-annex, but ./annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
```
Is there any difference between the ria/ora bare-git and a bare git such as used in the git-annex page above.

Thanks!

#### What steps will reproduce the problem?

`git-annex get` on a dataset exported to a ria-store.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.14.0

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

yes! :D

**Comment by bpoldrack** [comment]
@bpinsard 

> Is there any difference between the ria/ora bare-git and a bare git such as used in the git-annex page above.

Yes. There's an important difference! The bare repo in a RIA store doesn't know it has an annex objects tree. It looks like it's just a regular, bare git-annex repo, but it isn't. It's just a git repo. The objects are accessed only by the ORA special remote. In addition the layout of that `annex/objects` is different from what git-annex would expect in a bare repository (in case that means something to you: it's using dirhashmixed like a regular non-bare annex repo instead of dirhashlower, which is what annex uses with bare repositories).

So, essentially you need some outside of the store repo to have the data first. However, you do not necessarily go through `datalad push/publish` and by extension the special remote. The `annex/objects` tree in that bare repo is identical to the one you'd have in a regular clone. Plus: If you're going for an archive in the store instead, there's `datalad export-archive-ora` to help with that.

Does that help?

**Comment by yarikoptic** [comment]
FWIW, unfortunately bare repos support overall is still lacking: https://github.com/datalad/datalad/issues?q=is%3Aissue+is%3Aopen+bare+label%3Abare-mode (in particular #2820)
