### ISSUE TITLE
How to convert online data to datalad dataset

### ISSUE THREAD

**Issue by mankoff** [datalad/datalad#5783]
#### What is the problem?

I have not found simple documentation on how to convert an existing dataset to a datalad data set. My use case is I would like to start serving existing data via datalad.

Does this exist somewhere in the manual and I have not found it? Or is this a chapter that should be added? 

#### What I have tried

I've patch together the following from the Handbook, but it does not seem to work. At the end, after `datalad get -r .`, the files do not appear in my dataset.

```bash
mkdir -p ~/tmp/datalad
cd ~/tmp/datalad
datalad create foo
cd foo

datalad create -d . -D "NW Greenland ice mask" Northwest_Greenland_ice_mask
cd Northwest_Greenland_ice_mask

datalad download-url -d . -m "Terms of use"  https://promice.org/PromiceDataPortal/api/download/d22917dd-338e-402c-ade9-641b58db7e25/PROMICE+terms+of+use.pdf

datalad save -d . -m "NW Greenland ice mask" *
```

And then I try to clone it elsewhere with:

```bash
cd ~/tmp/datalad
datalad clone -D bar ~/tmp/datalad/foo bar
cd bar
tree
datalad get -r .
tree
```

**Comment by adswa** [comment]
Hey, thanks for getting in touch. There is a general chapter on converting existing data into datasets in the docs [here](http://handbook.datalad.org/en/latest/beyond_basics/basics-retrospective.html), and an example workflow where data is downloaded and transformed into a dataset [here](http://handbook.datalad.org/en/latest/basics/101-139-s3.html).

The general principle would be
```
# mydata is a directory full of data, but not a dataset
$ cd mydata
$ datalad create -f .
$ datalad save . -m "Save all previously existing data at once"
```

However, your example does not look like "converting an existing dataset to a DataLad dataset", maybe you omitted the part where existing data is added? :)
Maybe I am misunderstanding your example, but what I see what you are doing is:
- creating a new dataset (if you were to transform an existing, non-empty directory you would need to use the ``--force`` flag)
- downloading a file into it
- (the ``save`` after ``datalad download-url`` wouldn't have anything to save at this point, ``download-url`` handles saving on its own)
- (the recursive operations don't do any harm, but they also don't do anything because recursive operations would require a hierarchy of datasets. Maybe you omitted superdatasets or subdatasets for the sake of brevity, but I wanted to explicitly state it at least)

In general, here's how I would do what you did in your example:

```
(handbook2) adina@muninn in /tmp
❱ datalad create -D "NW Greenland ice mask" myawesomedata
[INFO   ] Creating a new annex repo at /tmp/myawesomedata 
[INFO   ] scanning for unlocked files (this may take some time) 
create(ok): /tmp/myawesomedata (dataset)
(handbook2) adina@muninn in /tmp
❱ cd myawesomedata 
(handbook2) adina@muninn in /tmp/myawesomedata on git:master
❱ datalad download-url -m "Really important manula" https://www.ikea.com/de/de/manuals/troxhult-wall-shelf-white__AA-2180177-2_pub.pdf
[INFO   ] Downloading 'https://www.ikea.com/de/de/manuals/troxhult-wall-shelf-white__AA-2180177-2_pub.pdf' into '/tmp/myawesomedata/' 
download_url(ok): /tmp/myawesomedata/troxhult-wall-shelf-white__AA-2180177-2_pub.pdf (file)               
add(ok): troxhult-wall-shelf-white__AA-2180177-2_pub.pdf (file)                                           
save(ok): . (dataset)                                                                                     
action summary:                                                                                           
  add (ok: 1)
  download_url (ok: 1)
  save (ok: 1)
(handbook2) adina@muninn in /tmp/myawesomedata on git:master
❱ cd ..
(handbook2) adina@muninn in /tmp
❱ datalad clone myawesomedata myawesomeclone
[INFO   ] scanning for unlocked files (this may take some time)                                           
install(ok): /tmp/myawesomeclone (dataset)
(handbook2) adina@muninn in /tmp
❱ cd myawesomeclone 
(handbook2) adina@muninn in /tmp/myawesomeclone on git:master
❱ tree
.
└── troxhult-wall-shelf-white__AA-2180177-2_pub.pdf -> .git/annex/objects/Xz/6V/MD5E-s829587--ca14c39b7e63b718659e880b19cd3d51.pdf/MD5E-s829587--ca14c39b7e63b718659e880b19cd3d51.pdf

0 directories, 1 file
(handbook2) adina@muninn in /tmp/myawesomeclone on git:master
❱ datalad get .
get(ok): troxhult-wall-shelf-white__AA-2180177-2_pub.pdf (file) [from origin...]                          
(handbook2) adina@muninn in /tmp/myawesomeclone on git:master

```


PS: I tried to use your PDF for recreating your example, but I run into an SSL error on the server side:

```
datalad download-url -m "Terms of use" https://promice.org/PromiceDataPortal/api/download/d22917dd-338e-402c-ade9-641b58db7e25/PROMICE+terms+of+use.pdf
[INFO   ] Downloading 'https://promice.org/PromiceDataPortal/api/download/d22917dd-338e-402c-ade9-641b58db7e25/PROMICE+terms+of+use.pdf' into '/tmp/myawesomeclone/' 
download_url(error): /tmp/myawesomeclone/ (file) [Failed to establish a new session 1 times. Last exception was: HTTPSConnectionPool(host='promice.org', port=443): Max retries exceeded with url: /PromiceDataPortal/api/download/d22917dd-338e-402c-ade9-641b58db7e25/PROMICE+terms+of+use.pdf (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1123)'))) [adapters.py:send:514] [http.py:get_downloader_session:564]]
```

Maybe @yarikoptic knows if that is something that needs fixing on the serverside or on our side?

PS: Apologies in advance if I don't get back to this fast - I am on vacation, and used some waiting time to answer to this, but will be largely offline for the rest of the week

**Comment by mankoff** [comment]
> However, your example does not look like "converting an existing dataset to a DataLad dataset", maybe you omitted the part where existing data is added? :)

Thanks for the detailed reply. I may be using the incorrect words to describe what I want. I have a bunch of datasets with the data online, DOI'd and archived (just not in datalad). I'd like to turn all these into datalad datasets.

Your example works: when I clone it, and then `get`, the PDF shows up. 

The only difference between your example and mine that I see is that I was trying to create sub-datasets. Because I have a bunch of related but separate data online, I was going to create a bunch of sub-datasets all under a master dataset that is our project/group. Later I would nest this into a department level, and then eventually a community level dataset.

That is, if I take your example and add these two lines at the top,

```bash
datalad create foo
cd foo
```

then the sub-dataset `get` does not seem to do anything. What (else) am I doing wrong here?

**Comment by mankoff** [comment]
Aha! It seems I was missing a `datalad save . --recursive` (from the top-level dataset). That is what I was trying to do with the `datalad save` commands that were redundant in my first example. Thank you!

**Comment by dorianps** [comment]
Not sure I understand everything, but I have done this more than once.
First I force create the parent dataset, but do not save anything after
creation, otherwise all data are saved under parent. Then I go to force
create all subdatasets and save them too. Once subdatasets are saved, they
are tracking their own chunk of data. The parent dataset knows that those
are subdatasets/submodules and has no business checking what's inside them.
So at the end I go save the parent dataset which simply records the latest
commits of each subdatasets.

I think that this can be done without creating a parent as well, that is
starting with individual subdatasets and at the end creating the parent.
But this is not the conventional way. I discovered this by mistake. Someone
had left a .git folder inside a code folder because he was using git, and
when he gave me the folder I tried to integrate it in an existing dataset.
Guess what, datalad saved it as subdataset because it thought that folder
is already tracked with git.

Dorian
