### ISSUE TITLE
Operate webserver setup for test purposes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5791]
It has been mentioned repeatedly that setting up the necessary environment for a particular test can be much more demanding that the actual test implementation. The leads to less tests being implemented, and implemented test to run less often then desired.

I would appreciate if we could host a series of HTTP server(s) (virtual hosts), something like `ci-test-<scenario>.datalad.org` that are available to test against a number of predefined scenarios.

Their availability would be beneficial for the RIA-related functionality. With all other supported "services" we have deployments to test against, not for RIA. All is done adhoc, and nowhere complete enough.

I would appreciate your feedback on how this could be achieved. A preconfigured container might be a possibility (to keep it within the context of a CI and always fresh). But a static deployment is also an option.

**Comment by aqw** [comment]
For what it's worth, we deploy all of our datastores using Ansible. I'm happy to share the relevant playbooks if it's beneficial.

Static-vs-container us up to the person hosting IMO (yarik).

**Comment by bpoldrack** [comment]
I think enhancing the docker image(s) we already deploy for SSH testing might be the way to go.
I started working on that for SSH based RIA testing already.

**Comment by yarikoptic** [comment]
FWIW we have already a number of repositories (visit https://github.com/datalad?q=testrepo-&type=&language=&sort=) some of which which were programmatically populated using logic/setup in https://github.com/datalad/datalad/blob/master/datalad/tests/utils_testrepos.py IIRC, and are already used in a good number of tests explicitly or implicitly via `@with_testrepos(flavor=['network'])` .  

Re repeatedly setup -- there is also https://github.com/datalad/datalad/blob/master/datalad/tests/utils_cached_dataset.py , so in principle it is not per se about one-time setup burden, if test uses a cached version.

Overall I feel that we have already some framework(s) which already used, but were "refactored away" to get "per test setup" instead of seeing how to adjust/make use of them more efficiently.  Not sure if we need yet another additional setup.

**Comment by bpoldrack** [comment]
> ...
> Overall I feel that we have already some framework(s) which already used, but were "refactored away" to get "per test setup" instead of seeing how to adjust/make use of them more efficiently. Not sure if we need yet another additional setup.

I don't see any of that addressing the issue. We need, for example, a RIA store that is served via HTTP. That can't be done via a service hosting git repos. And mocking it, by serving a path locally comes with issues we already stumbled upon, where access is possible in different ways and the test can't easily ensure we know which access method was actually used.

**Comment by yarikoptic** [comment]
If we can't ensure type of access used, it would indeed be an issue to be fixed, and we can and do provide ssh, file, http methods quite easily. Note: we already have store.datalad.org, so we can host test datasets there as well

**Comment by yarikoptic** [comment]
And if so desired, that store can be moved to other location, I don't care, as long as it is as reliable/accessible to the developers. What I oppose is adding yet another infrastructure component since IMHO it could be avoided

**Comment by mih** [comment]
I am closing this issue after four months of inactivity. It remains accessible for future generation, wondering why they didn't do it.
