### ISSUE TITLE
Rename auto-related issue/pr labels

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5833]
I think they are hard to find in the slew of labels we have, and a common prefix like `version-` would substantially aid discoverability for me -- as someone who is actively developing, but not into daily release management operations.

**Comment by yarikoptic** [comment]
I think `auto` doesn't support "custom labels", @jwodder ?  I just remember them "by heart" now, it is only a few.

**Comment by jwodder** [comment]
`auto` does support changing the label names; see <https://intuit.github.io/auto/docs/configuration/autorc#labels>.

**Comment by mih** [comment]
Now that these labels are also required for working on master, I would really appreciate this rename to aid findability.

I also feel like the descriptions could be clarified. There is only the list in CONTRIBUTION.md, which also has other labels (so there is no standalone list that identifies the full set of relevant choices).

- minor — for changes corresponding to an increase in the minor version component
- patch — for changes corresponding to an increase in the patch/micro version component; this is the default label for unlabelled PRs
- internal — for changes only affecting the internal API
- tests — for changes to tests

`patch` is described as "default", but it seems it is actually necessary to be selected manually, if no others are selected.

It seems that `internal` and `tests` semantically mean `...-only`, as in it is not necessary to bump patch or minor version.

Is there any practical use for the additional `tests` label vs. just `internal`? If yes, do you now expect any PR (i.e. practically all of them) to have an additional `tests` label?

A common label prefix would also clarify the semantics of such generic terms as "internal" and "tests".

Again, these labels might be obvious in standard repos with a handful of labels, but we are presently operating a model with ~100 labels.

**Comment by yarikoptic** [comment]
> *  `patch` is described as "default", but it seems it is actually necessary to be selected manually, if no others are selected.

just because to help us to not forget etc, I asked @jwodder to add that action which would do extra checks that we didn't forget to label our PRs. `auto` would just use `patch` by default indeed

> It seems that `internal` and `tests` semantically mean `...-only`, as in it is not necessary to bump patch or minor version.

correct

> Is there any practical use for the additional `tests` label vs. just `internal`? If yes, do you now expect any PR (i.e. practically all of them) to have an additional `tests` label?

those are also used in groupping log messages in corresponding subsections, see https://github.com/dandi/dandi-cli/blob/master/CHANGELOG.md .  So there is "extra semantic" for `minor` and `patch` (@jwodder correct me if I am wrong) reflecting what semver expects them to be: `patch` -- "Bug Fix", `minor` -- "Enhancement".

> There is only the list in CONTRIBUTION.md, which also has other labels (so there is no standalone list that identifies the full set of relevant choices)

I think that list is providing a full set.

I don't mind seeing `version-` prefix added to `major`, `minor`, `patch` if that would be of help, and definitely wouldn't mind label descriptions extended. Not sure if adding `version-` to others would not be more confusing than helpful.  But adding `auto-` might make sense - it would also place them on top in the list, and make it easier to find all.

**Comment by mih** [comment]
Adding a note here, rather than filing a separate issue, given that things are in flux still. I files a bunch of PRs with just documentation. Neither of the required labels seem to fit. I think the `semver` CI test should also except the `documentation` label is good-enough.

**Comment by yarikoptic** [comment]
you are 100% correct @mih . I have pushed 721315d5d1139a603a410cc98b047f0095aca63e to address that straight into `maint` -- if works out as it should on some sample PR, I will merge into `master`.

**Comment by mih** [comment]
Ok, nobody cares, and I was not able to learn how the release mechanism is implemented within the last 3 months. With ~100 labels it would be really nice to have a grouping. I cannot see how a novice user is supposed to get an understanding. But the datalad project onboarding model is still very much "come live with us for a year". So let's put this to rest and stay in-group

**Comment by adswa** [comment]
I found this issue while checking all those closed issue notifications.

> I don't mind seeing version- prefix added to major, minor, patch if that would be of help, and definitely wouldn't mind label descriptions extended. Not sure if adding version- to others would not be more confusing than helpful. But adding auto- might make sense - it would also place them on top in the list, and make it easier to find all.

I would be very much in favor of adding a custom prefix. It would make it so much easier to find and to get an overview which labels are actually possible. What do you think about ``semver`` - purely because this constantly failing check is called "semver"?

**Comment by mih** [comment]
Sounds good!
