### ISSUE TITLE
(Re)design of `remove` as `purge`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5842]
Companion of #5832 (to be discussed in conjunction)

Context: This is about approaching an improved implementation of the `remove` command, not in isolation, but in the context of a reconsideration of the drop/uninstall/remove combo, with the partial goal to replace the old remove entirely, and with that make progress towards #3368

This is an opportunity to reconsider the role of `remove` in the API, and amend it with the missing functionality we have identified (issues are linked below). This draft description is not about making a contrast to what the present `remove` is doing (there are massive overlaps), but about a comprehensible concept of what as companion of a refurbished `drop` (#5832) would need to do, and not do. The initial design draft is the result of a discussion of @adswa and @mih.

### Basic concept

`purge` is the companion of `drop` with a focus on "destructive" operations. It could be thought of as the antagonist to `clone`. It is used fully wipe out datasets, including top-most superdatasets.

`purge` is called `purge` not `remove` to indicate the severity of the operation, and set it semantically apart from operations like `git rm`, which are typically reversible. This simplifies user expectations and avoid clunky alternative indicator (#4097).

`purge` is needed for two things:
1. to delete (sub-)datasets, because repositories and submodules are under special protection by git-annex
2. to trigger a adequate `drop` call (the intention get rig of file content is semantically more clear when calling `drop`, than when saving the deletion of a file. Actual dropping behavior can be tweaked in `purge` (see below), not in `save`)

`purge` prevents data loss by default. It inherits a number of parameters from `drop`, for which it typically acts as a frontend to benefit from its data security mechanisms (this includes primarily `--reckless`, and `--jobs`). `purge` supports a dedicated `--reckless` mode to immediately wipe out a dataset (hierarchy) with not checks whatsoever (#1282, #2673).

`purge` should be able to recognize a botched attempt to remove a dataset with a plain `rm -rf`, and act on it in a meaningful way, even if it is just hinting at `chmod + rm -rf`.

### Use cases

The following use cases operate in the dataset hierarchy depicted below.

```
super
├── dir
│   ├── fileD1
│   └── fileD2
├── fileS1
├── fileS2
├── subA
│   ├── fileA
│   ├── subsubC
│   │   ├── fileC
│   └── subsubD
└── subB
    └── fileB
```

Unless explicitly stated, all command are assumed to be executed in the root of `super`.

- `datalad purge subB`
   Wipe out `subB`, leave `super` dirty (analog to `datalad clone` behavior)
- `datalad purge -d . subB`
   Wipe out `subB`, save removal in `super` (analog to `datalad clone -d .` behavior)

- `datalad purge fileS2`
   commits deletion, like `rm fileS2 + datalad save`, but with a prior `drop`!
- `datalad purge dir`
   like above, commits deletion of the entire directory and its content, unless subdatasets are found underneath (errors in this case)

- `datalad purge subA`
   errors because of present subdatasets
- `datalad purge subA -r`
   wipes out subdataset hierarchy, leaves `super` dirty

- `datalad purge .` (purge in `super`)
  errors, because of subdataset presence

- `cd .. && datalad purge super -r`
   eradicates super and its subdatasets entirely

The following use case are executed in `subB/` (equivalent to a `super` without subdatasets present)

- `datalad purge .`
  removes all files in the dataset, does *not* purge the dataset
- `datalad purge -d .`
  refuses to wipe out the entire dataset that is in CWD (like `rm -rf` does)
- `cd .. && datalad purge subB`
  wipes out `subB` with all its content and the dataset itself too

**Comment by yarikoptic** [comment]
yet to grasp in full, but in general I think I might prefer to avoid having a command which does destructive operation without requiring some extra option (like `--nocheck`) since then data loss is only a top level command call away.  Somewhat related is an old desire/discussion about `--kill` https://github.com/datalad/datalad/issues/1282 but there (again) it is an option, not a command.

Another quick comment (relates to `remove` and `drop` as well I guess, but there it would be at least up to `--nocheck`) on
- `datalad purge dir` or `datalad purge file` -- would its effect be "isolated" to the `dir` or `file`? e.g. if points to annex'ed keys, which also present in other paths?  Only recently joey implemented a mechanism to address [option to `drop path` to not drop "all copies"](https://git-annex.branchable.com/todo/option_to___96__drop_path__96___to_not_drop___34__all_copies__34__/) wishlist.  I haven't tried it yet.  But if `purge` is to unconditionally drop the keys which might be used elsewhere -- it is an amplified recipe for a "data loss" IMHO.

**Comment by aqw** [comment]
As someone who plays with the infra underpinning others precious data , I strongly support the idea of separating destructive and non-destructive commands. It really helps with indicating to my brain when I'm playing with real fire vs the normal juggling.

+1 on the verb choice of `purge`.

**Comment by mih** [comment]
> But if purge is to unconditionally drop the keys which might be used elsewhere -- it is an amplified recipe for a "data loss" IMHO.

True, but the expressed goal is data security, not "drop by default".

**Comment by yarikoptic** [comment]
> Running `datalad purge <dataset>` on a dataset without subdatasets would

not sure then why it shouldn't be done by `remove` and we need a new `purge` for that... just to unify operation between `uninstall` and `remove` ? (see related: https://github.com/datalad/datalad/issues/2967)

**Comment by mih** [comment]
> not sure then why it shouldn't be done by `remove` and we need a new `purge` for that... just to unify operation between `uninstall` and `remove` ? (see related: #2967)

I tried to explain that with the following statement in the OP:

> purge is called purge not remove to indicate the severity of the operation, and set it semantically apart from operations like git rm, which are typically reversible. This simplifies user expectations and avoid clunky alternative indicator (#4097).

Unlike #2967 it will not be `remove+uninstall` that get merged, but `drop+uninstall`, as described in https://github.com/datalad/datalad/issues/5832

**Comment by adswa** [comment]
Its probably redundant to state that I am in favor of the (re-)implementations proposed here and in #5832 because @mih and I discussed what is proposed in those issues. I like them in particular due to the clear and also semantic separation of "non-destructive" and "destructive" commands, the potential to simplify the API down to two commands (``drop``, ``purge`` compared to ``drop``-``uninstall``-``remove``), and a more unified approach between the "get-rid-of-something" commands ``drop`` & ``purge``, and the "get-something" commands ``clone`` & ``get``.

> not sure then why it shouldn't be done by remove and we need a new purge for that...

I feel like @mih that there is an added value of the name change - ``purge`` communicates the potential severity of the command a bit better than ``remove``. I feel like implementing it in a new command also allows us to keep remove as is during a deprecation period, and then eventually remove it (like it will be done with ``publish``) once a ``purge`` command has reached maturity.

**Comment by bpoldrack** [comment]
While I generally like the aim, it seems to me the concept for `purge` is less clear and consistent than the proposal for its `drop` companion.

First, we have the idea, that its operations are somehow more destructive than `drop`. That doesn't seem to be true. There are basically just additional `git rm`s - as stated in the opening post, that's reversible. The destructiveness is less with the command itself. It lies within `drop` (when force dropping) or within wiping out a repo, that wasn't pushed somewhere else. So, it's as destructive/non-destructive as `drop` - depending on whether or not there are copies somewhere and whether or not we are checking for that. By default both - `drop` as well as `purge` do those checks. `drop` (with the "right" options) is in some sense even more destructive, since a "copy" of the git-history for the additional deletion is sure to locally exist (in opposition to file content). So, I don't really see the described functionality as being more destructive. I may, however, miss an aspect of that, of course.

Second, I'm not yet convinced of its usage semantics. One thing is that it makes quite a difference whether the target is a file or a subdataset, defying the aim of a "mono-repo experince". `datalad purge sub` w/o further options doesn't commit, `datalad purge file` w/o further options does. Why the different meaning? And why is there no way to not commit the file deletion? As mentioned in `drop` (https://github.com/datalad/datalad/issues/5832#issuecomment-889643422) it probably boils down to getting `-d` straight. By extension (and therefore in some sense consistently) this then propagates to deal with directories (incl. `.`) differently, depending on whether or not there are subdatasets present.
This feels like an additional safeguard against the removal of subdatasets. (Consider how `datalad purge` is proposed to fail in presence of subdataset) But why? `drop` deals with subdatasets as well. If the intention is to use `drop` more carelessly, I don't see a need to have a higher bar for subdatasets wrt `purge`. I guess it really stems from the `-d` / no `-d` behavior when the given path is a subdataset, rather than being an intended extra safeguard for subds removal.

I think being more like `drop` could solve this. So, first have `-d`'s effect be identical wrt to subdatasets and files. `datalad purge path` leaves dirty, `datalad purge -d . path` commits. In both cases. Second have the same `--type` option to deal with the presence of subdatasets. `datalad purge subds --type files`/ `datalad purge . --type files` is no problem if there are subdatasets. Same then goes for `--type dataset` and `--type all`. Something along those lines. WDYT, @datalad/developers ?

**Comment by yarikoptic** [comment]
> ...  semantic separation of "non-destructive" and "destructive" commands 

note: there is no guarantee that `drop`'ed (even with a check done *now*) content or `uninstall`ed (sub-)datasets would remain available available in the future.  Also some `purged` local repository clone doesn't really remove data remotely - repositories and data might still exist on remotes. So any explicit "semantic separation" might actually exemplify promises which we cannot really provide one way or another.

**Comment by mih** [comment]
> First, we have the idea, that its operations are somehow more destructive than drop. That doesn't seem to be true. There are basically just additional git rms - as stated in the opening post, that's reversible.

No. What is stated in the opening is

> purge is the companion of drop with a focus on "destructive" operations. It could be thought of as the antagonist to clone. It is used fully wipe out datasets, including top-most superdatasets.

The proposal to also have it do `git rm` is a relatively minor detail.

I cannot follow the argument that the `--dataset` argument use is not "straight", concrete examples would help.

> I think being more like drop could solve this. So, first have -d's effect be identical wrt to subdatasets and files. datalad purge path leaves dirty, datalad purge -d . path commits. In both cases.

I cannot parse this. What is "in both cases"? It would help to see concrete references to the use cases, or the proposal of concrete new use case in the same style as in the design proposal.

**Comment by mih** [comment]
It seems that the only operation that requires anything but a `drop` in the spirit of https://github.com/datalad/datalad/issues/5832 is a `git rm <path-to-subdataset>` after having dropped/uninstalled a subdataset. This operation will never be "recursive" and always be a mere `git rm` + `save`.

**Comment by bpoldrack** [comment]
> The proposal to also have it do git rm is a relatively minor detail.

Well, what I meant by referring to git rm is "the kind of removal that affects the history". In case of a (sub-) dataset that's a little more than an added `git rm` call, but to me it's conceptually the same thing: `drop` to get rid of "content" but keep the reference in the worktree, `purge` to remove that as well. For files and datasets.

Re -d:

I guess will drop (no pun intended) the argument. It has little to do with `drop`/`purge` but is more general. While I know how to use it, I cannot come up with a concise, comprehensible explanation for what exactly it means for a CLI-only user. Everything other than listing examples, that I can think of, is only partially true. I thought if we ever want to have an ironed interface, we should use such occasions, since the alternative is to either never get there or have a huge breaking-everything overhaul. But then again it wouldn't exactly yield consistent meaning across commands if we started a different approach with single commands. I don't know. Ignore that aspect.

Although I'm kinda fine with the idea to have nothing but `drop`, I can still see room for a command that helps removing/wiping out. 
It's not clear to me why to get rid of that notion. (But I see it helping to realize that it's not a necessity). Preference for me would be to have a command that helps removing: drop + (chmod) + (git) rm + (save) . Whether that's called `purge` if only to not deal with deprecations, I don't care).

Anyways - I can live with `drop` only.

**Comment by mih** [comment]
The more I keep thinking about `drop` the more I am convinced that `remove` is nothing but a lightly wrapped `git rm`. Even recursive operation is irrelevant.

**Comment by mih** [comment]
So #6111 now reimplements `remove` as a thing wrapper around `drop`. `drop` provides the safety net, and then runs `save` to record a removal -- not more. This is not the same as what is proposed here, but it nevertheless removes most (if not all) incentives to fully flesh out a design for a `purge` command.
