### ISSUE TITLE
Method to combine subdatasets into one dataset OR method to add a s3 source to already downloaded files

### ISSUE THREAD

**Issue by jsmentch** [datalad/datalad#5849]
I am working with the HBN data and want this to be a datalad dataset. I have a folder where each subject is a dataset (files added from s3 via addurls). I've realized these should not be subdatasets because each only contains 30-50 files and it should be one dataset with subfolders not subdatasets...

1) is there an easy way to convert this folder of subdatasets into one large dataset with subfolders(not subdatasets) for each subject, and all files still maintaining their provenance so that they can be dropped and redownloaded from s3 as needed. When there was a superdataset of these subdatasets, operations were prohibitively slow.

If it is easier, on our server, someone has already downloaded the entire HBN data and it is in BIDS format. 

2) is there an easy way to make this existing folder a datalad dataset, and adding the s3 source of each existing file and making datalad trust that is the source. Some files have been renamed by necessity.

3) are either of those above options too complicated - ideally, we wouldn't want to redownload all of the data but maybe that is the most feasible option. Haven't been able to figure out the best way to do this, any input on this problem appreciated - thanks!

**Comment by yarikoptic** [comment]
eh, HBN... I should have finished it.  Are you interested in only raw or also preprocessed data?  IIRC it was preprocessed which gave me pains.

1. no "built-in" but it is a matter of adding each subfolder as a simple helper
    - move within each subdataset first under corresponding directory within it
    - move subdirectories aside somewhere, and `datalad save ` that they are gone
    - add remotes for each subdatasets
    - do a single monster `git merge <all subdataset remotes>`, `git annex update`, and `annex get` I guess to re-get from all local ones
    - kill original subdirectories you placed aside

may be there is a better way

2. don't quite get it... renames aren't relevant to git-annex since it keeps availability information per content key so even if file is renamed in git/git-annex -- already added urls should be there

3. I used `datalad-crawler` extension to prepare my versions of datasets from INDI ones, such as http://datasets.datalad.org/?dir=/hbnssi .  `datalad addurls` was born later to provide some nice features and not yet "integrated"/used by elderly datalad-crawler .

overall if you already have it all locally, might be best to just do 1. or alike

**Comment by jsmentch** [comment]
We want the nifti files available on s3 and then will run the latest fMRIprep and ideally upload the derivatives to their s3 bucket for anyone that wants to use. 

Ok, I think I understand method in 1. and am going to give that a try!

2) Ah I should clarify here: Someone has already downloaded all HBN data into a separate directory on our server but this was not done using datalad addurls, it was downloaded directly via aws and the files were renamed etc. So it is a complete directory with all HBN data but not a datalad dataset and thus the provenance of the files is not tracked. But if there was some not too crazy way to add the origin of these files I could turn this directory into a datalad dataset (if easier than 1. )

**Comment by yarikoptic** [comment]
you can add urls to existing annexed files. `git annex registerurl` command. Even `datalad addurls` would do that, resorting to `annex` to do just basic check on file size IIRC... but paranoid me wouldn't do that, since if file was modified on S3 (may be without effect to file size), you wouldn't know and it might be different/have different checksum. in theory amazon s3 etag could be (ab)used to verify identity by recomputing it locally. But that might fail if deduction of block size which was used during upload would be "wrong", and thus you might get different ETag if you compute locally.  Another "in theory" approach, used by datalad-crawler for "updates"  (so getting only "newer" keys) from S3 -- fetch full history for bucket (iirc it is versioned), filter out keys for the date when files were downloaded, populate with those keys/versionId urls.

**Comment by yarikoptic** [comment]
> We want the nifti files available on s3

so question stands -- only the "raw" bids and not derivatives? ie. only what is under `http://fcp-indi.s3.amazonaws.com/data/Projects/HBN/MRI/` (for different sites)?

**Comment by jsmentch** [comment]
Hmm Ok sounds like method 1. is the way to go then.

> > We want the nifti files available on s3
> 
> so question stands -- only the "raw" bids and not derivatives? ie. only what is under `http://fcp-indi.s3.amazonaws.com/data/Projects/HBN/MRI/` (for different sites)?

Sorry, yes only the "raw" bids (for running fMRIprep:latest w/ recent bug fixes). But placing all subjects from all sites into one folder, not per site folders. The derivatives available on s3 seem to only be: Freesurfer_version6.0.0, dwi_dpisner_autoDTI, dwi_qsiprep/.

**Comment by mih** [comment]
Have you tried whether the `datalad copy-file` command would do the job for you?

**Comment by yarikoptic** [comment]
As multiple ways to do "combine" were presented/provided I will consider this issue "addressed". Please reopen if disagree/need more ;)

As for "splitting" out subdatasets, there is a dedicated https://github.com/datalad/datalad/issues/3554 with some pointers, but unfortunately no datalad helper exists yet.
