### ISSUE TITLE
datalad remove sibling not working as expected 

### ISSUE THREAD

**Issue by scovitz** [datalad/datalad#5977]
We are running a script that clones from an RIA store on a remote server, gets all the data, then uses this local copy as input to a YODA analysis; however, when we try to run the analysis, we see datalad attempting to clone the data from the original remote RIA store. We tried using **datalad siblings remove -s SIBLINGNAME** and **git annex dead SIBLINGNAME**.  When we run **datalad siblings** in the input dataset, the only listed sibling is **here**; however, our when we try to datalad run the analysis we still see attempts to clone from the remote RIA sibling that has already been removed. Is there a way to confirm the sibling we removed is actually gone? We are not sure why this is happening and would welcome any insights. @mattcieslak

**Comment by bpoldrack** [comment]
> Would it be a really bad idea to delete the unkillable-store lines from remotes.log on the git-annex branch?

It's conceptually unreliable, but could work. But you'd need to push back that change to the (intermediate) store, too - just like with the `autoenable=false` approach above. Hence, I'd not recommend it. Any clone that happens to exist before could reintroduce it (which is why one cannot simply remove a special remote) and you end up with an availability record in the annex branch, that points to an "undefined" source. It may not be an issue in a concrete setup, where you actually control all existing clones, but it would rely on `git-annex` not stumbling on inconsistent entries (which may vary over git-annex versions).

**Comment by mattcieslak** [comment]
This ended up working for us, thanks again for the response. I think we can close this @scovitz
