### ISSUE TITLE
Failed to load metadata extractor for 'datalad_core' and other test failures

### ISSUE THREAD

**Issue by TheChymera** [datalad/datalad#6000]
for `=datalad-0.15.0` on Gentoo Linux, I get this:

https://ppb.chymera.eu/34e315

Can you help me out with any of the errors?

Also, I'm wondering about the following more general questions regarding the test suite:
1. it's taking a very long time, can it maybe be parallelized?
2. There were a lot of other errors initially, which were sorted out by pulling in the non-core dependencies from the downloaders and metadata sections. Is there a way to only run the test suite for core functionality?
3. Is there a way to sandbox the test suite so that it works without outbond connectivity, or barring that turn off all the test functions which require network access?
4. There's a number of non-python dependencies (obviously) not covered in `setup.py`. One is clearly `git-annex`, and an other is `p7zip`. Did I perhaps miss anything else?

**Comment by yarikoptic** [comment]
1. may be
2. majority of errors seems to be due to missing installation of `keyrings.alt` which is the declared dependency AFAIK.  Also I would recommend to run tests as `python -m nose` not via `nosetests` since it might be using different python/environment.
3. run with `DATALAD_TESTS_NONETWORK=1` env var
4. I think that is it. Always can consult debian packaging dependencies: https://github.com/datalad/datalad/blob/debian/debian/control#L84

**Comment by mih** [comment]
> Is there a way to only run the test suite for core functionality?

I tend to do:

```sh
python -m nose -s -v datalad.core
```

**Comment by TheChymera** [comment]
thank you, this worked :)
