### ISSUE TITLE
Info: datalad is now also avaliable via spack package manager

### ISSUE THREAD

**Issue by manuelakuhn** [datalad/datalad#6040]
I wanted to let you know that I have built `datalad` packages for the [spack package manager](https://spack.io/), making installations as ​simple as:
```
$ git clone https://github.com/spack/spack.git
$ . spack/share/spack/setup-env.sh
$ spack install py-datalad
```
or
```
$ spack install py-datalad@0.14.6
```
to install an older version. ​This will also install git-annex as a dependency.

To use it:
```
$ spack load py-datalad
```

datalad packages available in spack so far:
- `py-datalad`
- `py-datalad-container`
- `py-datalad-hirni`
- `py-datalad-metalad`
- `py-datalad-neuroimaging`
- `py-datalad-webapp`

**Comment by mih** [comment]
Wonderful! Thx much! I am not familiar with spack yet. But it looks like as if there is nothing to do in order to keep these packages up-to-date, correct?

**Comment by manuelakuhn** [comment]
Not quite, by default spack only installs trusted downloads. That means that for new versions the correct checksum has to be known. If there are no dependency changes for a package this is just a one-liner, like
```
version('0.15.1', sha256='0a905b3c3419786ae85b61a7aee34b0fc9eecd814f38408f2767ae7122b57a8b')
``` 
If dependencies change these have to be integrated.  

The spack people are usually quite fast with checking and merging pull requests, so that helps as well.

**Comment by mih** [comment]
OK, thanks the explanation.

What is the process behind determining this shasum? I am asking because ultimately we need to decide how to act on the fact that DataLad is listed there. If we decide to advertise this (e.g. in the handbook) we need to have a QA process attached to this venue that ensures that new releases make it there. Do you see yourself maintaining this listing for the foreseeable future?

**Comment by mih** [comment]
I have tagged this issue FOI, and will close now. It seems there is nothing we need to act on here.
