### ISSUE TITLE
Formulate explicit ROADMAP

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6247]
This topic came up so many times over the past weeks that I believe we should have a something written here. We had several discussion in the topic of an upcoming "1.0" release, but I believe such a document should describe an even broader characterization of what we are aiming for in the long run.

I propose to start collection aspects here, and I will then volunteer to put together a document for the docs, which can then also be linked from the website.

**Comment by adswa** [comment]
This is a very utopian wish/aim, but I would like to link (main) DataLad documentation/user tutorials closer to the source code in the spirit of [documentation driven development](https://gist.github.com/zsup/9434452).
The most important points for me include:
- A feature essentially only exists if it is documented, so we document everything
- Unit tests that check for the functionality that is documented. If features or workflows break, tests should fail immediately, and either the documentation and tests, or the code change needs to be revisited
- Documentation and source code releases are completely linked and versioned. The documentation should have a version switch to provide a documentation version that matches ones software version. Documentation and software features shouldn't get out of alignment.

I think the current state of things isn't too bad (I'm currently writing a companion issue in the handbook), but there is a lot of room for improvement, still. My personal role model is [mne-python](https://mne.tools/dev/index.html), which links source code and user-focused walk-throughs very well.

**Comment by adswa** [comment]
Oh, I would also like to propose or at least start a discussion on adapting a practice of adding version notes to new commands or parameters - similar to how numpy does it (``added in version 0.16.4``). This would improve user experience and help to prevent confusion when one wants to use an old version of datalad with current documented workflows. I feel like adopting this practice makes a lot of sense after a future big release.

**Comment by mih** [comment]
I am in favor of starting this practice now. It boils to using the sphinx directives `versionadded`, `versionchanged`, and `deprecated` in the docstrings.

**Comment by adswa** [comment]
First item from today's discussion:

@jbpoline and @surchs brainstorm about meta data related functionalities that could assist in their usecase: @surchs provided a cool demonstrations of their Cohort Definition Tool. It is querying OpenNeuro + a parkinson DB based on age ranges, genders, modalities, diagnosis, whether or not one is a control subject, and Parkinson specific instruments like MOCA, UPDRS, or MMSE, and generates a list of matching subjects across queried datasets. The query is solely based on metadata, and no actual data content is involved and for certain datasets also not publicly available. Because the datasets are not always BIDSified or have standardized metadata fields, annotations are harmonized/enhanced with bids2nidm. They aim for a minimal set of metadata tuned to specific usecases (e.g., Parkinson-usecase with basic demographic information and a few assessment tools). The foundation of the tool is a graph data base. At the moment, a "download" after a successful query provides users with a CSV file with metadata information about individual subjects and information in which datasets they can be found. A useful addition for them would be that the query returned "something even more exciting". The best solution for their usecase would be an "additional field in the CSV with a DataLad-URL from which to obtain the file". 

How could be DataLad be helpful? How can we collaborate? General thoughts in the discussion? How does it fit into the DataLad Roadmap?

- @mih mentions that this field would need to store a bunch of additional information (everything relevant to parametrize a git annex call), but we discussed the potential for datalad-metalad/datalad-catalogue output of file-level descriptions with information their tool could ingest.
- DataLad should try to understand and support the Cohort Definition Tool data representation by writing a datalad metadata extractor. It could perform or assist in the metadata harmonization/standardization that the Cohort Definition Tool performs in the case of updated datasets. @mih discusses how the new metalad concept is less datalad-centric and more centralized, which could be useful in that context, and how ingesting this ability could assist the datalad catalogue in the future. The current process of standardization is somewhat "hard-coded" on a per dataset level (some fields (gender, age) can be automatically harmonized, other fields (diagnosis) need more manual work) as a mapping - once it exists, the mapping can be used to redo a standardization, but it doesn't necessarily work on a different dataset. Ideally, data providers contribute this knowledge/the manual annotation effort in some way, incentivized by the resulting greater visibility and usability of the data.
- It would be cool to contribute back/expose the improvements obtained via the annotation/harmonization effort
- general consensus was that the Cohort Definition Tool and the dataset catalogue project are similar in spirit, and additional meetings with @christian-monch and @jsheunis would be useful (sometime in Jan)


(please add and correct what I have missed or butchered up)

**Comment by adswa** [comment]
@yarikoptic demonstrates datalad-fuse which can become useful in the context of metadata, too. 
The idea is to have a locally installed superdataset (file content does not need to be retrieved) and bindmount it somewhere, and then be able to access those files without having their content. ``fsspec`` is used to interface the remote files by their url. The result is a "Git worktree with sparse files (unless they are fetched in full)". This works with all files that are accessible via ``http``, and support for ``ssh`` is planned.

Example call with local datalad superdataset: 
```
$ datalad fusefs -f -d ~/datalad /mnt/datalad
$ cd /mnt/datalad
$ ls -lr
<looks like a normal git worktree, lacks a .git directory>
``` 
This sparse mount can show every installed dataset in that directory, it can show the file size extracted from the annex key. It can then be browsed fast without downloading data content. In the demo, a multi-GB file consumes only 6MB of space in a cache (from nifti headers) for a ``nib-ls``.



Roadmap items
- How can datalad-fuse work together with metalad? The difficulty lies in the ``.git`` directory in the mounted dataset being hidden.
- At the moment, bare repositories are not supported, but it may be a useful addition.

maybe @yarikoptic can link the issues created during the call

**Comment by adswa** [comment]
I'm not sure if this issue still serves a meaningful purpose - we used it to document a couple of meeting notes, but it seems to me that a proper roadmap to a 1.0 release never really emerged. Since this issue was first created:
-  there were some changes in the larger datalad ecosystem, for example the ``datalad-next`` extension or runtime patches in core from extension #6642 that have the potential to change future development strategies
- quite some internal talk on the future of DataLad core that boiled down to robustifying, shrinking, and improving maintainability of core while outsourcing more developments to extensions. CodeClimate reports were enabled with the intention of progressing this internal aim. 
- With regard to maintenance, #6365 created some rough "team" assignments for internal coordination of responsibilities. I still like the idea, although I would say that there wasn't much longterm improvement from that issue - maybe more visible exposure of this information brings an initial surge in PRs and issues fixes back.

Shall we take another try at formulating a 1.0 roadmap in this issue, @datalad/developers?

**Comment by yarikoptic** [comment]
I don't think overthinking of what 1.0 should be would get us to 1.0.  To me 1.0 is just a version upon which we would start to be *even more* careful about *not* breaking API, and do have sensible .MINOR (stuff added) and .PATCH versions.  `maint` would track the .MINOR.PATCH and `master` could as well be our jumping through `MAJOR.`. That would also allow us to come up with more pragmatic ROADMAPs for the next `MAJOR.`.

So, what about 1.0.0 to follow current 0.17.0 and we concentrate on a short-vision ROADMAP for the next few months?  or we will just can this discussion until similar-to-arbitrarily-identical moment in the future? (e.g. to celebration of the 10th anniversary of DataLad project in less than a year on May 21 2023 ;) )

**Comment by adswa** [comment]
I found #4585 (again), and scanned it for content not included in this attempt at a ROADMAP. Since this issue is the most recent ROADMAP I'm aware of, I am in favor of recording everything relevant from that issue here, and then closing the older one.


The discussion in #4585 centered around the ``.core`` and ``.coreapi`` commands of datalad, which at the point in time were deemed too plentiful, and currently contain
```py
import datalad.coreapi as dlcore;
 print([x for x in dir(dlcore) if not x.startswith("_")])
['Dataset', 'add_archive_content', 'add_readme', 'addurls', 
'check_dates', 'clean', 'clone', 'configuration', 'copy_file', 'create',
 'create_sibling', 'create_sibling_gin', 'create_sibling_gitea', 
'create_sibling_github', 'create_sibling_gitlab', 
'create_sibling_gogs', 'create_sibling_ria', 'create_test_dataset',
 'diff', 'download_url', 'drop', 'export_archive', 'export_archive_ora',
 'export_to_figshare', 'foreach_dataset', 
'get', 'install', 'no_annex', 'push', 'remove', 'rerun', 'run', 
'run_procedure', 'save', 'shell_completion', 'siblings', 'sshrun', 
'status', 'subdatasets', 'uninstall', 'unlock', 'update', 'wtf']
```

They still contain some corpses, such as ``sshrun`` (ref #4593). @yarikoptic said:

>  I also agree it would be a good thing in general, but I would not make it an ultimate goal for 1.0 -- would delay it etc.  I think providing a release with at least limited promise such that `.core` and `.coreapi` are stable and have no corpses would already be very valuable. It would be ok with me to have some corpses outside (in `.support` etc) if that would minimize breakage of externals etc. 

Both #4585 and https://github.com/datalad/datalad/issues/4590 concluded that there could be value in shrinking the ``.coreapi`` of DataLad to an agreed upon subset of stable commands.

**Comment by adswa** [comment]
Linking #6366

**Comment by adswa** [comment]
well, this issue is two years old, and it hasn't seen many updates since. I've attached an for-our-information issue so that we can find it if needed, and I will close it now
