### ISSUE TITLE
`ConfigManager` cannot handle bare repo's (dataset/branch config)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6264]
It uses the path `.datalad/config` to check for the presence of a config, rather than something like `--blob`. More specifically `HEAD:.datalad/config`, which works with bare and non-bare repos.

The critical question here is how to deal with uncommitted config files. So far this was completely ignored. Any modification was immediately effective. It would probably be necessary to retain this behavior for non-bare repos -- but worth keeping in mind.

**Comment by bpoldrack** [comment]
> The critical question here is how to deal with uncommitted config files.

I agree, that it's ignored so far (as opposed to be a conscious decision) and that we'll need to retain this behavior in the non-bare case at least for some time.
I am not sure what to aim for, though. On the one hand, the point of `.datalad/config` is to be a committed config. So, issuing a warning on `ConfigManager`'s initial read (not reload) in case of uncommitted changes seems in order from that point of view (but questionable re performance). May be better on `push`, though.


Not sure whether to aim for only considering committed configs in the long run, though. I think not. I am working on the worktree when I work with a repository. What about uncommitted changes to registered procedures, containers, etc.? I think we'd want to operate on the state of the worktree rather than `HEAD`.
