### ISSUE TITLE
Resolving dataset for toplevel functions in a consistent way

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#631]
This is about API consistency and logic.

Most `datalad` commands have a `dataset` parameter and `path` parameter(s). In case no `dataset` was given to operate on, former implementations used to try to derive the required `Dataset` instance from the `path` argument or CWD. While it is useful to derive needed subdatasets from passed paths, I think we should fail, if there is no dataset to start with. That way it is always clear, that any of these functions need to operate on a dataset and this is determined always the same way. For the cmdline, this means, that any datalad command will fail, if CWD is not inside a dataset and neither `-d` nor `-C` is used. Basically just like git itself.
The issue rises from things like this:

    /no/dataset$> datalad add path/into/ds/file-to-add.dat

We could do the magic to detect the dataset at `/no/dataset/path/into/ds`, but I don't think we should.
Nevertheless, once we are in a dataset, possibly needed subdatasets will still be derived from the paths.

Note: `-d` might disappear from cmdline as we thought about elsewhere, but that doesn't change anything regarding this topic, I think.

Do we agree on this, @yarikoptic , @hanke ? Any clarification required?

**Comment by yarikoptic** [comment]
sounds reasonable, especially since it is inline with git/git-annex "mode of operation" IIRC.  BUT if someone has looked/expressed himself about DataLadRIs (https://github.com/datalad/datalad/issues/589) idea/handling, it might benefit.  E.g. in case if we would allow users to specify explicitly to operate on the centralized installation.... But actually, having slept on it, may be we could just add e.g. `-g` (global? or `-u` for `user`?) or some other option which would dictate that the DataLadRI/path we are talking is intended for the global dataset -- pretty much a shortcut to `-d ~/.datalad` ?

**Comment by bpoldrack** [comment]
Yes, we could have a dedicated option for that or just not hide the `-d`. I just don't want to operate on a dataset, that the user might not be aware of and avoid inconsistent or incomprehensible API.

**Comment by mih** [comment]
I think we have it fairly consistent now, #813 being the last one on my radar (before heading to publish). As there is a dedicated milestone, I will close this now and we can continue to use the former to track any further/future issues.
