### ISSUE TITLE
Discussion: Changelog generation

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6388]
At the moment, releases are automated. As a part of the release workflow, the CHANGELOG is generated automatically based on PR tags and PR titles.
There is a recurring discussion in the devcall whether or not these CHANGELOGs are sufficiently readable, because PR titles are limited in length and do not always convey the true effect of a PR in a release. The core discussion seems to circle around the trade-off between substantial manual work to create a CHANGELOG prior to a release and the descreased CHANGELOG value when relying purely on automation. 

In our chat, I proposed an alternative I have seen many projects use successfully - a contributing workflow in which each PR is accompanied with a CHANGELOG entry by the respective author. This would relieve the amount of work that needs to go into the CHANGELOG prior to a release (it would continuously grow and be almost ready before a release), and would also ensure that the description in the CHANGELOG is the most accurate it can be because respective author of the change generates it themselves. 
The ``auto`` [docs](https://intuit.github.io/auto/docs) seem to support disabling automatic changelog generation but keeping the rest of the release in case someone wonders about the technical feasibility.

Can we maybe vote (:+1: , :-1: , or :eyes: for indifference) on this or discuss it in comments?

**Comment by yarikoptic** [comment]
> In our chat, I proposed an alternative I have seen many projects use successfully...

do you have examples of the projects?  I am aware of sympy, see e.g. https://github.com/sympy/sympy/pull/22970 but judging from https://github.com/sympy/sympy/blob/c551e00961d47e6e9544fcaf1691764eb9932207/release/github_release.py#L120 it seems that it is not a fully automated process although it might be since the "release" helper is there (and quite sizeable): https://github.com/sympy/sympy/blob/3de9a69f142f2e714e1bff936856a2e52ab701b5/release/fabfile.py

**Comment by adswa** [comment]
``mne-python`` (https://mne.tools/dev/install/contributing.html#describe-your-changes-in-the-changelog) and `autoreject` (https://autoreject.github.io/stable/whats_new.html) do this (I only know because I contributed, and part of the PR needs to be a Changelog entry). This isn't as automated as the Simpy bot, its just a social convention or rule in PR templates and contributing guidelines, enforced by PR reviewers. "LGTM, but please add a CHANGELOG entry" etc. I think it can become a habit easily.

**Comment by yarikoptic** [comment]
I am all for adding extra annotation by PR authors to the PRs. But my main concern would be that for patch releases, changelog for which typically to consist of minor notices of what was fixed etc, the necessity to assemble CHANGELOG entries would re-introduce additional burden to cut a release thus delaying them.  I really got spoiled by `auto`'s automation of releases in the projects where we have it.  I rarely read CHANGELOGs in general, but whenever I did, forced to be short PR titles with convenient groupping was enough to pin point specific issue/PR to look into further.  For minor/major releases indeed 1 sentence titles, and frequently "complimentary" PRs (one PR adds a feature, subsequent ones fix it up more before release) require more elaborate setups and/or manual intervention.  So may be we could also "pair" the idea of Release notes and `auto` that whenever possible, PR title should correspond to Release notes statement?  That would allow for rapid releases of patch releases with `auto` and provide content to compile while preparing minor/major release CHANGELOGs?

**Comment by adswa** [comment]
> But my main concern would be that for patch releases, changelog for which typically to consist of minor notices of what was fixed etc, the necessity to assemble CHANGELOG entries would re-introduce additional burden to cut a release thus delaying them.

Maybe I'm misunderstanding something, but this "workflow" would prevent exactly this need to assemble CHANGELOG entries, in my opinion. Any PR against ``maint`` adds a CHANGELOG entry for the next patch release. Any PR against ``master`` adds a CHANGELOG entry for the next upcoming minor release. Whatever we release, the CHANGELOG has grown with each PR and is complete at the time of the release, lacking only a placeholder for next release to collect future PRs. The only minor inconvenience I see would maybe lie in CHANGELOG conflicts when maint is merged into master, but those are trivial to resolve, and CHANGELOG conflicts when a PR is rebased from one branch to the other, which should also be resolveable. We could write a GitHub workflow that checks whether a PR includes a change to the CHANGELOG, similar to how the semver check reminds us to tag a PR. This seems to be how scikit learn is doing it, apparently: https://github.com/scikit-learn/scikit-learn/actions/runs/478579518/workflow

**Comment by yarikoptic** [comment]
oh -- I guess I have just missed that we will have automation which would be adding those Release notes from PR descriptions into resultant CHANGELOG.  What automation would do that exactly and what would be approach?  

*CHANGELOG.md entries are added within PR diff?*: looking at scikit -- sample PR https://github.com/scikit-learn/scikit-learn/pull/22328/files -- can't find changes to changelog, but it is green... dunno...  oh -- found one  https://github.com/scikit-learn/scikit-learn/pull/22285/files -- so the idea is to edit CHANGELOG directly in the PR and add the corresponding record to it.  We had (might still have) the same approach in fail2ban. problem comes in merge conflicts whenever PRs adding to the same section of changelog.  The easiest is to add a changelog entry right before merging, but that requires yet another long run of CI (well, may be could be skipped), and in general "slows DX".  

*CHANGELOG.md entries are added **after** PR is merged?* Because of the aforementioned shortcomings,  having changelog entries in titles and/or descriptions is IMHO better.  But we need something to collate/inject them into CHANGELOG.md - and then question "when" to do that?  `auto` does it at release step, but could be done on CRON or after merge of each PR.

FWIW -- merge conflicts from `maint` to `master` indeed a nobrainer and ok to live with ;)

**Comment by mih** [comment]
From my POV the automation aspect is a side show. The changelogs of auto-generated releases are nothing more than link farms to pull-requests and issues. The additional text is almost a distraction, because to get any idea what happened, one needs to visit GitHub -- let's pray that they will like us and live forever!

Automated or not, I will continue to flag PRs that carry no hand-crafted changelog entries. I am OK that there is pressure to have releases be quick, and I am OK that patch releases always come with shitty changelogs. But having real changelog snippets provided, turns assembling a proper (post-hoc) changelog into a rather feasible task. I continue to consult the changelog more than the git-log whenever I want to get a sense of high-level or strategic changes/decisions.

**Comment by mih** [comment]
I think this is going nicely now. Thx for making it happen!
