### ISSUE TITLE
a multithreaded walk function to speed up local file operations

### ISSUE THREAD

**Issue by satra** [datalad/datalad#6419]
we are investigating some performance issues on a parallel file system for dandi, and came across [this gist](https://gist.github.com/jart/0a71cde3ca7261f77080a3625a21672b), which provides a multi-threaded operant on the filesystem. i forked and just updated a few things for python 3 and made [a version that also does digesting](https://gist.github.com/satra/0e02cd7554672120cf8073df3986f302) to simply check performance. the fscacher version of this took a couple of hours, this took 15 mins on a particular tree of 263k files (about 100KB each) on about 20 threads (this machine has 112 hyperthreaded cores).

perhaps this can help with some of the datalad operations. 

i will probably be comparing this with asyncio as well, but out of the box, that tiny walk function was very performant.

**Comment by bpoldrack** [comment]
Thanks, @satra!

I think we'd have to adjust further to use `pathlib` instead of `os.path`, since we are trying to switch entirely for way better cross-platform support, but otherwise that should be useful!

**Comment by yarikoptic** [comment]
IIRC @mih mentioned that we do not really traverse filesystem ourselves, and rely on `git` commands for that.  I see `os.walk` and `find_files` used only in tests and "archives" module... may be could be of benefit there but would not be of drastic contribution. As such I guess we could just let this issue RiP since I do not see where we could take advantage at datalad level from multithreaded walk. But if someone sees where -- feel more than welcome to reopen!
