### ISSUE TITLE
Shall we add capability to process all output of sub processes in `BatchedCommand`?

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#6444]
### What is the problem?

The BatchedCommand implementation is structured around line-based output from the subprocesses. Due to this fact, there might be unprocessed output (output that does not contain line-endings) when the command is closed. There might in addition be output that is emitted after stdin to the subprocess is closed.

This output is currently not processed, for example in calls to `git annex registerurl --batch`. Although this fact does currently not imped the execution of batched commands, we might want to do something about the situation. E.g. allow processing of unterminated output and of output that was generated after closing a command's stdin. There are three reasons:

1. It might help us to detect changes or unexpected behavior in commands
2. It might become necessary to do this in future commands
3. It seems prudent to be able to handle all output-behavior of sub-processes.

On the other hand: if we will only use BatchedCommand to invoke `git` and `git-annex` in batch-mode, usually with JSON-protocol, there might be no need for action. Also, the exit code should inform us about errors in the batched command. 

### What steps will reproduce the problem?

```python
import logging

from datalad.cmd import BatchedCommand


logger = logging.getLogger("datalad")
logger.setLevel(logging.DEBUG)

dataset_path = "<path to annexed dataset>"
key = "<a key of a file in the annex of dataset at dataset_path>"

bc = BatchedCommand(
    cmd=["git-annex", "registerurl", "--batch"],
    path=dataset_path,
    output_proc=lambda _: None
)

# register some web location
bc(f"{key} http://www.example.org/file")
bc.close()
```

This script will log a debug message showing the unprocessed, i.e. remaining, content:

`[DEBUG] BatchedCommand(...): remaining content: ['registerurl stdin ok', '(recording state in git...)']`

**Comment by yarikoptic** [comment]
ref: issue which inspired this one AFAIK https://github.com/datalad/datalad/issues/6431 .

> 3. It seems prudent to be able to handle all output-behavior of sub-processes.

I would say so too! But the problem is that I don't see a generic robust solution to the problem of "detecting git-annex finish to produce full output we expect to receive"  unless it is terminated by some character (e.g. classically by an EOL).  So, if it was not `registerurl` where we don't care about output from git-annex really, and we expected confirmation from git-annex on the result, we can't rely on simply waiting for stopping that process to get remaining content processed.

That is why, I think, it is ok to leave BatchedCommand as is and seek to fix up/enhance git-annex in making specific interfaces behave consistently (EOL to separate outputs) and also preferably in "machine readable" serialization (i.e. `--json` option for all `git annex` commands).  Any other annex command besides `registerurl` we might need to raise an issue about? (for register url it was already [done](https://git-annex.branchable.com/todo/--json_for_registerurl/))

**Comment by christian-monch** [comment]
> any other annex command besides registerurl we might need to raise an issue about?

I am not aware of all the annex commands we use, so I cannot answer the question properly without digging into it. Any ideas @bpoldrack or @mih?
