### ISSUE TITLE
Redesign credential system

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6519]
`[The top post is repeatedly updated in response to comments below]`

### Problem
The current credential subsystem is tightly coupled to "providers" and consequently mostly targeting "downloads". However, since its inception other uses of credentials were needed (API tokens, etc), and support for those was bolted onto this system, yielding the present state.

One key problem is that we do not know which credentials are know/necessary until a particular credential request is made. This is a limitation of the `keyring` system that underlies our credential setup, and it used as its main (only) data store. Not knowing which credentials exist (because of a lack of identifiers), prevent associating additional information with a credential, such as a priority (#322), and complicates/prevents credential maintenance (update, removal).

The "provider" concept amends the credential store with a configuration file that is used to associated additional information with a credential (but actually in reverse, it associates a credential with a download scenario). I believe we could improve the design by making these systems more or fully separate. A credential can be used in more than one scenario. It requires a dedicated API for query and manipulation (#396).

### Proposal

It would make sense to me to start using the configuration mechanism as the main registry for credentials too. It would provide the complete list of credentials known to datalad. It would be the place to annotate credentials with additional aspects, such as scope (e.g. URL regex), priority, expiration date, and linkage to credential storage subsystems.

http://docs.datalad.org/en/stable/design/credentials.html already defines the config variable setup

   `datalad.credential.<name>.<component>`

only that `component` would no longer be limited to `token`, `username`, `password`, but could be amended with `priority`, `expiration`, etc. as needed.

*On top* of what is defined in the configuration, a management API could list credential names and types known to the provider subsystem. On accessing any unknown credential in any backend, the management layer would leave a trace about a new credential in the config, such that any custom credential becomes accessible over time.

Looking at actual credentials in my local credential store, here are a few properties to consider:

- description
- type (token, password, ...)
- secret (the piece that needs protection)
- username/identity (whatever would be necessary in addition to the secret)
- usage cateory (login, ...)
- date created/synced
- realm (some label to identify a matching credential)
- times-used, last-used
- action-url (location to use it with)
- original-url (location/service that provided it)

Beyond the basic secret, all other properties could be useful for making decisions on what credential is applicable or matches in a particular context. Only a user of the credential system can know what makes sense in the general case. The credential system should ease flexible queries, but make no decisions.

The ability for users to indicate which credential should be used will be a crucial feature. We need `name` from  `datalad.credential.<name>.<component>` already to bind properties from secret storage and config mechanism, so this will be a given identification method. It is largely identical to the value semantics of the various `--credential` arguments, and is similar to what secretstorage calls "label".

Moreover, it makes sense to support other (generic) specifications like a realm. This could conceptually replace the direct specification of a single credential label in a provider configuration. Something like `s3_hcp` could be a realm that several credentials are associated with (think: I know multiple credential sets, maybe one read-only, and one for admin-access, different gihub tokens, etc.). This would make it possible to better separate the user-defined namespace of credential labels from datalad-provider defined credential scopes. A default for a `--credential` argument of a command that interacts with the github API could be `realm:github-api`, and would automatically find a suitable credential. If there is only one, everything is fine. If there are multiple ones, a user can identify a precise one via a label.

### API

The primary (possibly only) API to interact with the credential system is a dedicated `credentials` command (plural name to follow established pattern: `subdatasets`, `containers-run`, `siblings`, `osf_credentials`). It implements the following operations:

- `set <name> <spec>`
- `get <name> [type=...]`
- `remove <name> [type=...]`
- `query [<spec>]`

where `<name>` is a unique identifier/label, and `<spec>` are key-value pairs that annotate a credential. For `set` the `<spec>` are a complete list of all credential properties, for `query` it is a list that any matching credential must have. For maximum usability, multiple formats for specifying `<spec>` will be supported (Python iterable, k/v-pairs like `configuration`, JSON-formatted string). Property names must be valid Git-config variable names. They are used for the `<component>` slot in the `datalad.credential.<name>.<component>` naming convention, whereas `<name>` is used as `<name>`.

The API does not define a finite list of credential types (token, user-pass, etc). The type is merely a property. For reasons of backward compatibility only, `get` supports a type-hint specification using the same syntax as `<spec>` (see below).

The number and identify of properties is not limited.

Each credential has a single secret. Its value is not constrained to a particular nature. An additional credential property could (optionally) signal different types of encodings (e.g., a multi-part credential encoded as a JSON-array/object). If a secret is not part of the `<spec>` given to `set`, interactive secret entry is performed. Secret always go into whatever the available/active secret store is for a particular installation.

`remove` is used to wipe out an entire credential with all its properties.

In order to modify or remove individual properties of a credential, `set` is used while specifying only the key, and no value (in case of removing a property), or an alternative value (for a modification of a property). In Python, "no value" can be `None` (as a non-string value), for a CLI call the equivalent could be `:key`  (followed by no `=` and no value, akin to deleting a remote refspec with git-push). An alternative CLI notation could be just a key name (no prefix), but this might cause more accidents (e.g. unintentional whitespace between key and `=<value>` etc.).

##### Set a credential
`credentials set mycred username=mike` will ask for secret interactively.

`credentials set mycred username=mike secret=precious` will not ask for secret interactively.

`-c datalad.credential.mycred.secret=precious credentials set mycred username=mike` will also not ask for secret interactively.

##### Update a credential

`credentials set mycred :secret` will delete a previously defined secret, and because afterwards there is none defined, we ask for a new one interactively.

`credentials set mycred secret=update` will replace a previously defined secret, non-interactively.

`-c datalad.credential.mycred.secret=precious credentials set mycred :secret` will also delete a previously defined secret, but because there is one provided via cfg, will not ask interactively.

##### Remove a credential entirely

`credentials remove mycred`

##### Find credential candidates

`credential query 'realm=http://api.github.com'` report all credentials for the given realm. Credentials are yielded as results, with all their properties. Client code can decide which one to use, if there are many, e.g. by `last-used` timestamp, etc.

### Implementation details

Given that credentials are typically personal information, non-secret information is put into the `global` configuration scope (i.e. user-config), whenever no alternative implementation is available. Secrets are always stored in and retrieved from a secret store (via `keyring`). On systems where alternative implementations are available (e.g. `secretstorage` in the future), secrets *and* additional properties can be placed together in a secret store.

`get` and `remove` can be given a credential `type` hint, in order to be able to retrieve and delete credentials stored by the previous credential system, where type-information is only available within the context of a credential request.

**Comment by bpoldrack** [comment]
I'd like to add a couple of aspects.

- We now have an interface to the `git credential` system. In Git credentials don't exist on their own but only in a particular context (a git url matching pattern). Thus a git credential is actually more the equivalent of our current providers (with linked credential). Other systems that we may want to interface in the future may behave similarly. A refactoring should account for this.
- We currently somewhat "abuse" the keyring as a key-value store resulting in different entries for username/password. Furthermore, we insist on special names to be used (prefix `datalad_`). For those reasons we can not simply use/link existing credentials in someone's keyring unless they were put there exclusively for datalad and with that technical knowledge. We should be able to use any credentials that were put there by other means.

Those aspects are relevant even for just changing the way things are specified, because we need to get it conceptually right what is a credential and what is(are) the context it is used for. This relates to

>  a management API could list credential names and types known to the provider subsystem.

The experience with `git credential` makes me think, that the correct top-level entity to deal with, is the context (provider), not the mere credential. This relates to some refactoring needed, since we fail to ask the correct question at the correct time and the correct spot (it makes no sense to query anything for credentials w/o knowing the context/URL we want to use it with). That leads to several issues, where we can't correctly deal with redirects or send credentials where they aren't needed, etc. (provider/credential is determined before we even know authentication is required and what exact URL with)

What currently is specified in provider config files should migrate to the general config mechanism (that didn't exist when most of this was written) - I absolutely agree.

**Comment by mih** [comment]
> A refactoring should account for this (git credential)

Maybe you could add some more info on what you think must be done. To me the git-credential system is *exactly* like the provider setup -- lookup by location.

But when I have datasets on three different account on google drive this kind of lookup does not work, hence it cannot be "the way".

> we need to get it conceptually right what is a credential and what is(are) the context it is used for

Is that true? I can instruct any functionality to use a particular credential for authentication. The credential is what it is regardless of what service it is being used with.

> it makes no sense to query anything for credentials w/o knowing the context/URL we want to use it with

We have a number of commands that take explicit credential identifiers without a user knowing what "location" they will be used with. I personally use SSO credentials in all kinds of places, and thanks to the location-based setup I have it duplicated all over the place. It is an immense pleasure each time the duplicates need to be updated, location by location. I would not want to get behind "makes no sense".

**Comment by bpoldrack** [comment]
> Maybe you could add some more info on what you think must be done. To me the git-credential system is exactly like the provider setup -- lookup by location.

Yes, it is at the same level, although providers have more properties (like authentication method for example). We cannot currently map `git credential` into our system frictionless. Providers have no type, no backend, they can link credentials only ba name and so on. Something like this would be needed. And when switching to get rid of provider configs altogether (migrating to proper datalad configs) I'd want to include some RF'ing in that regard so, that the `git`-type credential can be thrown out again and replaced by something better fitting, rather than taking that along with that migration.

> I can instruct any functionality to use a particular credential for authentication. 

Yes, and with that you have a context that the credential is used with. I don't mean to restrict context to only mean "a particular URL". That's why I try to use a different word to not imply that I am convinced providers need to stay as they are. The dataset we are operating on also provides a context (and one that becomes necessary for config lookup - providers have no good idea of that yet).

> The credential is what it is regardless of what service it is being used with.

Yes. It should remain its own thing that is linked by context. The linkage doesn't necessarily have to be via a URL - I agree. Telling a particular command to use a credential by name is fine. The system I imagine would simply respond with that credential when asked by the command to provide some for its context. I just think that the general approach should be: An internal call to the "credential management API" should query for credentials to use based on what they are used for (URL, dataset, special remote, you name it).

> We have a number of commands that take explicit credential identifiers without a user knowing what "location" they will be used with.

I didn't mean to imply the user always has to specify some sort of URL. The credential is still tied to something specific that it is used with. It's not "here datalad, I give you bunch of credentials send them to whoever asks for credentials, no matter what you are doing and whom you are talking to"

**Comment by bpoldrack** [comment]
> But when I have datasets on three different account on google drive this kind of lookup does not work, hence it cannot be "the way".

Yes, the dataset needs to be part of the context. I introduced that with a `set_context(ds, url)` to the `Credential` classes, but I think either the providers need to be enhanced to include that or we need an additional representation of context and cut down providers a bit. Not completely sure yet - trying to work that out. The way I did it has to remain an intermediate step, I think. And when we transition to proper datalad configs I just want to think that kind of thing alongside, to have the structure of those configs not become something that possibly conflicts with ow we need to represent things internally.

**Comment by mih** [comment]
I think I found the root of our difference:

> An internal call to the "credential management API" should query for credentials to use based on what they are used for

For me this would be:

An internal call to the "credential management API" should request a credential to use, after its ID was already determined based on what it needs to be used for

The credential system is about credentials, not about what credentials are used for. The fact that there is no clear separation between these two aspects, is the problem of the current system.

That being said, I see no problem in annotating credentials with information like "scope", or "applicability", or matching URLs, or anything really. The credential system could report any and all of such annotations, and other systems can request them. I don't think this is critical, or even unique (just check how many properties a browser stores for any credential). But it is critical what minimum information must exist in order to define and query a credential -- and a believe that a context is not one of them.

**Comment by bpoldrack** [comment]
> The credential system is about credentials, not about what credentials are used for. The fact that there is no clear separation between these two aspects, is the problem of the current system.

Agree.

> An internal call to the "credential management API" should request a credential to use, after its ID was already determined based on what it needs to be used for

I see. Ok.
With the edited OP things are clearer for me. I see no conflict with what I am concerned with.

**Comment by mih** [comment]
There is a new credential subsystem with a `credential`command available now from the https://github.com/datalad/datalad-next extension. Advanced features, such as query credential by authentication realm and used in additional commands provides/patched by the extension.

There is no value in keeping this issue open any further.
