### ISSUE TITLE
git annex (now?) distrusts datalad special remote to handle s3:// urls

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6680]
Example repo: http://github.com/jdkent/ds000001

```
(git-annex)lena:/tmp/ds000001[add/fmriprep]git-annex
$> git annex get **/sub-09_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
get derivatives/fmriprep/sub-09/anat/sub-09_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz (from datalad...) 
  Getting URL keys with this remote is not secure; the content cannot be verified to be correct. (Use annex.security.allow-unverified-downloads to bypass this safety check.)

  Unable to access these remotes: datalad

  No other repository is known to contain the file.

  (Note that these git remotes have annex-ignore set: origin)
failed
get: 1 failed
```

# WTF
- datalad: version=0.16.2+146.g9cec945af
- dependencies: cmd:git=2.35.1 cmd:annex=8.20211123 cmd:bundled-git=UNKNOWN cmd:system-git=2.35.1 cmd:system-ssh=9.0p1 cmd:7z=16.02 annexremote=1.5.0 platformdirs=2.5.0 boto=2.49.0 exifread=2.3.2 humanize=3.14.0 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 mutagen=1.45.1 requests=2.27.1

**Comment by jdkent** [comment]
another potential factor could be how I added the data, I used the `--fast` option when using `addurls`, ex:

```
datalad addurls --fast .datalad/urls.txt '{url}' 'derivatives/{destination}'
```
[from this branch](https://github.com/jdkent/ds000001/tree/try/datalad_crawl)

**Comment by mih** [comment]
Using the fast switch would cause annex to use the URL key backend (it never saw the file content, and could never determine a checksum). This explains the situation, indeed.

**Comment by mih** [comment]
From my POV, there is nothing to be done here from a datalad perspective.

**Comment by bpoldrack** [comment]
While I agree, that this is not new behavior on annex' end and caused by `--fast`, I am not sure, datalad shouldn't do anything.

One thing would be a more general shortcoming:

`git -c annex.security.allow-unverified-downloads=ACKTHPPT annex get **/sub-09_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz` works, but `datalad -c annex.security.allow-unverified-downloads=true get **/sub-09_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz` doesn't, since the config isn't passed on.

Another would be documentation on what `--fast` implies and how to deal with that. Doc for `addurls` only points to `git annex addurl --fast`, and the man page of `git annex addurl` isn't helpful in that regard.

**Comment by yarikoptic** [comment]
I agree that it is a matter of documentation. Smells like I've of those "hints" situations to provide feedback on best/better practices
