### ISSUE TITLE
test_ro_operations might need changes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6708]
That test was primarily to ensure that basic operations such as `annex get` which does not need to get anything (content is already here) or `annex info` etc could operate without crashing.

OSX builds of git-annex started to fail recently due to that test.  Exception tail

```
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c annex.merge-annex-branches=false annex find --not --in . --json --json-error-messages -c annex.dotfiles=true -- file1' failed with exitcode 1 under /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_tree_test_ro_operationsokdcb__s/clone [info keys: stdout_json] [err: 'git-annex: Git refuses to operate in this repository,
probably because it is owned by someone else.

To add an exception for this directory, call:
	git config --global --add safe.directory .']
```
brought me to [10.20220504-55-gaf0d85446 AKA 10.20220525~13](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=af0d854460c28230dc682faa7c6daf3d96698cb6) from few days back where @joeyh was accounting for some new `git` behaviors... I am yet to grasp/analyze/account for this, but we need to address it asap since it causes a regression in our testing.

**Comment by yarikoptic** [comment]
Reading original CVE and @joeyh's analysis, I think one of the best solutions we could do on our end is to pass `--git-dir` to all invocations of `git` (and `git-annex`) whenever user explicitly specified `dataset` instance/path (in CLI's `-d`), since the path is explicitly specified and thus it is up to user to shoot in the foot. That would make `git` to bypass the security check.  But it would be very tricky AFAIK currently to accomplish such a drill due to code design + flyweight pattern over datasets (and now "deduced path dataset" would need to become different from "explicit dataset").
Given that the use case is rare, I guess relying on that `git config` `safe.directory` would be sufficient for those rare cases where accessing datalad datasets of others is desired, and would be the only way to use `git` directly on those anyways.

**Comment by yarikoptic** [comment]
Thank you @joeyh.  I also arrived at conclusion to "not try to bypass git's security model" ;) so in https://github.com/datalad/datalad/pull/6726 I just do set that `safe.directory` globally (well -- in our dedicated to tests run fake `$HOME`) in that test.

**Comment by joeyh** [comment]
So this does not appear to be a bug in git-annex. Your test is setting up a
repository that is owned by root and then trying to access it with a process
owned by another user. git's new security model does not allow that unless
the repository is whitelisted in safe.directory, like the message says.

Using --git-dir will not avoid this, for the simple reason that
git-annex does not propagate that option to this probe, which would defeat
the purpose of the probe..

Also, I don't think it's wise to bypass git's security model. That's why,
depite git-annex otherwise using --git-dir everywhere (for other reasons),
I have made sure that it does not allow access to a repo git now prevents
access to.

I think your best solution would be to add the path to safe.directory.
Although you would have to put it in ~/.gitconfig, so you might have to
override HOME.

-- 
see shy jo

**Comment by bpoldrack** [comment]
Just alerting @joeyh to the fact that the original post via mail showed up only now, in case the time correlation with something else provides a clue about what went wrong.
