### ISSUE TITLE
The `datalad wtf` command may violate the project code of conduct

### ISSUE THREAD

**Issue by arokem** [datalad/datalad#6896]
### What is the problem?

`datalad wtf` command contains when expanded through it's well-known acronymization a word that clearly violates the requirement that contributors not "... use [...] sexualized language or imagery". Please consider changing it to something that would be less likely to be offensive.

**Comment by adswa** [comment]
I'm sorry for spelling it out as "what the fuck" in the lecture today. Its actually my personal interpretation of that command. It is not formally defined to be pronounced like this http://handbook.datalad.org/en/latest/basics/101-135-help.html#f1 and I'm sorry I made that impression

**Comment by arokem** [comment]
I respectfully disagree. I think that it _could_ stand for any of the things in that footnote, but in the vast majority of cases, it would immediately be pronounced in a way that would be offensive to some, and even if you choose to say: "consider this command! 'wtf' stands here for 'what's it for?'", your audience would likely still hear something else in their mind's ear. Or in other words, I think that you did what any reasonable speaker of English would do when faced with that acronym. Renaming this command would both remove a barrier to entry for users from communities where profanity is not casually uttered, and remove a pitfall from y'all when teaching about this command.

**Comment by yarikoptic** [comment]
Although I can find a number of good synonyms for a *party pooper*: [drag](https://www.merriam-webster.com/dictionary/drag), [grinch](https://www.merriam-webster.com/dictionary/grinch), [killjoy](https://www.merriam-webster.com/dictionary/killjoy), [spoilsport](https://www.merriam-webster.com/dictionary/spoilsport), [wet blanket](https://www.merriam-webster.com/dictionary/wet%20blanket) (ref: https://www.merriam-webster.com/dictionary/party%20pooper) , and although the same dictionary gives a number of very well fitting informal descriptions of the meaning of [WTF](https://www.merriam-webster.com/dictionary/WTF) with examples of use from well respected journals like *Wall Street Journal*, the dictionary does not offer any synonyms. I am at loss of finding some other as short and as descriptive term ATM to be used instead.

**Comment by arokem** [comment]
What about [oof](https://www.merriam-webster.com/dictionary/oof), [egad](https://www.merriam-webster.com/dictionary/egad) (might be offensive to some, I am not sure), [boo](https://www.merriam-webster.com/dictionary/boo), or [ouch](https://www.merriam-webster.com/dictionary/ouch)/[ow](https://www.merriam-webster.com/dictionary/ow)?

**Comment by mih** [comment]
I think we should take the core of the issue apart into the two pieces it seems to be comprised of.

Let's assume for the following that `wtf` is synonymous with "what-to-fuck"
 
1. Rename because the spelled out `wtf` as "what-the-fuck" is considered offensive by some.
2. Acknowledge that the command name is violating our own code of conduct.

I will not respond to (1) right now.

Re (2): I am not a native speaker, but I never crossed my mind to consider the statement "what the fuck" to be of any sexual nature. The dictionary defines the meaning of the term to be exactly what made us name the command to begin with:

![image](https://user-images.githubusercontent.com/136479/181690021-ec4f1276-739a-4a61-844b-eea1ce2eee20.png)

https://dictionary.cambridge.org/dictionary/english/what-the-actual-fuck?q=what+the+fuck

The English language also has a curious multi-use of the word "fuck", most of which -- to me -- have no sexual nature at all: fuck off, fuck (someone) up, fuck (someone) around, ...

Having voted in favor of the code of conduct in its present form, I can say that "what the fuck" is not an example "use of sexualized language or imagery, and sexual attention or advances of any kind" -- to me.
To me, "sexualization" refers to what is covered by https://en.wikipedia.org/wiki/Sexualization -- in particular "to make something sexual in character or quality or to become aware of sexuality, especially in relation to men and women".

What-the-fuck does none of that, from my POV.

**Comment by jsheunis** [comment]
I have been mulling over this for a while now and have to admit that my core views on this are somewhat contradictory, or at least seemingly so.

**On the one hand** I do not think that WTF, if implied or expanded to mean “what the fuck”, constitutes a code of conduct violation in reference to the passage “Examples of unacceptable behavior include: [...] The use of sexualized language or imagery [...]”. I would argue that the interpretation of WTF is highly context dependent and subjective. I do agree with @arokem that WTF would likely be expanded to “what the fuck” by most users, irrespective of whichever alternative definitions have been put forward for this acronym by the project, officially or unofficially. Especially in the “tech-savvy world” (for the lack of a better expression), where the use of WTF to mean an often exasperated “i have no idea what is going on” is a well known expression with a widely shared context. The sexual connotation, for me and in this case, is far from clear or intended, and not within this shared context.

**On the other hand**, I do acknowledge that the use of what is considered by some to be profane language, will be offensive to some. And I feel strongly about not wanting to promote a community culture that (inadvertently or not) gives offence through the use of profanity. Now, again, profane language is also context dependent and subjective. Some people are from cultures or working environments where profanity (e.g. the expanded WTF) is not tolerated at all, or at least considered unprofessional. Some might flinch internally when reading or hearing a profane expression, others might not bat an eye. For personal reasons, I don’t consider this instance of profanity to be a problem. But I am pretty sure some people might.

Considering this, I think @mih summarised the two main issues succinctly:

> 1. [...] the spelled out wtf as "what-the-fuck" is considered offensive by some.
> 2. Acknowledge that the command name is violating our own code of conduct.

While the second point seems to be the core point of this issue, I feel that it is easy to conflate the two. After all, if some word/expression allegedly violates a code of conduct it is very likely to have caused offence, probably inextricably so (i.e. which one happened first?). And I suggest that if and while any conflation is occurring, it doesn’t make sense to argue the specifics of the meanings, etymology, or context-dependence of the expression (and suggested CoC violation). These are and will remain subjective, and difficult to form a consensus around. To me, the bigger point to focus on when considering the use of profanity is whether the project is adhering to the pledge in its CoC to “act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community”. 

Now, quantifying this is also a difficult task. Again, I would argue that it would not make sense to focus on the (subjective) meanings of offensive words. Rather, the focus should be on quantifying the evidence of possible harm caused (yes, another difficult task - I am a collector). Is the project using profanity in such a way that, e.g. according to the CoC, “could reasonably be considered inappropriate in a professional setting”? And is there evidence of offence caused/taken? Then, IMO, there has to be a corrective response from the project.

And the remaining question is what type of response could be provided based on such a possible violation of the CoC? One could, on the one hand, remove interpreted profanity from the codebase or documentation (in this specific instance, and/or any other instances if they exist). And on the other hand one could make a conciliatory statement without changing anything. I am not suggesting either, per se, since this is partly where I still have somewhat contradictory views on the matter. But perhaps this is a valid avenue for further thought and discussion?

**Comment by mih** [comment]
Thanks @jsheunis! Based on all we have heard in here (so far), I propose the following action: We close this issue, because we do not think that `wtf` represents a CoC violation in the original sense of OP ("... use [...] sexualized language or imagery").

As pointed out by @jsheunis, there are wider implications that deserve continued discussion in how far they should result in additional actions. I propose that this discussion is best have in channels more suitable for debate (chat, calls, etc.) not a github issue.
