### ISSUE TITLE
Where to learn about setting and searching for metadata?

### ISSUE THREAD

**Issue by mgamble** [datalad/datalad#6903]
I've started to accumulate a large number of datasets and I need an efficient way to search and filter them. I find the current documentation on metadata somewhat confusing. I'm interested in being able to set dataset-level and file-level metadata. Essentially want to add key:value pairs and tags. Can someone point me to the best tutorial/documentation about how to do this? I find the datalad handbook and documentation too vague even when it comes to the default extractors. Any help would be appreciated, as I feel I must be reinventing the wheel with the solution I'm trying to cobble together in the meantime. Thanks much.

**Comment by adswa** [comment]
Hi! Indeed the handbook doesn't have anything on metadata - mostly because it was in the middle of been overhauled when the handbook work was its busiest. I'm tagging @yarikoptic and @christian-monch who hopefully know the best up-to-date pointers.

**Comment by yarikoptic** [comment]
@mgamble what kinds (data standards and formats?) of data do you work with?

**Comment by ddeepwel** [comment]
I am also interested if there is a potential release date for metalad. There is huge value in having metadata extraction and querying available, so I want to know if this is coming soon or I need to find another short-term solution.

**Comment by mslw** [comment]
Ah, for the record - my answer focused on documentation, but datalad-metalad is already released (current version: 0.4.2, [available from pypi](https://pypi.org/project/datalad-metalad/)) and can be used.

**Comment by ddeepwel** [comment]
I have tried working with metalad, but it is not very intuitive, especially with the limited documentation.

It is my understanding that you need to run an extractor, then can save the metadata that was extracted, then can aggregate that metadata between datasets. Currently, I am unclear on how use extracted metadata in the aggregation step. From your (@mslw) [notes](https://github.com/mslw/catalog-notes/blob/main/notes.org), it looks like the metadata extraction requires an output file, but how to use this in the metadata aggregation?

Please see my other issues related to:
1) where metadata is stored during/after extraction (issue #6975)
2) duplicate functions (issue 276 in the metalad repo)
and 3) how meta-aggregate works (issue 275 in the metalad repo)

I would greatly appreciate a minimalist example showcasing metadata extraction, storage, aggregation, followed by a query.

**Comment by christian-monch** [comment]
@ddeepwel Hi David, thanks for the questions on metalad. First, there are a two generations of metalad. The first generation was implemented as part of `datalad`, and later improved in the `datalad-metalad` extension version <= 0.2.

The second generation is the `datalad-metalad` extension version >= 0.3. This generation has a different philosophy that manifests itself, among other things, in different metalad-commands.  We try to provide basic commands that do one thing properly and can be combined to achieve more complex goals (unix-shell-like). As you also pointed out, the documentation (`http://docs.datalad.org/projects/metalad/en/latest/#`) is not complete yet, we are working on it.

There is a gist that gives an example how to use metalad version >=0.3: `https://gist.github.com/christian-monch/63c52f20a5c24b04146db0a8f2750d0c`.

I would like to point out, that the extractors delivered with metalad <= 0.2 can still be used in metalad >= 0.3. But they have to be executed individually on files and datasets. (There is automation in metalad >= 0.3 to execute extractors on each file or subdataset of a dataset, i.e. `meta-conduct`). 

Since I am mainly working on metalad, feel free to ping me on any metalad issue, and I will work to explain, document, and solve it. I will work on documentation with high priority.

**Comment by yarikoptic** [comment]
@ddeepwel  what kinds (data standards and formats?) of data do you work with?

**Comment by ddeepwel** [comment]
@yarikoptic, in the near term I will be working with DICOM files from a wide variety of medical studies. Eventually I will also work with other bioinformatics formats (such as proteomics, metabolomics, genomics). In principle, I may work with any format or standard that is relevant to the various research groups I interact with

**Comment by ddeepwel** [comment]
@christian-monch, Thank you for the clear explanation and for the link to the gist! I will reach out with more questions as they come up
