### ISSUE TITLE
DataLad GitHub Action

### ISSUE THREAD

**Issue by thewtex** [datalad/datalad#6929]
### What is the problem?

Hi folks!

I am interested in a DataLad GitHub Action to provide CI testing data. Functionality

- Download / install DataLad
- Across platforms
- Possibly of a specific version
- Optionally `clone` and `get` datasets

### Have you had any success using DataLad before?

Yes, with a bit of help from @yarikoptic :-) I recently read [FAIRly big: A framework for computationally reproducible processing of large-scale data](https://www.nature.com/articles/s41597-022-01163-2) and was inspired. Going through the wonderful handbook now.

**Comment by yarikoptic** [comment]
I think it indeed would make total sense to simplify life of others.  What "action API" (options etc) do you envision? We might want to start with some rudimentary design doc PR into a file under https://github.com/datalad/datalad/tree/master/docs/source/design ?

But I think it probably should be a separate repo since overall would have its own life cycle.  Do you have any experience with establishing github actions? is there any template to start from ? (attn @vsoch and @jwodder who might know more)

**Comment by vsoch** [comment]
It's pretty easy to make actions - when y'all have a design I'd be happy to take an initial shot, or let me know if install/get is a good start!

**Comment by yarikoptic** [comment]
Yeah, I think at large it is `install/get`, and I would say 

- should use datalad-installer for install needs. Command should be smth like `datalad-installer -E {miniconda_env_file:=~/miniconda_env.sh} miniconda --path {miniconda_path:=~/miniconda} miniconda git-annex -m conda datalad -m conda` (might need dedicated `git` for windows https://github.com/datalad/datalad-installer/issues/46 attn @jwodder). 
(I used bash-inspired {var:=DEFAULT} above)

- action configuration should expose those options above ({miniconda*})
```yaml
[miniconda_env_file: str ...]
[miniconda_path: str ... # if exists, could just reuse]
datasets: list[dict(source: str, [path: str], [recurisive:bool], [recursion_limit:int], [get_paths: list[str]] ]
  
```

with [] marking optional, and those dicts in `datasets` 
- `source` : url for dataset to install
- `path`: path to install under
- `recursive` either to install recursively
- `recursion_limit` - possibly limit recursion
- `get_paths` - paths to `get`

so for this step it is roughly:

```python
import datalad.api as dl
for ds_spec datasets_spec:
   # kw should be populated based on relevant options
   ds = dl.install(source=ds_spec.source, **kw)
   ds.get(ds_spec.get_paths) 
```

**Comment by thewtex** [comment]
@yarikoptic @vsoch awesome, thanks for the support! :pray: 

I took a first stab, based on @yarikoptic 's suggestion here: https://github.com/datalad/datalad/pull/6931

I was not sure how miniconda fits, so I left it out for now.

**Comment by vsoch** [comment]
lol ok, my help is not needed! Thanks @thewtex

**Comment by vsoch** [comment]
Oh I didn't read well :laughing: Do y'all still want me to take a shot for the implementation? I was thinking a composite action would be appropriate here.

**Comment by thewtex** [comment]
@vsoch your help in implementation would be greatly appreciated! :pray:

**Comment by vsoch** [comment]
Woot! Ok I’ll care away some time soon - likely latest over the weekend.

**Comment by thewtex** [comment]
@vsoch thank you!

> I was thinking a composite action would be appropriate here

Cool!  Maybe there could be a [cache action](https://github.com/actions/cache) to make subsequent runs super fast :zap: ?

**Comment by vsoch** [comment]
okay just started on my own account (and can move over when ready). https://github.com/vsoch/datalad-action Install is looking good, I'm not familiar with datalad but will try to use the examples here to take a shot at the downloads tomorrow!

**Comment by vsoch** [comment]
okay I'm done - https://github.com/vsoch/datalad-action it's missing some of the args mentioned, mostly because I can't find good usage example. This is a personal project so I can only work evenings / weekends, so (when you are ready) I can transfer it over here, and maybe give me maintainer permission on it (or add me to datalad org) so I can continue working on it. I did tweak the design a bit - I don't think it's a good design to allow providing multiple datasets into one action - my 0.02 (and the design here) is that one dataset get call == one source and parameters relevant to it. For next steps:

- find whatever args are missing, show me how to add them
- open other issues for discussion, etc.

Ty!

**Comment by yarikoptic** [comment]
Woohoo!! Thank you @vsoch ! As soon as I am done replacing roofing before the rain comes, I will have a look/give it a try.

**Comment by vsoch** [comment]
ohno, don't get wet! :laughing:

**Comment by yarikoptic** [comment]
ok, we have https://github.com/datalad/datalad-action and I just tagged 0.1.0 of it. Thank you @vsoch for making it happen!
Let's consider this issue closed and open any other desired issue in that repo.
