### ISSUE TITLE
clean's parameter specification sticks out

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#7026]
The `--what` parameter to the `clean` command is an outlier in how the choices for it are specified. Most commands use `EnsureChoice` while this one specifies `choices` for argparse instead.

Not sure yet, whether we should aim to unify by using either one of them everywhere or both or rework the interface specification even more and come up with a new way. However, this makes parameter discovery harder for datalad-gooey.

**Comment by adswa** [comment]
What was the reason for going with ``choices`` instead of ``constraints`` for ``clean``? On a first quick look, wouldn't this achieve the same thing?

```diff
❱ git diff
diff --git a/datalad/local/clean.py b/datalad/local/clean.py
index c6edc5351..b7fe564b8 100644
--- a/datalad/local/clean.py
+++ b/datalad/local/clean.py
@@ -33,7 +33,10 @@ from datalad.interface.common_opts import (
 )
 from datalad.interface.results import get_status_dict
 from datalad.interface.utils import eval_results
-from datalad.support.constraints import EnsureNone
+from datalad.support.constraints import (
+    EnsureNone,
+    EnsureChoice,
+)
 from datalad.support.param import Parameter
 from datalad.utils import (
     Path,
@@ -92,8 +95,8 @@ class Clean(Interface):
         what=Parameter(
             args=("--what",),
             dest='what',
-            choices=('cached-archives', 'annex-tmp', 'annex-transfer',
-                     'search-index'),
+            constraints=EnsureChoice('cached-archives', 'annex-tmp', 'annex-transfer',
+                     'search-index') | EnsureNone(),
             nargs="*",
             doc="""What to clean. If none specified -- all known
             targets are considered."""),
```

or is there a downside to ``constraints`` compared to ``choices``? Otherwise, since ``constraints`` is used in other commands I'd lean towards unifying it.

**Comment by mih** [comment]
I don't think there was a reason. It is merely exploiting the needless flexibility of this machinery. Declaring `choices=` is both simpler than defining a constraint, and less useful (requires custom code for validation -- but that is not much of a concern, because most parameter values are processed without validation within the Python API).

> However, this makes parameter discovery harder for datalad-gooey.

This is not a concern. Gooey inspects any of these declarations and handles them uniformly by always building a comprehensive constraint which also covers all the other `argparse`-specific specifications (e.g., `action=append`, `nargs=*`, `action=store_true`, etc.)
