### ISSUE TITLE
Handling terabytes of data

### ISSUE THREAD

**Issue by anikfal** [datalad/datalad#7144]
I created a subdataset in an HPC server, containing about 55 thousand data files, with a total size of 21 Terabytes.

After `datalad save`, it was so time-consuming that I just left it to be run in the background. I don't have any idea how long it would exactly take to be completed.

I suppose, I will face more serious issues in the next stages of the Datalad procedure.

**Comment by mih** [comment]
Saving 55k file of 21TB total needs to read 21TB of the storage system for checksumming and then move 55k files into an annex. How long do you expect the read operation to last? Datalad cannot possibly be faster than your storage system. How long is long in your experience? What percentage of sliwdown do you see with datalad, compared to md5sum?

**Comment by anikfal** [comment]
This is the situation I'm dealing with. The project consists of lots of big data files.

Perhaps using xxhash as an external git-annex backend would be an option?

**Comment by mih** [comment]
Neither size nor number of files is unusual. It is hard to give advice without more facts.

**Comment by anikfal** [comment]
I'll come back with more information.

**Comment by mih** [comment]
Thanks! I will close this issue for the time being. Please feel free to reopen this one or a more targeted one, once we know what we are dealing with.

If it turns out to be backend performance related, let me mention that implementing a  custom backend is fairly straightforward. The datalad-next extension provides ready-to-use tooling for that.

If you want to give it a go, I can provide feedback on an implementation and a test suite. If you want to convince another dev to do this (eventually), a comprehensive performance (difference) assessment would be instrumental.

**Comment by mih** [comment]
Here is a link to the corresponding git-annex issue for xxhash https://git-annex.branchable.com/todo/add_xxHash_backend/
