### ISSUE TITLE
Data Can't Be Moved, PermissionError 13?

### ISSUE THREAD

**Issue by emstruong** [datalad/datalad#7151]
### What is the problem?

I want to copy a datalad dataset to a local drive from a network folder.

### What steps will reproduce the problem?

1) Install dataset on Synology NAS
2) Move dataset using GUI on Synology NAS webUI
3) Attempt to `rsync` or `cp` the data back

I get 
```
[ERROR  ] PermissionError([Errno 13] Permission denied: '/media/.../OpenNeuro/ds000031/sourcedata/dicom_headers/sub-01/ses-107/func/.sub-01_ses-107_task-retinotopy_run-001_bold.json.swp') (PermissionError)
```

### DataLad information

datalad 0.15.5

Ubuntu 22.04

### Have you had any success using DataLad before?

No, this is my first time.

**Comment by bpoldrack** [comment]
A couple of things, @emstruong:

1. Literally copying a dataset generally isn't advisable, since you'd also copy a bunch of identifiers thus "pretending" that the two copies are in fact the same instance. In general the way to go would be to make a clone instead (and `datalad get` or `datalad push` the data you want to be there).

2. Similarly `rsync`ing back can be troublesome. A dataset is a git repository (not only but at the most fundamental layer) and intended to be worked with the same way. Getting data back is a question of having the source as a remote and `datalad get` the data. Or - if the target doesn't exist anymore/yet - clone the source.

3. Your datalad version is quite old. It could be that your python is too old ( <=3.6 which reached end of life). With at least python 3.7 you should be able to update to the `0.17.x` series.

4. Generally, I think 1. and 2. should also avoid the permission issue. If not, we'd need to know what filesystem you're running on (NAS and the machine to get the data back to) to figure what's going on.

**Comment by emstruong** [comment]
Hi @bpoldrack  (and also future searchers),

I've updated Datalad to `0.17.8` by adding the neurodebian respositories, as detailed here -- https://neuro.debian.net/index.html. 

The Synology NAS is running BTRFS on a Synology Hybrid Raid with 1-drive fault tolerance. My local drive is ext4. 

I've attached an [error.log](https://github.com/datalad/datalad/files/9966392/error.log) of the message I'm getting when I run `git status` in the `ds000031` folder.

**Comment by bpoldrack** [comment]
@emstruong 

> I've attached an error.log of the message I'm getting when I run git status in the ds000031 folder.

Which copy/clone is this the status of?

And: Did you try the clone+get approach instead?

**Comment by emstruong** [comment]
@bpoldrack 

The error.log is for the copy that I moved from one folder to another in the Synology NAS. The original no longer exists and I couldn't r-sync back because of the permission issues. 

I'm not sure what you mean by copy-back or how to do the clone + get approach.

**Comment by adswa** [comment]
I don't have any experience with Synology at all, but there are a [few](https://git-annex.branchable.com/tips/Synology_NAS_and_git_annex/) [posts](https://git-annex.branchable.com/bugs/Synology_NAS__58___timer__95__create__58___Bad_address/?updated#comment-f5a8ceef2907d7b7aff6e7c58b76f763) in the git-annex forum on how to sync annex repos with synology NAS. Most of those posts deal with all sorts of trouble when installing git-annex on the NAS side. The most recent one I could find was from 4 years ago, so support might now be better. Sadly, the support/issue page of Synology requires a customer account it seems. However, I found [some documentation](https://kb.synology.com/en-global/DSM/help/Git/git?version=7) about the necessary steps to work with git repositories. To me, all of that somewhat sounds like there are some server-side requirements in order to properly work with git/annex repos/datalad datasets. Since you installed a dataset on the NAS, I assume that git-annex and datalad are installed on it?

What also strikes me as odd is the path in the error message you posted:
``'/media/.../OpenNeuro/ds000031/sourcedata/dicom_headers/sub-01/ses-107/func/.sub-01_ses-107_task-retinotopy_run-001_bold.json.swp'``
I assume its Unix a swap file - those are not part of the original dataset on OpenNeuro. Has there been a failed editing attempt on that file maybe? And has anything saved that file in the dataset (it does not show up as untracked or modified in your attached ``git status`` log)?  The existence of the file or the fact that something saved it does not explain the permission denied error, but it might hint at other processes that led to the state the dataset is currently in. 
The ``git status`` call from your log also shows that almost all files in that dataset are either modified or deleted - can you check what modifications those are, e.g., with a ``git diff``?

> I'm not sure what you mean by copy-back or how to do the clone + get approach.

As @bpoldrack said, its generally not advisable to copy/rsync datasets from device A to device B. You would usually (depending on how A and B are connected) either do a ``create-sibling`` from the dataset on A to a location on B and ``push`` dataset contents from A to B, or you ``clone`` from A to B and ``get`` the data. From the Synology docs it seems like SSH access is in principle possible. Could you try to run  ``datalad clone ssh@yourNAS:/path-to-ds``  instead of rsyncing/copying it from the NAS, and then try to retrieve data in that clone using ``datalad get``? 

My apologies that its hard for us to get behind this, but we don't have access to such systems to reproduce this or test anything.

**Comment by emstruong** [comment]
Hi @adswa, 

Thank you for getting back to me, but I ended up completely wiping out the files from my Synology NAS and re-downloading the repositories directly to my local drive. Next, I intend to follow this [older link as a potential guide on how to back-up my data to the NAS](https://github.com/datalad/datalad/issues/4369). 

Regarding what you posted, I downloaded the data by network mounting the Synology NAS to a Raspberry PI then using Datalad to download from the repository, so I did not intentionally install Git or datalad on the NAS. I also didn't intentionally modify the files aside from moving them via the Synology GUI. From what I understand, the file permissions on these files are set to read and execute only, so I don't understand the existence of the `.swp` file either.

Unfortunately, I can't do any more `git diff` or `status` because the files are gone now. 

I think this is likely to be an edge-case scenario and it's difficult to support so many configurations, so I understand. That being said, it is spooky that permission to do anything to the files could simply disappear like that. If it had been the sole copy of the data, I would be much more worried. 

I'll close this issue now because it's no longer an issue for me.
