### ISSUE TITLE
DataLad should not unconditionally assume `annex-ignore=true` for newly created siblings via `create-sibling-gitea`

### ISSUE THREAD

**Issue by matrss** [datalad/datalad#7179]
There is a fork of gitea which enables git-annex support at https://github.com/neuropoly/gitea. Considering this, `create-sibling-gitea` should not always set `annex-ignore` for the newly created remote. As far as I can tell, this is currently happening somewhere around here:
https://github.com/datalad/datalad/blob/19404cbab9b54e9dac2ea7d019783e4f0897c23c/datalad/distributed/create_sibling_gitea.py#L33-L37

In my opinion, any `create-sibling-*` command should allow for annex support in the created sibling and check dynamically if it is there, even if annex support for this type of target is unlikely.

**Comment by bpoldrack** [comment]
Thanks for the pointer, @matrss!

> In my opinion, any create-sibling-* command should allow for annex support in the created sibling and check dynamically if it is there, even if annex support for this type of target is unlikely.


I do see the argument. One of the troubles with that approach (as far as I remember) is communication to the user. If we call `git annex enableremote` unconditionally, we need to account for it possibly failing. But then we would need to figure out why it's failing and whether that's fine and what output to relay to the datalad user.
If we are trying to filter out the specific failures that are to be expected we get into the business of string parsing annex' output, which isn't wel maintainable in the long run. One can instead pass through any output of annex, but that turned out most often to be more confusing than helpful to datalad users.
If I didn't expect something to support annex, I don't need to be told that annex couldn't enable it. I may even start wondering what I did wrong leading to datalad trying to enable it.
If I use the `create-sibling-*` commands to set up a pair of a git remote and a git-annex special remote and we'd try to enable the git remote, the message saying that this failed may be even more confusing.


Always doing something that is sort of expected to fail also is a scaling issue with respect to performance. Those commands can be run recursively on a dataset hierarchy. If I have 10K subdatasets, that's a lot of time spent on trying something that is doomed to fail (That's 10K requests to that service). So, a switch to try (or not) is needed one way or another. One can argue about the most convenient default, though.

Point is: All doable for any given usecase, but not yet sure about a general solution.

**Comment by matrss** [comment]
You are right, this might be confusing for some users. It would be similar to how datalad currently emits warnings about a missing git-annex installation when cloning from e.g. github or gitlab. This certainly confused me at some point.

Also good point on the scaling issue, I am usually not dealing with that many datasets at once. Although we might just keep a cache of if a target at a specific location supports git-annex or not.

Instead of always trying we might also have some kind of per domain option in the user specific git config, so that I could tell datalad to not set annex-ignore for a gitea instance at some domain. That way we could use a sensible default for the target otherwise, i.e. no annex on gitea.

**Comment by bpoldrack** [comment]
> Instead of always trying we might also have some kind of per domain option in the user specific git config, so that we could tell datalad to not set annex-ignore for a gitea instance at some domain.

I think, I  like that approach. :)
