### ISSUE TITLE
Moving files between subdatasets?

### ISSUE THREAD

**Issue by asmacdo** [datalad/datalad#7454]
### Is it a new bug?

I did not find an existing issue about my problem

### What is the problem?

I've made an error, and I dont know how to get out of it :)

what I had yesterday: 

```
root-dataset/
     /image-dataset/singularity-image.sif
```

Then, I rebuilt the image, but accidently left it in the root dataset. When i saved it, it was git-annexified

```
root-dataset/
     /new-singularity-image.sif
     /image-dataset/old-singularity-image.sif
```

Then I deleted the old image with `datalad remove`

```
root-dataset/
     /new-singularity-image.sif
     /image-dataset/ # nothing
```

Unfortunately though, the new image is just a symlink, and there is no "datalad move". So I did `git mv new-image.sif image-dataset/new-image.sif, and this is where I'm now confused. I've somehow deleted the subdataset and the symlink is angry.

Below is actual copy paste, the image (old and new) is opfvta.sing

```
(asmacdo-datalad2) [f006rq8@ndoli opfvta-replication-2023]$ git mv opfvta.sing code/images/opfvta-singularity/
(asmacdo-datalad2) [f006rq8@ndoli opfvta-replication-2023]$ git status
On branch master
Your branch is up to date with 'con/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    code/images/opfvta-singularity
	renamed:    opfvta.sing -> code/images/opfvta-singularity/opfvta.sing

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	code/images/opfvta-singularity/.datalad/
	code/images/opfvta-singularity/.gitattributes
```

**Comment by adswa** [comment]
I have too little time at the moment to think into this, but this might be helpful: https://handbook.datalad.org/en/latest/basics/101-136-filesystem.html#moving-files-across-dataset-boundaries

**Comment by yarikoptic** [comment]
as I briefly replied in matrix -- do not forget about basic tools you still have at your disposal -- `cp`, `git` and `git-annex` which could be used directly ;)  e.g., if I saved some file by mistake in super dataset and didn't yet share any of the work publicly I would have just 

- `cp --reflink-auto -L new-singularity-image.sif image-dataset/old-singularity-image.sif`  # reflink=auto on CoW filesystem would make it super fast/efficient
- `git annex drop --force new-singularity-image.sif`  # so git-annex doesn't keep a copy in this one 
- `git reset --hard HEAD^`  # disregard that original `save` commit.  Might have used `git rebase -i ...` if it was not recent commit
- `datalad -d . -m "New image" -r image-dataset`  # save addition of new image
- declared a victory

as nearly always -- there are multiple ways to get around, e.g. could use `git revert` instead of `reset` or `rebase` if I wanted to keep a record of the crime, etc.
