### ISSUE TITLE
Using `git annex move` instead of `datalad get` to obtain data from RIA store

### ISSUE THREAD

**Issue by askieslinger** [datalad/datalad#7487]
### What is the problem?

Dear datalad team,

we are working with a very large dataset (~1TB in multiple subdatasets) and little storage. 
We are roughly following the ["fairly big processing workflow"](https://github.com/psychoinformatics-de/fairly-big-processing-workflow) that uses a RIA remote to store unmerged new data, then merges and gets the data from RIA remote to the original dataset.

Our problem is: This "outputstore" can get very large und we are very constrained on space. We would like to merge the results into our original dataset and drop them from the remote so as to not double the amount of space needed.
One possible solution seems to be to use `git annex move --from output-storage <path>`, which gets the file content and simultaneously removes it in the remote.

Do you see any problems with this solution?
In particular, when moving a whole directory, can we be sure that newer file versions in our original dataset are not overwritten with possibly older filecontent from the remote?

**Comment by yarikoptic** [comment]
> One possible solution seems to be to use `git annex move --from output-storage <path>`, which gets the file content and simultaneously removes it in the remote.
> 
> Do you see any problems with this solution?

sounds sensible to me but I am not a "fairly big" fella ;)  I would say: try on a small/toy example and see if works?

shameless plug: since you are proceeding a "fairly big" way, checkout https://github.com/PennLINC/babs (preprint: https://www.biorxiv.org/content/10.1101/2023.08.16.552472v1).  If your approach works, might be worth proposing/incorporating it in babs.

> In particular, when moving a whole directory, can we be sure that newer file versions in our original dataset are not overwritten with possibly older filecontent from the remote?

I might be missing the point, but: `annex move` works with annexed content and not with "file tree".  As far as you use checksum based git-annex backend (like md5 default for datalad datasets), there is no possibility for `git-annex move` to overwrite any content since content with the same checksum simply would not be transferred.  So the answer to the question in my understanding of it would be **No**.

**Comment by askieslinger** [comment]
Thank you for your input on this, FYI `git annex move` seems to work well for us so far!

**Comment by yarikoptic** [comment]
thanks for the update @askieslinger !
