### ISSUE TITLE
Change "pushurl" of a RIA store after sibling creation

### ISSUE THREAD

**Issue by oesteban** [datalad/datalad#7520]
### What is the problem?

I have configured a RIA store, and the HPC has two modes of transferring data:

- Through a login node, where ssh is allowed.
- Through a data transfer node, where only scp can be done.

I have successfully created the sibling against the login node, and I checked I indeed can push. However, it would be great if 1) I could push through the data transfer node (not to overload the login node and faster transfer), and 2) change the user to access the remote (so that other users in the cluster, who have rights to access the path of the ria store, can access too).

### Have you had any success using DataLad before?

Lots, thanks!

**Comment by oesteban** [comment]
@yarikoptic -- maybe this is trivial, but I haven't been able to see where the pushurl is configured

**Comment by yarikoptic** [comment]
it is configured 
- either for the specific remote within your `.git/config` ([docs](https://git-scm.com/docs/git-push#_named_remote_in_configuration_file)), so e.g `url` is just https url and `pushurl` your ssh url. 
- "user wide", I have in my `~/.gitconfig`

```
[url "git@github.com:"]
    pushinsteadOf = https://yarikoptic@github.com/
    pushinsteadOf = https://github.com/
    pushinsteadOf = http://github.com/
    pushInsteadOf = git://github.com/
```

so if `url` is one of the https or git protocols, I would use `ssh` one for pushing.  Note that you can provide alternative user there instead of `git@`.  Also you can instruct to setup some "fake" host in users' `~/.ssh/config`, e.g. 

```
Host center-ria-store
   Hostname real.hostname.example.com
   User customuser
```

and use `center-ria-store:...` ssh address.

Does that help?

**Comment by oesteban** [comment]
It shows as an "ora-store" remote, so the `.git/config` file doesn't look anything like a git remote. However, this system accepts rsync - would adding a git-annex remote "manually" (AFAIK there's no datalad sibling specific for rsync) work?

**Comment by yarikoptic** [comment]
sorry, I am still trying to grasp the goal here, so you want to access ORA remote via one URL for `git-annex get` and another URL for `git-annex copy` (in git-annex terms, so we do not mixin `git push` which also to happen during `datalad push` if git remote etc)?

**Comment by oesteban** [comment]
Sorry for abandoning this question. I'm not even sure this would resolve the problem. I think my issues are more related to #7543. I'm closing this in favor of that one.
