### ISSUE TITLE
Missing tab completions and linter help for datalad Python API

### ISSUE THREAD

**Issue by magland** [datalad/datalad#7591]
Hello datalad maintainers,

I’m using the datalad Python API and noticed that tab completions and linter help aren’t available when working in VSCode. For instance, the `run` function imported from `datalad.api` doesn’t show any suggestions. Is this a known issue? If this isn’t currently supported, is it something I could help implement?

(Note: I tried posting this on neurostars, but I have exceeded my daily activity limit on my first day, after accidentally posting to the wrong category and deleting and reposting)

**Comment by yarikoptic** [comment]
That's I believe due to our somewhat an ad-hoc framework to build up those both Python and CLI interfaces from the same singular specification of a subclass of an [Interface](https://github.com/datalad/datalad/blob/fda2048a1e5e6f7a13b94b31995c48eb7cdb7575/datalad/interface/base.py#L479) implementation but then using its `@staticmethod` `__call__` as the actual function entry, or a dataset method (hence `@datasetmethod`) . 

The framework does establish the `__doc__` (in Python) and `--help` (in CLI) for them so they are well documented with a single specification for the interface (e.g. see that one of [Run](https://github.com/datalad/datalad/blob/maint/datalad/core/local/run.py#L93))  but indeed I guess impairing ability to inspect signatures in full by the IDEs etc... although in general many parameters are available/described through `inspect.signature`:

```
In [6]: for param in inspect.signature(dl.run).parameters.values():
   ...:     print(f"Name: {param.name}, Kind: {param.kind}, Default: {param.default}")
   ...:     
Name: cmd, Kind: POSITIONAL_OR_KEYWORD, Default: None
Name: dataset, Kind: KEYWORD_ONLY, Default: None
Name: inputs, Kind: KEYWORD_ONLY, Default: None
Name: outputs, Kind: KEYWORD_ONLY, Default: None
Name: expand, Kind: KEYWORD_ONLY, Default: None
Name: assume_ready, Kind: KEYWORD_ONLY, Default: None
Name: explicit, Kind: KEYWORD_ONLY, Default: False
Name: message, Kind: KEYWORD_ONLY, Default: None
Name: sidecar, Kind: KEYWORD_ONLY, Default: None
Name: dry_run, Kind: KEYWORD_ONLY, Default: None
Name: jobs, Kind: KEYWORD_ONLY, Default: None
```

**Comment by magland** [comment]
Got it, thanks.
