### ISSUE TITLE
Precompute required disk space and warn if insufficient

### ISSUE THREAD

**Issue by mih** [datalad/datalad#919]
Just waited for an hour downloading only to get the drive filled up and datalad die with 'insufficient space' error. I guess why could easily check that we have enough space before starting the download.

**Comment by yarikoptic** [comment]
you would not know exactly how much you would need unfortunately, e.g. in case of working with content from archives. Though whenever we RF get to do all the analysis, we could guestimate as

- size of archive tarballs needed to be downloaded
- approx size of extracted tarballs (i.e. at least multiply first size twice)

**Comment by bpoldrack** [comment]
If the datasets themselves are already installed, we can check before (with restrictions as yarik mentioned). If not so - we can't. Or do I miss something? So once we go for checking recursively what we need before actually get it, what behaviour seems reasonable in case of implicit installation? Fail as soon as we know we can't get everything? Install at least the datasets but without content? Just go ahead until we hit the first dataset, that doesn't fit anymore?

**Comment by bpoldrack** [comment]
To be clear: The "insufficient memory" comes from `annex get` itself, which is called once per dataset. So, on a dataset basis we should just rely on `annex` I guess. What we need to do is considering multiple repos recursively, that annex doesn't know about.

**Comment by yarikoptic** [comment]
nope... we should also do our check I guess in 'get' when doing analysis of what/how much we need to download, since annex would only know about what we ask it to get, it wouldn't know e.g. about extracting archives etc.  but sure thing we should also catch annex' out of space message (which I think we do already)

**Comment by bpoldrack** [comment]
Well, yes. Extend `annex``s analysis by checking for archives on the level of `AnnexRepo.get()` (since we got a OutOfSpaceError from there already whenever `annex` knows, there isn't sufficient memory). But what is less clear how to deal with (at least to me) and what needs to be done on higher level is caring for memory needs of hierarchies. Better? ;-)

**Comment by mih** [comment]
Related to #1618 in that the error reporting is not very informative.

**Comment by mih** [comment]
Closing this issue of mine, acting on the apparent lack of motivation to work on it.
