### ISSUE TITLE
Central switch to engage direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#982]
We should have a config switch to engage direct mode for all installed and created repositories.

Once we have it, there should be a travis test run that exercises the entire battery in direct mode.

This should give us an initial idea how far we got off the track already and to make sure we dont diverge any further.

@bpoldrack Do you want to give that a try?

**Comment by bpoldrack** [comment]
FTR: I'm on it and as expected, it's a mess ;-)

I'm currently approaching it via the datalad config mechanism, so you could provide the switch via env variable `DATALAD_MODE_DIRECT` for example. If this config item is set, `AnnexRepo.__init__()` uses it as the default of its parameter `direct`, so any repo created or initialized is switched to direct mode right in the constructor.

**Comment by bpoldrack** [comment]
This again raises a general question: To GitPython or not to GitPython?
Since it uses direct `git` calls, we are in trouble with direct mode. We would need to inject `annex proxy` or `-c core.bare=false` option deep into GitPython in order to work in direct mode. May be there is a solution (need to think about it), but just seems to add to the cons of using it at all.
