### ISSUE TITLE
RFC: do not autogenerate a Dataset id if not defined. Generate one during create (only)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#986]
Currently I can do in any directory:

```shell
hopa:/tmp
$> python -c 'from datalad.distribution.dataset import Dataset; print(Dataset(".").id)'
54e5a0aa-8d05-11e6-95c9-8019340ce7f2
```
which imho makes little sense... and in general -- I thought we could discriminate between a Dataset and non-Dataset by checking for their id, and if None - consider it to not correspond to a dataset

edit 1: well -- ATM the only way to initiate a dataset in existing git/annex repo seems to use `create --force` but not sure if what `--force` does doesn't have side-effects... seems it doesn't and just indeed does only initialization of the dataset if git or annex repo is already there.  May be we should add explicit `--init-only` which, unlike `--force` wouldn't try to create one?

**Comment by bpoldrack** [comment]
I'm not sure, what implications it would have for metadata if there wasn't an `id` in this case. May be it makes sense to have `None` here. @mih?

But as far as it regards this aspect:
> I thought we could discriminate between a Dataset and non-Dataset by checking for their id, and if 
> None - consider it to not correspond to a dataset

How about `Dataset.is_installed()` or `Dataset.repo is None`? Why would you need a third method of figuring out, whether or not there is a dataset? Or do I misunderstand the purpose of your wanted check via `Dataset.id`?

**Comment by mih** [comment]
Implication would be no metadata unless there is an ID. I think that was
merged already. Or at least there is an issue with this resolution.

On Oct 10, 2016 13:14, "Benjamin Poldrack" <notifications@github.com> wrote:

I'm not sure, what implications it would have for metadata if there wasn't
an id in this case. May be it makes sense to have None here. @mih
<https://github.com/mih>?

But as far as it regards this aspect:

I thought we could discriminate between a Dataset and non-Dataset by
checking for their id, and if
None - consider it to not correspond to a dataset

How about Dataset.is_installed() or Dataset.repo is None? Why would you
need a third method of figuring out, whether or not there is a dataset? Or
do I misunderstand the purpose of your wanted check via Dataset.id?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/datalad/datalad/issues/986#issuecomment-252589711>, or mute
the thread
